### ISSUE TITLE
Hikari connection pool InstanceNotFoundException on Websphere

### ISSUE THREAD

**Issue by gaenshr** [brettwooldridge/HikariCP#1010]
I am working on creating a HikariDataSource and pass in HikariConfig (with setRegisterMbeans(true)). Then I create MBeanServerProxy in the method 

`private HikariPoolMXBean createMBeanServerAndPoolProxy() {
		MBeanServer mBeanServer = MBeanManagement.getMBeanServer();		
		ObjectName poolProxy = null;
		try {
			poolProxy = new ObjectName("com.zaxxer.hikari:type=Pool "+"("+hikariConfig.getPoolName()+")");
		} catch (MalformedObjectNameException e) {
			throw new ConfigurationException(e);			
		}		
		 return JMX.newMXBeanProxy(mBeanServer, poolProxy, HikariPoolMXBean.class);
	}
`
Then I set the values in a bean

`DataSourceInformationBeanImpl connectionInformation = new DataSourceInformationBeanImpl();
		HikariPoolMXBean hikariConfigAndPoolMxBean = createMBeanServerAndPoolProxy();			connectionInformation.setActiveConnectionCount(String.valueOf(hikariConfigAndPoolMxBean.getActiveConnections()));`

Calling the method hikariConfigAndPoolMxBean.getActiveConnections() fails with an instanceNotFoundException on Websphere. It works fine on Tomcat. I think the pool could not be found.

What is the resolution of this issue?

**Comment by gaenshr** [comment]
`Caused by: javax.management.InstanceNotFoundException: com.zaxxer.hikari:type=Pool (HikariPool-1)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1107)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBeanInfo(DefaultMBeanServerInterceptor.java:1387)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getMBeanInfo(JmxMBeanServer.java:932)
        at com.ibm.ws.management.AdminServiceImpl.getMBeanInfo(AdminServiceImpl.java:1542)
        at com.ibm.ws.management.AdminServiceImpl.checkForAttrDeprecation(AdminServiceImpl.java:2334)
        at com.ibm.ws.management.AdminServiceImpl.preInvoke(AdminServiceImpl.java:2228)
        at com.ibm.ws.management.AdminServiceImpl.preInvoke(AdminServiceImpl.java:2102)
        at com.ibm.ws.management.AdminServiceImpl.preInvoke(AdminServiceImpl.java:2075)
        at com.ibm.ws.management.AdminServiceImpl.getAttribute(AdminServiceImpl.java:870)
        at com.ibm.ws.management.connector.AdminServiceDelegator.getAttribute(AdminServiceDelegator.java:141)
        at com.ibm.ws390.management.connector.corba.CorbaConnectorImpl.getAttribute(CorbaConnectorImpl.java:476)
        at com.ibm.ws390.management.connector.corba._CorbaConnectorImplBase._invoke(_CorbaConnectorImplBase.java:203)
        at com.ibm.ws390.orb.CommonBridge.invoke(CommonBridge.java:1898)
        at com.ibm.ws390.orb.ORBEJSBridge.invoke(ORBEJSBridge.java:286)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.ws390.orb.parameters.ORBEJSBridgeInvoke.ORBEJSBridgeInvokeParmSetter(ORBEJSBridgeInvoke.java:234)
`

**Comment by brettwooldridge** [comment]
This is a question for either stackoverflow or the WebSphere group.
