### ISSUE TITLE
Could not open JDBC Connection for transaction; nested exception is org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.

### ISSUE THREAD

**Issue by angeletos** [brettwooldridge/HikariCP#102]
Hello Brett,

Thank your for your great work on HikariCP!

After attempting to upgrade to 1.3.9 / 1.4.0 from 1.3.8 I am experiencing the infamous error: "Cannot change transaction isolation level in the middle of a transaction."

The issue is also occurring intermittently.

Java 1.7.0_60
Spring 3.2.9.RELEASE
Tomcat 7.0.54
PostgreSQL JDBC: 9.3-1101

``` java
CustomExceptionHandler:75 - Could not open JDBC Connection for transaction; nested exception is org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
    at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:241)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:372)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:417)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:255)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy32.myMethod(Unknown Source)
...
...
Caused by: org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
    at org.postgresql.jdbc2.AbstractJdbc2Connection.setTransactionIsolation(AbstractJdbc2Connection.java:944)
    at com.zaxxer.hikari.proxy.ConnectionProxy.setTransactionIsolation(ConnectionProxy.java:562)
    at org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction(DataSourceUtils.java:193)
    at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:213)
    ... 91 more
```

``` xml
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
        <property name="maximumPoolSize"        value="3" />
        <property name="connectionTimeout"      value="30000" />
        <property name="autoCommit"             value="false" />
        <property name="isolateInternalQueries"     value="true" />     
        <property name="maxLifetime"            value="1800000" /> 

        <property name="dataSourceClassName" value="org.postgresql.ds.PGSimpleDataSource" />
        <property name="dataSourceProperties">
            <props>
                        ...
            </props>
        </property>

        <property name="registerMbeans"     value="false" />
        <property name="poolName"           value="myCP />

    </bean>

    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="shutdown">
        <constructor-arg ref="hikariConfig" />
    </bean>
```

Many thanks,
George

**Comment by jerori** [comment]
I'm still have the trouble even adding jdbc4ConnectionTest and connectionTestQuey  .. 
Stack: SprintBoot 1.3.5, Hikari 2.4.6 and Spring-Data-JPA, Postgresql 9.1-901-1.jdbc4.jar

INFO  com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc4.Jdbc4Connection.getNetworkTimeout() is not yet implemented.)
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Eagerly caching bean 'dataSource' to allow for resolving potential circular references
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Finished creating instance of bean 'dataSource'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.data.repository.core.support.RepositoryInterfaceAwareBeanPostProcessor'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'emBeanDefinitionRegistrarPostProcessor'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Creating shared instance of singleton bean 'jpaMappingContext'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Creating instance of bean 'jpaMappingContext'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Eagerly caching bean 'jpaMappingContext' to allow for resolving potential circular references
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Invoking afterPropertiesSet() on bean with name 'jpaMappingContext'
DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'

Any clue?
