### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by PatrickSauts** [brettwooldridge/HikariCP#1027]
#### Environment
```
HikariCP version: 2.7.3
JDK version     : 1.8.0_111
Database        : MySQL 5.7.18
Driver version  : 5.1.44
```
-----------------------------------------------------------------------------------------

the singleton

```
public class MysqlServiceFactory {
  private static MysqlService mysql;

  public static MysqlService getInstance() {
    if (mysql == null) {
      synchronized (MysqlService.class) {
        if (mysql == null) {
          mysql = new MysqlService();
        }
      }
    }
    return mysql;
  }

  public static void close() {
    try {
      getInstance().close();
    } catch (IOException e) {
      //Do Nothing
    }
  }

  public static class MysqlService implements Closeable, Serializable {
    private static final long serialVersionUID = -3560100625922230304L;
    private final HikariDataSource pool;

    private MysqlService() {
      super();
      HikariConfig config = new HikariConfig();
      config.setJdbcUrl(MYSQL_JDBC_URL);
      config.setUsername(MYSQL_JDBC_USERNAME);
      config.setPassword(MYSQL_JDBC_PASSWORD);
      config.addDataSourceProperty("cachePrepStmts", "true");
      config.addDataSourceProperty("prepStmtCacheSize", "250");
      config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
      config.addDataSourceProperty("useServerPrepStmts", "true");
      config.addDataSourceProperty("useLocalSessionState", "true");
      config.addDataSourceProperty("useLocalTransactionState", "true");
      config.addDataSourceProperty("rewriteBatchedStatements", "true");
      config.addDataSourceProperty("cacheResultSetMetadata", "true");
      config.addDataSourceProperty("cacheServerConfiguration", "true");
      config.addDataSourceProperty("elideSetAutoCommits", "true");
      config.addDataSourceProperty("maintainTimeStats", "false");
      config.setInitializationFailTimeout(5l);

      this.pool = new HikariDataSource(config);
    }

    @Override
    public void close() throws IOException {
      pool.close();
    }

    public HikariDataSource getPool() {
      return pool;
    }
  }
}
```

-----------------------------------------------------------------------------------------

How it's used

```
public class TransactionLock {

  public final static String LOCK_TABLE_NAME = "LockState";

  public static final long LOCK_EXPIRES_AFTER = TimeUnit.MINUTES.toMillis(5);

  private final static String SELECT_LOCK_QUERY = "SELECT * FROM  " + LOCK_TABLE_NAME + " WHERE lock_key = '%s'";
  private final static String INSERT_LOCK_QUERY = "INSERT INTO " + LOCK_TABLE_NAME
      + " (lock_key, sys_created_at) VALUES (%s, %d%n)";
  private final static String DELETE_LOCK_QUERY = "DELETE FROM " + LOCK_TABLE_NAME + "  WHERE lock_key = '%s'";

  private boolean lockAcquired = false;
  private String lockKey;
  private MysqlService mysql;
  
  public TransactionLock() {
    this.mysql = MysqlServiceFactory.getInstance();
  }


  /**
   * Block until lock is acquired
   * 
   * @param lockKey
   * @throws SQLException
   */
  public void acquireLock(String lockKey) throws SQLException {
    try (Connection con = mysql.getPool().getConnection()) {
      try (Statement stmt = con.createStatement()) {
        this.lockKey = lockKey;
        Long now = System.currentTimeMillis();
        try {
          String queryInsertLock = String.format(INSERT_LOCK_QUERY, lockKey, now);
          stmt.executeUpdate(queryInsertLock);
          this.lockAcquired = true;
        } catch (SQLException sqle) {
          // Already locked
          String querySelectLock = String.format(SELECT_LOCK_QUERY, lockKey);
          try (ResultSet rs = stmt.executeQuery(querySelectLock)) {
            if (rs.next()) {
              Long createdAt = rs.getLong("sys_created_at");
              if (now - createdAt > LOCK_EXPIRES_AFTER) {
                deleteLock();
                acquireLock(lockKey);
              }
            } else {
              acquireLock(lockKey);
            }
          }
        }
      }
    }
  }

  public void releaseLock() throws IllegalStateException, SQLException {
    if (this.lockAcquired) {
      deleteLock();
    } else {
      throw new IllegalStateException("Unable to releaseLock as lock wasn't accquired");
    }
  }

  private void deleteLock() throws SQLException {
    try (Connection con = mysql.getPool().getConnection()) {
      try (Statement stmt = con.createStatement()) {
        String queryDeleteLock = String.format(DELETE_LOCK_QUERY, this.lockKey);
        stmt.executeUpdate(queryDeleteLock);
        this.lockAcquired = false;
      }
    }
  }
}
```

The Unit test

```@RunWith(JUnit4.class)
public class TransactionLockTest {

  @Before
  public void before() {
  }

  @After
  public void after() {
  }

  public Long elapsed = 0l;

  Thread t = new Thread() {
    @Override
    public void run() {
      TransactionLock transactionLock = new TransactionLock();
      long before = System.currentTimeMillis();
      try {
        transactionLock.acquireLock("TEST_KEY");
        transactionLock.releaseLock();
      } catch (SQLException e1) {
        e1.printStackTrace();
        Assert.assertTrue("Sql Exception occured in the test", false);
      }
      elapsed = System.currentTimeMillis() - before;
      try {
        transactionLock.acquireLock("TEST_KEY");
      } catch (SQLException e) {
        e.printStackTrace();
      }

    }
  };

  @Test
  public void test() {
    try {
      TransactionLock transactionLock = new TransactionLock();
      transactionLock.acquireLock("TEST_KEY");
      t.start();
      Thread.sleep(500);
      transactionLock.releaseLock();
      Thread.sleep(300);
      Assert.assertTrue(elapsed >= 500l);
    } catch (Exception e) {
      e.printStackTrace();
    }finally{
      MysqlServiceFactory.close();
    }
  }
}
```

-----------------------------------------------------------------------------------------

The logs

```13:28:20,572 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - catalog.........................none
13:28:20,572 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - connectionInitSql...............none
13:28:20,573 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - connectionTestQuery.............none
13:28:20,573 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - connectionTimeout...............30000
13:28:20,573 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - dataSource......................none
13:28:20,573 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - dataSourceClassName.............none
13:28:20,574 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - dataSourceJNDI..................none
13:28:20,621 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - dataSourceProperties............{cacheServerConfiguration=true, useServerPrepStmts=true, elideSetAutoCommits=true, cachePrepStmts=true, rewriteBatchedStatements=true, cacheResultSetMetadata=true, useLocalSessionState=true, maintainTimeStats=false, prepStmtCacheSize=250, prepStmtCacheSqlLimit=2048, password=<masked>, useLocalTransactionState=true}
13:28:20,621 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - driverClassName.................none
13:28:20,621 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - healthCheckProperties...........{}
13:28:20,622 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - healthCheckRegistry.............none
13:28:20,622 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - idleTimeout.....................600000
13:28:20,622 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - initializationFailFast..........true
13:28:20,624 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - initializationFailTimeout.......5
13:28:20,624 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - isolateInternalQueries..........false
13:28:20,624 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - jdbc4ConnectionTest.............false
13:28:20,625 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - jdbcUrl.........................jdbc:mysql://localhost:3306/core?useSSL=false
13:28:20,625 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - leakDetectionThreshold..........0
13:28:20,625 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - maxLifetime.....................1800000
13:28:20,625 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - maximumPoolSize.................10
13:28:20,627 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - metricRegistry..................none
13:28:20,627 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - metricsTrackerFactory...........none
13:28:20,627 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - minimumIdle.....................10
13:28:20,628 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - password........................<masked>
13:28:20,628 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - poolName........................"HikariPool-1"
13:28:20,628 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - readOnly........................false
13:28:20,628 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - registerMbeans..................false
13:28:20,628 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - scheduledExecutor...............none
13:28:20,628 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - scheduledExecutorService........internal
13:28:20,629 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - schema..........................none
13:28:20,629 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - threadFactory...................internal
13:28:20,629 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - transactionIsolation............default
13:28:20,629 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - username........................"rbc"
13:28:20,629 DEBUG com.zaxxer.hikari.HikariConfig-logConfiguration:1085 - validationTimeout...............5000
13:28:20,630  INFO com.zaxxer.hikari.HikariDataSource-<init>:71 - HikariPool-1 - Starting...
13:28:21,113 DEBUG com.zaxxer.hikari.pool.HikariPool-checkFailFast:537 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5f683daf
13:28:21,115  INFO com.zaxxer.hikari.HikariDataSource-<init>:73 - HikariPool-1 - Start completed.
13:28:21,151 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@23c5ba7c
13:28:21,156 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@62f8b047
13:28:21,160 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5350d50a
13:28:21,166 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@2d74f08
13:28:21,172 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@4ebfd710
13:28:21,177 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@699316e
13:28:21,183 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@720c863e
13:28:21,190 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@602adfde
13:28:21,194 DEBUG com.zaxxer.hikari.pool.HikariPool-call:699 - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@21cd81a4
13:28:21,219 DEBUG com.zaxxer.hikari.pool.HikariPool-logPoolState:403 - HikariPool-1 - Pool stats (total=10, active=10, idle=0, waiting=1)
13:28:51,198 DEBUG com.zaxxer.hikari.pool.HikariPool-logPoolState:403 - HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=0)
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.13:28:51,201  INFO com.zaxxer.hikari.HikariDataSource-close:347 - HikariPool-1 - Shutdown initiated...
13:28:51,201 DEBUG com.zaxxer.hikari.pool.HikariPool-logPoolState:403 - HikariPool-1 - Before shutdown stats (total=10, active=0, idle=10, waiting=0)

	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:39)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.utils.TransactionLock.acquireLock(TransactionLock.java:58)
	at io.hotschedules.lake.TransactionLockTest.test(TransactionLockTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
13:28:51,203 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@5f683daf: (connection evicted)
13:28:51,205 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@23c5ba7c: (connection evicted)
13:28:51,206 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@62f8b047: (connection evicted)
13:28:51,206 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@5350d50a: (connection evicted)
13:28:51,206 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@2d74f08: (connection evicted)
13:28:51,206 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@4ebfd710: (connection evicted)
13:28:51,206 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@699316e: (connection evicted)
13:28:51,207 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@720c863e: (connection evicted)
13:28:51,207 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@602adfde: (connection evicted)
13:28:51,207 DEBUG com.zaxxer.hikari.pool.PoolBase-quietlyCloseConnection:137 - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@21cd81a4: (connection evicted)
13:28:51,212 DEBUG com.zaxxer.hikari.pool.HikariPool-logPoolState:403 - HikariPool-1 - After shutdown stats (total=0, active=0, idle=0, waiting=0)
13:28:51,212  INFO com.zaxxer.hikari.HikariDataSource-close:349 - HikariPool-1 - Shutdown completed.
```

I am able to connect to the database using the same driver and user/pass and connection URL through DbVisualizer.

I am using HikariCP in an other project (Keycloak) without any problem.

Can you help me solve this please

**Comment by PatrickSauts** [comment]
found my pb
sorry
