### ISSUE TITLE
 total connection would be reach the maxSize and idle connection could not be closed when idleTimeout

### ISSUE THREAD

**Issue by gaoquanbing-ausxin** [brettwooldridge/HikariCP#1037]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_144
Database        : mysql
Driver version  : 5.6.42
-----------------------------------------------------------------------------------------
database conf:

  context: amque
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@13221655

2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - configuration:
2017-12-01 20:02:55 DEBUG ~ allowPoolSuspension.............false
2017-12-01 20:02:55 DEBUG ~ autoCommit......................true
2017-12-01 20:02:55 DEBUG ~ catalog.........................none
2017-12-01 20:02:55 DEBUG ~ connectionInitSql...............none
2017-12-01 20:02:55 DEBUG ~ connectionTestQuery............."/* ping */ SELECT 1"
2017-12-01 20:02:55 DEBUG ~ connectionTimeout...............2000
2017-12-01 20:02:55 DEBUG ~ dataSource......................none
2017-12-01 20:02:55 DEBUG ~ dataSourceClassName.............none
2017-12-01 20:02:55 DEBUG ~ dataSourceJNDI..................none
2017-12-01 20:02:55 DEBUG ~ dataSourceProperties............{password=<masked>}
2017-12-01 20:02:55 DEBUG ~ driverClassName................."com.mysql.jdbc.Driver"
2017-12-01 20:02:55 DEBUG ~ healthCheckProperties...........{}
2017-12-01 20:02:55 DEBUG ~ healthCheckRegistry.............none
2017-12-01 20:02:55 DEBUG ~ idleTimeout.....................0
2017-12-01 20:02:55 DEBUG ~ initializationFailFast..........true
2017-12-01 20:02:55 DEBUG ~ initializationFailTimeout.......1
2017-12-01 20:02:55 DEBUG ~ isolateInternalQueries..........false
2017-12-01 20:02:55 DEBUG ~ jdbc4ConnectionTest.............false
2017-12-01 20:02:55 DEBUG ~ jdbcUrl...........................
useUnicode=true&characterEncoding=UTF-8"
2017-12-01 20:02:55 DEBUG ~ leakDetectionThreshold..........0
2017-12-01 20:02:55 DEBUG ~ maxLifetime.....................0
2017-12-01 20:02:55 DEBUG ~ maximumPoolSize.................120
2017-12-01 20:02:55 DEBUG ~ metricRegistry..................none
2017-12-01 20:02:55 DEBUG ~ metricsTrackerFactory...........none
2017-12-01 20:02:55 DEBUG ~ minimumIdle.....................5
2017-12-01 20:02:55 DEBUG ~ password........................<masked>
2017-12-01 20:02:55 DEBUG ~ poolName........................"HikariPool-1"
2017-12-01 20:02:55 DEBUG ~ readOnly........................false
2017-12-01 20:02:55 DEBUG ~ registerMbeans..................false
2017-12-01 20:02:55 DEBUG ~ scheduledExecutor...............none
2017-12-01 20:02:55 DEBUG ~ scheduledExecutorService........internal
2017-12-01 20:02:55 DEBUG ~ threadFactory...................internal
2017-12-01 20:02:55 DEBUG ~ transactionIsolation............default
2017-12-01 20:02:55 DEBUG ~ username........................"amque"
2017-12-01 20:02:55 DEBUG ~ validationTimeout...............5000
2017-12-01 20:02:55 INFO  ~ HikariPool-1 - Starting...
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@34f5438e
2017-12-01 20:02:55 INFO  ~ HikariPool-1 - Start completed.
2017-12-01 20:02:55 INFO  ~ ---------
useUnicode=true&characterEncoding=UTF-8 for default
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@df50c95
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@48eecff6
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6d45e414
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@d01288e
2017-12-01 20:02:55 DEBUG ~ HikariPool-1 - After adding stats (total=5, active=0, idle=5, waiting=0)
2017-12-01 20:02:58 INFO  ~ Guice injector created with modules: 
-----------------------------------------------------------------------------------------
2017-12-02 10:28:06 DEBUG ~ HikariPool-1 - Before cleanup stats (total=33, active=1, idle=32, waiting=0)
2017-12-02 10:28:06 DEBUG ~ HikariPool-1 - After cleanup  stats (total=33, active=1, idle=32, waiting=0)
2017-12-02 10:28:07 INFO  ~ ====================获取通话详单 
2017-12-02 10:28:12 INFO  ~ ====================获取通讯录   end====================
2017-12-02 10:28:12 INFO  ~ ************** init customerSegmentParam **************572
2017-12-02 10:28:12 INFO  ~ ************** init initSegmentInfoCache **************0
2017-12-02 10:28:12 INFO  ~ ************** init initChallengerFlowInfoCache **************216
2017-12-02 10:28:12 INFO  ~ ************** init initCustomerLabelInfo **************1
2017-12-02 10:28:12 INFO  ~ ************** init initCustomerParams **************0
2017-12-02 10:28:13 INFO  ~ ************** init customerSegmentParam **************604
2017-12-02 10:28:13 INFO  ~ ************** init initSegmentInfoCache **************0
2017-12-02 10:28:13 INFO  ~ ************** init initChallengerFlowInfoCache **************185
2017-12-02 10:28:13 INFO  ~ ************** init initCustomerLabelInfo **************0
2017-12-02 10:28:13 INFO  ~ ************** init initCustomerParams **************1
2017-12-02 10:28:14 INFO  ~ update firstValidCallTime
2017-12-02 10:28:14 INFO  ~ update latestValidCallTime
2017-12-02 10:28:14 INFO  ~ update latestFollowTime
2017-12-02 10:28:14 INFO  ~ Response JSON =>{"content":{"status":"FAILED","transResponse":"卡内可用余额不足，请换其他卡支付","date":"2017-12-02 05:05:39"},"result":"success","errors":[]}
2017-12-02 10:28:14 INFO  ~ ************** init customerSegmentParam **************710
2017-12-02 10:28:14 INFO  ~ ************** init initSegmentInfoCache **************0
2017-12-02 10:28:14 INFO  ~ ************** init initChallengerFlowInfoCache **************246
2017-12-02 10:28:14 INFO  ~ ************** init initCustomerLabelInfo **************1
2017-12-02 10:28:14 INFO  ~ ************** init initCustomerParams **************1
2017-12-02 10:28:15 INFO  ~ ************** init customerSegmentParam **************622
2017-12-02 10:28:17 INFO  ~ getImageInfo Parameter: loanCode[5847127]
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7383410d
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7fd115e
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@9135b68
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@52e08441
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@561a1047
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1c432626
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5e38c7a5
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5c0e23df
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1962a729
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@4fe0cddf
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5240106a
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@12265e89
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7b9a4efc
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@69bbc61
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@640135ba
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5e1b07bf
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@653b775c
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@678ae5de
2017-12-02 10:28:17 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@2d4330f5
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@24a102f1
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6cfc8bd
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1d1d8d61
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@27c49367
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@549c2fca
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@475b80b8
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@51b3bdc4
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@760aa832
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@24484338
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7211bc72
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@937b46b
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6f7ec153
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@50f322d3
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5490d1d4
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3f9c2b50
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@185ed191
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@189f11d8
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@20cf761c
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@47d745ca
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7d87fdd6
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6a88902c
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@145e3967
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5751ec8d
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@4c17c6c0
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@19218c0
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@c794910
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@234d5cc2
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@e837fc0
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@2390d41d
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@4a00bef3
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@121f403b
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@58b7afad
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@291bec2f
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@736ab532
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@79a139ad
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@522d81dc
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@60b60344
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@680776c6
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7bac87f0
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@2bbbdb69
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1a1ad557
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5feca030
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6e7b4d94
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7585282b
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6a276343
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3210b44b
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@2452d70f
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@71c8f3b3
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@e9de6f4
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1e17ddb3
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@4469c97
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@16281131
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1bf05eb1
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3b559baa
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@41eaf552
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@77a5af8b
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6f693690
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3826ec7d
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3f5b251
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@57a5d830
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@66eb2f53
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@5b2d2a56
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@1a5c66c0
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@32ff19e4
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3b66ba26
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@6c22b0dc
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3119ea1d
2017-12-02 10:28:18 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@39df8d56
2017-12-02 10:28:20 DEBUG ~ HikariPool-1 - Timeout failure stats (total=120, active=120, idle=0, waiting=26)
2017-12-02 10:28:20 DEBUG ~ HikariPool-1 - Timeout failure stats (total=120, active=120, idle=0, waiting=26)
2017-12-02 10:28:20 DEBUG ~ HikariPool-1 - Timeout failure stats (total=120, active=120, idle=0, waiting=25)
2017-12-02 10:28:20 DEBUG ~ HikariPool-1 - Timeout failure stats (total=120, active=120, idle=0, waiting=23)
2017-12-02 10:28:20 DEBUG ~ HikariPool-1 - Timeout failure stats (total=120, active=120, idle=0, waiting=23)
2017-12-02 10:28:20 ERROR ~ HikariPool-1 - Connection is not available, request timed out after 2000ms.
2017-12-02 10:28:20 ERROR ~ HikariPool-1 - Connection is not available, request timed out after 2000ms.
2017-12-02 10:28:20 ERROR ~ HikariPool-1 - Connection is not available, request timed out after 2000ms.
2017-12-02 10:28:20 ERROR ~ HikariPool-1 - Connection is not available, request timed out after 2000ms.
2017-12-02 10:28:20 ERROR ~ HikariPool-1 - Connection is not available, request timed out after 2000ms.
2017-12-02 10:28:20 DEBUG ~ HikariPool-1 - Timeout failure stats (total=120, active=120, idle=0, waiting=22)
2017-12-02 10:28:20 ERROR ~ HikariPool-1 - Connection is not available, request timed out after 2000ms.
2017-12-02 10:28:20 ERROR ~ 

@766oockh2
Internal Server Error (500)

Oops: PersistenceException
Unexpected error : Unexpected Error, caused by exception PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:255)
	at play.Invoker$Invocation.run(Invoker.java:317)
	at play.server.ServletWrapper$ServletInvocation.run(ServletWrapper.java:559)
	at play.Invoker.invokeInThread(Invoker.java:70)
	at play.server.ServletWrapper.service(ServletWrapper.java:147)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
	at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1397)
	at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:62)
	at play.db.jpa.JPA.withTransaction(JPA.java:249)
	at play.db.jpa.JPA.withinFilter(JPA.java:212)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:292)
	at play.Invoker$Invocation.withinFilter(Invoker.java:281)
	at play.Invoker$Invocation.run(Invoker.java:298)
	... 26 more
Caused by: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:67)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:221)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:157)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:160)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1387)
	at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:59)
	... 31 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 2000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.service.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:141)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:301)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:214)
	... 36 more
2017-12-02 10:28:20 ERROR ~ 

@766oockh3
Internal Server Error (500)

**Comment by brettwooldridge** [comment]
A few things.  You have idleTimeout=0 which means idle connections will never expire (see the documentation).  Second, your maxPoolSize is very high.  See [here](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).  Third, you may have a connection leak; enable the leakDetectionThreshold and watch the logs.  Lastly, please upgrade to the latest version.

**Comment by gaoquanbing-ausxin** [comment]
idleTimeout is like the confied 10min

2017-12-02 08:13:10 DEBUG ~ HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3a4dcb5d
2017-12-02 12:31:06 DEBUG ~ HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@3a4dcb5d: (connection has passed idleTimeout)

**Comment by gaoquanbing-ausxin** [comment]
@brettwooldridge  I have set the idletimeout: 2017-12-01 20:04:36 DEBUG ~ idleTimeout.....................600000

**Comment by gaoquanbing-ausxin** [comment]
@brettwooldridge  thanks, I will enable the leakDetectionThreshold and watch the logs

**Comment by brettwooldridge** [comment]
@gaoquanbing-ausxin Sorry, I was reading on my iPhone ... the way the text wrapped I only saw a zero for the ``idleTimeout``.  The default should be fine.

**Comment by gaoquanbing-ausxin** [comment]
I have upgrade HikariCP version: 2.6.3 to 2.7.4 and enable the leakDetectionThreshold and get some logs as follow, but I still could not get the solution from logs

2017-12-15 10:09:11 WARN  ~ Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@321c35f9 on thread jobs-thread-8, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.service.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:141)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:301)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:214)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:157)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:160)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1387)
	at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:59)
	at play.db.jpa.JPA.withTransaction(JPA.java:249)
	at play.db.jpa.JPA.withinFilter(JPA.java:212)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:292)
	at play.jobs.Job.withinFilter(Job.java:185)
	at play.jobs.Job.call(Job.java:204)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gaoquanbing-ausxin** [comment]
@brettwooldridge  thanks, I have found why my system connection leak;  there is a place in code that a connection is closed before preparestatement closing. as follow:
        
        .....
        customerExtUpdatePst.close();
        customerUpdatePst.close();
        writeConnection.close();
        readStatement.close();
        .....


I have modified the closing sequence(close preparement and then close connetion ) and the system is running good! 
also , I set the maximumPoolSize lower than before, 

2018-01-10 12:30:16 DEBUG ~ HikariPool-1 - configuration:
2018-01-10 12:30:16 DEBUG ~ allowPoolSuspension.............false
2018-01-10 12:30:16 DEBUG ~ autoCommit......................true
2018-01-10 12:30:16 DEBUG ~ catalog.........................none
2018-01-10 12:30:16 DEBUG ~ connectionInitSql...............none
2018-01-10 12:30:16 DEBUG ~ connectionTestQuery............."/* ping */ SELECT 1"
2018-01-10 12:30:16 DEBUG ~ connectionTimeout...............2000
2018-01-10 12:30:16 DEBUG ~ dataSource......................none
2018-01-10 12:30:16 DEBUG ~ dataSourceClassName.............none
2018-01-10 12:30:16 DEBUG ~ dataSourceJNDI..................none
2018-01-10 12:30:16 DEBUG ~ dataSourceProperties............{password=<masked>}
2018-01-10 12:30:16 DEBUG ~ driverClassName................."com.mysql.jdbc.Driver"
2018-01-10 12:30:16 DEBUG ~ healthCheckProperties...........{}
2018-01-10 12:30:16 DEBUG ~ healthCheckRegistry.............none
2018-01-10 12:30:16 DEBUG ~ idleTimeout.....................600000
2018-01-10 12:30:16 DEBUG ~ initializationFailFast..........true
2018-01-10 12:30:16 DEBUG ~ initializationFailTimeout.......1
2018-01-10 12:30:16 DEBUG ~ isolateInternalQueries..........false
2018-01-10 12:30:16 DEBUG ~ jdbc4ConnectionTest.............false
2018-01-10 12:30:16 DEBUG ~ jdbcUrl.........................
2018-01-10 12:30:16 DEBUG ~ leakDetectionThreshold..........0
2018-01-10 12:30:16 DEBUG ~ maxLifetime.....................0
2018-01-10 12:30:16 DEBUG ~ maximumPoolSize.................48
2018-01-10 12:30:16 DEBUG ~ metricRegistry..................none
2018-01-10 12:30:16 DEBUG ~ metricsTrackerFactory...........none
2018-01-10 12:30:16 DEBUG ~ minimumIdle.....................5
2018-01-10 12:30:16 DEBUG ~ password........................<masked>
2018-01-10 12:30:16 DEBUG ~ poolName........................"HikariPool-1"
2018-01-10 12:30:16 DEBUG ~ readOnly........................false
2018-01-10 12:30:16 DEBUG ~ registerMbeans..................false
2018-01-10 12:30:16 DEBUG ~ scheduledExecutor...............none
2018-01-10 12:30:16 DEBUG ~ scheduledExecutorService........internal
2018-01-10 12:30:16 DEBUG ~ schema..........................none
2018-01-10 12:30:16 DEBUG ~ threadFactory...................internal
2018-01-10 12:30:16 DEBUG ~ transactionIsolation............default
2018-01-10 12:30:16 DEBUG ~ username........................"amque"
2018-01-10 12:30:16 DEBUG ~ validationTimeout...............1500
2018-01-10 12:30:16 INFO  ~ HikariPool-1 - Starting...

**Comment by brettwooldridge** [comment]
@gaoquanbing-ausxin Hmmm, that is disturbing.  Closing the Connection before the Statement should not cause a leak.  The close() method has [explicit code](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L233) to close all open Statements when the Connection itself is closed.

Are you *sure* that is the source of the leak?
