### ISSUE TITLE
PostgreSQL   relation "mytable" does not exist

### ISSUE THREAD

**Issue by sergioszy** [brettwooldridge/HikariCP#1044]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 1.8.0_102
Database        : PostgreSQL
Driver version  : postgresql-42.1.4.jar
```

PreparedStatement prepared = connection.preparedStatement(
"select mytable.column1, mytable.column2 from mytable where mytable.column1 > 0" );  //OK

When execute  resultSet = prepared.executeQuery();

throws this exception 

org.postgresql.util.PSQLException: ERROR: relation mytable does not exist
  Position: 176
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)

-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
This is not a HikariCP question, this is a PostgreSQL question.

PostgreSQL will not throw an error on prepare, even if the relation does not exist, because the driver will not actually prepare the statement until it has been executed several times.  Creating a Statement via ``Statement stmt = connection.createStatement()``, and then executing the same query via ``resultSet = stmt.executeQuery("select ...")`` will fail with the same error.

You may be connecting to PostgreSQL server, but you are not connecting to the *database* which contains that table.  Either specifiy the database, or check that the user has permission to see that table.

**Comment by sergioszy** [comment]
But, if I use directly the PGSimpleDatasource everthing is OK. Then the problem is in how HikariCP 


**this run OK**
		try {
			PGSimpleDataSource pgds = new PGSimpleDataSource();
			pgds.setUser("postgres");
			pgds.setUrl("jdbc:postgresql://10.1.2.5:5432/database");
			pgds.setPassword("mypass");
			pgds.setApplicationName("asdfdasfsdaf");
			
			Connection connection=  pgds.getConnection();
			System.out.println("asfsafsafasf");
			PreparedStatement pstmt= connection.prepareStatement(
					"select nttipo.codigo_c, nttipo.descrp_c, nttipo.nttipo_o from nttipo  " );
			ResultSet rs = pstmt.executeQuery();
			while ( rs.next() ) {
				System.out.println( rs.getObject(1) + ":" + rs.getObject(2));
			}
		}
		catch(Exception e) {
			e.printStackTrace();
		}

**this throws Exception**
		try {
			HikariConfig config = new HikariConfig();
			config.setJdbcUrl( "jdbc:postgresql://10.1.2.5:5432/database" );
			config.setUsername( "postgres" );
			config.setPassword( "mypass" );
			config.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
			
			HikariDataSource pgds = new HikariDataSource(config);
			
			Connection connection=  pgds.getConnection();
			System.out.println("asfsafsafasf");
			PreparedStatement pstmt= connection.prepareStatement(
					"select nttipo.codigo_c, nttipo.descrp_c, nttipo.nttipo_o from nttipo  " );
			
			ResultSet rs = pstmt.executeQuery();
			while ( rs.next() ) {
				System.out.println( rs.getObject(1) + ":" + rs.getObject(2));
			}
	
		}
		catch(Exception e) {
			e.printStackTrace();
		}


org.postgresql.util.PSQLException: ERROR: relation "nttipo" does not exist
  Position: 63
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at nova.test.entity.TestDatasource.<init>(TestDatasource.java:89)

Thanks for your response,

**Comment by brettwooldridge** [comment]
You are mixing *jdbcUrl*-based and *DataSource*-based configuration.

You can use either jdcbUrl configuration, without specifying a DataSource class name:
```
HikariConfig config = new HikariConfig();
config.setJdbcUrl( "jdbc:postgresql://10.1.2.5:5432/database" );
config.setUsername( "postgres" );
config.setPassword( "mypass” );
```
*Or*, do not use a jdbcURL, and configure the DataSource via properties:
```
HikariConfig config = new HikariConfig();
config.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
config.setUsername( "postgres" );
config.setPassword( "mypass" );
config.addDataSourceProperty("serverName", "10.1.2.5");
config.addDataSourceProperty("portNumber", "5432");
config.addDataSourceProperty("databaseName", "database");
```
