### ISSUE TITLE
Hikari 2.7.4 with solr-solrj 7.1.0

### ISSUE THREAD

**Issue by natpoornal** [brettwooldridge/HikariCP#1048]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 1.8.0_111
Database        : SOLR
Driver version  : solr-solrj 7.1.0
```
Connection Pool is not getting initialized due to the following exception:

2017-12-20 03:13:23.836 ERROR 12296 --- [io-19091-exec-7] com.zaxxer.hikari.pool.HikariPool        : HikariPool-4 - Exception during pool initialization.

java.lang.UnsupportedOperationException: null
	at org.apache.solr.client.solrj.io.sql.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:189) ~[solr-solrj-7.1.0.jar!/:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:16:00]
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:467) ~[HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:422) ~[HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:380) ~[HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204) ~[HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459) [HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533) [HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114) [HikariCP-2.7.4.jar!/:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97) [HikariCP-2.7.4.jar!/:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:600) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:682) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:736) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:199) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:279) [spring-jdbc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@natpoornal Please open an issue against solrj.  ``Connection.getTransactionIsolation()`` [should return](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#TRANSACTION_NONE)  ``TRANSACTION_NONE``:
> TRANSACTION_NONE
A constant indicating that transactions are not supported.
