### ISSUE TITLE
PostgreSQL | PSQLException: This ResultSet is closed (on getting connection from pool).

### ISSUE THREAD

**Issue by didjee2** [brettwooldridge/HikariCP#1066]
#### Environment
```
HikariCP version    : 2.7.4
JDK version         : 1.8.0_144
Database            : PostgreSQL
Driver version      : 10.1
Operating System : Windows
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already?* Yes
*How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?* Yes
In both of these I didn't really find the same issue.

I am having the following error with HikariCP, saying that the ResultSet is closed, and this happens when I try to get a connection out of the pool:
```
11:48:35 [SEVERE] java.sql.SQLTransientConnectionException: BungeeUtilisals - Connection is not available, request timed out after 8001ms.
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
11:48:35 [SEVERE]     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
11:48:35 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.storage.hikari.PostgreSQLStorageManager.getConnection(PostgreSQLStorageManager.java:31)
11:48:35 [SEVERE]     at com.dbsoftwares.bungeeutilisals.api.storage.AbstractStorageManager.initialize(AbstractStorageManager.java:49)
11:48:35 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.BungeeUtilisals.loadDatabase(BungeeUtilisals.java:148)
11:48:35 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.BungeeUtilisals.onEnable(BungeeUtilisals.java:87)
11:48:35 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
11:48:35 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
11:48:35 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
11:48:35 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
11:48:35 [SEVERE] Caused by: com.zaxxer.hikari.pool.PoolBase$ConnectionSetupException: org.postgresql.util.PSQLException: This ResultSet is closed.
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:441)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:380)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:70)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:696)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:682)
11:48:35 [SEVERE]     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
11:48:35 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
11:48:35 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
11:48:35 [SEVERE]     at java.base/java.lang.Thread.run(Unknown Source)
11:48:35 [SEVERE] Caused by: org.postgresql.util.PSQLException: This ResultSet is closed.
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2654)
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1771)
11:48:35 [SEVERE]     at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:39)
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:211)
11:48:35 [SEVERE]     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1773)
11:48:35 [SEVERE]     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:263)
11:48:35 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:775)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:467)
11:48:35 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:422)
11:48:35 [SEVERE]     ... 10 more
```

This is how I initialize the DataSource:
```
        config = new HikariConfig();
        config.setDataSourceClassName(Utils.classFound("org.postgresql.ds.PGSimpleDataSource") ? "org.postgresql.ds.PGSimpleDataSource" : "com.impossibl.postgres.jdbc.PGDataSource");
        config.addDataSourceProperty("serverName", configuration.getString("storage.hostname"));
        config.addDataSourceProperty("portNumber", configuration.getInteger("storage.port"));
        config.addDataSourceProperty("databaseName", configuration.getString("storage.database"));
        config.addDataSourceProperty("user", configuration.getString("storage.username"));
        config.addDataSourceProperty("password", configuration.getString("storage.password"));

        config.setMaximumPoolSize(configuration.getInteger("storage.pool.max-pool-size"));
        config.setMinimumIdle(configuration.getInteger("storage.pool.min-idle"));
        config.setMaxLifetime(configuration.getInteger("storage.pool.max-lifetime") * 1000);
        config.setConnectionTimeout(configuration.getInteger("storage.pool.connection-timeout") * 1000);

        config.setPoolName("BungeeUtilisals");
        config.setLeakDetectionThreshold(10000);
        config.setConnectionTestQuery("/* BungeeUtilisals ping */ SELECT 1;");

        try {
            config.setInitializationFailTimeout(-1);
        } catch (NoSuchMethodError e) {
            config.setInitializationFailFast(false);
        }
        dataSource = new HikariDataSource(config);
```
I tried setting up the database with config.setPassword() and config.setUsername(), which made no difference.

My getConnection() method on which the error occurs (shouldn't be the issue though):
```
    @Override
    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }
```

My initialize function (being executed after class (and datasource) construction):
```
        try (InputStream is = plugin.getResourceAsStream(type.getSchema())) {
            if (is == null) {
                throw new Exception("Could not find schema for " + type.toString() + ": " + type.getSchema() + "!");
            }
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8)); Connection connection = getConnection(); Statement st = connection.createStatement()) {

                StringBuilder builder = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    builder.append(line);

                    if (line.endsWith(";")) {
                        builder.deleteCharAt(builder.length() - 1);

                        String statement = PlaceHolderAPI.formatMessage(builder.toString().trim());
                        if (!statement.isEmpty()) {
                            st.addBatch(statement);
                        }

                        builder = new StringBuilder();
                    }
                }
                st.executeBatch();
            }
        }
```

The error itself happens on this line:
```
try (BufferedReader reader = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8)); Connection connection = getConnection(); Statement st = connection.createStatement()) {
```

I load in libraries in the following way (in case the classes ain't present):
https://hastebin.com/cuyoreyebi.java

My plugin is supposed to support MySQL, MariaDB, SQLite & PostgreSQL, the first three work fine with the same settings (other ports ofcourse).

I import HikariCP (using maven) in the following way:
```
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.7.4</version>
        </dependency>
```

**Comment by didjee2** [comment]
Added information on how I import HikariCP

**Comment by didjee2** [comment]
Still having same issue after upgrading to HikariCP 2.7.6: https://hastebin.com/quxuqicozu.vbs

**Comment by brettwooldridge** [comment]
@didjee2 How many statements in the batch?

**Comment by didjee2** [comment]
Uhm 26 I think: https://hastebin.com/qiramiqoco.sql
Is there a limit on that?

Using it quite similar for SQLite, but without a pool there.

MySQL & MariaDB (with pool) have less statements (they don't have a separate create index statement).

**Comment by brettwooldridge** [comment]
@didjee2 All of the lines are DDL?

If there are only 26 statements, you might try executing each individually.  Also, I don't think you can mix DDL and DML in the same batch in PostgreSQL (but I could be mistaken).

**Comment by didjee2** [comment]
All statements are DDL statements. I just tried using this code:
```
        try (InputStream is = plugin.getResourceAsStream(type.getSchema())) {
            if (is == null) {
                throw new Exception("Could not find schema for " + type.toString() + ": " + type.getSchema() + "!");
            }
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8));
                 Connection connection = getConnection(); Statement st = connection.createStatement()) {

                StringBuilder builder = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    builder.append(line);

                    if (line.endsWith(";")) {
                        builder.deleteCharAt(builder.length() - 1);

                        String statement = PlaceHolderAPI.formatMessage(builder.toString().trim());
                        if (!statement.isEmpty()) {
                            st.executeUpdate(statement);
                        }

                        builder = new StringBuilder();
                    }
                }
            }
        }
```

And the same error pops up:
```
15:29:23 [SEVERE] java.sql.SQLTransientConnectionException: BungeeUtilisals - Connection is not available, request timed out after 8002ms.
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
15:29:23 [SEVERE]     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:95)
15:29:23 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.storage.hikari.PostgreSQLStorageManager.getConnection(PostgreSQLStorageManager.java:31)
15:29:23 [SEVERE]     at com.dbsoftwares.bungeeutilisals.api.storage.AbstractStorageManager.initialize(AbstractStorageManager.java:49)
15:29:23 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.BungeeUtilisals.loadDatabase(BungeeUtilisals.java:148)
15:29:23 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.BungeeUtilisals.onEnable(BungeeUtilisals.java:87)
15:29:23 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
15:29:23 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
15:29:23 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
15:29:23 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
15:29:23 [SEVERE] Caused by: com.zaxxer.hikari.pool.PoolBase$ConnectionSetupException: org.postgresql.util.PSQLException: This ResultSet is closed.
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:441)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:380)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:70)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:696)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:682)
15:29:23 [SEVERE]     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
15:29:23 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
15:29:23 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
15:29:23 [SEVERE]     at java.base/java.lang.Thread.run(Unknown Source)
15:29:23 [SEVERE] Caused by: org.postgresql.util.PSQLException: This ResultSet is closed.
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2654)
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1771)
15:29:23 [SEVERE]     at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:39)
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:211)
15:29:23 [SEVERE]     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1773)
15:29:23 [SEVERE]     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:263)
15:29:23 [SEVERE]     at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:775)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:467)
15:29:23 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:422)
15:29:23 [SEVERE]     ... 10 more
```

Error keeps on happening in this part:
```
 Connection connection = getConnection();
```

**Comment by didjee2** [comment]
After watching the HikariCP source code and testing a little bit, I tried removing the ConnectionTestQuery, after which the error changed. It could not connect to the server.

Now I am having this error:
```
16:26:48 [SEVERE] java.sql.SQLTransientConnectionException: BungeeUtilisals - Connection is not available, request timed out after 8002ms.
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
16:26:48 [SEVERE]     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:95)
16:26:48 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.storage.hikari.PostgreSQLStorageManager.getConnection(PostgreSQLStorageManager.java:30)
16:26:48 [SEVERE]     at com.dbsoftwares.bungeeutilisals.api.storage.AbstractStorageManager.initialize(AbstractStorageManager.java:49)
16:26:48 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.BungeeUtilisals.loadDatabase(BungeeUtilisals.java:148)
16:26:48 [SEVERE]     at com.dbsoftwares.bungeeutilisals.bungee.BungeeUtilisals.onEnable(BungeeUtilisals.java:87)
16:26:48 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
16:26:48 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
16:26:48 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
16:26:48 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
16:26:48 [SEVERE] Caused by: com.zaxxer.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Connection.isValid(int) is not yet implemented.
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:441)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:380)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:70)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:696)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:682)
16:26:48 [SEVERE]     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
16:26:48 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
16:26:48 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
16:26:48 [SEVERE]     at java.base/java.lang.Thread.run(Unknown Source)
16:26:48 [SEVERE] Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Connection.isValid(int) is not yet implemented.
16:26:48 [SEVERE]     at org.postgresql.Driver.notImplemented(Driver.java:753)
16:26:48 [SEVERE]     at org.postgresql.jdbc4.AbstractJdbc4Connection.isValid(AbstractJdbc4Connection.java:120)
16:26:48 [SEVERE]     at org.postgresql.jdbc4.Jdbc4Connection.isValid(Jdbc4Connection.java:21)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:455)
16:26:48 [SEVERE]     at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:422)
16:26:48 [SEVERE]     ... 10 more
```

**Comment by didjee2** [comment]
Got it to work now, I was downloading the wrong libary, which is why the method wasn't implemented yet.

Thank you for your help on this, sorry if I wasted your time.

**Comment by brettwooldridge** [comment]
@didjee2 No problem, glad you got it working.  Welcome to HikariCP.

**Comment by SandeepSoni123** [comment]
> Got it to work now, I was downloading the wrong library, which is why the method wasn't implemented yet.
> 
> Thank you for your help on this, sorry if I wasted your time.

can i know  library

**Comment by dieterblancke** [comment]
The library class can be found on my git(lab): https://git.dbsoftwares.eu/dbsoftwares/BungeeUtilisalsX/blob/master/bungee/src/main/java/com/dbsoftwares/bungeeutilisals/library/StandardLibrary.java#L38-43

https://mvnrepository.com/artifact/org.postgresql/postgresql is where you can find the versions of it (and I now found out I'm running 1 version behind :P )
