### ISSUE TITLE
Connection recovery with multi-node JDBC URL and PgSQL

### ISSUE THREAD

**Issue by MaZaL0veR** [brettwooldridge/HikariCP#1067]
#### Environment
```
HikariCP version: 2.7.4
JDK version     : 1.8.0_151
Database        : PostgreSQL 9.6
Driver version  : 42.1.4
```
-----------------------------------------------------------------------------------------
I'm running a master-slave configuration with a streaming replication, and a java program that runs in an endless loop with a ```30s``` pause between iterations and gets 1st employee from database and prints it. I get my connections via HikariCP with ```jdbcUrl=jdbc:postgresql://10.0.0.1,10.0.0.2/metacortex?user=neo&password=&socketTimeout=1``` and also
```
connectionTimeout=1500
validationTimeout=1300
maximumPoolSize=1
```
During 1st pause, I shut down network interface on primary node, here is the print out
```
13:10:16.669: Getting user
13:10:16.681: Thomas A Anderson
13:10:46.696: Getting user
Jan 18, 2018 1:10:57 PM org.postgresql.jdbc.PgConnection isValid
WARNING: Validating connection.
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1311)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:160)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:171)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at com.mycompany.primer.db.pg.HikariPgJdbcLoadBalancingTest2.run(HikariPgJdbcLoadBalancingTest2.java:33)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:288)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1963)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	... 11 more

13:10:57.723: Query failed
13:10:57.723: Getting user
13:10:59.224: Query failed
13:10:59.224: Getting user
13:11:00.725: Query failed
13:11:00.725: Getting user
13:11:00.796: Thomas A Anderson
13:11:30.796: Getting user
13:11:30.799: Thomas A Anderson
```
My understanding is that when I get a pooled connection, following should happen
1. Validate connection, e.g. ping database and blow up if no response is received within ```socketTimeout=1```
2. Retry validation until ```validationTimeout=1300``` is reached, then blow up
3. Give up on getting connection within ```connectionTimeout=1500``` and blow up, close the connection

I don't understand why it took ```11.027s``` to fail 1st time? Why not ```1.5s```?
Note, that subsequent attempts fail within ```1.5s```.

I don't understand why it didn't recover on the next try? 
Because ```maximumPoolSize=1```, I would expect a new JDBC connection to be created when I request it during next iteration. And that should use standby server as a simple test with reopening PostgreSQL JDBC connections shows.

**Comment by MaZaL0veR** [comment]
Code,
``
package com.mycompany.primer.db.pg;

import static java.lang.System.out;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Properties;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

public class HikariPgJdbcLoadBalancingTest2 implements Runnable {
	
	private static HikariDataSource db;
	private static DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");
		
	/**
	 * targetServerType=preferSlave
	 * loadBalanceHosts=true
	 */
	private static String jdbcUrl = 
		"jdbc:postgresql://10.0.0.1,10.0.0.2/metacortex?"
		+ "user=neo&password="
		+ "&socketTimeout=1";
		
	public void run() {
		while (true) {
			long startTime = System.currentTimeMillis();
			out.printf("%s: Getting user\n", getTime());
			try (Connection dbConnection = db.getConnection()) {
				ResultSet employeeRecord = dbConnection.createStatement().executeQuery("select * from employees where id = 1");
				employeeRecord.next();
				printEmployeeRecord(employeeRecord, startTime);    
				Thread.sleep(30000);
			} catch (SQLException e) {
				out.printf("%s: Query failed\n", getTime());
			} catch (InterruptedException e) {
				out.println("%s: Thread was interrupted");
			}
		}
	}
	
	
	public static void main(String[] args) {
		Properties dbConfigProperties = new Properties();
		dbConfigProperties.setProperty("connectionTimeout", "1500");
		dbConfigProperties.setProperty("validationTimeout", "1200");
		dbConfigProperties.setProperty("maximumPoolSize", "1");
		dbConfigProperties.setProperty("jdbcUrl", jdbcUrl);

		db = new HikariDataSource(new HikariConfig(dbConfigProperties));

		new Thread(new HikariPgJdbcLoadBalancingTest2()).start();
	}
	
	public String getTime() {
		return dateFormatter.format(LocalDateTime.now());
	}
	public long getDuration(long startTime) {
		return System.currentTimeMillis() - startTime;	
	}
	
	public void printEmployeeRecord(ResultSet employeeRecord, long startTime) throws SQLException {
		out.printf("%s: %s %s %s\n",
			getTime(),
			employeeRecord.getString(2), 
			employeeRecord.getString(3),
			employeeRecord.getString(4)
		);
	}
}

**Comment by MaZaL0veR** [comment]
I think, I missed ```loadBalanceHosts=true``` in the ```jdbcUrl```. Closing.
