### ISSUE TITLE
ClassCastException: com.zaxxer.hikari.pool.PoolEntry cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by benoit-ponsero** [brettwooldridge/HikariCP#1072]
#### Environment
```
HikariCP version: 2.7.1
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 5.1.44
```
-----------------------------------------------------------------------------------------
Caused by: java.lang.ClassCastException: com.zaxxer.hikari.pool.PoolEntry cannot be cast to java.lang.String
        at scalikejdbc.Binders$$anon$2.apply(Binders.scala:36)
        at scalikejdbc.interpolation.SQLSyntax.eq(SQLSyntax.scala:68)
        at scalikejdbc.interpolation.SQLSyntax$.eq(SQLSyntax.scala:286)
        at net.smartbe.contract.market.Currency$.findByCode(Currency.scala:144)

Hello,

I had this error 2 times in a week on a production app. I don't understand what cause this. Someone have an idea ?
After the first exception, no more db request of this function can be performed, but other db request in the app can be.

**Comment by brettwooldridge** [comment]
@benoit-ponsero Please open an issue against scalikejdbc, this is not a HikariCP bug.
