### ISSUE TITLE
Frequent occurrences of "Closing connection com.mysql.jdbc.JDBC4Connection@xx: (connection is dead)"

### ISSUE THREAD

**Issue by rohitmukherjee** [brettwooldridge/HikariCP#1079]
#### Environment
```
HikariCP version: 2.7.6
JDK version     : 1.8.0_111
Database        : MariaDB
Driver version  : JDBC4
Slick version:  2.1.0
mysql-connector-j version: 5.1.34

```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

Hi Brett,

Firstly, thanks for writing such a well-documented and well-maintained library. I'm migrating a large Scala application using slick 2.1.0 from c3p0 to hikariCP. 

The reason for the switch is because our application runs a cron that runs on ~40K records and ends up locking and the entire thread pool ends up waiting and the app becomes unresponsive.

My connection settings for HikariCP are as follows:

```
2018-02-04 19:10:29,555 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
2018-02-04 19:10:29,558 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
2018-02-04 19:10:29,558 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
2018-02-04 19:10:29,558 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
2018-02-04 19:10:29,558 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............none
2018-02-04 19:10:29,559 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
2018-02-04 19:10:29,559 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
2018-02-04 19:10:29,559 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
2018-02-04 19:10:29,559 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
2018-02-04 19:10:29,562 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>, cachePrepStmts=true}
2018-02-04 19:10:29,562 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................."com.mysql.jdbc.Driver"
2018-02-04 19:10:29,562 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
2018-02-04 19:10:29,562 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
2018-02-04 19:10:29,563 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
2018-02-04 19:10:29,563 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
2018-02-04 19:10:29,563 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
2018-02-04 19:10:29,563 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
2018-02-04 19:10:29,564 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
2018-02-04 19:10:29,564 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:mysql://localhost:3306/nv_am
2018-02-04 19:10:29,564 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
2018-02-04 19:10:29,564 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................28770000
2018-02-04 19:10:29,564 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................100
2018-02-04 19:10:29,565 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
2018-02-04 19:10:29,565 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
2018-02-04 19:10:29,565 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................100
2018-02-04 19:10:29,565 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
2018-02-04 19:10:29,565 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-1"
2018-02-04 19:10:29,565 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
2018-02-04 19:10:29,566 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
2018-02-04 19:10:29,566 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
2018-02-04 19:10:29,566 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........internal
2018-02-04 19:10:29,566 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - schema..........................none
2018-02-04 19:10:29,566 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
2018-02-04 19:10:29,567 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
2018-02-04 19:10:29,567 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - username........................"user"
2018-02-04 19:10:29,567 [primary-pool-3] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
```
I keep seeing this debug statement in our app logs:

```2018-02-04 00:03:29,117 [primary-pool-98] WARN  com.zaxxer.hikari.pool.PoolBase - primary-db-pool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@1e2d1bc4 (No operations allowed after      connection closed.)
2018-02-04 00:03:29,117 [primary-db-pool connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - primary-db-pool - Closing connection com.mysql.jdbc.JDBC4Connection@5617f214 failed
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
    at sun.reflect.GeneratedConstructorAccessor99.newInstance(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_141]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_141]
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1232) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1225) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5532) ~[mysql-connector-java-5.1.34.jar:5.1.34]
    at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:551) ~[HikariCP-2.7.6.jar:na]
    at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:139) ~[HikariCP-2.7.6.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:433) [HikariCP-2.7.6.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Thr
```

Is this normal?

I also see this warning:

```
[primary-pool-98] WARN  com.zaxxer.hikari.pool.PoolBase - primary-db-pool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@26176197 (No operations allowed after      connection closed.)
```

The MySQL wait_timeout is 28800000 ms, so changing maxLifeTime to 28770000 ms still seems to log these warnings/debug statements. I'd really appreciate some help with this, as I'd like to migrate from c3p0 as soon as possible but I can't confidently shift to HikariCP unless I know that our configuration/usage is correct.

Thanks,
Rohit

**Comment by brettwooldridge** [comment]
@rohitmukherjee The good news is that it (basically) all looks normal ('ish).

The first exception (logged at DEBUG) is not very surprising.  HikariCP detected a "broken" connection, and calls ``close()`` *anyway* in order to give the driver the opportunity to clean up resources.  Sometimes these Connections are already closed, from the perspective of the driver, and therefore an exception is thrown.  It is normal.  The [log just before that exception](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L137) might provide more context on why the connection was being closed.  Likely, it failed validation.

The second warning is also not an issue, but indicates a possibly sub-optimal configuration.  Basically, it is better for HikariCP to evict connections in the background, on its own schedule, rather than detecting a closed/broken Connection at the time when one is requested.

The important question to be answered (for you), whether any exceptions have reached the application itself.  The two above exceptions would not do so.

You mention that ``wait_timeout`` is ``28800000``.  I hope that is a *translation* of the ``wait_timeout`` value, because the ``wait_timeout`` value itself is [given in seconds](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout) rather than milliseconds.

Regardless, I recommend a much shorter timeout in HikariCP.  The default (30 minutes) is a pretty good choice.  HikariCP retires and replaces connections in the background and distributes the retirements over time.  Typically the retirement/replacement time is measured in milliseconds and takes place in the background, so the effects would be extremely difficult to detect at the application level.

**Comment by rohitmukherjee** [comment]
@brettwooldridge Thanks for the prompt response.

> You mention that wait_timeout is 28800000. I hope that is a translation of the wait_timeout value, because the wait_timeout value itself is given in seconds rather than milliseconds.

Yes, I translated it to milliseconds. I'll test the app using Hikari's default timeout.

I have two other questions:
1. Is `maximumPoolSize = 100` sufficient? We used to have the same maximum pool size using c3p0 but the cron used to move much quicker. This leads me to my next question
2. We used to run c3p0 with `validateConnectionOnCheckout = false`. HikariCP validates connections older than 100s so the check shouldn't add too much overhead. Is there something wrong with my selection of `maximumPoolSize`? 

We need a sufficiently large pool as the service might take some web requests while running the cron.

**Comment by brettwooldridge** [comment]
@rohitmukherjee 100 connections seems large, but you know your application best.  My advice would be to take some imperical measurements of the pool to determine the *actual* high-water mark.  Enable JMX metrics, and use JConsole or VisualVM to graph the *active* connections.  When you think you have enough coverage, set the pool at 10-20% higher than that high-water mark.

**Comment by brettwooldridge** [comment]
@rohitmukherjee As mentioned in [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing):

> ... systems with a mix of long running transactions and very short transactions are generally the most difficult to tune with any connection pool. In those cases, creating two pool instances can work well (eg. one for long-running jobs, another for "realtime" queries).

**Comment by rohitmukherjee** [comment]
@brettwooldridge Thanks, I think I'll do some profiling using VisualVM and post my findings back here. 
I'll close the issue after posting my results.

Cheers,
Rohit

**Comment by rohitmukherjee** [comment]
Hi @brettwooldridge

I tried deploying the app with the default `maxLifeTime` and a poolSize = 80 to start profiling. I'm now seeing Timeout Failure Stats as follows:

```2018-02-07 01:30:25,247 [primary-pool-201] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=127)
2018-02-07 01:30:26,235 [primary-pool-261] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=127)
2018-02-07 01:30:26,643 [primary-pool-219] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=127)
2018-02-07 01:30:27,317 [primary-pool-286] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=128)
2018-02-07 01:30:28,253 [primary-pool-276] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=128)
2018-02-07 01:30:29,528 [primary-pool-191] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=130)
2018-02-07 01:30:29,697 [primary-pool-168] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=130)
2018-02-07 01:30:30,125 [primary-pool-200] DEBUG com.zaxxer.hikari.pool.HikariPool - db-pool - Timeout failure stats (total=80, active=80, idle=0, waiting=130)
```

the waiting number keeps growing and the cron thread eventually dies. The strange thing is that I don't see this issue when I'm running the service locally and connecting to the remote database. 

Based on https://github.com/brettwooldridge/HikariCP/issues/830, this might indicate a connection leak. I still don't really understand why the connections from my local machine to the remote DB don't encounter timeout failures.

Thanks for the quick responses, I really appreciate your help on this.

**Comment by brettwooldridge** [comment]
As a first step enable the leakDetectionThreshold and see if it can pinpoint the problem.

**Comment by rohitmukherjee** [comment]
Hi @brettwooldridge,

I've managed to figure out and fix the issue. Turns out it was related to the way I was using withSession in slick. Just to provide some background, we use dynamic sessions and have a wrapper that accepts a function: `f : => T`

The wrapper looks like this: 

`def withSession[T](f: => T): T = DAO.database().withDynSession[T](f)`

where `database: JDBCBackend#Database`

There are a few places in our code we were doing the following:
```
def read(predicate: TableQuery[MyTable] => Column[Boolean]): T = {
withSession {
  val records = TableQuery[MyTable].filter(predicate)
  records.map(populateAuxillaryData)
}
}
```
and `populateAuxilaryData` is a method that has it's own `withSession {}` closure and fetches data from some subtables to construct entity T. Looks like everytime `read`  is called, we're leaking a connection. The leaked connection doesn't get released and eventually leads to the timeout exception from HikariCP.

When I rewrite `read` as:

```
def read(predicate: TableQuery[MyTable] => Column[Boolean]): T = {
withSession {
  val records = TableQuery[MyTable].filter(predicate)
}
records.map(populateAuxillaryData)
}
```
I don't get the "Apparent connection leak detected" message from HikariCP. Thanks so much for all your help @brettwooldridge. I've tested the app and it seems to be working fine.

**Comment by brettwooldridge** [comment]
Great to here.  I’m not that familiar with Scala (I came to the Functional-ish side starting with Kotlin) ... was a Connection somehow getting captured by a closure?  Almost feels like the Scala compiler “lifted” that function out in an unexpected way...

**Comment by rohitmukherjee** [comment]
Hi @brettwooldridge,

Sorry for the late reply. I was caught up making the fixes to our DAO's before a production deadline.

>  I’m not that familiar with Scala (I came to the Functional-ish side starting with Kotlin) ... was a Connection somehow getting captured by a closure?

So in cases where we have nested `withSession` blocks:

```def read(predicate: TableQuery[MyTable] => Column[Boolean]): T = {
withSession {
  val records = TableQuery[MyTable].filter(predicate)
  records.map(populateAuxillaryData)
}
```

and `populateAuxillaryData` has a withSession inside it as well, the structure reduces to:
```
withSession {
    op1
    withSession {
         op2
    }
}
```

In such cases, slick 2.1.0 doesn't close both connections, it only closes one. https://stackoverflow.com/a/18380125 is the closest issue I've found to this. Seems like it was the library maintainer's decision to have the `withSession` work this way.

Let me know if you have any more questions.

**Comment by brettwooldridge** [comment]
As yes, I believe that Slick 3.x contains substantial changes to DB connection/transaction handling.

**Comment by rohitmukherjee** [comment]
Yup, we're planning to migrate once we have some bandwidth. Thanks again for all your help.
