### ISSUE TITLE
Upgrading from Hikari 2.7.6 to 2.7.7 leads to "count cannot be increased"

### ISSUE THREAD

**Issue by sarahgerweck** [brettwooldridge/HikariCP#1084]
In my project, which uses [Slick](https://github.com/slick/slick) as its DB layer, I am having a reproducible issue where upgrading Hikari from 2.7.6 to 2.7.7 leads to the following errors in the logs.

```logs
[ERROR] Exception in thread "slick.db-1" java.lang.IllegalArgumentException: requirement failed: count cannot be increased
[ERROR] 	at scala.Predef$.require(Predef.scala:277)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.$anonfun$increaseInUseCount$1(ManagedArrayBlockingQueue.scala:40)
[ERROR] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.slick$util$ManagedArrayBlockingQueue$$locked(ManagedArrayBlockingQueue.scala:217)
[ERROR] 	at slick.util.ManagedArrayBlockingQueue.increaseInUseCount(ManagedArrayBlockingQueue.scala:39)
[ERROR] 	at slick.util.AsyncExecutor$$anon$2$$anon$1.beforeExecute(AsyncExecutor.scala:74)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
```

It's entirely possible that this is a configuration issue or a bug in Slick of some kind, but I don't see anything in the 2.7.7 release notes that would lead me to think that there are new restrictions. I can make this exception come and go at will by switching between Hikari 2.7.6 (no error) and 2.7.7 (error). Is there an intentional change that might lead to this behavior change?

**Comment by sarahgerweck** [comment]
I haven't opened a ticket against Slick yet, as it's consistent for me that it happens with Hikari 2.7.7 and that it doesn't happen with Hikari 2.7.6. Since you seem convinced that it was not an unintended behavior change in Hikari, I'll open a ticket there next and link it to this one.

One thing I wonder is whether the changes to sealed configurations might be preventing Slick from adjusting settings that it was previously able to adjust in Hikari 2.7.6?

**Comment by brettwooldridge** [comment]
@sarahgerweck I thought that was possible too (Slick adjusting settings), but a search of their code did not reveal any runtime-changes to the pool (as far as I could find).  If Slick *is* doing that, there are official APIs to do to (``HikariConfigMXBean``).
