### ISSUE TITLE
Log spam: SLF4J: Failed toString() invocation on an object of type [com.sun.proxy.$Proxy0] (UndeclaredThrowableException)

### ISSUE THREAD

**Issue by noahlz** [brettwooldridge/HikariCP#1107]
#### Environment
```
HikariCP version: 2.4.11
JDK version     : 1.7.0
Database        : MySQL and SQL Server
Driver version  : 5.1.35 mysql / 1.3.1 jTDS
LogBack version : 1.2.3
SLF4J version   : 1.7.16
```
-----------------------------------------------------------------------------------------
I am seeing a lot of the below stack trace in captured stdout. It is not hurting any functionality but is a bit irritating to scroll through.  It goes to standard out, not our logs, so it's not really clear what's causing it - likely a background thread and not application code?

```
SLF4J: Failed toString() invocation on an object of type [com.sun.proxy.$Proxy0]
Reported exception:
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy0.toString(Unknown Source)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:299)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:271)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:233)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:173)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.classic.AsyncAppender.preprocess(AsyncAppender.java:43)
	at ch.qos.logback.classic.AsyncAppender.preprocess(AsyncAppender.java:28)
	at ch.qos.logback.core.AsyncAppenderBase.append(AsyncAppenderBase.java:160)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.warn(Logger.java:704)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:172)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:169)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
```

Any thoughts on how to suppress this particular output / error?

**Comment by brettwooldridge** [comment]
Are you seeing that error with both MySQL and SQL Server?  What other libraries are in use?  Are you running within an application container?  Somehow, the Connection that HikariCP has wrapped is a proxy object.  As far as I know, neither driver returns proxy objects, which makes me suspect that is something else going on.

**Comment by noahlz** [comment]
As a matter of fact, we use novus-jdbc which may in fact use proxies. I will investigate. I'll close for now and re-open if there is an issue in Hikari (sounds like there isn't).
