### ISSUE TITLE
Connection is not available, request timed out after 120005ms

### ISSUE THREAD

**Issue by nirav-patel** [brettwooldridge/HikariCP#1109]
I have noticed that while doing performance testing in HikariCP for multiple concurrent user requests, when the count of threads waiting for a connection is less than total connections (maximumPoolSize), then HikariCP performs well and hardly throw any error (i.e, connectionTimeout error or leakDetectoinError).

i.e., In this case, pool statistics are as shown below:

DEBUG HikariPool - TestHikariCP - Before cleanup stats (total=5, active=5, idle=0, waiting=2)
DEBUG HikariPool - TestHikariCP - After cleanup  stats (total=5, active=5, idle=0, waiting=2)

But as soon as waiting threads count > total connection count (maximumPoolSize), HikariCP`s performance degrades exponentially and many errors for connectionTimeout and leakDetection are thrown.
Also, systems almost hang at this point and no users request are being served smoothly or very fewer requests are able to complete the transaction successfully and rest are timed-out. 

i.e., pool statistics are as shown below in this situation: 
```
DEBUG HikariPool - TestHikariCP - Before cleanup stats (total=5, active=5, idle=0, waiting=6)
DEBUG HikariPool - TestHikariCP - After cleanup  stats (total=5, active=5, idle=0, waiting=6)
```

here getting connection timeout error as shown below:

```
SEVERE: Servlet.service() for servlet [appServlet] in context with path [/AopExample] threw exception [Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Could not open connection] with root cause
java.sql.SQLTransientConnectionException: HikariCP - Connection is not available, request timed out after 120005ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:667)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:183)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:148)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
	at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:450)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:450)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.handleExistingTransaction(AbstractPlatformTransactionManager.java:429)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:349)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy19.saveActivityInfo(Unknown Source)
	at com.demo.spring.service.UserServiceImpl.saveUserInfo(UserServiceImpl.java:35)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy21.saveUserInfo(Unknown Source)
```

HIkariCP configuration properties for datasourceare are : 

```
driverClassName=org.postgresql.Driver
jdbcUrl=jdbc:postgresql://localhost:5432/demo
username=test
password=test
autoCommit=false
minimumIdle=2
maximumPoolSize=5
connectionTimeout=120000
idleTimeout=15000
leakDetectionThreshold=120000
validationTimeout=10000
maxLifetime=1800000
dataSource.implicitCachingEnabled=true
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.useServerPrepStmts=true
registerMbeans=true

```
#### Environment
```
HikariCP version  : 2.7.8
JDK version       : 1.8.0_131
Database          : PostgreSQL
Driver version    : 42.2.1
Spring version    : 4.2.1.RELEASE
Hibernate version : 4.3.10.Final
Tomcat version    : 8.0.41
```

Even if I increase the maximumPoolSize value here, an issue will again reproduce the moment there are so many concurrent user requests and waiting threads for connection count increases the maximumPoolSize value. _Here increasing connectionTimeOut value is also not helping much._

Can you please help what is the issue here, and what can be the preferred configuration values in such scenarios where concurrent bulk user requests will be there and one user request can execute multiple queries during one transaction and can take more than 1 minute to finish one transaction.

**Previously, I was using tomcat-dbcp2 as connection-pool and I did not found such issues there for the same scenario.**

<sup>⚠️ Also issue exists in other databases like Oracle, SQLServer. </sup>

**Comment by brettwooldridge** [comment]
Strange.  When you were using dbcp2 did you have removeAbandoned* enabled?

This looks more like a Connection leak, rather than just slow queries.  Do you ever see messages like “Previously reported leaked connection was returned to the pool”?  What if you set the leakDetectionThreshold to 3 minutes?

By the way, those datasource properties look like MySQL DataSource properties, not PostgreSQL DataSource properties.

**Comment by nirav-patel** [comment]
@brettwooldridge , Yes, in dbcp2 I used to have removeAbandoned* properties, but timeout values for them were much higher (about 15 minutes).

Yes, I do get messages for every connection stating that connection returned to the pool as shown below:

`INFO  ProxyLeakTask - Previously reported leaked connection org.postgresql.jdbc.PgConnection@680e49b0 on thread http-nio-8080-exec-9 was returned to the pool (unleaked)`

Also, I have created property file to read values and then using them to create HikariConfig bean.

```
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
	<property name="poolName" value="TestHikariCP" />
	<property name="driverClassName" value="${driverClassName}" />
	<property name="jdbcUrl" value="${jdbcUrl}" />
	<property name="username" value="${username}" />
	<property name="password" value="${password}" />
	<property name="autoCommit" value="${autoCommit}" />
	<property name="maximumPoolSize" value="${maximumPoolSize}" />
	<property name="minimumIdle" value="${minimumIdle}" />
	<property name="idleTimeout" value="${idleTimeout}" />
	<property name="connectionTimeout" value="${connectionTimeout}" />
	<property name="validationTimeout" value="${validationTimeout}" />
	<property name="maxLifetime" value="${maxLifetime}" />
	<property name="leakDetectionThreshold" value="${leakDetectionThreshold}" />
	<property name="registerMbeans" value="${registerMbeans}" />
	<property name="metricRegistry" ref="metricRegistry" />
	<property name="healthCheckRegistry" ref="healthCheckRegistry" />
	<property name="dataSourceProperties">
		<props>
			<prop key="prepStmtCacheSize">${dataSource.prepStmtCacheSize}</prop>
			<prop key="prepStmtCacheSqlLimit">${dataSource.prepStmtCacheSqlLimit}</prop>
			<prop key="cachePrepStmts">${dataSource.cachePrepStmts}</prop>
			<prop key="implicitCachingEnabled">${dataSource.implicitCachingEnabled}</prop>
			<prop key="useServerPrepStmts">${dataSource.useServerPrepStmts}</prop>
		</props>
	</property>
</bean>

<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource"
	destroy-method="close">
	<constructor-arg ref="hikariConfig" />
</bean>
```

**Comment by nirav-patel** [comment]
@brettwooldridge  I have noted one more thing while setting data source properties for HikariCP. i.e., default value for **maximumPoolSize** is 10. But if we set **minimumIdle** to higher value i.e., 20, and we do not set maximumPoolSize value explicitly, then maximumPoolSize`s value is set to 20 which is same as minimumIdle.  So is this behavior expected or minimumIdle value should have been set to maximumPoolSize value which is 10? I do not find anything on the wiki page about this behavior so just wanted to clarify this.

**Comment by brettwooldridge** [comment]
``minimumIdle`` should always be less than or equal to ``maximumPoolSize``.  If ``minimumIdle`` is set to something higher, it will *push up* ``maximumPoolSize`` to an equal value.  It is not documented, but at the same time, it seemed evident that ``minimumIdle`` cannot logically be more than ``maximumPoolSize``, because ``maximumPoolSize`` specified the maximum number of actually connections to the backend database.

**Comment by brettwooldridge** [comment]
@nirav-patel Oh, I didn't realize you were using a metric registry.  What is the histogram data for connection "Usage" (how long connections are out of the pool, in-use)?

If you can share a log from your test run, it would be helpful.  Even better, if you can run the same load test with HikariCP and dbcp2, with the same maximum pool sizes, and share those logs it would be more useful.  You can zip them and attach them here if there is nothing secret in them.

**Comment by nirav-patel** [comment]
I`m attaching screenshot for connection "Usage". 
![image](https://user-images.githubusercontent.com/5373143/37243881-b56882dc-24a6-11e8-90a8-9b178b849018.png)

Hope this is helpful to you. Let me know if this is something else then what you expect.
For, dbcp2, I`ll run tests and will provide you information.

**Comment by brettwooldridge** [comment]
@nirav-patel Can you provide a screenshot of the "Wait" metric as well?

**Comment by billoneil** [comment]
If your transactions take up to 1 second and you only have 5 connections you won't get very high throughput. That's worst case 5 concurrent transactions a second if they don't touch any of the same rows that are locked. All other connections would be blocked until those are done.

Was your dbcp2 pool also limited to only 5 connections? The recommended lower pool sizes tend to be tailored for a high volume of fast queries. If you have a lot of longer running queries it might make sense to increase the pool size but you really need to test it.

**Comment by brettwooldridge** [comment]
@billoneil That was my thinking as well.  If 5 threads hit at the same time, and each takes > 1min20sec to execute, any additional threads are going to timeout.  However, my reasoning was that dbcp2 is being run with identical max. size, and the issue is not being seen, which gives me pause.

However, it could also be that dbcp2 simply blocks connections once the pool reaches saturation.  If ``maxWaitMillis`` is not set on dbcp2, connections will block indefinitely until a connection is available -- and therefore will never timeout.

**Comment by nirav-patel** [comment]
Let me share new screenshots for both "Usage", "Wait" and "ConnectionTimeoutRate" with the new test.

![image](https://user-images.githubusercontent.com/5373143/37244564-ee77bf8e-24b0-11e8-9022-596177e43afa.png)


![image](https://user-images.githubusercontent.com/5373143/37244555-d4c7f1e4-24b0-11e8-80e0-361ec8c688f2.png)

![image](https://user-images.githubusercontent.com/5373143/37244570-19587716-24b1-11e8-9759-d5ab0d28d167.png)

Also, ideally each transaction should take appx. 1 second to finish it but yes when 1 thread is waiting till another finishes its execution, this time will increase. For load testing I have set maxPoolSize = 5, and hence to increase waitCount, I`m making the back-to-back parallel requests using 6 postman-clients (i.e., one client will send one POST request to save data in the table, once it receives the response, it will make another request to save data and so on. So one client will send the request in synchronous mode but as I`m using 6 clients for load testing, there will be 6 requests in most of the cases).

So, as mentioned by @billoneill, I can increase the `maximumPoolSize `value here so that number of waiting threads will be less for this scenario and user requests will be handled appropriately. Let`s say I`m setting `maximumPoolSize `to 15, But my concern here is when there are more than 15 clients making parallel requests, the same issue will happen again. So, how should I configure connection pool parameters to handle some dynamic load?

**Comment by brettwooldridge** [comment]
@nirav-patel You'll have do to some back-of-the-napkin calculations, based on estimates -- or better, historical data.  Some questions you will need to have answers (or guesses) for are:

* What is the maximum number of expected users?
* What percent of total interactions (database) exceed more than a few seconds?

Even with this data in hand, unless there is an architecture change, there is always the possibility of either, 1) users must wait up to 1 minute or more because all connections are in-use for long queries, or 2) the application will encounter timeouts, which it must catch and handle -- either retry or report the error to the user.

My guess is that dbcp2 never times out because ``maxWaitMillis`` was not set.  If this is acceptable (i.e. wait forever until a connection is available), simply set HikariCP's ``connectionTimeout`` to some absurdly large value.  My guess is, this will not deliver the experience that users are expecting.

There are two ways to go architecturally:

1) Employ two pools.  One for short, interactive, queries.  One for long running queries.  Or...
2) If the code path that leads to long-running queries is known, then add the work to a queue that is serviced by a thread pool with a number of threads less than the pool size.

The second is probably both easiest and most reliable.  Psuedo-code:
```java
private static final ThreadPoolExecutor executor;

static {
   executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(3); // <-- smaller than maximumPoolSize
   executor.allowCoreThreadTimeOut(true);
   executor.setKeepAliveTime(30, TimeUnit.SECONDS);
}

public methodWithLongQuery(final param1, final param2, ...) {
   // returns immediately, performs work in the background. tell user request is being processed.
   executor.execute(() -> {
      try (Session session ...) {
         // execute long query using param1, param2, etc. as inputs
      }
      catch (SQLException sqle) {
         // log exception ... somehow asynchronously report error to user
      }
   });
}
```
I haven't used Hibernate in years, so I don't know how you acquire sessions etc.  The important point is to *not acquire a Session/Connection* outside of the worker thread, or you'll be in the same spot on holding onto too many connections for too long.

By keeping the number of threads servicing long queries to less than ``maximumPoolSize``, you ensure that several connections are always available for quick interactive queries by the user.

**Comment by nirav-patel** [comment]
Previously for DBCP2, I used to have bit more maxPoolSize value and maxWaitMillis was not set, but to be fair with HikariCP, I have tested same load testing scenario in DBCP2 with similar parameter values as HikariCP and ran the test.

DBCP2 Properties:

```
driverClassName=org.postgresql.Driver
jdbcUrl=jdbc:postgresql://localhost:5432/demo
username=test
password=test
autoCommit=false
minimumIdle=2
maximumPoolSize=5
connectionTimeout=120000
dbcp2.maximumIdle=4
dbcp2.accessToUnderlyingConnectionAllowed=true
dbcp2.removeAbandonedOnBorrow=true
dbcp2.removeAbandonedTimeout=900
dbcp2.removeAbandonedOnMaintenance=true
dbcp2.timeBetweenEvictionRunsMillis=300000
dbcp2.minEvictableIdleTimeMillis=900000
```

Datasorce Configuration:

```
<bean id="dataSource" class="org.apache.commons.dbcp2.BasicDataSource" destroy-method="close">
	<property name="driverClassName" value="${driverClassName}" />
	<property name="url" value="${jdbcUrl}" />
	<property name="username" value="${username}" />
	<property name="password" value="${password}" />
	<property name="defaultAutoCommit" value="${autoCommit}" />
	<property name="maxTotal" value="${maximumPoolSize}" />
	<property name="minIdle" value="${minimumIdle}" />
	<property name="maxIdle" value="${dbcp2.maximumIdle}" />
	<property name="maxWaitMillis" value="${connectionTimeout}" />
	<property name="accessToUnderlyingConnectionAllowed" value="${dbcp2.accessToUnderlyingConnectionAllowed}" />
	<property name="removeAbandonedOnBorrow" value="${dbcp2.removeAbandonedOnBorrow}" />
	<property name="removeAbandonedTimeout" value="${dbcp2.removeAbandonedTimeout}" />
	<property name="removeAbandonedOnMaintenance" value="${dbcp2.removeAbandonedOnMaintenance}" />
	<property name="timeBetweenEvictionRunsMillis" value="${dbcp2.timeBetweenEvictionRunsMillis}" />
	<property name="minEvictableIdleTimeMillis" value="${dbcp2.minEvictableIdleTimeMillis}" />
</bean>
```
Jconsole Screenshot:
![image](https://user-images.githubusercontent.com/5373143/37246232-8f831a9e-24cb-11e8-85c8-6c2792812db3.png)


Here I noticed that, for initial few requests (appx. 100), DBCP2 performed smoothly. Later for few connections, it starts throwing the **connectionTimeOut** exception for those threads which cross idleTimeout value waiting for the connection.

Though, I have noticed that after connectionTimeOut error, DBCP2 seems to be performing faster when it comes to handling connections for next transactions, while in case of HikariCP, further user requests are handled very slowly. 

@brettwooldridge , Answers to questions you mentioned earlier: 
- What is the maximum number of expected users?
A: I`m expecting maximum 500 users.

- What percent of total interactions (database) exceed more than a few seconds?
A: More than 60% of total interactions will exceed more than a few seconds. (In the current system, when one user request starts one transaction, it performs multiple queries for different business rule validations and inserts/updates data in multiple tables.)

@billoneil , @brettwooldridge  I`ll try to use one of the solutions you mentioned above and will see how it performs. Thanks for your suggestions.

**Comment by brettwooldridge** [comment]
Unfortunately, without maxWaitMillis set for dbcp2 I simply cannot take any performance comparison seriously.  I given such a low transaction rate I would be surprised if there is any measurable difference between the two.

Regarding pool sizing, if you are running transactions on user request threads, and expect that 60% of 500 users could be executing queries exceeding 1 minute at any given time, then you would need a pool with 300 connections.

I fail to see how that can possibly scale in any reasonable manner.  You must restrict the number of simultaneous requests to a load that matches a reasonable pool size and the capabilities of the database.  That means getting the queries off of request threads and into a threadpool/work queue.

**Comment by KBArjun** [comment]
Even i am facing the same issue...
Can some one help me out to solve this?

Added the logs below

javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1423)
	at org.hibernate.query.Query.getResultList(Query.java:146)
	at com.emudhra.emcaServices.daoImpl.EmcaCustomRepositoryImpl.validateUser(EmcaCustomRepositoryImpl.java:66)
	at com.emudhra.emcaServices.daoImpl.EmcaCustomRepositoryImpl$$FastClassBySpringCGLIB$$999c214c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.emudhra.emcaServices.daoImpl.EmcaCustomRepositoryImpl$$EnhancerBySpringCGLIB$$e2a2280e.validateUser(<generated>)
	at com.emudhra.emcaServices.serviceImpl.EMCAServiceImpl.validateUser(EMCAServiceImpl.java:21)
	at com.emudhra.emcaServices.services.CreateX509CertHelper.getX509CertRes(CreateX509CertHelper.java:119)
	at com.example.demo.RestController1.getCreateX509CertificateRequest(RestController1.java:87)
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:109)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1985)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1915)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1893)
	at org.hibernate.loader.Loader.doQuery(Loader.java:938)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
	at org.hibernate.loader.Loader.doList(Loader.java:2692)
	at org.hibernate.loader.Loader.doList(Loader.java:2675)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2507)
	at org.hibernate.loader.Loader.list(Loader.java:2502)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:392)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1489)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
	... 73 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30011ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:606)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)
	... 93 more
