### ISSUE TITLE
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by ItzVinex** [brettwooldridge/HikariCP#1132]
#### Environment
```
HikariCP version: 3.0.0
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : Not sure.
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

Yes.

I have two errors which are the same but in different classes.
https://hastebin.com/banobifipe.md

LINE 744:
`ps2 = getHikari().getConnection().prepareStatement(
							"UPDATE `Players` SET `1v1Rating`=?, `2v2Rating`=?, `FFARating`=?, `FFAKills`=?, `FFADeaths`=?, `Coins`=?, `Spins`=?, `Skeleton`=?, `Creeper`=?, `Zombie`=?, `Enderman`=?, `Herobrine`=?, `Dreadlord`=?, `Arcanist`=?, `Shaman`=?, `Golem`=?, `Pigman`=?, `Blaze`=?, `Spider`=?, `Block`=?, `VanityArmor`=?, `Trail`=?, `PlayerName`=? WHERE `UUID`=?");`

LINE 153:
`PreparedStatement sql2 = Corrupted.getInstance().getHikari().getConnection().prepareStatement("SELECT * FROM `Players`");`

My configuration:
`		hikari = new HikariDataSource();
		hikari.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
		hikari.setMaximumPoolSize(10);
		hikari.addDataSourceProperty("serverName", "localhost");
		hikari.addDataSourceProperty("port", "3306");
		hikari.addDataSourceProperty("databaseName", "DB");
		hikari.addDataSourceProperty("user", "username");
		hikari.addDataSourceProperty("password", "mypass");`

If this helps I have another program using the same database with HikariCP and works perfectly fine.

**Comment by ItzVinex** [comment]
Okay I’ll enable that. I changed my code around completely and now I seem to only be getting primary key duplicate error.

**Comment by ItzVinex** [comment]
What should I use for that leakDetectionThreshold?

Also here's the duplicated entry error:
https://hastebin.com/ifutocofor.md

**Comment by brettwooldridge** [comment]
Two things...

One, try 30 seconds (30000ms) for the leakDetectionThreshold.  

Two, duplicate key errors have nothing to do with the pool, but represent an application bug.  If it *was* working on another pool, it is likely due to a “lucky” side-effect, such as commit-on-close behavior.  You’re on your own chasing that one down.

**Comment by ItzVinex** [comment]
Okay I'll try that out

**Comment by ItzVinex** [comment]
Fixed it. Thanks.

**Comment by ItzVinex** [comment]
Okay looks like the leakDetectionThreshold picked this

https://hastebin.com/gasiyifota.vbs

I also provided my code and line number

**Comment by ItzVinex** [comment]
Not sure what caused that but it hasn't happened since.

**Comment by brettwooldridge** [comment]
@ItzVinex Looking at the code, the following pattern will leak a connection:
```java
try {
   conn = hikari.getConnection();  <-- Possible leak.  If an exception is thrown, the Connection is never closed.
   sql = conn.prepareStatement(...);
   ...

   conn = hikari.getConnection();   <-- Leak.  Previous Connection referenced by conn is overwritten and never closed.
   sql = conn.prepareStatement(...);
} catch (SQLException e) {
   ...
} finally {
}
```

First, you do not need two Connections here.  Second, use Java's [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) to handle closing Connections and Statements.

Better:
```java
try (Connection conn = hikari.getConnection();
      PreparedStatement sql1 = conn.prepareStatement(...);
      PreparedStatement sql2 = conn.prepareStatement(...)) {

   sql1.setXXX(...);
   ...
   sql1.executeUpdate();

   // No need to close 'conn', 'sql1' or 'sql2' explicitly.  The try guarantees they will be closed.
}
catch (SQLException e) {
   ...
}

**Comment by ItzVinex** [comment]
`public void newDatabaseEntry(Player p) {
		final String uuid = p.getUniqueId().toString();
		final String name = p.getName();
		Bukkit.getScheduler().scheduleAsyncDelayedTask(plugin, new Runnable() {

			@Override
			public void run() {
				try (Connection conn = hikari.getConnection();
					      PreparedStatement sql1 = conn.prepareStatement("INSERT INTO `Players` values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?");
					      PreparedStatement sql2 = conn.prepareStatement("INSERT INTO `KitCustomizer` values(?,?,?,?,?,?,?,?,?,?,?,?,?)")) {
					sql1.setString(1, uuid);
					sql1.setInt(2, 1000);
					sql1.setInt(3, 1000);
					sql1.setInt(4, 1000);
					sql1.setInt(5, 0);
					sql1.setInt(6, 0);
					sql1.setInt(7, 0);
					sql1.setInt(8, 1);
					sql1.setString(9, "1|0|0");
					sql1.setString(10, "1|0|0");
					sql1.setString(11, "0|0|0");
					sql1.setString(12, "0|0|0");
					sql1.setString(13, "0|0|0");
					sql1.setString(14, "0|0|0");
					sql1.setString(15, "0|0|0");
					sql1.setString(16, "0|0|0");
					sql1.setString(17, "0|0|0");
					sql1.setString(18, "0|0|0");
					sql1.setString(19, "0|0|0");
					sql1.setString(20, "0|0|0");
					sql1.setString(21, "1|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|WOOD");
					sql1.setString(22, "1|0|0|0|0|NONE");
					sql1.setString(23, "1|0|0|0|0|0|0|0|0|0|NONE");
					sql1.setString(24, name);
					sql1.execute();
					sql1.close();

					sql2.setString(1, "1|2|3|4|5|6|7|8|9");
					sql2.setString(2, "1|2|3|4|5|6|7|8|9");
					sql2.setString(3, "1|2|3|4|5|6|7|8|9");
					sql2.setString(4, "1|2|3|4|5|6|7|8|9");
					sql2.setString(5, "1|2|3|4|5|6|7|8|9");
					sql2.setString(6, "1|2|3|4|5|6|7|8|9");
					sql2.setString(7, "1|2|3|4|5|6|7|8|9");
					sql2.setString(8, "1|2|3|4|5|6|7|8|9");
					sql2.setString(9, "1|2|3|4|5|6|7|8|9");
					sql2.setString(10, "1|2|3|4|5|6|7|8|9");
					sql2.setString(11, "1|2|3|4|5|6|7|8|9");
					sql2.setString(12, "1|2|3|4|5|6|7|8|9");
					sql2.setString(13, uuid);
					sql2.execute();
					sql2.close();
				} catch (SQLException e) {
					e.printStackTrace();
				}
			}
		}, 0L);`

Updated the code. So you're saying I don't need to close them at all?

**Comment by ItzVinex** [comment]
Worked perfectly! Wow I never new you could do that with try-and-catches.

**Comment by ItzVinex** [comment]
Take that back it ended up giving me this error.

https://hastebin.com/owexebaxag.vbs

Provided code and line number within the log.

**Comment by ItzVinex** [comment]
I also converted my SQLManager class to your try-with-resource statement suggestion and this happen.

`[22:38:13 WARN]: java.sql.SQLException: No value specified for parameter 1
[22:38:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[22:38:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[22:38:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[22:38:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2211)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2191)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2121)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1941)
[22:38:13 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[22:38:13 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[22:38:13 WARN]:        at com.venomsurge.api.mysql.SQLManager.sndUserExistDatabase(SQLManager.java:97)
[22:38:13 WARN]:        at main.main.events.HubEventManager$1.run(HubEventManager.java:119)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:38:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:38:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:38:13 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '15ee5b74-5f75-425d-a4eb-cec7fc39d752' for key 'PRIMARY'
[22:38:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:38:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:38:13 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:38:13 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:38:13 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[22:38:13 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[22:38:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[22:38:13 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[22:38:13 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[22:38:13 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[22:38:13 WARN]:        at com.venomsurge.api.mysql.SQLManager.insertNewSNDUserData(SQLManager.java:46)
[22:38:13 WARN]:        at main.main.events.HubEventManager$1.run(HubEventManager.java:124)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:38:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:38:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:38:13 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '15ee5b74-5f75-425d-a4eb-cec7fc39d752' for key 'PRIMARY'
[22:38:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:38:13 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:38:13 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:38:13 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:38:13 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[22:38:13 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[22:38:13 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[22:38:13 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[22:38:13 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[22:38:13 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[22:38:13 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[22:38:13 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[22:38:13 WARN]:        at com.venomsurge.api.mysql.SQLManager.insertNewSNDKitData(SQLManager.java:87)
[22:38:13 WARN]:        at main.main.events.HubEventManager$1.run(HubEventManager.java:125)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:38:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:38:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
`

`public static boolean sndUserExistDatabase(Player p) {
			String statement = "SELECT * FROM snd_users WHERE user_uuid=?";
			try (Connection conn = VSAPI.getInstance().getHikari().getConnection();
					PreparedStatement sql = conn.prepareStatement(statement);
					LINE 97: ResultSet rs = sql.executeQuery()) {
				sql.setString(1, p.getUniqueId().toString());

				if (rs.next()) {
					EconomyManager.getBalanceMap().put(p.getName(), rs.getDouble("user_coins"));
					// EloManager.getEloMap().put(p.getName(), res.getInt("user_elo"));
					return true;
				} else {
					return false;
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
			return false;
		}`

**Comment by ItzVinex** [comment]
All fixed, but if you can explain why you can't use RS in the resource.

**Comment by brettwooldridge** [comment]
Line 81 is executing the query before you have set the query parameters on line 82.  ResultSets are automatically closed when the Statement is closed, so don’t worry about it.

**Comment by ItzVinex** [comment]
Ok I appreciate it. Thanks!

**Comment by tharindu-kalhara** [comment]
from https://stackoverflow.com/questions/50390414/hikaricp-timeout-after-30000-waiting-for-a-connection
![screenshot_20190215103734](https://user-images.githubusercontent.com/20641865/52835873-6678b280-310e-11e9-8cb3-6b048ec69491.png)

it is correct.
