### ISSUE TITLE
Recovery from initial connection failure

### ISSUE THREAD

**Issue by harbulot** [brettwooldridge/HikariCP#1139]
#### Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_171
Database        : MSSQL
Driver version  : 6.4.0.jre8
```

The creation of the `DataSource` fails with an exception if the very first attempt to connect fails.

This is in the context of a Spring-based application, where a failure to establish this connection shouldn't prevent the rest of the application from working. The `DataSource` is initialised as follows:

```java
@Bean(destroyMethod = "close")
public DataSource dataSource() {
    HikariConfig config = new HikariConfig();
    config.setJdbcUrl(...);
    config.setUsername(...);
    config.setPassword(...);

    HikariDataSource ds = new HikariDataSource(config);
    return ds;
}
```

I've done a comparison with an Apache DBCP `BasicDataSource`, using a remote server (and triggering a disconnection by unplugging the network cable).

* **Cable plugged in at the start**:
With both DBCP and HikariCP, if the connection is available when the `DataSource` is instantiated, and if we pull the cable later at some point, then both are able to recover when the cable is plugged back in. (Of course, queries executed when the cable is unplugged fail, but the `DataSource` recovers when the cable is plugged back in, and further queries work.)

* **Cable unplugged at the start**:
If the connection cannot be established when the `DataSource` is instantiated, the HikariCP `DataSource` isn't even created, which makes the whole application fail to start (due to further dependencies on this data source). In contrast, when using a DBCP `BasicDataSource`, even if the first connection fails, the rest of the application can start (whatever is not using the DB works), and the `DataSource` recovers once the cable is plugged back in.

Here is the exception I get with HikariCP:

```
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host XXXXXXXXXXXXXXXXXXXXXXX, port 1433 has failed. Error: "XXXXXXXXXXXXXXXXXXXXXXX. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2437)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:641)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2245)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
```
(This exception prevents the `@Bean` method above from completing normally, because of this exception.)

Here is what I get with Apache DBCP:

```
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (The TCP/IP connection to the host XXXXXXXXXXXXXXXXXXXXXXX, port 1433 has failed. Error: "XXXXXXXXXXXXXXXXXXXXXXX. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
    ...
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host XXXXXXXXXXXXXXXXXXXXXXX, port 1433 has failed. Error: "XXXXXXXXXXXXXXXXXXXXXXX. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2437)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:641)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2245)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
```

This exception only occurs when trying to execute a query, but the `BasicDataSource` instance itself is created and works.

**Comment by brettwooldridge** [comment]
@harbulot See the documentation on the project page for ``initializationFailTimeout``.
