### ISSUE TITLE
Oracle-RAC Can not get Connection, java.lang.VerifyError

### ISSUE THREAD

**Issue by ysstech** [brettwooldridge/HikariCP#1140]
#### Environment
```
HikariCP version: hikaricp-java6-2.3.2
JDK version     : 1.7.1
Database        : Oracle-RAC
Driver version  : ojdbc6-11.2.0.3
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

Caused by: java.lang.VerifyError: JVMVRFY012 堆栈形状不一致 类=com/zaxxer/hikari/proxy/ConnectionJavassistProxy，方法=createStatement()Ljava/sql/Statement;，pc=1
	at com.zaxxer.hikari.proxy.ProxyFactory.getProxyConnection(ProxyFactory.java) ~[na:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:215) ~[na:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:183) ~[na:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:503) ~[na:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:172) ~[na:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:61) ~[na:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:49) ~[na:na]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:78) ~[na:na]
	at 

-----------------------------------------------------------------------------------------

**Comment by brettwooldridge** [comment]
@ysstech You're on Java 7, upgrade to the Java 7 artifact.
