### ISSUE TITLE
Connection getting closed abruptly

### ISSUE THREAD

**Issue by smhasan11** [brettwooldridge/HikariCP#1162]
#### Environment
```
HikariCP version: 2.7.6
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : x.x.x
```
I've two data-sources created using *HikariDataSource* as below for my rest-API:

```
public class DBConnection {

	private static Logger logger = Logger.getLogger(HospitalDaoImpl.class);
	private DataSource hospitalDataSource, rssDataSource = null;
	private String timezoneSopprt = "?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
	private String hospitalDbUrl = "jdbc:mysql://localhost:3306/hospitals"+timezoneSopprt;
	private String rssDbUrl = "jdbc:mysql://localhost:3306/nsw_rss"+ timezoneSopprt;
	
	public DBConnection() {
		hospitalDataSource = getHospitalDataSource(hospitalDbUrl);
		rssDataSource = getRssDataSource(rssDbUrl);
	}
	
	private DataSource getRssDataSource(String rssDbUrl){
		HikariConfig config = this.getCommonConfig();
		config.setJdbcUrl(rssDbUrl);
		
		return new HikariDataSource(config);
	}

	private DataSource getHospitalDataSource(String hospitalDbUrl){
		HikariConfig config = getCommonConfig();
		config.setJdbcUrl(hospitalDbUrl);
		
		return new HikariDataSource(config);
	}
	
	private HikariConfig getCommonConfig() {
		//TODO read info from properties file
		
		HikariConfig config = new HikariConfig();
		
		config.setDriverClassName("com.mysql.cj.jdbc.Driver");
		config.setUsername("root");
		config.setPassword("root");
		
		config.setMaximumPoolSize(10);
		config.setMinimumIdle(5);
		config.setMaxLifetime(50 * 1000);
		config.setConnectionTimeout(50 * 1000);
		config.setIdleTimeout(50 * 1000);
		config.setLeakDetectionThreshold(60 * 1000);
		
		return config;
	}
	
	public Connection getHospitalDBConnnection() {
		Connection hsDBconn = null;
		try {
			hsDBconn = hospitalDataSource.getConnection();			
		}
		catch (SQLException e) {

			logger.error(e.getMessage(), e);
		}

		return hsDBconn;
	}

	public Connection getRssDBConnnection() {
		Connection rssDBconn = null;
		try {
			rssDBconn = rssDataSource.getConnection();			
		}
		catch (SQLException e) {

			logger.error(e.getMessage(), e);
		}

		return rssDBconn;
	}

	public static void closeConnection(Connection connection, PreparedStatement ps, ResultSet rs)
	{
		if (rs != null) {
			try {
				rs.close();
			} catch (SQLException e) {
				logger.error("Error closing resultset: " + e.getMessage());
				e.printStackTrace();
			}
		}
		if (ps != null) {
			try {
				ps.close();
			} catch (SQLException e) {
				logger.error("Error closing PreparedStatement: " + e.getMessage());
				e.printStackTrace();
			}
		}
		if (connection != null) {
			try {
				connection.close();
				logger.info(".................CONNECTION CLOSED SUCCESSFULLY...............");
			} catch (SQLException e) {
				logger.error("Error closing connection: " + e.getMessage());
				e.printStackTrace();
			}
		}		
	}
}
```

One of my endpoint method looks like as below:
```
	@GET
	@Produces("application/json")
	@Path("/AllHospitals")
	public String getAllHospitals(@Context ServletContext context)
	{
		String hospitalsDetails = null;
		List<Hospital> hospitalList = null;

		if(context!= null) {
			logger.info(context.getAttributeNames());

			DBConnection hsDBconn = (DBConnection) context.getAttribute("dbConnection");
			if(hsDBconn!= null) {

				if(hsDBconn.getHospitalDataSource() != null) {
					Connection connection = hsDBconn.getHospitalDBConnnection();

					HospitalDaoImpl hsImpl = new HospitalDaoImpl(connection);			
					hospitalList = hsImpl.getAllHospitals();

					Gson gson = new Gson();
					hospitalsDetails = gson.toJson(hospitalList);			
				}
				else {
					logger.error("-----------------------Hospital data source is null");
				}
			}
			else {
				logger.error("DBConnection object is null.....................");
			}
		}
		else {
			logger.error("ServletContext is NULL..........................................");
		}

		return hospitalsDetails;
	}
```
And this is how I retrieve data in my Dao:
	
```
	public HospitalDaoImpl(Connection hsDBconn) {

		this.connection = hsDBconn;
		hospitalList = new ArrayList<Hospital>();		
	}

	public List<Hospital> getAllHospitals() 
	{
		PreparedStatement ps = null;
		ResultSet rs = null;
		try 
		{
			ps = connection.prepareStatement(
					"SELECT * from hospitals.hospitals");

			rs = ps.executeQuery();
			hospitalList.clear();
			while(rs.next())
			{
				Hospital hospital = new Hospital();
				hospital.setId(rs.getLong("hospital_id"));
				hospital.setHospitalName(rs.getString("hospital_name"));
				hospital.setStreetAddress(rs.getString("hospital_street_address"));
				hospital.setCountryCode(rs.getString("hospital_country_code"));
				hospital.setCity(rs.getString("hospital_city"));
				hospital.setSuburb(rs.getString("hospital_suburb"));
				hospital.setPostalCode(rs.getString("hospital_postal_code"));
				hospital.setState(rs.getString("hospital_state"));
				hospital.setPublic(rs.getBoolean("is_public"));
				hospital.setPhone(rs.getString("hospital_phone"));
				hospital.setFax(rs.getString("hospital_fax"));
				hospital.setEmail(rs.getString("hospital_email"));
				hospital.setUrl(rs.getString("hospital_url"));
				
				hospitalList.add(hospital);
			}

			return hospitalList;
		}
		catch (SQLException e) {
			e.printStackTrace();
		}	
		finally {
			logger.info("Going to CLOSE Connection from 'getAllHospitals()'...");
			DBConnection.closeConnection(connection, ps, rs);
		}
		return null;
	}
```
As you can see, I'm closing the connection (which I'm getting from the pool while creating the object) in the **finally** block. 
But for some reason, getting **java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 50020ms.** after certain time. 
Below is what I've got from log file:
```
2018-05-21 22:06:14 DEBUG HikariConfig:512 - Driver class com.mysql.cj.jdbc.Driver found in Thread context class loader ParallelWebappClassLoader
  context: unsaarAPI-1.0
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@f49f1c

2018-05-21 22:06:14 WARN  HikariConfig:1101 - HikariPool-1 - idleTimeout is close to or more than maxLifetime, disabling it.
2018-05-21 22:06:14 WARN  HikariConfig:1112 - HikariPool-1 - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
2018-05-21 22:06:14 DEBUG HikariConfig:1139 - HikariPool-1 - configuration:
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - allowPoolSuspension.............false
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - autoCommit......................true
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - catalog.........................none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - connectionInitSql...............none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - connectionTestQuery.............none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - connectionTimeout...............50000
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - dataSource......................none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - dataSourceClassName.............none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - dataSourceJNDI..................none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - dataSourceProperties............{password=<masked>}
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - driverClassName................."com.mysql.cj.jdbc.Driver"
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - healthCheckProperties...........{}
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - healthCheckRegistry.............none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - idleTimeout.....................0
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - initializationFailFast..........true
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - initializationFailTimeout.......1
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - isolateInternalQueries..........false
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - jdbc4ConnectionTest.............false
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - jdbcUrl.........................jdbc:mysql://localhost:3306/hospitals?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - leakDetectionThreshold..........0
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - maxLifetime.....................50000
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - maximumPoolSize.................10
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - metricRegistry..................none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - metricsTrackerFactory...........none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - minimumIdle.....................5
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - password........................<masked>
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - poolName........................"HikariPool-1"
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - readOnly........................false
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - registerMbeans..................false
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - scheduledExecutor...............none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - scheduledExecutorService........internal
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - schema..........................none
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - threadFactory...................internal
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - transactionIsolation............default
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - username........................"smhasan11"
2018-05-21 22:06:14 DEBUG HikariConfig:1171 - validationTimeout...............5000
2018-05-21 22:06:14 INFO  HikariDataSource:81 - HikariPool-1 - Starting...
Mon May 21 22:06:15 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:06:16 DEBUG HikariPool:537 - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@b42dd5
2018-05-21 22:06:16 INFO  HikariDataSource:83 - HikariPool-1 - Start completed.
2018-05-21 22:06:16 DEBUG HikariConfig:512 - Driver class com.mysql.cj.jdbc.Driver found in Thread context class loader ParallelWebappClassLoader
  context: unsaarAPI-1.0
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@f49f1c

2018-05-21 22:06:16 WARN  HikariConfig:1101 - HikariPool-2 - idleTimeout is close to or more than maxLifetime, disabling it.
2018-05-21 22:06:16 WARN  HikariConfig:1112 - HikariPool-2 - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
2018-05-21 22:06:16 DEBUG HikariConfig:1139 - HikariPool-2 - configuration:
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - allowPoolSuspension.............false
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - autoCommit......................true
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - catalog.........................none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - connectionInitSql...............none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - connectionTestQuery.............none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - connectionTimeout...............50000
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - dataSource......................none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - dataSourceClassName.............none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - dataSourceJNDI..................none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - dataSourceProperties............{password=<masked>}
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - driverClassName................."com.mysql.cj.jdbc.Driver"
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - healthCheckProperties...........{}
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - healthCheckRegistry.............none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - idleTimeout.....................0
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - initializationFailFast..........true
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - initializationFailTimeout.......1
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - isolateInternalQueries..........false
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - jdbc4ConnectionTest.............false
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - jdbcUrl.........................jdbc:mysql://localhost:3306/nsw_rss?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - leakDetectionThreshold..........0
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - maxLifetime.....................50000
2018-05-21 22:06:16 DEBUG HikariPool:403 - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - maximumPoolSize.................10
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - metricRegistry..................none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - metricsTrackerFactory...........none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - minimumIdle.....................5
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - password........................<masked>
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - poolName........................"HikariPool-2"
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - readOnly........................false
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - registerMbeans..................false
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - scheduledExecutor...............none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - scheduledExecutorService........internal
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - schema..........................none
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - threadFactory...................internal
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - transactionIsolation............default
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - username........................"smhasan11"
2018-05-21 22:06:16 DEBUG HikariConfig:1171 - validationTimeout...............5000
Mon May 21 22:06:16 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:06:16 INFO  HikariDataSource:81 - HikariPool-2 - Starting...
Mon May 21 22:06:16 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:06:17 DEBUG HikariPool:699 - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1d3d212
Mon May 21 22:06:17 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:06:17 DEBUG HikariPool:537 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1f92fb5
2018-05-21 22:06:17 INFO  HikariDataSource:83 - HikariPool-2 - Start completed.
....
2018-05-21 22:13:03 INFO  HospitalDaoImpl:163 - Going to CLOSE Connection from 'getHospitalbyName()'...
2018-05-21 22:13:03 INFO  HospitalDaoImpl:179 - .................CONNECTION CLOSED SUCCESSFULLY...............
2018-05-21 22:13:03 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@344ea4: (connection has passed maxLifetime)
Mon May 21 22:13:03 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:03 DEBUG PoolBase:137 - HikariPool-1 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@1ff8f7b: (connection has passed maxLifetime)
Mon May 21 22:13:03 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:04 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@1853497: (connection has passed maxLifetime)
2018-05-21 22:13:04 DEBUG HikariPool:699 - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1a9f96d
2018-05-21 22:13:04 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@134fd01
Mon May 21 22:13:04 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:05 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@a16755
2018-05-21 22:13:05 DEBUG HikariPool:403 - HikariPool-2 - After adding stats (total=5, active=0, idle=5, waiting=0)
2018-05-21 22:13:06 INFO  Bismillah:130 - java.util.Collections$3@1a72959
2018-05-21 22:13:06 INFO  HospitalDaoImpl:119 - Going to CLOSE Connection from 'getHospitalbyId()'...
2018-05-21 22:13:06 INFO  HospitalDaoImpl:179 - .................CONNECTION CLOSED SUCCESSFULLY...............
2018-05-21 22:13:09 INFO  Bismillah:296 - java.util.Collections$3@ac9458
2018-05-21 22:13:12 INFO  Bismillah:52 - java.util.Collections$3@79142c
2018-05-21 22:13:16 DEBUG HikariPool:403 - HikariPool-1 - Pool stats (total=10, active=10, idle=0, waiting=1)
2018-05-21 22:13:17 DEBUG HikariPool:403 - HikariPool-2 - Pool stats (total=5, active=0, idle=5, waiting=0)
2018-05-21 22:13:46 DEBUG HikariPool:403 - HikariPool-1 - Pool stats (total=10, active=10, idle=0, waiting=1)
2018-05-21 22:13:47 DEBUG HikariPool:403 - HikariPool-2 - Pool stats (total=5, active=0, idle=5, waiting=0)
2018-05-21 22:13:49 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@10d3f87: (connection has passed maxLifetime)
Mon May 21 22:13:49 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:49 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@122c0c8: (connection has passed maxLifetime)
2018-05-21 22:13:49 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@f7fe77
Mon May 21 22:13:49 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:50 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@d80138
2018-05-21 22:13:50 DEBUG HikariPool:403 - HikariPool-2 - After adding stats (total=5, active=0, idle=5, waiting=0)
2018-05-21 22:13:51 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@16c5d43: (connection has passed maxLifetime)
Mon May 21 22:13:51 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:52 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@965b49
2018-05-21 22:13:53 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@134fd01: (connection has passed maxLifetime)
Mon May 21 22:13:53 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:54 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1cd38f5
2018-05-21 22:13:55 DEBUG PoolBase:137 - HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@a16755: (connection has passed maxLifetime)
Mon May 21 22:13:55 EDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2018-05-21 22:13:55 DEBUG HikariPool:699 - HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1a8dea8
2018-05-21 22:14:02 DEBUG HikariPool:403 - HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=0)
2018-05-21 22:14:02 ERROR HospitalDaoImpl:74 - HikariPool-1 - Connection is not available, request timed out after 50020ms.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 50020ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:95)
	at util.DBConnection.getHospitalDBConnnection(DBConnection.java:70)
	at com.unsaar.api.Bismillah.getAllHospitals(Bismillah.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

I couldn't find how **HikariPool-1** got in this state:
`DEBUG HikariPool:403 - HikariPool-1 - Pool stats (total=10, active=10, idle=0, waiting=1)`
I thought when I close the connection, it goes back to the pool. Am i missing something? What am I doing wrong?
Can you please help me to fix it.

**Comment by zimmi** [comment]
It seems like you are forgetting to close the connections from your hospitalDataSource (HikariPool-1) somewhere.
As a crude debugging help, you could add a print statement inside `DBConnection::getHospitalDBConnnection` and look for missing `Going to CLOSE Connection ...` lines right after.

**Comment by smhasan11** [comment]
Thanks @zimmi . At one place I didn't close the connection. 
May Almighty Allah bless you and show you the right path.
