### ISSUE TITLE
Unable to connect to Postgres 10, patch hack provided

### ISSUE THREAD

**Issue by techwanker** [brettwooldridge/HikariCP#1167]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_131
Database        : PostgreSQL 10.4
Driver version  : 9.1-901.jdbc4
```
[main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.postgresql.util.PSQLException: This ResultSet is closed.
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2674)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1791)
	at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:39)
	at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:211)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1772)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:263)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:775)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:464)

423,425c423,431
<          if (transactionIsolation != defaultTransactionIsolation) {
<             connection.setTransactionIsolation(transactionIsolation);
<          }
---
>      	if (transactionIsolation != defaultTransactionIsolation) {
> 			if (transactionIsolation == -1) {
> 				LOGGER.warn("transactionIsolationSet to  -1 not setting transactionIsolation");
> 			} else {
> 				LOGGER.info("=== changing transactionIsolation from " + defaultTransactionIsolation + " to "
> 						+ transactionIsolation);
> 				connection.setTransactionIsolation(transactionIsolation);
> 			}
> 		}
474,475c480,485
<                throw e;
<             }
---
>             	   if (e.getSQLState().equals("55000")) {
>                        // postgresql
>             	   } else {
>                        throw e;
>             	   }
>             	}

**Comment by brettwooldridge** [comment]
Please use the latest pgsql driver, v42.2.2.
