### ISSUE TITLE
Question : How to use HikariCP is resilient environments?

### ISSUE THREAD

**Issue by afrin216** [brettwooldridge/HikariCP#1193]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_172
Database        : OJDBC
Driver version  : 12.2.0.1
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

@brettwooldridge 
Love HikariCP and the blazing speed it provides! Had couple of questions, hope someone from this community can answer.

We have dev & prod testing environments where the databases have been configured without failover nodes. So whenever the single database server goes down, HikariCP starts logging messages that it is unable to establish connections, which is fine expected.

However after our DB admins go and bring the database back up (sometimes after couple of hours)  HikariCP still keeps logging out the same `SQLConnectionTransientException`s that it cannot establish connection to the database. The total number of connections and idle connections remain at 0.

Restarting the services fixes this issues, as the pool is recreated and reinitialized.

On searching through the issues I found https://github.com/brettwooldridge/HikariCP/issues/843, specifically https://github.com/brettwooldridge/HikariCP/issues/843#issuecomment-287615297 that states that HikariCP doesn't close abandoned connections.

This is the right approach for the client side and I agree if the application is the one at fault. However if the database server goes down and all connections in HikariCP gets abandoned and then the database server comes back up, not recovering seems to go against supporting resiliency.

We could add failover nodes to the database, still if all the failover nodes go down along with the main one, then this problem can creep back up again. Without restarting the instance after the database comes back up we can't recover from this bad state.

Is there some configuration I'm missing? Or is this HikariCP's stance? 

Do you have any suggestions on how to handle this (besides the obvious solution of adding failover nodes)?

**Comment by afrin216** [comment]
To illustrate my point, I created a simple unit test

```java
  private static class TestDriver implements Driver {
    private static boolean throwException = true;

    @Override
    public Connection connect(final String url, final Properties info) throws SQLException {
      if (throwException) {
        try {
          TimeUnit.SECONDS.sleep(1);
        } catch (final InterruptedException e) {
          e.printStackTrace();
        }
      }
      return mock(Connection.class);
    }

    @Override
    public boolean acceptsURL(final String url) throws SQLException {
      return url.startsWith("jdbc:mock");
    }

    @Override
    public DriverPropertyInfo[] getPropertyInfo(final String url, final Properties info)
        throws SQLException {
      return new DriverPropertyInfo[0];
    }

    @Override
    public int getMajorVersion() {
      return 0;
    }

    @Override
    public int getMinorVersion() {
      return 0;
    }

    @Override
    public boolean jdbcCompliant() {
      return true;
    }

    @Override
    public Logger getParentLogger() throws SQLFeatureNotSupportedException {
      return null;
    }
  }

  @Test
  public void recoversFromTransientSQLExceptions() SQLException, InterruptedException {

    DriverManager.registerDriver(new TestDriver());
    final ImmutableMap defaults = ImmutableMap.of(
        "minimumIdle", "1",
        "maximumPoolSize", "2",
        "connectionTimeout", "250",
        "maxLifetime", "100");
    final HikariConfig dsProps = new HikariConfig();
    dsProps.setMinimumIdle(1);
    dsProps.setMaximumPoolSize(2);
    dsProps.setMaxLifetime(100);
    dsProps.setConnectionTimeout(250);
    dsProps.setJdbcUrl("jdbc:mock:abc");

    final HikariDataSource dataSource = new HikariDataSource(dsProps);
    final HikariDataSource finalDataSource = dataSource;
    IntStream.range(0, 10).forEach((i) -> {
      if (i == 4) {
        TestDriver.throwException = false;
        try {
          TimeUnit.SECONDS.sleep(10);
        } catch (final InterruptedException e) {
          e.printStackTrace();
        }
      }
      try {
        System.out.println(finalDataSource.getConnection());
      } catch (final SQLException e) {
        System.out.println("Got [" + i + "] sqlexception");
        e.printStackTrace();
      }
    });

    TimeUnit.SECONDS.sleep(10);
    TestDriver.throwException = false;

    System.out.println("Getting connection after registering proper driver:");
    System.out.println(dataSource.getConnection());

  }
```

I should have gotten
attempt 0 - exception
attempt 1 - exception
attempt 2 - exception
attempt 3 - exception
attempt 4 and remaining - works


But I never get a connection object. All I get are exceptions for all the calls 
```
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 252ms.
```

Does this mean HikariCP doesn't want to recover from a bad state, even though database has recovered?

**Comment by brettwooldridge** [comment]
@afrin216 Your test is not valid.  Connections are never closed.  Stll...

I modified the print in the try..catch slightly:
```java
         try {
            final Connection connection = finalDataSource.getConnection();
            System.out.println("Got [" + i + "] " + connection);
         } catch (final SQLException e) {
            System.out.println("Got [" + i + "] sqlexception");
            e.printStackTrace();
         }
```

What I get is (in summary):
```
Got [0] HikariProxyConnection@1513867245 wrapping Mock for Connection, hashCode: 1866768727
Got [1] sqlexception
Got [2] sqlexception
Got [3] sqlexception
Got [4] HikariProxyConnection@57241990 wrapping Mock for Connection, hashCode: 360936478
Got [5] sqlexception
...
Got [9] sqlexception
```
Explanation:
 * When the pool is initialized, 1 connection is created before your test even starts ... the ``connectionTimeout`` does not apply.
 * Therefore, when the test starts, there is one connection in the pool ... thus the "Got [0] ..." line.
 * However, this connection is not closed, so the pool is at "1 Total, 1 Used, 0 Idle".
 * Iterations 1, 2, 3 timeout as expected.
 * Iteration 4 sets ``throwException = false``, therefore the "Got [4] ..." line above.
 * However, this connection is not closed, so the pool is at "2 Total, 2 Used, 0 Idle".
 * There is no more capacity in the pool.  The ``maximumPoolSize`` is 2, so no more can be created.
 * Therefore, iterations 5-9 all timeout.

The behavior is correct.

**Comment by afrin216** [comment]
Ah, thanks for that. But in dev, I see this from Hikari debug log

---

[HikariPool-1f0098bdce20acf7fa739bd69020b909bfe205733ffa620eaa8ac336e68209bc housekeeper] com.zaxxer.hikari.pool.HikariPool [cid:] HikariPool-1f0098bdce20acf7fa739bd69020b909bfe205733ffa620eaa8ac336e68209bc - Before cleanup stats (total=0, active=0, idle=0, waiting=0)

DEBUG [HikariPool-1f0098bdce20acf7fa739bd69020b909bfe205733ffa620eaa8ac336e68209bc housekeeper] com.zaxxer.hikari.pool.HikariPool [cid:] HikariPool-1f0098bdce20acf7fa739bd69020b909bfe205733ffa620eaa8ac336e68209bc - After cleanup stats (total=0, active=0, idle=0, waiting=0)

---

So if it was because of connections not getting closed, we should have seen active>0, right? We're using `idle=2` and `maximumPoolSize=20`. In our specific instance, this state occurs when database goes down due to archiver fault. This exception keeps getting thrown every time when HIkariCP tries to establish a connection. Even after database admin fixes it, HIkariCP keeps throwing same exception along with all stats at 0

---

java.sql.SQLTransientConnectionException: HikariPool-.net1f0098bdce20acf7fa739bd69020b909bfe205733ffa620eaa8ac336e68209bc - Connection is not available, request timed out after 30000ms. at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190) at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155) at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) at .
.
.
.
.
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454) at 
.
.
.
at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1382) at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) 


Caused by: java.sql.SQLException: ORA-00257: Archiver error. Connect AS SYSDBA only until resolved. at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494) at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:441) at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:436) at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:546) at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623) at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252) at oracle.jdbc.driver.T4CTTIoauthenticate.doOSESSKEY(T4CTTIoauthenticate.java:519) at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:615) at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688) at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39) at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692) at java.util.concurrent.FutureTask.run(FutureTask.java:266)

---

I still don't see why can't HikariCP recover from this state?

**Comment by brettwooldridge** [comment]
If the driver keeps throwing 

Caused by: java.sql.SQLException: ORA-00257: Archiver error. Connect AS SYSDBA only until resolved.

What is HikariCP supposed to do?  If the driver refuses to give it a connection, the issue is either with the driver itself or more likely the database.
