### ISSUE TITLE
getConnection(username,password) is not supported

### ISSUE THREAD

**Issue by techwanker** [brettwooldridge/HikariCP#1197]
#### Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.1.4

    Caused by: java.sql.SQLFeatureNotSupportedException: null
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:135) ~[HikariCP-3.1.0.jar:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]

From HikariDataSource.java

    @Override
   public Connection getConnection(String username, String password) throws SQLException
   {
      throw new SQLFeatureNotSupportedException();
   }

Certainly people are using Hikari with Spring, it is included with SpringBoot.

**Comment by brettwooldridge** [comment]
@techwanker This is almost certainly a misconfiguration in your Spring setup.  [See here](https://stackoverflow.com/questions/31880955/what-to-replace-the-datasourceconnectionproviderimpl-class).  What version of Hibernate are you using?

**Comment by brettwooldridge** [comment]
@ljnelson There are [other solutions](https://stackoverflow.com/questions/39333530/how-to-configure-hikaricp-with-eclipselink) as well.

HikariCP does not support ``getConnection(username, password)``, because that would allow changing users for different connection instances.  Having different users can mean having different permissions or even database visibility, which creates havoc in the application.  Many other pools also do not implement this method.

I suggest taking advantage of the several patterns available for EclipseLink to avoid this issue.
