### ISSUE TITLE
Multiple HikariPools - Mac vs Win behaviour

### ISSUE THREAD

**Issue by wondris009** [brettwooldridge/HikariCP#1204]
#### Environment
```
HikariCP version: from SpringBoot 2.0.1
JDK version     : 1.8.0_181
Database        : Oracle12c in Docker
Driver version  : ojdbc8-12.2.0.1.jar
```
I have multiple unit tests accessing oracle database in docker. During some of them i am getting this weird behaviour. Unit test creates HikariPool-3 but db transactions are made under HikariPool-1 which is of course closed and therefore test fails. See attached logs

`14:50:39.274 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - Driver class oracle.jdbc.OracleDriver found in Thread context class loader sun.misc.Launcher$AppClassLoader@2a139a55
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-3 - configuration:
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............none
14:50:39.423 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................."oracle.jdbc.OracleDriver"
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:oracle:thin:@localhost:1521:XE
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................10
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........com.zaxxer.hikari.metrics.micrometer.MicrometerMetricsTrackerFactory@45e53fcc
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
14:50:39.424 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-3"
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........internal
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - schema..........................none
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - username........................"tracing"
14:50:39.425 [Test worker] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
14:50:39.425 [Test worker] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Starting...
14:50:39.481 [Test worker] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@35c97feb
14:50:39.484 [Test worker] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Start completed.
14:50:39.574 [Test worker] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Building JPA container EntityManagerFactory for persistence unit 'default'
14:50:39.579 [Test worker] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
14:50:39.588 [HikariPool-3 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Pool stats (total=1, active=0, idle=1, waiting=0)
14:50:39.649 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@4ba51093
14:50:39.720 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@589a453a
14:50:39.780 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@2030f613
14:50:39.845 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@600ede1e
14:50:39.908 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@3b3439b5
14:50:39.980 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@7891a606
14:50:40.035 [Test worker] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
14:50:40.036 [Test worker] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
14:50:40.036 [Test worker] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.
14:50:40.036 [Test worker] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
14:50:40.036 [Test worker] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'tracingScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 3 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

14:50:40.036 [Test worker] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'tracingScheduler' initialized from an externally provided properties instance.
14:50:40.036 [Test worker] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.3
14:50:40.037 [Test worker] INFO  org.quartz.core.QuartzScheduler - JobFactory set to: com.gfkl.dma.scheduler.AutowiringSpringBeanJobFactory@7c5ab0f9
14:50:40.037 [Test worker] INFO  o.s.s.quartz.SchedulerFactoryBean - Starting Quartz Scheduler now
14:50:40.037 [Test worker] INFO  org.quartz.core.QuartzScheduler - Scheduler tracingScheduler_$_NON_CLUSTERED started.
14:50:40.039 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@60c16bba
14:50:40.097 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@30965d40
14:50:40.155 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@31cf6f92
14:50:40.155 [HikariPool-3 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - After adding stats (total=10, active=0, idle=10, waiting=0)
14:50:41.181 [Test worker] WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
14:50:43.679 [Test worker] INFO  c.g.d.m.p.WrongAddressCycleBreakerIntegrationTest - Started WrongAddressCycleBreakerIntegrationTest in 7.032 seconds (JVM running for 41.888)
14:50:43.683 [Test worker] INFO  c.g.dma.scheduler.TracingScheduler - init
[EL Info]: transaction: 2018-07-18 14:50:43.726--ClientSession(834986934)--Thread(Thread[Test worker,5,main])--Communication failure detected when attempting to create transaction on database.  Attempting to retry begin transaction. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
Error Code: 0.
[EL Warning]: 2018-07-18 14:50:43.729--ClientSession(834986934)--Thread(Thread[Test worker,5,main])--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
Error Code: 0

Internal Exception: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
Error Code: 0
Query: ValueReadQuery(sql="SELECT SEQ_PROVIDER_DELIVERY.NEXTVAL FROM DUAL")
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
Error Code: 0
Query: ValueReadQuery(sql="SELECT SEQ_PROVIDER_DELIVERY.NEXTVAL FROM DUAL")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:147)
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:170)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:313)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:581)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1660)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:321)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.beginTransaction(DatasourceAccessor.java:254)
	at org.eclipse.persistence.sessions.server.ClientSession.retryTransaction(ClientSession.java:786)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicBeginTransaction(AbstractSession.java:747)
	at org.eclipse.persistence.sessions.server.ClientSession.addWriteConnection(ClientSession.java:755)
	at org.eclipse.persistence.sessions.server.ServerSession.acquireClientConnection(ServerSession.java:268)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:280)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:270)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:256)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:327)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelect(DatasourceCallQueryMechanism.java:309)
	at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:197)
	at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
	at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137)
	at org.eclipse.persistence.internal.sessions.AbstractSession.internalExecuteQuery(AbstractSession.java:3346)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1892)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1874)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1824)
	at org.eclipse.persistence.sequencing.QuerySequence.select(QuerySequence.java:323)
	at org.eclipse.persistence.sequencing.QuerySequence.updateAndSelectSequence(QuerySequence.java:268)
	at org.eclipse.persistence.sequencing.StandardSequence.getGeneratedVector(StandardSequence.java:73)
	at org.eclipse.persistence.sequencing.Sequence.getGeneratedVector(Sequence.java:265)
	at org.eclipse.persistence.internal.sequencing.SequencingManager$Preallocation_NoTransaction_State.getNextValue(SequencingManager.java:683)
	at org.eclipse.persistence.internal.sequencing.SequencingManager.getNextValue(SequencingManager.java:1107)
	at org.eclipse.persistence.internal.sequencing.ClientSessionSequencing.getNextValue(ClientSessionSequencing.java:70)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:366)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:325)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.assignSequenceNumber(UnitOfWorkImpl.java:530)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNotRegisteredNewObjectForPersist(UnitOfWorkImpl.java:4386)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.registerNotRegisteredNewObjectForPersist(RepeatableWriteUnitOfWork.java:521)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNewObjectForPersist(UnitOfWorkImpl.java:4331)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.persist(EntityManagerImpl.java:593)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:304)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:490)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:593)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.gfkl.dma.module.providerDelivery.WrongAddressCycleBreakerIntegrationTest.Master result code of given provider delivery should be changed for there are already some deliveries for given ref no. Setting is taken from application-dev.properties file(WrongAddressCycleBreakerIntegrationTest.groovy:37)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
	... 63 more

`
Problem is that this is not working only on MAC machine, other colleagues working on WINDOWS machines creates pool HikariPool-1 and make db transaction on that pool and therefore it is normally working. Question is why is it creating more pools? Can somebody put some light for me on that?

**Comment by brettwooldridge** [comment]
Sounds like you are holding a datasource reference in a static variable somewhere...
