### ISSUE TITLE
Connection Pool Size NOT going down.

### ISSUE THREAD

**Issue by Tonyrajarat** [brettwooldridge/HikariCP#1208]
JDK : 1.7
HirakiCP : HirakiCP-Java7 : 2.4.13

I have 2 DB connections, both ORACLE.

Problem Statement : Can someone please explain why total 10+3 and keep increasing  active=3. Since this is running in my local IDE, no one opening connection.  I checked all DAO's whereever getDataSource() references, properly closed in finally block using 
if(con!=null){
   con.close()
}
HikariPool-2 - After adding stats (total=13, active=3, idle=10, waiting=0)

wprConfig.setJdbcUrl(_wprDbUrl);
wprConfig.setUsername(_wprDbUserName);
wprConfig.setPassword(_wprDbPwd);
wprConfig.setMaximumPoolSize(20);
wprConfig.setMinimumIdle(10);
wprConfig.setConnectionTimeout(30000);
wprConfig.setConnectionInitSql("select 1 from dual");
wprConfig.setDriverClassName("oracle.jdbc.driver.OracleDriver");        
wprConfig.setIdleTimeout(300000);
wprConfig.setLeakDetectionThreshold(60000);
//wprConfig.setMaxLifetime(1800000);
wprConfig.addDataSourceProperty( "cachePrepStmts" , "true" );
wprConfig.addDataSourceProperty( "prepStmtCacheSize" , "250" );
wprConfig.addDataSourceProperty( "prepStmtCacheSqlLimit" , "2048" );
wprConfig.addDataSourceProperty("driverType", "thin");
wprDs = new HikariDataSource(wprConfig);

emanConfig.setJdbcUrl(_emanDbUrl);
emanConfig.setUsername(_emanDbUserName);
emanConfig.setPassword(_emanDbPwd);
emanConfig.setMaximumPoolSize(20);
emanConfig.setMinimumIdle(10);
emanConfig.setConnectionTimeout(30000);
//emanConfig.setMaxLifetime(1800000);
emanConfig.setConnectionInitSql("select 1 from dual");
emanConfig.setDriverClassName("oracle.jdbc.driver.OracleDriver");
emanConfig.setIdleTimeout(300000);
emanConfig.setLeakDetectionThreshold(60000);
emanConfig.addDataSourceProperty( "cachePrepStmts" , "true" );
emanConfig.addDataSourceProperty( "prepStmtCacheSize" , "250" );
emanConfig.addDataSourceProperty( "prepStmtCacheSqlLimit" , "2048" );
emanConfig.addDataSourceProperty("driverType", "thin");
emanDs = new HikariDataSource(emanConfig);

-----------
LOG :

2018-07-24 15:52:44 DEBUG HikariPool:380 - HikariPool-1 - Pool stats (total=7, active=0, idle=7, waiting=0)
2018-07-24 15:52:44 DEBUG HikariPool:443 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@77fd1109
2018-07-24 15:52:44 DEBUG HikariPool:615 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@77fd1109
2018-07-24 15:52:44 DEBUG HikariPool:443 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@769a36a
2018-07-24 15:52:44 DEBUG HikariPool:615 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@769a36a
2018-07-24 15:52:44 DEBUG HikariPool:443 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@286787f3
2018-07-24 15:52:44 DEBUG HikariPool:615 - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@286787f3
2018-07-24 15:52:44 DEBUG HikariPool:380 - HikariPool-1 - After adding stats (total=10, active=0, idle=10, waiting=0)
2018-07-24 15:52:44 DEBUG HikariPool:380 - HikariPool-2 - Pool stats (total=11, active=3, idle=8, waiting=0)
2018-07-24 15:52:44 DEBUG HikariPool:443 - HikariPool-2 - Added connection oracle.jdbc.driver.T4CConnection@3c562185
2018-07-24 15:52:44 DEBUG HikariPool:615 - HikariPool-2 - Added connection oracle.jdbc.driver.T4CConnection@3c562185
2018-07-24 15:52:44 DEBUG HikariPool:443 - HikariPool-2 - Added connection oracle.jdbc.driver.T4CConnection@3ab2c1b5
2018-07-24 15:52:44 DEBUG HikariPool:615 - HikariPool-2 - Added connection oracle.jdbc.driver.T4CConnection@3ab2c1b5
2018-07-24 15:52:44 DEBUG HikariPool:380 - HikariPool-2 - After adding stats (total=13, active=3, idle=10, waiting=0)

Thanks in advance,
-Ant.

**Comment by brettwooldridge** [comment]
@Tonyrajarat Ok, I have a question...

Are you saying that the ``leakDetectionThreshold`` never reports a leak for *HikariPool-2* after one minute?

Also, these settings...
```
wprConfig.addDataSourceProperty( "cachePrepStmts" , "true" );
wprConfig.addDataSourceProperty( "prepStmtCacheSize" , "250" );
wprConfig.addDataSourceProperty( "prepStmtCacheSqlLimit" , "2048" );
```
...are specific to MySQL and do not apply to Oracle.

**Comment by Tonyrajarat** [comment]
Hello Brett,

yes HikariPool-2 (emanConfig) not showing any details on leakDetectionThreshold.

I can see in log, which ideally active should release back to pool NOT happening.
HikariPool-2 - After adding stats (total=13, active=3, idle=10, waiting=0)

Please correct me if I miss anything here.

Thanks for your reply.

**Comment by Tonyrajarat** [comment]
Any help !!!
Getting below Exception and manually I have to restart application.
HikariPool-2 - Connection is not available, request timed out after 30000ms.

Thanks,
-Ant.

**Comment by brettwooldridge** [comment]
@Tonyrajarat When a leak is detected, it should look like this in your log:
```
  23:15 [pool-2-thread-1] WARN ProxyLeakTask - Connection leak detection triggered for com.zaxxer.hikari.mocks.StubConnection@16ad008c on thread main, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[classes/:?]
	at com.zaxxer.hikari.pool.MiscTest.testLeakDetection(MiscTest.java:118) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) ~[junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) ~[junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) ~[junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) ~[surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272) ~[surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236) ~[surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) ~[surefire-junit4-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386) ~[surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323) ~[surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143) ~[surefire-booter-2.20.jar:2.20]
```
Given your ``leakDetectionThreshold`` of ``60000ms`` I would expect to see quite a few of these.
