### ISSUE TITLE
How does Hikari Housekeeping Timer work?

### ISSUE THREAD

**Issue by gitterjoe** [brettwooldridge/HikariCP#1213]
#### Environment
```
HikariCP version: 2.3.13
JDK version     : 1.8.0_121-b13
Database        : MariaDB
Driver version  : mariadb-java-client 2.0.2
```
Hello there. We are working with `Hibernate 5.0.10` (Wildfly 10.1). We have 3 separate HikariCPs. Additionally one of them is in multi-tenancy mode.

After startup the two single tenant CPs have exactly one Houskeeper Timer Thread each. The multitenant CP has three.

Is that ok so? On which numbers does the number of Houseeeeping-Timer-Threads depend?

In unregular periods we see the following log. Sometimes directly after startup of the pool, sometimes after calling the `maximumPoolSize + 1st` time `getSession()` on the `SessionFactory`.

```
Exception in thread "HikariCP connection closer (pool HTS-Multitenant-HikariCP-Pool)" java.lang.NullPointerException
        at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:271)
        at com.zaxxer.hikari.pool.PoolUtilities.quietlyCloseConnection(PoolUtilities.java:67)
        at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Exception in thread "HikariCP connection closer (pool HTS-Multitenant-HikariCP-Pool)"   at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
        at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:271)
        at com.zaxxer.hikari.pool.PoolUtilities.quietlyCloseConnection(PoolUtilities.java:67)
        at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "HikariCP connection closer (pool HTS-Multitenant-HikariCP-Pool)" java.lang.NullPointerException
        at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:271)
        at com.zaxxer.hikari.pool.PoolUtilities.quietlyCloseConnection(PoolUtilities.java:67)
        at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "HikariCP connection closer (pool HTS-Multitenant-HikariCP-Pool)" java.lang.NullPointerException
        at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:271)
        at com.zaxxer.hikari.pool.PoolUtilities.quietlyCloseConnection(PoolUtilities.java:67)
        at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "HikariCP connection closer (pool HTS-Multitenant-HikariCP-Pool)" java.lang.NullPointerException
        at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:271)
        at com.zaxxer.hikari.pool.PoolUtilities.quietlyCloseConnection(PoolUtilities.java:67)
        at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Besides the multi tenancy, all pools have the same settings. Interestingly this `Logger` instance is not always null!  `slf4j` (version 1.7.22) and `slf4j-log4j-12` are provided.

The single tenant CPs work perfectly! Thie `MultiTenantConnectionProvider` is also used in another project, working just fine without any NPEs caused by the Logger (although there are only 2 Houskeeping Timer Threads).

Have you any clue what might cause this issue?

**Comment by brettwooldridge** [comment]
@gitterjoe Your version of HikariCP is extremely old.  Please upgrade to v3.x and re-open if the problem still occurs.
