### ISSUE TITLE
HikariCP-java6-2.3.13 / Oracle 12c

### ISSUE THREAD

**Issue by dm-msk** [brettwooldridge/HikariCP#1214]
Hello. Sometimes an application cannot connect to oracle database. Why?

2018-июл-31 19:03:09 : DEBUG main com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.addConnection(line:466) - Connection attempt to database dataSource failed: Ошибка ввода/вывода: Connection reset
java.sql.SQLRecoverableException: Ошибка ввода/вывода: Connection reset
...
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at oracle.net.ns.DataPacket.send(DataPacket.java:199)
	at oracle.net.ns.NetOutputStream.flush(NetOutputStream.java:211)
	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:227)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:175)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:100)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:85)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:123)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:79)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1122)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:1099)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:288)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:366)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:752)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:366)
	... 25 more

Oracle log
***********************************************************************

Fatal NI connect error 12170.

VERSION INFORMATION:
TNS for Linux: Version 12.1.0.2.0 - Production
Oracle Bequeath NT Protocol Adapter for Linux: Version 12.1.0.2.0 - Production
TCP/IP NT Protocol Adapter for Linux: Version 12.1.0.2.0 - Production
Time: 31-JUL-2018 18:15:10
Tracing not turned on.
Tns error struct:
ns main err code: 12535

TNS-12535: TNS:operation timed out
ns secondary err code: 12606
nt main err code: 0
nt secondary err code: 0
nt OS err code: 0
Client address: (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.166.19)(PORT=36020))
Tue Jul 31 18:15:10 2018
WARNING: inbound connection timed out (ORA-3136)

**Comment by dm-msk** [comment]
2018-авг-10 09:06:46 : DEBUG Hikari Housekeeping Timer (pool dataSource) com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.logPoolState(line:588) - Before cleanup pool stats dataSource (total=0, inUse=0, avail=0, waiting=0)
2018-авг-10 09:06:46 : DEBUG Hikari Housekeeping Timer (pool dataSource) com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.logPoolState(line:588) - After cleanup pool stats dataSource (total=0, inUse=0, avail=0, waiting=0)
2018-авг-10 09:07:16 : DEBUG Hikari Housekeeping Timer (pool dataSource) com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.logPoolState(line:588) - Before cleanup pool stats dataSource (total=0, inUse=0, avail=0, waiting=0)
2018-авг-10 09:07:16 : DEBUG Hikari Housekeeping Timer (pool dataSource) com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.logPoolState(line:588) - After cleanup pool stats dataSource (total=0, inUse=0, avail=0, waiting=0)
2018-авг-10 09:07:46 : DEBUG Hikari Housekeeping Timer (pool dataSource) com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.logPoolState(line:588) - Before cleanup pool stats dataSource (total=0, inUse=0, avail=0, waiting=0)
2018-авг-10 09:07:46 : DEBUG Hikari Housekeeping Timer (pool dataSource) com.zaxxer.hikari.pool.HikariPool - BaseHikariPool.logPoolState(line:588) - After cleanup pool stats dataSource (total=0, inUse=0, avail=0, waiting=0)

**Comment by dm-msk** [comment]
http://www.usn-it.de/index.php/2009/02/20/oracle-11g-jdbc-driver-hangs-blocked-by-devrandom-entropy-pool-empty/

I added -Djava.security.egd=file:///dev/urandom
