### ISSUE TITLE
HikariPool-4 - Connection is not available, request timed out after 10014ms

### ISSUE THREAD

**Issue by rajeevvs2007** [brettwooldridge/HikariCP#1215]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 6.0.5 (MySQL Connector)
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*
Yes

While the application is trying to get a connection from the Hikari pool ,getting the below error and it seems Hikari is trying to create a new  connection instead of using one avaialble in the pool.I am adding the execption and pool status
```

2018-07-31 20:16:17,616 DEBUG - [] [jobId::] [runId::] [] Caller+1 at com.zaxxer.hikari.pool.HikariPool$HouseKeeper.run(HikariPool.java:696) - HikariPool-4 - Pool stats (total=50, active=0, idle=50, waiting=0)

```

```
Could not get JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 10014ms. at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:615) at 

```

**Comment by brettwooldridge** [comment]
@rajeevvs2007 I need to see a larger section of the log, especially the 60 seconds before and after the exception.  You can .zip up a log and attach it here.

**Comment by 112921482** [comment]
I have this querstion too.
My application.yml config like this:
  datasource:
    url: jdbc:mysql://localhost:3306/mdf_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
    username: root
    password: CxhCKcU5&ver2ZYt
    hikari:
      connectionTimeout: 10000
      max-lifetime: 28740000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

**Comment by aleroot** [comment]
I'm having the same issue too, using Hikari in my local network, sometimes I get the following error : 

`java.sql.SQLTransientConnectionException: main_datasource - Connection is not available, request timed out after 30000ms.`

and the application freeze completely like in a deadlock, so I do have to restart the app to fix.

I'm experiencing the issue with the version 3.2.0 of HikariCP and mysql driver: mariadb-java-client:2.2.6 with the following url: `jdbc:mariadb:aurora://192.168.1.2:3306/mydb?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true`

And configuration: 

```
dataSourceClassName="org.mariadb.jdbc.MySQLDataSource"
minimumIdle="1"
maximumPoolSize="5"
idleTimeout="1840000"
poolName="main_datasource"
```

**Comment by macgregor** [comment]
@aleroot I was struggling with this for days but think I have things properly configured now, details on what I was seeing will be below. The trick was setting `usePipelineAuth=false` ([source](https://stackoverflow.com/questions/44002312/sqltransientconnectionexception-after-upgrading-mariadb-connector)). 

Final Config (I also added the performance tuning suggested in [the docs](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration) as best I could as maridb doesnt have all the same properties):

```
spring:
  datasource:
    url: jdbc:mariadb://HOST/database
    username: user
    password: password
    hikari:
      minimumIdle: 16
      maximumPoolSize: 16
      registerMbeans: true
      leakDetectionThreshold: 60000
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: false
        useSSL: true
        usePipelineAuth: false
```

I dont think this will help the other two as they are using the MySQL jdbc drivers and usePipelineAuth is a mariadb driver features as far as I can tell. Maybe there is something similar though, someone else can take a look: [mariadb jdbc properties](https://mariadb.com/kb/en/library/about-mariadb-connector-j/), [mysql jdbc properties](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html).


**Problem Details**

After some time the pool seems to get exhausted. JMX shows the pool is at max connections with threads waiting for a connection, running a client against the service shows errors like:

```
java.sql.SQLTransientConnectionException: activemq-persistence-pool - Connection is not available, request timed out after 30000ms
```

I also noticed after leaving it running over night that while the jmx console showed all 16 connections as active, the database only showed 2 connections from the host, one of which seemed actually active (the server was processing some connections, but slowly) and the other asleep for 25 minutes. The pool still thinks there are 16 active connections. 

```
MariaDB [(none)]> show processlist;
+-------+---------------+------------------------------------------------------------+----------+---------+------+-------+------------------+----------+
| Id    | User          | Host                                                       | db       | Command | Time | State | Info             | Progress |
+-------+---------------+------------------------------------------------------------+----------+---------+------+-------+------------------+----------+
| 46731 | REDACTED      | REDACTED-master:33680                                      | db       | Sleep   | 1558 |       | NULL             |    0.000 |
| 46794 | REDACTED      | REDACTED-master:34334                                      | db       | Sleep   |    4 |       | NULL             |    0.000 |
+-------+---------------+------------------------------------------------------------+----------+---------+------+-------+------------------+----------+
```

When this is happening I do not see log statements about the connection being returned which I normally see when the pool is healthy, though I think this is probably a red herring and doesn't really tell us much.

```
2018-09-21T08:56:57.640-0400 DEBUG 38868 --- [ActiveMQ BrokerService[umb] Task-64] com.zaxxer.hikari.pool.PoolBase          : activemq-persistence-pool - Reset (isolation) on connection org.mariadb.jdbc.MariaDbConnection@46ba5185
```

When I look at the database connections when the problem first starts happening, I see a single active connection in the database while the other 15 sleep. This is also what the connection state in the database looks like when the pool is properly idling except that according to JMX all 16 are active and only one connection is actually doing any work. So the pool is confused about the state of the connections for some reason.

It seems this is due to the mariadb jdbc driver feature `usePipelineAuth`:

> During connection, different queries are executed. When option is active those queries are send using pipeline (all queries are send, then only all results are reads), permitting faster connection creation.

Which makes sense with the behavior I am seeing. From what I understand the driver is trying to optimize the connections so all the requests essentially get funneled to one connection. I guess that how the driver does this confuses hikari which thinks the connections are still running. Setting a timeout on queries may also work, but you still want to set `usePipelineAuth=false`.

Things look alot better so far, connections look sane from the database now, but as this is sort of a load/time based bug for me I can't be sure until I let it sit for a while. I will leave things running over the weekend, that should show if it is a complete solution or not.
