### ISSUE TITLE
oracle 11G close  IO Error: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by YuiFn** [brettwooldridge/HikariCP#1219]
#### Environment
```
HikariCP version: 3.0.0
JDK version     : 1.8.0_111
Database        : ORACLE 11G.
Driver version  : oracle
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
#### Config
```
2018-08-08 22:36:02.281 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : HikariPool-1 - configuration:
2018-08-08 22:36:02.283 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : allowPoolSuspension...........
..false
2018-08-08 22:36:02.283 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : autoCommit....................
..false
2018-08-08 22:36:02.283 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : catalog.......................
..none
2018-08-08 22:36:02.284 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : connectionInitSql.............
..none
2018-08-08 22:36:02.284 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : connectionTestQuery...........
..none
2018-08-08 22:36:02.284 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : connectionTimeout.............
..30000
2018-08-08 22:36:02.284 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSource....................
..none
2018-08-08 22:36:02.284 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSourceClassName...........
..none
2018-08-08 22:36:02.284 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSourceJNDI................
..none
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSourceProperties..........
..{password=<masked>}
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : driverClassName...............
.."oracle.jdbc.OracleDriver"
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : healthCheckProperties.........
..{}
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : healthCheckRegistry...........
..none
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : idleTimeout...................
..600000
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : initializationFailTimeout.....
..1
2018-08-08 22:36:02.286 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : isolateInternalQueries........
..false
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : jdbcUrl.......................
..jdbc:oracle:thin:@xxxx.xxx.xxxx:1521:orcl
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : leakDetectionThreshold........
..2000
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : maxLifetime...................
..1800000
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : maximumPoolSize...............
..66
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : metricRegistry................
..none
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : metricsTrackerFactory.........
..none
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : minimumIdle...................
..33
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : password......................
..<masked>
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : poolName......................
.."HikariPool-1"
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : readOnly......................
..false
2018-08-08 22:36:02.287 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : registerMbeans................
..false
2018-08-08 22:36:02.288 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : scheduledExecutor.............
..none
2018-08-08 22:36:02.288 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : schema........................
..none
2018-08-08 22:36:02.288 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : threadFactory.................
..internal
2018-08-08 22:36:02.288 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : transactionIsolation..........
..default
2018-08-08 22:36:02.288 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : username......................
.."xxx"
2018-08-08 22:36:02.288 DEBUG 3648 --- [           main] com.zaxxer.hikari.HikariConfig           : validationTimeout.............
..5000

```

#### Exception 1 java.sql.SQLRecoverableException:   IO Error: Broken pipe (Write failed)
```
2018-08-08 21:35:46.740 DEBUG 31966 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - After adding stats (total=34, active=1, idle=33, waiting=0)
2018-08-08 21:35:47.493 DEBUG 31966 --- [et-expired-jobs] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@7975ca98 failed

java.sql.SQLRecoverableException:   IO Error: Broken pipe (Write failed)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:587)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:4011)
	at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:132)
	at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:441)
	at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2038)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at com.zaxxer.hikari.pool.HikariPool.closeConnection(HikariPool.java:440)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:386)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:87)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:112)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:230)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:237)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214)
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:52)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1512)
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:45)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189)
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.asyncexecutor.ResetExpiredJobsRunnable.run(ResetExpiredJobsRunnable.java:59)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException:  IO Error: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at oracle.net.ns.DataPacket.send(DataPacket.java:210)
	at oracle.net.ns.NetOutputStream.flush(NetOutputStream.java:230)
	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:321)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:268)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:190)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:107)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:124)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:80)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1137)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:350)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:61)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:574)
	... 30 common frames omitted

```
#### Exception 2  the poll hash more connection but can't get connection from pool
```
2018-08-08 21:35:47.493 DEBUG 31966 --- [et-expired-jobs] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Timeout failure stats (total=34, active=1, idle=33, waiting=0)
2018-08-08 21:35:47.493  WARN 31966 --- [et-expired-jobs] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null
2018-08-08 21:35:47.493 ERROR 31966 --- [et-expired-jobs] o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 926646ms.
2018-08-08 21:35:47.493 ERROR 31966 --- [et-expired-jobs] o.a.e.i.a.ResetExpiredJobsRunnable       : exception during resetting expired jobs

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:431)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.asyncexecutor.ResetExpiredJobsRunnable.run(ResetExpiredJobsRunnable.java:59)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1700)
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:48)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189)
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380)
	... 8 common frames omitted
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:90)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:112)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:230)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:237)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214)
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:52)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1512)
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:45)
	... 10 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 926646ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:386)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:87)
	... 17 common frames omitted
```

**Comment by YuiFn** [comment]
network problem
