### ISSUE TITLE
Connections in pool drop to 0, no leaks detected

### ISSUE THREAD

**Issue by danielmustafa** [brettwooldridge/HikariCP#1245]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_77
Database        : MariaDB
Driver version  : mariadb-java-client 2.3.0
```

```
US-1-crdbms - configuration:                                                                                                                                                                                                      
allowPoolSuspension.............false                                                                                                                                                                                             
autoCommit......................true                                                                                                                                                                                              
catalog.........................none                                                                                                                                                                                              
connectionInitSql...............none                                                                                                                                                                                              
connectionTestQuery.............none                                                                                                                                                                                              
connectionTimeout...............1000                                                                                                                                                                                              
dataSource......................none                                                                                                                                                                                              
dataSourceClassName............."org.mariadb.jdbc.MariaDbDataSource"                                                                                                                                                              
dataSourceJNDI..................none                                                                                                                                                                                              
dataSourceProperties............{user=taxadmin, url=jdbc:mariadb://<redacted>?autoReconnect=true, password=<masked>}                                        
driverClassName.................none                                                                                                                                                                                              
healthCheckProperties...........{}                                                                                                                                                                                                
healthCheckRegistry.............none                                                                                                                                                                                              
idleTimeout.....................0                                                                                                                                                                                                 
initializationFailTimeout.......1                                                                                                                                                                                                 
isolateInternalQueries..........false                                                                                                                                                                                             
jdbcUrl.........................none                                                                                                                                                                                              
leakDetectionThreshold..........5000                                                                                                                                                                                              
maxLifetime.....................120000                                                                                                                                                                                            
maximumPoolSize.................15                                                                                                                                                                                                
metricRegistry..................none                                                                                                                                                                                              
metricsTrackerFactory...........none                                                                                                                                                                                              
minimumIdle.....................15                                                                                                                                                                                                
password........................<masked>                                                                                                                                                                                          
poolName........................"US-1-crdbms"                                                                                                                                                                                     
readOnly........................false                                                                                                                                                                                             
registerMbeans..................false                                                                                                                                                                                             
scheduledExecutor...............none                                                                                                                                                                                              
schema..........................none                                                                                                                                                                                              
threadFactory...................internal                                                                                                                                                                                          
transactionIsolation............default                                                                                                                                                                                           
username........................none                                                                                                                                                                                              
validationTimeout...............5000                                                                                                                                                                                              
```

I have a service that utilizes several connection pools connecting to different datasources.  We've observed that over a couple of days, the above connection pool will lose connections in the pool and it eventually drops to 0.  Obviously when this happens any requests that consume this datasource now fail.  I set the leakDetectionThreshold to 5 seconds and no leaks are being reported.  A thread dump reveals the 'connection adder' for this connection pool seems to be in a locked state:

```
"US-1-crdbms connection adder" #121518 daemon prio=5 os_prio=0 tid=0x00007f28e01ed000 nid=0x329c runnable [0x00007f28ca4d9000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000007b9cadae8> (a java.io.BufferedInputStream)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:236)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:207)
	at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:89)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:783)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:507)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1195)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:560)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:174)
	at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:288)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

We have 16 instances of this app running and this will happen arbitrarily on just one node, so I dont suspect it to be a database issue.  Some of the other datasources are DB2 and I've not observed this issue happening in those pools.  Based on the thread stack I'm wondering if it has to do with mariadb.  Our current workaround is to simply restart the broken node when this occurs.  I'm attaching the logs where you can see the drop of connections to eventually 0 and then the failures start occurring.  I also attached the thread dump.

Also just to clarify, we're using Spring Framework, utilizing a NamedParameterJdbcTemplate which queries so all the getting/releasing of the connection is handled by Spring.

```
2018-09-27 18:13:00.911 DEBUG 1266 --- [US-1-crdbms housekeeper] com.zaxxer.hikari.pool.HikariPool        : US-1-crdbms - Pool stats (total=15, active=0, idle=15, waiting=0)
2018-09-27 18:13:30.911 DEBUG 1266 --- [US-1-crdbms housekeeper] com.zaxxer.hikari.pool.HikariPool        : US-1-crdbms - Pool stats (total=12, active=0, idle=12, waiting=0)
2018-09-27 18:14:00.912 DEBUG 1266 --- [US-1-crdbms housekeeper] com.zaxxer.hikari.pool.HikariPool        : US-1-crdbms - Pool stats (total=9, active=0, idle=9, waiting=0)
2018-09-27 18:14:30.912 DEBUG 1266 --- [US-1-crdbms housekeeper] com.zaxxer.hikari.pool.HikariPool        : US-1-crdbms - Pool stats (total=4, active=0, idle=4, waiting=0)
2018-09-27 18:15:00.913 DEBUG 1266 --- [US-1-crdbms housekeeper] com.zaxxer.hikari.pool.HikariPool        : US-1-crdbms - Pool stats (total=3, active=0, idle=3, waiting=0)
2018-09-27 18:15:20.718 DEBUG 1266 --- [catalina-exec-39] com.zaxxer.hikari.pool.HikariPool        : US-1-crdbms - Timeout failure stats (total=0, active=0, idle=0, waiting=1)
```
[logs.zip](https://github.com/brettwooldridge/HikariCP/files/2425620/logs.zip)

**Comment by danielmustafa** [comment]
@brettwooldridge Hey Brett, any ideas on this?

**Comment by nunnrlc** [comment]
Hi, I think the JDBC URL autoReconnect=true option might be problematic, try removing that.

**Comment by danielmustafa** [comment]
@nunnrlc We can remove that - However just fyi it was only recently added (maybe a couple of days before I posted), and the problem had existed before we introduced that change.  We actually added it to see if it would help.

**Comment by brettwooldridge** [comment]
@wheezymustafa If the thread is stuck in a socket operation, then the issue is outside of HikariCP.  This indicates a firewall or other network related issue.

HikariCP protects most internal operations, such as connection validation, with a network timeout, however it does not do so with initial connection establishment.  That is up to you to configure.

The MariaDB driver has a ``connectTimeout`` driver property that should be set.  Additionally, as a *fallback*, I would recommend setting the ``socketTimeout`` driver property.  Be careful with the ``socketTimeout`` it affects all operations -- set it to something like 120 seconds, *assuming you have no queries that exceed that*.

**Comment by brettwooldridge** [comment]
Any update on this issue?  Have you tried the above suggestions?

**Comment by danielmustafa** [comment]
Hey Brett, sorry for the late response. After your suggestion I set a socket timeout just to make sure we were covering ourselves. Since then we’ve not observed the issue. We’ll keep monitoring. Thanks!

**Comment by bhemar** [comment]
I have the same issue with HikariCP and Microsoft SQL driver (the service is connected to the SQL Server database). I set the socketTimeout to 5 minutes, but this problem is not solved :(

I have only this Hikari log:
HikariPool-1 - Timeout failure stats (total=0, active=0, idle=0, waiting=3)

And lots of connection timeouts (ofc). Do you have any other advice?
I have all default Hikari properties, except this:
* leak-detection-threshold: 60000
* max-lifetime: 600000

**Comment by connect2sandeepgade** [comment]
Hi @brettwooldridge 

Can you please take a look at https://issues.apache.org/jira/browse/HIVE-26669

Looks like we are having the same issue. Setting up oracle jdbc driver Connect_Timeout  should help from 'connection adder' thread blocking rest of the thread to establish a new connection??
