### ISSUE TITLE
Error connecting to MySQL 8 Cannot cast com.mysql.cj.jdbc.Driver to javax.sql.DataSource

### ISSUE THREAD

**Issue by esthrim** [brettwooldridge/HikariCP#1261]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_65
Database        : MySQL
Driver version  : 8.0.12
```
```

			HikariConfig config = new HikariConfig();
			config.setJdbcUrl("jdbc:mysql://192.168.1.161:3306/mydb?serverTimeZone=UTC");
			config.setUsername("admin");
			config.setPassword("myP@assw0rd");
			config.addDataSourceProperty("cachePrepStmts", "true");
			config.addDataSourceProperty("prepStmtCacheSize", "250");
			config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");

			HikariDataSource ds = new HikariDataSource(config);
```
When I run, it throws error like below

```

java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast com.mysql.cj.jdbc.Driver to javax.sql.DataSource
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:113)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:332)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:71)
	at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:59)
```
Please help

**Comment by brettwooldridge** [comment]
Are you sure that is the entire configuration?  It looks like you are setting the DataSource class name to the class name if the driver, in addition to the JDBC URL.  Don’t do that.  

You can optionally set the Driver class name, but do not set the DataSource class name.

**Comment by esthrim** [comment]
@brettwooldridge I'm just following the configuration from [here](https://github.com/brettwooldridge/HikariCP#initialization),   Is there any complete configuration guide to connect with mysql 8  ? I'm stuck here.

**Comment by brettwooldridge** [comment]
Do this:
```
HikariConfig config = new HikariConfig();
config.setJdbcUrl("jdbc:mysql://localhost:3306/simpsons");
```
or this:
```
HikariConfig config = new HikariConfig();
config.setJdbcUrl("jdbc:mysql://localhost:3306/simpsons");
config.setDriverClassName("com.mysql.cj.jdbc.Driver");
```
but *not* this:
```
HikariConfig config = new HikariConfig();
config.setJdbcUrl("jdbc:mysql://localhost:3306/simpsons");
config.setDataSourceClassName("com.mysql.cj.jdbc.Driver");  <-- wrong
```

**Comment by esthrim** [comment]
Thanks @brettwooldridge sorry my mistake, i fix the configuration the error not showed up anymore. but there is another error like below 
```

HikariPool - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:832)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:393)
	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:125)
	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:71)
	at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:59)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(Unknown Source)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:841)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:152)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:829)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
	at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1084)
	at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:663)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:256)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5080)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
```
Is this a network problem or not ? because I can connect to the mysql database from my computer to the mysql database with heidi sql.

**Comment by brettwooldridge** [comment]
@esthrim Does this error happen right away, or after some period of time?  It is not uncommon that it occurs after some time, when the database *wait_timeout* is shorter than the HikariCP ``maxLifetime`` setting.  Try shortening the ``maxLifetime`` setting to 15 minutes (900000ms).  Or better yet, determine what the MySQL configured *wait_timeout* value is, and set the HikariCP ``maxLifetime`` to a few minutes lower.

**Comment by liudc001** [comment]
@brettwooldridge 

i met some errors like this,  
it happens almost  every 8 hours,  
most of the time,  the active connections less than 5.

env:


- mysql8,   

- hikari, 2.7.9   

     maxLifetime: 1800000 (30 minutes)  
     idleTime: 600000  (10 minutes),  
     minimum-idle=5,  
     maximum-pool-size=100  
     connection-test-query=select 1  

- driver: 8.0.21,  

- mysql server wait_timeout 28800 (8 hours),     




application errors: 

The last packet successfully received from the server was 26 milliseconds ago. The last packet sent successfully to the server was 26 milliseconds ago.
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:474) ~[spring-tx-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289) ~[spring-tx-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]

org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

mysql errors:
 
[MY-013417] [Server] The wait_timeout period was exceeded, the idle time since last command was too long.

[MY-010914] [Server] Aborted connection 757212 to db: 'dbname' user: 'username' host: 'dbip' (Got timeout reading communication packets).
