### ISSUE TITLE
oracle 12c hikari pool  :java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by godpit** [brettwooldridge/HikariCP#1262]
java.lang.NullPointerException: null
        at oracle.jdbc.driver.T4CConnection.updateSessionProperties(T4CConnection.java:1862) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIkvarr.unmarshal(T4CTTIkvarr.java:119) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:515) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:416) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:825) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:596) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]

how to solve it ? thanks a lot.

**Comment by prayagupa** [comment]
hi @godpit you might want to provide more information on how it can be re-produced or how your jdbc settings looks like. Seems some of the required jdbc properties is null.
