### ISSUE TITLE
Connection is not available, request timed out after 30001ms

### ISSUE THREAD

**Issue by HelloNick666** [brettwooldridge/HikariCP#1293]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_92
Database        : MySQL
Driver version  : x.x.x
```
**this is error log:**

`java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601) ~[HikariCP-2.6.2.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194) ~[HikariCP-2.6.2.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-2.6.2.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-2.6.2.jar:?]
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$getConnection$3(JDBCClientImpl.java:197) ~[vertx-jdbc-client-3.5.2.jar:3.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
2018-12-12 14:35:14.304 |- DEBUG in com.zaxxer.hikari.pool.HikariPool:389 [HikariPool-1 housekeeper] - HikariPool-1 - Pool stats (total=15, active=15, idle=0, waiting=1)
2018-12-12 14:35:15.283 |- DEBUG in com.zaxxer.hikari.pool.HikariPool:389 [vertx-jdbc-service-get-connection-thread] - HikariPool-1 - Timeout failure stats (total=15, active=15, idle=0, waiting=0)`

**this is my config:**
`		"connectionTestQuery": "SELECT 1",
		"connectionTimeout": 30000,
		"idleTimeout": 60000,
		"maxLifetime": 120000,
		"maximumPoolSize": 10,
		"minimumIdle": 10`

**this is my question:**
     That's what happens,When you have more access to server.   what should i do? thanks!

**Comment by seagulljohnson** [comment]
> #### Environment
> ```
> HikariCP version: 2.6.2
> JDK version     : 1.8.0_92
> Database        : MySQL
> Driver version  : x.x.x
> ```
> **this is error log:**
> 
> `java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms. at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601) ~[HikariCP-2.6.2.jar:?] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194) ~[HikariCP-2.6.2.jar:?] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HikariCP-2.6.2.jar:?] at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-2.6.2.jar:?] at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$getConnection$3(JDBCClientImpl.java:197) ~[vertx-jdbc-client-3.5.2.jar:3.5.2] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] 2018-12-12 14:35:14.304 |- DEBUG in com.zaxxer.hikari.pool.HikariPool:389 [HikariPool-1 housekeeper] - HikariPool-1 - Pool stats (total=15, active=15, idle=0, waiting=1) 2018-12-12 14:35:15.283 |- DEBUG in com.zaxxer.hikari.pool.HikariPool:389 [vertx-jdbc-service-get-connection-thread] - HikariPool-1 - Timeout failure stats (total=15, active=15, idle=0, waiting=0)`
> 
> **this is my config:**
> `	"connectionTestQuery": "SELECT 1", "connectionTimeout": 30000, "idleTimeout": 60000, "maxLifetime": 120000, "maximumPoolSize": 10, "minimumIdle": 10`
> 
> **this is my question:**
> That's what happens,When you have more access to server. what should i do? thanks!

Had you resolve it?

**Comment by seagulljohnson** [comment]
@HelloNick666 Have you resolve it?

**Comment by brettwooldridge** [comment]
Enable debug logging for the ``com.zaxxer.hikari`` package and post relevant logs here.  Also, enable the ``leakDetectionThreshold`` to determine if you have any connection leaks (that is the most common cause).

**Comment by seagulljohnson** [comment]
Following are the logs
2019-01-10 00:13:35.808 +0000 DEBUG [HikariPool-1 housekeeper] [c.z.h.p.HikariPool] - HikariPool-1 - Pool stats (total=4, active=0, idle=4, waiting=0) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:13:47.115 +0000 DEBUG [HikariPool-1 connection closer] [c.z.h.p.PoolBase] - HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@45ad3f32: (connection has passed maxLifetime) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:13:47.119 +0000 DEBUG [HikariPool-1 connection adder] [c.z.h.p.HikariPool] - HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@78f67e2f - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:13:47.119 +0000 DEBUG [HikariPool-1 connection adder] [c.z.h.p.HikariPool] - HikariPool-1 - After adding stats (total=4, active=0, idle=4, waiting=0) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:14:03.438 +0000 DEBUG [HikariPool-1 connection closer] [c.z.h.p.PoolBase] - HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@100a83cb: (connection has passed maxLifetime) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:14:05.808 +0000 DEBUG [HikariPool-1 housekeeper] [c.z.h.p.HikariPool] - HikariPool-1 - Pool stats (total=3, active=0, idle=3, waiting=0) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:14:06.296 +0000 DEBUG [HikariPool-1 connection closer] [c.z.h.p.PoolBase] - HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@540e8f33: (connection has passed maxLifetime) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:14:06.364 +0000 DEBUG [HikariPool-1 connection closer] [c.z.h.p.PoolBase] - HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@6bf5d1ef: (connection has passed maxLifetime) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:14:11.736 +0000 INFO [http-nio-8080-exec-6] [log.performance] - SUCCESS - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [result=SUCCESS, path=/health, method=GET, requestId=a7e35db4-146c-11e9-8767-0242ac110015, Accept-Language=null, type=perf, status=200] - [totalTime=12]
2019-01-10 00:14:35.809 +0000 DEBUG [HikariPool-1 housekeeper] [c.z.h.p.HikariPool] - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:14:36.050 +0000 DEBUG [HikariPool-1 connection closer] [c.z.h.p.PoolBase] - HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@78f67e2f: (connection has passed maxLifetime) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []
2019-01-10 00:15:05.809 +0000 DEBUG [HikariPool-1 housekeeper] [c.z.h.p.HikariPool] - HikariPool-1 - Pool stats (total=0, active=0, idle=0, waiting=0) - [beauty-snapshot_shopbasicinfo-api-40-40.a9782ba8-1468-11e9-9382-0242795553b3] - [] - []

total=0, active=0, idle=0, waiting=0  when it decrease 0,it could not get connections again until restart the server.
