### ISSUE TITLE
Interrupted during closing

### ISSUE THREAD

**Issue by nwhessel** [brettwooldridge/HikariCP#1295]
HikariCP version: 3.2.0
JDK version     : 1.8.0_191
Database        : DB2
Driver version  : 9.7.4

2018-12-14 09:34:02.649  WARN 13212 --- [   scheduling-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Warning Code: 4474, SQLState: 01000
2018-12-14 09:34:02.650  WARN 13212 --- [   scheduling-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : [jcc][t4][10217][10310][4.12.55] Connection read-only mode is not enforceable after the connection has been established.
To enforce a read only connection, set the read-only data source or connection property. ERRORCODE=4474, SQLSTATE=01000
2018-12-14 09:34:02.657  WARN 13212 --- [   scheduling-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Warning Code: 4223, SQLState: null
2018-12-14 09:34:02.657  WARN 13212 --- [   scheduling-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Origination unknown: [10228][11541][4.12.55] Security exceptions occurred while loading driver. ERRORCODE=4223, SQLSTATE=null
2018-12-14 09:34:02.666 ERROR 13212 --- [   scheduling-1] c.c.p.c.ApplicationShutdownTrigger       : Calling SpringApplication.exit, camelContext status is: Stopped
2018-12-14 09:34:02.669 ERROR 13212 --- [   scheduling-1] c.c.p.c.ApplicationShutdownTrigger       : Returning exit code 0
2018-12-14 09:34:02.675  INFO 13212 --- [   scheduling-1] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-12-14 09:34:02.681  INFO 13212 --- [   scheduling-1] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2018-12-14 09:34:02.683  INFO 13212 --- [   scheduling-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2018-12-14 09:34:02.709  WARN 13212 --- [   scheduling-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Interrupted during closing

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1465)
	at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:248)
	at com.zaxxer.hikari.HikariDataSource.close(HikariDataSource.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:337)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1052)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1059)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
	at org.springframework.boot.SpringApplication.close(SpringApplication.java:1320)
	at org.springframework.boot.SpringApplication.exit(SpringApplication.java:1307)
	at com.churchmutual.pihub.consumer.ApplicationShutdownTrigger.exitWhenCriteriaMet(ApplicationShutdownTrigger.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nwhessel** [comment]
Looks like calling hikariDataSource.close() before SpringApplication.exit() fixes the issue
