### ISSUE TITLE
Fail-fast during pool initialization

### ISSUE THREAD

**Issue by mayanze** [brettwooldridge/HikariCP#1309]
`2019-01-03 09:12:00 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP pool HikariPool-0 is starting.
Exception in thread "main" java.lang.RuntimeException: Fail-fast during pool initialization
	at com.zaxxer.hikari.pool.HikariPool.fillPool(HikariPool.java:499)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:162)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:78)
	at com.zcxt.analysis.stormjdbc.spout.UserSpout.main(UserSpout.java:97)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1023)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:997)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:983)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:928)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2407)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2328)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:441)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:139)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:109)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:418)
	at com.zaxxer.hikari.pool.HikariPool.fillPool(HikariPool.java:498)
	... 4 more`

**Comment by mayanze** [comment]
使用官方storm提供的storm-jdbc例子运行，报错误

**Comment by nunnr** [comment]
Failing during initialisation "Could not create connection to database server. Attempted reconnect 3 times. Giving up." suggests any of:
- database unreachable from your Java machine
- database user credentials wrong so database won't give access
- database too busy (max allowed connections reached)

If following examples from https://storm.apache.org/releases/1.2.2/storm-jdbc.html then you must change the database name, user name, password, etc. in the code...

hikariConfigMap.put("dataSource.url", "jdbc:mysql://localhost/test");
hikariConfigMap.put("dataSource.user","root");
hikariConfigMap.put("dataSource.password","password");

To be honest, best not to ask for help here on HikariCP project, but instead ask https://storm.apache.org/getting-help.html

Good luck!
