### ISSUE TITLE
HikariCP initialization with springboot - Continues erros after maxLifeTime reached

### ISSUE THREAD

**Issue by ChandrasekharRajoli** [brettwooldridge/HikariCP#1325]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_111
Database        : Oracle 11g
Driver version  : x.x.x

Spring Boot Version : 2.1.0
```

Hi, I am auto-configuring HikariCP with spring boot with the below-mentioned properties files. 

Hikari is initializing the connections, but getting continues Connection refused error after maxLifetime reached.

```
### Datasource configuration property file ###
spring.datasource.url=jdbc:oracle:thin:@OracleConnectionDetails
spring.datasource.username=UserName
spring.datasource.password=Password
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.login-timeout=10000
spring.datasource.hikari.pool-name=POOLNAME
spring.datasource.hikari.connection-timeout=30000 
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=60000
```

Exception : 
```
c.z.h.p.PoolBase                         : SVC1 - Closing connection oracle.jdbc.driver.T4CConnection@34a790d7: (connection has passed maxLifetime)
c.z.h.p.PoolBase                         : SVC1 - Failed to create/setup connection: The Network Adapter could not establish the connection
c.z.h.p.HikariPool                       : SVC1 - Cannot acquire connection from data source
java.sql.SQLException: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:70) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:133) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:199) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:480) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:413) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:508) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:203) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:33) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:510) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:275) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:206) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:156) ~[ojdbc6-11.2.0.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) [HikariCP-3.2.0.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) [HikariCP-3.2.0.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706) [HikariCP-3.2.0.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692) [HikariCP-3.2.0.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:328) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:421) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:630) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:206) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:966) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:292) ~[ojdbc6-11.2.0.jar!/:?]
	... 17 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_191]
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:120) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.nt.ConnOption.connect(ConnOption.java:126) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:306) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:421) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:630) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:206) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:966) ~[ojdbc6-11.2.0.jar!/:?]
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:292) ~[ojdbc6-11.2.0.jar!/:?]
	... 17 more

```

**Comment by ropoman** [comment]
I have the same issue with Spring Boot 2.1.3 and MySQL. Did you solve this?

**Comment by ejschoen** [comment]
I know this is an old issue. We are seeing the same behavior with MySQL 5.7 and default maxLifetime of 30 minutes, where MySQL's wait_timeout is 8 hours.  (We're using Clojure, not in Spring Boot, and accessing MySQL through Korma and the Hikaricp adapter for Korma.) Setting the HikariCP maxLifetime to 5 minutes does appear to help.  Connections close and are then reopened.  At 30 minutes, new connections fail to open.
