### ISSUE TITLE
Failed to change HikariCP version

### ISSUE THREAD

**Issue by yljuniper** [brettwooldridge/HikariCP#1339]
#### Environment
```
HikariCP version: 2.4.7+
JDK version     : 1.8
Database        : MySQL
Driver version  : x.x.x
Hi,
I tried to upgrade HikariCP to higher version in my application, and I got a Exception as below:

Exception in thread "main" org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider] 
Caused by: org.hibernate.HibernateException: Could not instantiate connection provider [com.zaxxer.hikari.hibernate.HikariConnectionProvider]
	at org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator.instantiateExplicitConnectionProvider(ConnectionProviderInitiator.java:197)
	at org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator.initiateService(ConnectionProviderInitiator.java:120)
	at org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator.initiateService(ConnectionProviderInitiator.java:55)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:105)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:251)
	... 16 more
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [com.zaxxer.hikari.hibernate.HikariConnectionProvider] as strategy [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider]
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:128)
	at org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator.instantiateExplicitConnectionProvider(ConnectionProviderInitiator.java:194)

current version:2.4.7
new version:2.6.3, 2.7.8 ...

configuration:
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.connection.provider_class=com.zaxxer.hikari.hibernate.HikariConnectionProvider
preferredTestQuery=SELECT 1
unreturnedConnectionTimeout=120
debugUnreturnedConnectionStackTraces=true
hibernate.ejb.interceptor.session_scoped=com.btisystems.pronx.ems.db.model.physical.EntityListener

jars in project:
hibernate-core-4.3.11.Final.jar
hibernate-entitymanager-4.3.11.Final.jar
hibernate-commons-annotations-4.0.5.Final.jar
hibernate-jpa-2.1-api-1.0.0.Final.jar
HikariCP-2.7.8.jar

I check the [HikariConnectionProvider] in HikariCP2.4.7 and 2.7.8 and found nothing different, I also tried [org.hibernate.hikaricp.internal.HikariCPConnectionProvider] instead, but it still doesn't work.
Why 2.4.7 is OK but higher versions are failed. I suppose maybe other dependent jars lead to this issue, any help would be appreciated.  



<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by yljuniper** [comment]
It seems that HikariCP release is restricted to spring-boot-1.3.8 no more than 2.4.7, maybe, I should upgrade spring-boot version instead.
