### ISSUE TITLE
ConnectionTimeout not working SPring Boot 2.1.3.RELEASE

### ISSUE THREAD

**Issue by pronane** [brettwooldridge/HikariCP#1341]
Versions:
HikariCP:3.2.0
Spring boot 2.1.3.RELEASE
h2.database:2.1.4

All pulled in via spring boot 2.1.3.RELEASE

Datasource config looks like this
```
`@Configuration
public class DatabaseConfig {

  @Value("${spring.datasource.url}")
  private String dbUrl;

  @Bean
  public DataSource dataSource() {
      HikariConfig config = new HikariConfig();
      config.setJdbcUrl(dbUrl);
      return new HikariDataSource(config);
  }
}`

```
config(for test)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:D:/predictions;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true

Code That is executing and once 10 calls to DB made timing out as none are being released back to the pool:

```
`   @Override
        public void updateStandings(List<Standing> standings) {
            /**
             * home_score_points integer not null,
             *   away_score_points integer not null,
             *   correct_score integer not null,
             *   correct_result integer not null,
             *   bonus_point integer not null,
             *   points_total integer not null,
             */
            final String sql = "update TABLE_STANDING set home_score_points=? , " +
                                                 "away_score_points=?,  " +
                                                 "correct_score=?,  " +
                                                 "correct_result=?,  " +
                                                 "bonus_point=?,  " +
                                                 "points_total=?  " +
                                            " where standing_id=?;";

            PreparedStatement preparedStatement = null;
            try{
                preparedStatement = dataSource.getConnection().prepareStatement(sql);
                List<Standing> insertList = new ArrayList<>();
                int counterStatements = 0;
                for(Standing standing : standings) {
                    if(standing.getStandingId() == null) {
                        insertList.add(standing);
                    } else{
                        preparedStatement.setInt(1, standing.getHomeScorePoints());
                        preparedStatement.setInt(2, standing.getAwayScorePoints());
                        preparedStatement.setInt(3, standing.getCorrectScores());
                        preparedStatement.setInt(4, standing.getCorrectResults());
                        preparedStatement.setInt(5, standing.getBonus());
                        preparedStatement.setInt(6, standing.getPointsTotal());
                        preparedStatement.setInt(7, standing.getStandingId());
                        preparedStatement.addBatch();
                        counterStatements++;
                    }
                }
                if(!insertList.isEmpty()) {
                    insertStandings(insertList);
                }
                if(counterStatements > 0) {
                    int[] affectedRecords = preparedStatement.executeBatch();
                }

            } catch(Exception e) {
                logger.error(e);
            } finally {
                try {
                    if(preparedStatement != null) {
                        preparedStatement.close();
                    }
                }
               catch(Exception e) {
                    logger.error(e);
                }
            }
        }`

`        @Override
        public void insertStandings(List<Standing> standings) {
            final String sql = "insert into Table_Standing(standing_id, movement_id, player_id, correct_score, correct_result, " +
                                                            "home_score_points, away_score_points, bonus_point, points_total) " +
                                                " values(:standingId, :seriesMovement, :playerId, :correctScores," +
                                                            ":correctResults, :homeScorePoints, :awayScorePoints, :bonus, :pointsTotal)";
            SqlParameterSource[] parameterSource = SqlParameterSourceUtils.createBatch(standings.toArray());

            template.batchUpdate(sql, parameterSource);
        }`

```
Insert is being called more often at first.  

JDBC Template and Datasource at the point I create PreparedStatement:

![image](https://user-images.githubusercontent.com/3452999/54711133-23609380-4b41-11e9-994f-34684aaed90a.png)

I havent tested this against my postgresql database but im guessing its the same issue and would like it resolved before its pushed any further.

Logs:

org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:612) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:646) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:936) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.batchUpdate(NamedParameterJdbcTemplate.java:365) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.example.demo.dao.StandingDaoImpl.insertStandings(StandingDaoImpl.java:55) ~[classes/:na]
	at com.example.demo.dao.StandingDaoImpl.updateStandings(StandingDaoImpl.java:97) ~[classes/:na]
	at com.example.demo.dao.StandingDaoImpl$$FastClassBySpringCGLIB$$b99962b0.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) [spring-tx-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.example.demo.dao.StandingDaoImpl$$EnhancerBySpringCGLIB$$9f4c7246.updateStandings(<generated>) [classes/:na]
	at com.example.demo.service.StandingServiceImpl.updateStandings(StandingServiceImpl.java:35) [classes/:na]
	at com.example.demo.CalculateStandingsTest.testWeek6Predictions(CalculateStandingsTest.java:73) [test-classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-3.2.0.jar:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 47 common frames omitted

As i debugged through i did a counter of the calls to the updateStandings(it reached 10 then just sat there and timed out).

**Comment by nunnrlc** [comment]
The datasource Connection object is never closed. The code must call .close() to return the Connection back to the pool.

Probably tidiest to use a try-with-resources statement to take advantage of auto-close:

try (Connection con = dataSource.getConnection()) {
  try (PreparedStatement preparedStatement = con.prepareStatement(sql)) {
    ...
  }
} catch (...) {
  ...
}

**Comment by pronane** [comment]
Ah yes, I was closing the preparedStatement only and not the connection as well.  Silly red-eye mistake.

**Comment by nunnrlc** [comment]
No worries!
