### ISSUE TITLE
 Connection is not available, request timed out after 30780ms

### ISSUE THREAD

**Issue by mehmetekici** [brettwooldridge/HikariCP#1347]
Hi We have the similar problem and our parameters are as follows; We are using postgresql 9.6, hikari 3.1

2019-03-27 10:40:55.554 WARN 7 --- [ main] com.zaxxer.hikari.HikariConfig : HikariPool-1 - idleTimeout has been set but has no effect because the pool is operating as a fixed size pool.
2019-03-27 10:40:55.557 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : HikariPool-1 - configuration:
2019-03-27 10:40:55.561 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : allowPoolSuspension.............false
2019-03-27 10:40:55.561 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : autoCommit......................true
2019-03-27 10:40:55.562 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : catalog.........................none
2019-03-27 10:40:55.562 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : connectionInitSql...............none
2019-03-27 10:40:55.563 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : connectionTestQuery............."SELECT 1"
2019-03-27 10:40:55.564 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : connectionTimeout...............30000
2019-03-27 10:40:55.564 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : dataSource......................none
2019-03-27 10:40:55.565 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : dataSourceClassName.............none
2019-03-27 10:40:55.565 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : dataSourceJNDI..................none
2019-03-27 10:40:55.567 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : dataSourceProperties............{password=}
2019-03-27 10:40:55.568 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : driverClassName.................none
2019-03-27 10:40:55.568 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : healthCheckProperties...........{}
2019-03-27 10:40:55.568 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : healthCheckRegistry.............none
2019-03-27 10:40:55.569 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : idleTimeout.....................20000
2019-03-27 10:40:55.569 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : initializationFailTimeout.......1
2019-03-27 10:40:55.570 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : isolateInternalQueries..........false
2019-03-27 10:40:55.571 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : .................
2019-03-27 10:40:55.571 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : leakDetectionThreshold..........60000
2019-03-27 10:40:55.572 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : maxLifetime.....................1800000
2019-03-27 10:40:55.572 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : maximumPoolSize.................10
2019-03-27 10:40:55.573 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : metricRegistry..................none
2019-03-27 10:40:55.573 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : metricsTrackerFactory...........none
2019-03-27 10:40:55.574 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : minimumIdle.....................10
2019-03-27 10:40:55.575 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : password........................
2019-03-27 10:40:55.575 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : poolName........................"HikariPool-1"
2019-03-27 10:40:55.576 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : readOnly........................false
2019-03-27 10:40:55.577 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : registerMbeans..................false
2019-03-27 10:40:55.577 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : scheduledExecutor...............none
2019-03-27 10:40:55.578 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : schema..........................none
2019-03-27 10:40:55.579 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : threadFactory...................internal
2019-03-27 10:40:55.580 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : transactionIsolation............default
2019-03-27 10:40:55.580 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : username........................none
2019-03-27 10:40:55.581 DEBUG 7 --- [ main] com.zaxxer.hikari.HikariConfig : validationTimeout...............5000

the error is

2019-03-27 10:52:21.650 DEBUG 7 --- [o-8080-exec-198] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=97)
2019-03-27 10:52:21.652 DEBUG 7 --- [o-8080-exec-232] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=96)
2019-03-27 10:52:21.652 DEBUG 7 --- [o-8080-exec-228] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=95)
2019-03-27 10:52:21.652 DEBUG 7 --- [o-8080-exec-225] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=94)
2019-03-27 10:52:21.652 DEBUG 7 --- [o-8080-exec-259] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=93)
2019-03-27 10:52:21.671 ERROR 7 --- [o-8080-exec-194] Controller : HikariPool-1 - Connection is not available, request timed out after 30780ms.; nested exception is <openjpa-2.4.0-r422266:1674604 fatal general error> org.apache.openjpa.persistence.PersistenceException: HikariPool-1 - Connection is not available, request timed out after 30780ms.

org.springframework.orm.jpa.JpaSystemException: HikariPool-1 - Connection is not available, request timed out after 30780ms.; nested exception is <openjpa-2.4.0-r422266:1674604 fatal general error> org.apache.openjpa.persistence.PersistenceException: HikariPool-1 - Connection is not available, request timed out after 30780ms.
at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:418)
at org.springframework.orm.jpa.DefaultJpaDialect.translateExceptionIfPossible(DefaultJpaDialect.java:122)
at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:488)
at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)

**Comment by RoyReporty** [comment]
I had the same issue, I think it fixed in 3.3.1

**Comment by philiwa** [comment]
Hi RoyReporty, 
We're facing same issue with v3.2.0.
A fix in v3.3.1 sounds really good. But could you confirm this by a bugfix, new feature or code change? Or maybe you have a deterministic test?
It's an issue that is difficult to reproduce for us and a theoretical certainty would help.
Thanks.

Philippe
