### ISSUE TITLE
ERROR com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to execute isValid() for connection, configure connection test query. (oracle.jdbc.driver.T4CConnection.isValid(I)Z)

### ISSUE THREAD

**Issue by poppycoderr** [brettwooldridge/HikariCP#1372]
#### Environment
```
HikariCP version: java7 2.4.13.jar
JDK version     : 1.7.0
Database        : Oracle
Driver version  :ojdbc6。jar
```

17:10:05.298 [RMI TCP Connection(3)-127.0.0.1] WARN  com.zaxxer.hikari.util.DriverDataSource - **Registered driver with driverClassName=oracle.jdbc.OracleDriver was not found, trying direct instantiation.**
17:10:05.553 [RMI TCP Connection(3)-127.0.0.1] INFO  com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - **Driver does not support get/set network timeout for connections.** (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)
17:10:05.554 [RMI TCP Connection(3)-127.0.0.1] ERROR com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - **Failed to execute isValid() for connection, configure connection test query. (oracle.jdbc.driver.T4CConnection.isValid(I)Z)**

17:10:05.569 [RMI TCP Connection(3)-127.0.0.1] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource-his' defined in ServletContext resource [/WEB-INF/applicationContext-datasource.xml]: **Invocation of init method failed; nested exception is java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.isValid(I)Z**
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1412) ~[org.springframework.beans-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[org.springframework.beans-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	
**Caused by: java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.isValid(I)Z
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:411) ~[HikariCP-java7-2.4.13.jar:?]**
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:382) ~[HikariCP-java7-2.4.13.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346) ~[HikariCP-java7-2.4.13.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193) ~[HikariCP-java7-2.4.13.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:434) ~[HikariCP-java7-2.4.13.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:505) ~[HikariCP-java7-2.4.13.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114) ~[HikariCP-java7-2.4.13.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-java7-2.4.13.jar:?]
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy.afterPropertiesSet(LazyConnectionDataSourceProxy.java:163) ~[org.springframework.jdbc-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1469) ~[org.springframework.beans-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1409) ~[org.springframework.beans-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	... 58 more

-----------------------------------------------------------------------------------------
Is this a problem with the hikari connection pool? If not, please closed and sorry to bother！ thx ！

**Comment by poppycoderr** [comment]
I don't know what happened, but the program to work correctly

**Comment by maniranganathan97** [comment]
I am facing the smae error, need help!

**Comment by poppycoderr** [comment]
> I am facing the smae error, need help!

sorry, I have forgotten this issue, maybe u can reopen.
