### ISSUE TITLE
Connection Leak Postgres JPA Hibernate Spring boot 2

### ISSUE THREAD

**Issue by sergiommarcial** [brettwooldridge/HikariCP#1376]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.2.5
Hibernate version: 5.4.2.Final
Spring version  : 2.0.9.RELEASE
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

```
hikari-pool - configuration:
allowPoolSuspension.............false
autoCommit......................true
catalog.........................none
connectionInitSql...............none
connectionTestQuery............."SELECT 1"
connectionTimeout...............30000
dataSource......................none
dataSourceClassName.............none
dataSourceJNDI..................none
dataSourceProperties............{password=<masked>}
driverClassName................."org.postgresql.Driver"
healthCheckProperties...........{}
healthCheckRegistry.............none
idleTimeout.....................600000
initializationFailTimeout.......1
isolateInternalQueries..........false
jdbcUrl.........................jdbcUrl
leakDetectionThreshold..........30000
maxLifetime.....................1800000
maximumPoolSize.................10
metricRegistry..................com.codahale.metrics.MetricRegistry@78479f2b
metricsTrackerFactory...........none
minimumIdle.....................5
password........................<masked>
poolName........................"hikari-pool"
readOnly........................false
registerMbeans..................false
scheduledExecutor...............none
schema..........................none
threadFactory...................internal
transactionIsolation............default
username........................"username"
validationTimeout...............5000
hikari-pool - Starting...
hikari-pool - Added connection org.postgresql.jdbc.PgConnection@6205ec67
hikari-pool - Start completed.
hikari-pool housekeeper com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Before cleanup stats (total=1, active=1, idle=0, waiting=16)
hikari-pool housekeeper com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - After cleanup  stats (total=1, active=1, idle=0, waiting=16)
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@793a899e
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@58287cea
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@15d19312
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@537e5961
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@576ad72c
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@47964b78
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@41d30a77
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@35cf7289
hikari-pool connection adder com.zaxxer.hikari.pool.HikariPool - {} - hikari-pool - Added connection org.postgresql.jdbc.PgConnection@27eb7949
http-nio-127.0.0.1-8093-exec-2 com.zaxxer.hikari.pool.HikariPool - hikari-pool - Timeout failure stats (total=10, active=10, idle=0, waiting=195)
http-nio-127.0.0.1-8093-exec-9 com.zaxxer.hikari.pool.HikariPool - hikari-pool - Timeout failure stats (total=10, active=10, idle=0, waiting=195)
http-nio-127.0.0.1-8093-exec-11 com.zaxxer.hikari.pool.HikariPool - hikari-pool - Timeout failure stats (total=10, active=10, idle=0, waiting=195)
http-nio-127.0.0.1-8093-exec-13 com.zaxxer.hikari.pool.HikariPool - hikari-pool - Timeout failure stats (total=10, active=10, idle=0, waiting=195)
http-nio-127.0.0.1-8093-exec-10 com.zaxxer.hikari.pool.HikariPool - hikari-pool - Timeout failure stats (total=10, active=10, idle=0, waiting=195)
[WARN] 2019-05-11 00:34:15,359 hikari-pool housekeeper com.zaxxer.hikari.pool.ProxyLeakTask - {} - Connection leak detection triggered for org.postgresql.jdbc.PgConnection@6205ec67 on thread http-nio-127.0.0.1-8093-exec-12, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-3.3.1.jar:?]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:262) ~[spring-jdbc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:474) ~[spring-tx-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289) ~[spring-tx-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) ~[spring-data-jpa-2.0.14.RELEASE.jar:2.0.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.14.RELEASE.jar:2.0.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.1.RELEASE.jar:5.0.1.RELEASE]
```

**Comment by sergiommarcial** [comment]
I've through all the issues closed and open in this repository, and through most of the stackoverflow questions, I've tried using Hikari with the embed version in spring data JPA (Hikari 2.7.9) as well and got the same results as with version 3.3.1, also I've been trying using Spring MyBatis instead of Hibernate and got the same behavior, 

At this point I am not sure what is the problem, the only difference I see with the data provided in other examples is that I am using a Postgres cluster instead of a single instance however when using other Datasource like Tomcat-JDBC I don't see the connections not being killed, so I am wondering what could be wrong with my configuration before giving up and going back to tomact-jdbc

**Comment by sergiommarcial** [comment]
@brettwooldridge any ideas why could this be happening?
