### ISSUE TITLE
Connections closing after 5 minutes

### ISSUE THREAD

**Issue by wesoos** [brettwooldridge/HikariCP#1411]
#### Environment
```
HikariCP version: 2.7.8
JDK version     : 1.8.0_111
Database        : MySQL|...
Driver version  : 5.1.47
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

Hello,  I am trying to deploy my app (API) to Azure App Service (Linux, Tomact 8.5).  I am using Spring Boot 2.1.6.

The app starts up fine and the connections are created and I can run queries.  However after 5 minutes the connections just close.  They just drop off if they have been idle for 5 minutes.  And Hikari does not create new ones and add back to the pool.

Any ideas?  Below is my application.properties:

`spring.datasource.jdbcUrl=jdbc:mysql://<ip>:3306/database?useSSL=false&characterEncoding=UTF-8&connectionCollation=UTF-8
spring.datasource.username=ssssss
spring.datasource.password=dddddd
spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.datasource.maximumPoolSize = 15

spring.dataSource.cachePrepStmts=true
spring.dataSource.prepStmtCacheSize=250
spring.dataSource.prepStmtCacheSqlLimit=2048
spring.dataSource.useServerPrepStmts=true
spring.dataSource.useLocalSessionState=true
spring.dataSource.useLocalTransactionState=true
spring.dataSource.rewriteBatchedStatements=true
spring.dataSource.cacheResultSetMetadata=true
spring.dataSource.cacheServerConfiguration=true
spring.dataSource.elideSetAutoCommits=true
spring.dataSource.maintainTimeStats=false`

**Comment by wesoos** [comment]
The pool is not maintaining the minimumIdle value, which by default is supposed the same as the maximumPoolSize value...

**Comment by wesoos** [comment]
So after 5 minutes all connections are closed.  Then when you try to hit the database, I get the following error stack.  However it does then open all the connections again.

`07/20/2019 15:33:05.110 [Thread-1921] ERROR com.tekwave.api.user.UserWS - Error has occurred.org.springframework.dao.DataAccessResourceFailureException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connectionat org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:275)at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:253)at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527)at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)at com.tekwave.dao.impl.TcUserDaoImpl$$EnhancerBySpringCGLIB$$b04df0cc.findById(<generated>)at com.tekwave.api.user.UserWS.lambda$saveEntitySettings$1(UserWS.java:124)at java.lang.Thread.run(Thread.java:748)Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connectionat org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:109)at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:226)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:190)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:121)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:86)at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:188)at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4273)at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:511)at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:481)at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:222)at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:281)at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:124)at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:92)at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1257)at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:208)at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2881)at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2855)at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3490)at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3454)at sun.reflect.GeneratedMethodAccessor691.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350)at com.sun.proxy.$Proxy113.find(Unknown Source)at sun.reflect.GeneratedMethodAccessor691.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:308)at com.sun.proxy.$Proxy113.find(Unknown Source)at com.tekwave.dao.impl.BaseDaoImpl.findById(BaseDaoImpl.java:65)at com.tekwave.dao.impl.BaseDaoImpl$$FastClassBySpringCGLIB$$697aa6f7.invoke(<generated>)at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)... 5 common frames omittedCaused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30040ms.at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:667)at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:183)at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:148)at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)... 44 common frames omittedCaused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.at sun.reflect.GeneratedConstructorAccessor2153.newInstance(Unknown Source)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:423)at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)at com.mysql.jdbc.Util.getInstance(Util.java:408)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5494)at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:541)at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:162)at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:172)... 49 common frames omitted07/20/2019 15:33:05.115 [Thread-1920] ERROR com.tekwave.api.user.UserWS - Error has occurred.org.springframework.dao.DataAccessResourceFailureException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connectionat org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:275)at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:253)at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527)at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)at com.tekwave.dao.impl.TcUserDaoImpl$$EnhancerBySpringCGLIB$$b04df0cc.findById(<generated>)at com.tekwave.api.user.UserWS.lambda$saveEntitySettings$1(UserWS.java:124)at java.lang.Thread.run(Thread.java:748)Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connectionat org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:109)at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:226)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:190)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:121)at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:86)at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:188)at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4273)at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:511)at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:481)at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:222)at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:281)at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:124)at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:92)at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1257)at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:208)at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2881)at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2855)at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3490)at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3454)at sun.reflect.GeneratedMethodAccessor691.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350)at com.sun.proxy.$Proxy113.find(Unknown Source)at sun.reflect.GeneratedMethodAccessor691.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:308)at com.sun.proxy.$Proxy113.find(Unknown Source)at com.tekwave.dao.impl.BaseDaoImpl.findById(BaseDaoImpl.java:65)at com.tekwave.dao.impl.BaseDaoImpl$$FastClassBySpringCGLIB$$697aa6f7.invoke(<generated>)at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)... 5 common frames omittedCaused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30042ms.at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:667)at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:183)at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:148)at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)... 44 common frames omittedCaused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.at sun.reflect.GeneratedConstructorAccessor2153.newInstance(Unknown Source)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:423)at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)at com.mysql.jdbc.Util.getInstance(Util.java:408)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5494)at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:541)at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:162)at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:172)... 49 common frames omitted`

**Comment by billoneil** [comment]
Turn on debug logging for HikariCP and also turn on the leak detection. Paste what the log looks like a little before and during the connection issues.

**Comment by wesoos** [comment]
Thanks can I get some advice on turning those on?  I'm assuming leak detection is a property and logging would be in logback?

**Comment by billoneil** [comment]
see `leakDetectionThreshold` from the main readme. You can change the logging level with logback.

**Comment by wesoos** [comment]
What's the name in the logger?  com.zaxxer.HikariCP?

**Comment by wesoos** [comment]
or com.zaxxer.hikari?

**Comment by wesoos** [comment]
[log.log](https://github.com/brettwooldridge/HikariCP/files/3413828/log.log)

**Comment by wesoos** [comment]
I've attached a log file.  I watched the process when the issue occurred.  After my app starts, all good, hikari creates the 15 connections.  The housekeeper runs every 30 seconds and shows stats correctly.  I am also watching MySQL workbench, showing the actual connections.  After 5 minutes, all the connections drops out of workbench.  However, hikari still claims there are 15 connections.  Then I try to use the app, and you see the errors, and then hikari creates the connections again...

**Comment by billoneil** [comment]
First I would recommend upgrading to the latest version.

It sounds like something else is closing the connections and HikariCP isn't aware of it. Can you check the MySQL settings for wait_timeout? Also is there any type of proxy between your app and the database like HAProxy?

If something is set to have a connection limit of 5 minutes then you need to lower `maxLifetime` to be a few seconds shorter than that. See the description of `maxLifetime` for more info.

**Comment by wesoos** [comment]
Ok thanks. Yes there is a load balancer in the middle. I can't find any documentation on if there would be a 5 minute timeout, but I did thought of that as well.

I'm using the version that comes with the latest spring boot...

Wessel Oosthuizen

________________________________

**Comment by wesoos** [comment]
The MySQL timeout is 8 hours

Wessel Oosthuizen

________________________________

**Comment by billoneil** [comment]
Try setting `maxLifetime` for HikariCP to a little under 5 minutes and see if the problem persists.

**Comment by wesoos** [comment]
Thanks that did the trick

**Comment by timothyjward** [comment]
> Try setting maxLifetime for HikariCP to a little under 5 minutes and see if the problem persists.

Shouldn't HikariCP be able to see that the connection is broken (via a call to `Connection#isValid`) and avoid this situation?

**Comment by billoneil** [comment]
If you look at the posted log is is actually failing in the validate connection code path. I'm not too familiar with this area but it likely depends on various settings. One of which could be how long the OS waits until it thinks a connection is dead. It's more complicated with the proxy between the app and the database. Once all the connections timeout the app then needs to cycle through all 15 dead connections before the new ones are available.

```
07/20/2019 16:31:56.411 [Thread-8] WARN  com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@68df2d95 (No operations allowed after connection closed.)
```

**Comment by timothyjward** [comment]
I am enountering a similar problem. I have been able to recreate it in a (relatively) simple test case, which I have provided in PR #1414

**Comment by timothyjward** [comment]
Note that the issue *appears* to be that if you request a connection from the pool and *all* the pooled connections are broken then you get a failure from the pool (it doesn't wait for one of the newly created connections to become available before timing out).

**Comment by smallsnail-wh** [comment]
I have a similar problem. My computer uses wifi to connect to the network. It may be my router that caused the remote connection of my mysql database to be interrupted, but hikari did not check it.
