### ISSUE TITLE
Can't configure enum property in PGSimpleDataSource

### ISSUE THREAD

**Issue by gionn** [brettwooldridge/HikariCP#1412]
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_212
Database        : PostgreSQL
Driver version  : 42.1.4
```

I want to configure the `PGSimpleDataSource.autosave` property, which is an enum value of type `org.postgresql.jdbc.Autosave`.

With a spring configuration:
```
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
		<constructor-arg>
			<props>
				<prop key="dataSourceClassName">org.postgresql.ds.PGSimpleDataSource</prop>
				<prop key="dataSource.user">${database.username}</prop>
				<prop key="dataSource.password">${database.password}</prop>
				<prop key="dataSource.databaseName">${database.databaseName}</prop>
				<prop key="dataSource.serverName">${database.serverName}</prop>
				<prop key="dataSource.portNumber">${pg.port}</prop>
				<prop key="dataSource.autosave">conservative</prop>
				<prop key="maximumPoolSize">${database.poolSize}</prop>
				<prop key="leakDetectionThreshold">${database.leakDetectionThreshold}</prop>
				<prop key="initializationFailTimeout">${database.initializationFailTimeout}</prop>
			</props>
		</constructor-arg>
		<property name="dataSourceProperties">
			<props>
				<!-- needed to serialize strings to json type columns -->
				<prop key="stringType">unspecified</prop>
			</props>
		</property>
	</bean>
```

I get the exception for whatever value of the property (tried with `conservative`, `CONSERVATIVE` or even ordinal number):

```
17:42:26.854 ERROR PropertyElf  - Failed to set property autosave on target class org.postgresql.ds.PGSimpleDataSource [main]
java.lang.IllegalArgumentException: argument type mismatch
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:159) [4 skipped]
	at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59)
	at java.util.Hashtable.forEach(Hashtable.java:879)
	at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:317)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [3 skipped]
```

Similar to #135

**Comment by ljluestc** [comment]
```
<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
    <constructor-arg>
        <props>
            <prop key="dataSourceClassName">org.postgresql.ds.PGSimpleDataSource</prop>
            <prop key="dataSource.user">${database.username}</prop>
            <prop key="dataSource.password">${database.password}</prop>
            <prop key="dataSource.databaseName">${database.databaseName}</prop>
            <prop key="dataSource.serverName">${database.serverName}</prop>
            <prop key="dataSource.portNumber">${pg.port}</prop>
            <prop key="dataSource.dataSource.autosave">conservative</prop> <!-- Fix here -->
            <prop key="maximumPoolSize">${database.poolSize}</prop>
            <prop key="leakDetectionThreshold">${database.leakDetectionThreshold}</prop>
            <prop key="initializationFailTimeout">${database.initializationFailTimeout}</prop>
        </props>
    </constructor-arg>
    <property name="dataSourceProperties">
        <props>
            <!-- needed to serialize strings to json type columns -->
            <prop key="stringType">unspecified</prop>
        </props>
    </property>
</bean>

```
