### ISSUE TITLE
When initializing, Hikari ignores java.sql.SQLRecoverableException recoverability

### ISSUE THREAD

**Issue by jprante** [brettwooldridge/HikariCP#1416]
#### Environment
```
HikariCP version: 3.3.0
JDK version     : 1.8.0_111
Database        : Oracle
Driver version  : 18.3
```

When initializing, Hikari ignores recoverability from a ` java.sql.SQLRecoverableException` and fails fast with a `PoolInitializationException`.

Hikari should retry by closing connection and trying a new connection instead.

```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: IO Error: Got minus one from a read call
	   at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-3.3.0.jar:?]
	   at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:237) [groovy-2.5.4-indy.jar:2.5.4]
	   at org.xbib.hbz.multiserv.MultiServ.<init>(MultiServ.groovy:44) [multiserv-1.0.1.jar:?]
	   at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:237) [groovy-2.5.4-indy.jar:2.5.4]
	   at org.xbib.hbz.multiserv.MultiServ.main(MultiServ.groovy:29) [multiserv-1.0.1.jar:?]
Caused by: java.sql.SQLRecoverableException: IO Error: Got minus one from a read call
	   at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:801) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:782) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:704) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[HikariCP-3.3.0.jar:?]
	   ... 6 more
Caused by: oracle.net.ns.NetException: Got minus one from a read call
	   at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:546) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.net.ns.NIOPacket.readNIOPacket(NIOPacket.java:355) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:124) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.net.ns.NSProtocol.connect(NSProtocol.java:318) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1481) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:540) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:782) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:704) ~[ojdbc8-18.3.jar:18.3.0.0.0]
	   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[HikariCP-3.3.0.jar:?]
	   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[HikariCP-3.3.0.jar:?]
	   ... 6 more
```

**Comment by ljluestc** [comment]
```

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import oracle.jdbc.pool.OracleDataSource;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;

public class HikariCPOracleRetryExample {

    public static HikariDataSource getHikariDataSource() throws SQLException {
        // Create OracleDataSource and set connection properties
        OracleDataSource oracleDs = new OracleDataSource();
        
        // Set OracleDataSource properties (user, password, etc.)
        oracleDs.setUser("your_username");
        oracleDs.setPassword("your_password");
        oracleDs.setURL("jdbc:oracle:thin:@//localhost:1521/ORCL");

        // Set additional connection properties if necessary
        Properties connectionProperties = new Properties();
        connectionProperties.put("defaultRowPrefetch", "1000");
        oracleDs.setConnectionProperties(connectionProperties);

        // Create HikariConfig
        HikariConfig config = new HikariConfig();
        config.setDataSource(oracleDs);

        // HikariCP pool settings
        config.setMinimumIdle(5);                    // Minimum number of idle connections
        config.setMaximumPoolSize(50);               // Maximum pool size
        config.setConnectionTimeout(30000);          // 30s connection timeout
        config.setIdleTimeout(60000);                // 60s idle timeout
        config.setMaxLifetime(1800000);              // 30 minutes max lifetime for each connection
        config.setInitializationFailTimeout(60000);  // Retry for 60s before failing pool initialization

        // Setting validation timeout
        config.setValidationTimeout(10000);          // 10s validation timeout for checking connection liveness

        // Enable auto-commit
        config.setAutoCommit(true);

        // Create HikariDataSource from the config
        return new HikariDataSource(config);
    }

    public static void main(String[] args) {
        try (HikariDataSource dataSource = getHikariDataSource()) {
            // Test the connection
            try (Connection connection = dataSource.getConnection()) {
                System.out.println("Connected to the database successfully!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```
