### ISSUE TITLE
Incorrect/mysterious credentials being used by HikariCP for Spring Java app.

### ISSUE THREAD

**Issue by evalsinca** [brettwooldridge/HikariCP#1446]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 11
Database        : MySQL
Driver version  : 8.0.17
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

I have configured HikariCP with user name 'U' and a password 'P'.   When debugging is enabled, Hikari prints the configuration (the pool name is 'Hikari-1', max pool size = 10, and it echoes the user name and password that I have specified).  A single connection is established to the db and my Java code is able to successfully execute queries.

Now here's the weird thing - I also see periodic messages from Hikari as follows:

```
2019-09-10 01:35:13.452 DEBUG 4941 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Cannot acquire connection from data source

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar!/:8.0.17]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.3.1.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[HikariCP-3.3.1.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-3.3.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[HikariCP-3.3.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-3.3.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727) ~[HikariCP-3.3.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713) ~[HikariCP-3.3.1.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'administrator'@'localhost' (using password: YES)
```

When I look further at the logs, it is trying to connect to the db as 'administrator@localhost' where 'administrator' is the owner of the Java process.   There is, in fact, no user 'administrator' defined in the db, and the connection naturally fails.  

So my question: Who/what is trying to connect as this user?   My explicit JDBC connection properties specify a different user 'U'.  

I have googled like hell and not finding any help.  Is this a bug?  Or, a configuration error on my part?

Thanks!

**Comment by evalsinca** [comment]
@brettwooldridge I have created an issue on Stackoverflow as well.  Net-net:  Same Java spring boot app running as two different Linux users - one works and the other doesn't.  In both cases, Hikari is trying to create 10 connections to the db.  In one case, it succeeds.  In the other (as noted above), it creates one connection, and fails when trying to create the remaining nine.  I am stumped!


https://stackoverflow.com/questions/57878352/hikaricp-trying-to-obtain-connection-to-pool-with-different-user-id-than-provide

**Comment by brettwooldridge** [comment]
Sounds like a driver issue to me, or driver settings.  You can run tcpdump of the Linux box to see what is being sent on the wire.

**Comment by evalsinca** [comment]
@brettwooldridge  - thanks for your response.  It looks like a Hikari issue to me (perhaps induced by how the properties are getting set from the jdbcurl).  basically,  I have traced through the Hikari code in a debugger.  The first connection is created with the correct user name U and password P.   When the code is invoked again to create the second connection in the pool, the "config" object is mysteriously modified - with user name now set to the $USER and password still set correctly to P.  Obviously, there is no $USER defined in the db - hence error.    Not sure if this throws up any ideas for you.

**Comment by johnou** [comment]
@evalsinca set a breakpoint in the config object to find the calling thread that changes the username.
