### ISSUE TITLE
Connection pool TLSv1.3 renewal issue

### ISSUE THREAD

**Issue by Mutisk-zz** [brettwooldridge/HikariCP#1470]
#### Environment
```
HikariCP version: 3.4.1 
JDK version     : OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Database        : PostgreSQL 11.5
Driver version  : jdbc 42.2.5
```

-----------------------------------------------------------------------------------------
Description of the problem:

Initial connections to the database works fine, but at the 30-minute mark when it's time to renew, full certificate validation appears to be attempted and fail (which is expected with postgres is running with self-signed certificates). This happens if our database is running on ubuntu 18.04 (has openssl 1.1.1), but not on Ubuntu 16.04 (openssl 1.0.2g).

Packet captures indicate that the difference between the two databases in use is TLSv1.3 being used in the more recent db server, on the older 16.04 TLSv1.2 is used. 

Using a jdbc connection string with ?sslmode=allow works around the problem by preferring unencrypted postgres. 

However, forbidding SSL on the server works initially (traffic is unencrypted) yet at 30-minutes it attempts TLSv1.3 handshakes when renewing.

It seems pool renewals does not keep track of relaxed TLS validation modes (?sslmode=prefer or require) when TLSv1.3 is available? (Alternatively, if full certificate verification is required it's preferable to fail immediately, not after 30 minutes of operation.)

**Comment by Mutisk-zz** [comment]
Attaching (repeating) log message after 30 minutes of application operation time.
[exception_hikari.log](https://github.com/brettwooldridge/HikariCP/files/3724769/exception_hikari.log)

**Comment by Mutisk-zz** [comment]
Just verified that the issue persist with the most recent Hikari version 3.4.1

**Comment by brettwooldridge** [comment]
This is in no way a HikariCP issue.  HikariCP is simply calling ``Driver.connect()`` to create a new connection.  The failure is in the SSL handshake between the driver and the database...
```
Caused by: org.postgresql.util.PSQLException: SSL error: Invalid CertificateVerify signature
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:42)
        at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:435)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
        at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Invalid CertificateVerify signature
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
        at java.base/sun.security.ssl.CertificateVerify$T13CertificateVerifyMessage.<init>(CertificateVerify.java:978)
        at java.base/sun.security.ssl.CertificateVerify$T13CertificateVerifyConsumer.consume(CertificateVerify.java:1125)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:448)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:425)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:40)
        ... 18 common frames omitted
```
I have no idea why this error was not encountered during the initial connection setup, but whatever the reason, again, HikariCP has no effect or interaction with anything going on between the driver itself and the database.

**Comment by brettwooldridge** [comment]
If the database has self-signed SSL key, the public half of the key pair needs to be installed in the client's keystore, or a trust-all TrustStore need to be configured.  How that is done for the Oracle driver I do not know.  Google and Stackoverflow are your friends.

**Comment by Mutisk-zz** [comment]
I know it's not using validation. But adding ?sslmode=prefer, or ?sslmode=require should mean "I dont want to validate the certificate, but I still prefer or require encryption on it", and it does just this fine when filling the pool initially (we see 10 connections)

But later when it's time to refill the pool connection, some parameters must carry over or be different. During the first* connection jdbc talks unencrypted initially and then, using it's own protocol, transfers the certificate. I was suspecting something as a result of this sets the connection to be ssl-capable. But if that's not in HikariCP then I'll try recreate it using only the jdbc driver, or bug report the driver instead.     Thanks for looking into this!
