### ISSUE TITLE
java.lang.NoSuchMethodError: com.zaxxer.hikari.pool.HikariPool.<init>(Lcom/zaxxer/hikari/HikariConfig;)V

### ISSUE THREAD

**Issue by qjohnny719** [brettwooldridge/HikariCP#1498]
HikariCP version: 3.4.1
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 8.0.18

Exception in thread "main" java.lang.NoSuchMethodError: com.zaxxer.hikari.pool.HikariPool.<init>(Lcom/zaxxer/hikari/HikariConfig;)V
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.zaxxer.DBTest.main(DBTest.java:24)
-----------------------------------------------------------------------------------------

**Comment by ljluestc** [comment]
```

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.sql.Connection;
import java.sql.SQLException;

public class DBTest {
    public static void main(String[] args) {
        // Create HikariConfig and set database properties
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://localhost:3306/testdb");
        config.setUsername("root");
        config.setPassword("password");
        config.setDriverClassName("com.mysql.cj.jdbc.Driver");

        // Additional pool settings
        config.setMinimumIdle(5);
        config.setMaximumPoolSize(10);
        config.setConnectionTimeout(30000);

        // Initialize HikariDataSource
        HikariDataSource dataSource = new HikariDataSource(config);

        // Test connection
        try (Connection connection = dataSource.getConnection()) {
            System.out.println("Connection successful!");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```
