### ISSUE TITLE
can not obtain a connection 

### ISSUE THREAD

**Issue by dramaPainter** [brettwooldridge/HikariCP#1501]
#### Environment
```
HikariCP version: HikariCP-java7-2.4.13
JDK version     : 1.7
Database        : mysql
Driver version  : mysql-5.1.48
```
in my web case there has always been a problem on which a connection can not be obtained. Hikari says: "chat_master - Connection is not available, request timed out after 10000ms", so i checked the Hikari log and basically assured that it's not obtainable just because connection can not be inserted into Hikari Pool, but how can i fix it?

```
Driver class found in the HikariConfig class classloader java.net.URLClassLoader@77f71eb7
chat_master - idleTimeout is close to or more than maxLifetime, disabling it.
chat_master - configuration:
allowPoolSuspension.............false
autoCommit......................true
catalog.........................none
connectionInitSql..............."set names utf8mb4"
connectionTestQuery.............none
connectionTimeout...............10000
dataSource......................none
dataSourceClassName.............none
dataSourceJNDI..................none
dataSourceProperties............{password=<masked>}
driverClassName................."com.mysql.jdbc.Driver"
healthCheckProperties...........{}
healthCheckRegistry.............none
idleTimeout.....................0
initializationFailFast..........true
initializationFailTimeout.......1
isolateInternalQueries..........false
jdbc4ConnectionTest.............false
jdbcUrl........................."jdbc:mysql://192.168.0.133/record?useUnicode=true&characterEncoding=utf8&useSSL=false"
leakDetectionThreshold..........6000
maxLifetime.....................300000
maximumPoolSize.................50
metricRegistry..................none
metricsTrackerFactory...........none
minimumIdle.....................50
password........................<masked>
poolName........................"chat_master"
readOnly........................false
registerMbeans..................false
scheduledExecutor...............none
scheduledExecutorService........internal
threadFactory...................internal
transactionIsolation............default
username........................"root"
validationTimeout...............5000
```

15:44:43.758 [chat_master connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - chat_master - Closing connection com.mysql.jdbc.JDBC4Connection@51a42578: (connection is evicted or dead)
15:44:43.758 [chat_master connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - chat_master - Closing connection com.mysql.jdbc.JDBC4Connection@51a42578 failed
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1182)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1177)
	at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5464)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:505)
	at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:130)
	at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
.......

20:01:56.343 [chat_master] - Connection is not available, request timed out after 10010ms.
 at abit.dal.MySqlPool.getConnection(MySqlPool.java:36)
 at kefu.lerengu.com.dao.ChatDao.getChatMessage(ChatDao.java:129)
 at kefu.lerengu.com.biz.Chat.list(Chat.java:36)
 at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:583)
 at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
 at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
 at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
.......

20:07:23.032 [chat_master connection adder] DEBUG com.zaxxer.hikari.pool.PoolBase - chat_master - Closing connection com.mysql.jdbc.JDBC4Connection@30623ddc failed
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
  at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
  at com.mysql.jdbc.Util.getInstance(Util.java:408)
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
  at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1182)
  at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1177)
  at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5464)
  at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:505)
  at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:130)
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:352)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
  at com.zaxxer.hikari.pool.HikariPool.access$300(HikariPool.java:70)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:612)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:598)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
.......

Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet successfully received from the server was 5,005 milliseconds ago.  The last packet sent successfully to the server was 5,005 milliseconds ago.
  at sun.reflect.GeneratedConstructorAccessor70.newInstance(Unknown Source)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
  at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
  at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
  at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
  at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829)
  at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:729)
  at com.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:522)
  at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:392)
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
  ... 9 common frames omitted

Caused by: java.net.SocketTimeoutException: Read timed out
  at java.net.SocketInputStream.socketRead0(Native Method)
  at java.net.SocketInputStream.read(SocketInputStream.java:152)
  at java.net.SocketInputStream.read(SocketInputStream.java:122)
  at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
  at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
  at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966)
  at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
  ... 20 common frames omitted

**Comment by praneeth130** [comment]
@dramaPainter facing similar issues, how did you fix it?
