### ISSUE TITLE
HikariPool-2 - Connection is not available

### ISSUE THREAD

**Issue by zhiliao666** [brettwooldridge/HikariCP#1526]
Hello, the pro environment found a large number of errors that could not obtain the connection to the database, like:

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
at com.sun.proxy.$Proxy186.selectOne(Unknown Source)
at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82)
at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
at com.sun.proxy.$Proxy242.selectByUids(Unknown Source)
at com.ufoto.manager.friends.UfotoUserFriendsManager.checkWasFriendBeforeAndDelMsg(UfotoUserFriendsManager.java:138)
at com.ufoto.manager.friends.UfotoUserFriendsManager$$FastClassBySpringCGLIB$$d7f2c480.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
at

open debug,found the connetion always Repeat loop creation：

![image](https://user-images.githubusercontent.com/8140511/71973281-898de280-3249-11ea-98ca-50e03d8003f8.png)

What is the reason ？？？

**Comment by jaehun2841** [comment]
Pool locking is suspect (Dead lock)
Check the number of threads and the maximum pool size
This occurs because a thread is not allocated a connection while a race condition occurs between threads.

**Comment by brettwooldridge** [comment]
@zhiliao666 @jaehun2841 See [this link about pool locking](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing#pool-locking).
