### ISSUE TITLE
HikariCP serving up closed connections

### ISSUE THREAD

**Issue by markathomas** [brettwooldridge/HikariCP#1532]
HikariCP: 3.4.1
Java: 11.0.5
PostgreSQL JDBC: 42.2.8
PostgreSQL: Amazon Aurora 10.x

Got this today after months of no problems.  Hikari is serving up connections that are closed causing a major data loss.  Please advise:
```
2020-01-16 19:09:41.497 ERROR 8 --- [normalTaskExecutor-78] c.b.w.service.DefaultWaveformService     : Failed to insert entries into table XXX for org XXX

org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: Waveforms DataSource - Connection is not available, request timed out after 30000ms.
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:612)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:647)
        at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:936)
        at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:990)
        at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:981)
        at com.boxview.waveformserver.service.DefaultWaveformService.publishEntries(DefaultWaveformService.java:128)
        at com.boxview.waveformserver.service.DefaultWaveformService.handleNewWaveformEntryEvent(DefaultWaveformService.java:92)
        at com.boxview.waveformserver.service.WaveformReceiver$WaveformReceiverWorker.readAndProcess(WaveformReceiver.java:746)
        at com.boxview.waveformserver.service.WaveformReceiver$WaveformReceiverWorker$QueueProcessor.run(WaveformReceiver.java:799)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at com.boxview.concurrency.LoggingRunnable.run(LoggingRunnable.java:21)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLTransientConnectionException: Waveforms DataSource - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
        ... 13 common frames omitted
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:782)
        at org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1560)
        at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:552)
        at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:168)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
        ... 18 common frames omitted

```

**Comment by subodh022** [comment]
Hi @markathomas , Were you able to resolve this issue?

**Comment by markathomas** [comment]
Yes, it was do to threading

**Comment by subodh022** [comment]
@markathomas - It would help us a lot if you could explain a little more on what you found the issue was and how did you resolve it.

**Comment by markathomas** [comment]
Sure, my issue was I had hundreds of threads writing with only 10 DB connections so some threads were failing to retrieve a connection within 30 seconds.  I changed my code to use a queueing mechanism with shorter-lived transactions and that appeared to resolve the issue
