### ISSUE TITLE
ProxyDatabaseMetaData proxies null statements

### ISSUE THREAD

**Issue by bturner** [brettwooldridge/HikariCP#1534]
`ProxyDatabaseMetaData` is full of methods that follow this pattern:
```java
   @Override
   public ResultSet getTables(String catalog, String schemaPattern, String tableNamePattern, String[] types) throws SQLException {
      ResultSet resultSet = delegate.getTables(catalog, schemaPattern, tableNamePattern, types);
      ProxyStatement statement = (ProxyStatement) ProxyFactory.getProxyStatement(connection, resultSet.getStatement());
      return ProxyFactory.getProxyResultSet(connection, statement, resultSet);
   }
```

At first glance, this all looks okay. However, when using H2 (just for example), I see failures like this:
```
[INFO] java.lang.NullPointerException: null
[INFO] 	at com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java:76)
[INFO] 	at net.java.ao.Common.closeQuietly(Common.java:504)
[INFO] 	at net.java.ao.sql.SqlUtils.closeQuietly(SqlUtils.java:122)
[INFO] 	at net.java.ao.schema.helper.DatabaseMetaDataReaderImpl.getSequenceNames(DatabaseMetaDataReaderImpl.java:212)
[INFO] 	at net.java.ao.schema.helper.DatabaseMetaDataReaderImpl.getFields(DatabaseMetaDataReaderImpl.java:84)
[INFO] 	at net.java.ao.schema.ddl.SchemaReader.readFields(SchemaReader.java:126)
[INFO] 	at net.java.ao.schema.ddl.SchemaReader.readTable(SchemaReader.java:110)
[INFO] 	at net.java.ao.schema.ddl.SchemaReader.access$000(SchemaReader.java:62)
[INFO] 	at net.java.ao.schema.ddl.SchemaReader$1.apply(SchemaReader.java:99)
[INFO] 	at net.java.ao.schema.ddl.SchemaReader$1.apply(SchemaReader.java:97)
```

Based on the line number, it's getting a `NullPointerException` in `ProxyStatement` trying to call `delegate.close()`. That delegate is retrieved with `ResultSet.getStatement()`, so that must be returning `null`.

Looking at the Javadocs for `ResultSet.getStatement()` shows this:
```
     * Retrieves the <code>Statement</code> object that produced this
     * <code>ResultSet</code> object.
     * If the result set was generated some other way, such as by a
     * <code>DatabaseMetaData</code> method, this method  may return
     * <code>null</code>.
```

Based on that, the H2 database driver is _entirely within spec_ to return `null` from `getStatement()`.

It seems to me like the `ProxyDatabaseMetaData` methods need to actually _check_ the `getStatement()` result for `null` and only proxy the statement if there is one. Something like this:
```java
   @Override
   public ResultSet getTables(String catalog, String schemaPattern, String tableNamePattern, String[] types) throws SQLException {
      ResultSet resultSet = delegate.getTables(catalog, schemaPattern, tableNamePattern, types);
      Statement statement = resultSet.getStatement();
      if (statement != null) {
         statement = ProxyFactory.getProxyStatement(connection, statement);
      }
      return ProxyFactory.getProxyResultSet(connection, (ProxyStatement) statement, resultSet);
   }
```

This way the proxied `ResultSet` will return `null` from `getStatement()` when the underlying `ResultSet` does, and will return a proxied `Statement` otherwise. As it stands, a proxied `ResultSet` _always_ returns a proxy `Statement`, even when it's not wrapping anything.

**Comment by brettwooldridge** [comment]
HikariCP v3.4.2 has been released with this fix.

**Comment by bturner** [comment]
Thanks @brettwooldridge!
