### ISSUE TITLE
The setDS() function is not working for the get Connection() to the MYSQL database?

### ISSUE THREAD

**Issue by ChenSen-hub** [brettwooldridge/HikariCP#1548]
The tools that I use are MYSQL for the database and Java. 
The Problem that I write is in the comment of the programming:

```
public void setDS(DataSource ds){
        
        try{
      
        HikariConfig config = new HikariConfig();  
        config.addDataSourceProperty("serverName", "locahost");
        config.addDataSourceProperty("port", 0000);
        config.addDataSourceProperty("user", "root");
        config.addDataSourceProperty("password",  "admin");
        config.setDataSourceClassName("com.mysql.cj.jdbc.MysqlDataSource"); 
        config.addDataSourceProperty("cachePrepStmts", true);  
        config.addDataSourceProperty("prepStmtCacheSize", 500);  
        config.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);  
        config.setMinimumIdle(0);
        config.setMaximumPoolSize(20);
        config.setAutoCommit(true);  
        config.setIdleTimeout(180000);
        config.setMaxLifetime(1800000);
        config.setInitializationFailFast(true);
        config.setConnectionTestQuery("SELECT current_timestamp");
        ds = new HikariDataSource(config); 
        ds = this.ds;

      
        } catch (Exception e){
        	e.printStackTrace();
        }	
	}

public Connection getConnection() {
		
		if(getDS()!= null){
			try {  
				System.out.println("CONNECTION");
				return  getDS().getConnection();
			}catch (Exception e) {  
				e.printStackTrace();  
            //should be ds.resumePool(), not shutdown() or close(
				ds.resumePool();
				return null;
			}  
		}else{
			try {
				setDS(ds); // The problem is on here and I have already declare the variable but still can't work on it 
				System.out.println("CONNECTION2");
				return getDS().getConnection();
			} catch (Exception e) {
				System.out.println("CONNECTION2");
				e.printStackTrace();
				System.out.println("CONNECTION2");
                		
			}	
		}
		return null;
	}
```

The error is shown as below but something the codes are appearing as "NULL POINTER EXCEPTION" that make the code cannot run without any data sources in it :
```
"do
Mar 04, 2020 8:41:33 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/Program] threw exception [An exception occurred processing [admin/view_usrLst.jsp] at line [87]

Stacktrace:] with root cause
java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
    at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:50)
    at bgoc.adm.dbConn.Conn.setDS(Conn.java:49)
    at bgoc.adm.dbConn.Conn.getConnection(Conn.java:123)"
```

**Comment by ljluestc** [comment]
```

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import javax.sql.DataSource;
import java.sql.Connection;

public class Conn {

    private DataSource ds;  // Ensure this field is correctly declared

    // Method to initialize the DataSource using HikariCP
    public void setDS() {
        try {
            HikariConfig config = new HikariConfig();

            // Correct server details
            config.addDataSourceProperty("serverName", "localhost"); // Fixing typo: "locahost"
            config.addDataSourceProperty("port", 3306);  // Replace 0000 with the actual port for MySQL (usually 3306)
            config.addDataSourceProperty("user", "root");
            config.addDataSourceProperty("password", "admin");

            config.setDataSourceClassName("com.mysql.cj.jdbc.MysqlDataSource");

            // Additional HikariCP settings
            config.addDataSourceProperty("cachePrepStmts", "true");
            config.addDataSourceProperty("prepStmtCacheSize", "500");
            config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");

            config.setMinimumIdle(0);
            config.setMaximumPoolSize(20);
            config.setAutoCommit(true);
            config.setIdleTimeout(180000);   // 3 minutes
            config.setMaxLifetime(1800000);  // 30 minutes
            config.setInitializationFailFast(true);
            config.setConnectionTestQuery("SELECT current_timestamp");

            // Properly initialize the DataSource
            this.ds = new HikariDataSource(config);

        } catch (Exception e) {
            e.printStackTrace();  // Log the exception for debugging
        }
    }

    // Method to retrieve a connection from the DataSource
    public Connection getConnection() {
        try {
            if (ds == null) {
                // If DataSource is null, initialize it
                setDS();
            }

            // Retrieve a connection from the DataSource
            return ds.getConnection();

        } catch (Exception e) {
            e.printStackTrace();
            return null;  // Return null if unable to establish a connection
        }
    }

    // Getter for DataSource (optional if needed elsewhere)
    public DataSource getDS() {
        return ds;
    }
}
```
