### ISSUE TITLE
IllegalAccessError when getting connection

### ISSUE THREAD

**Issue by DotDebian** [brettwooldridge/HikariCP#1598]
Hello,
I'm getting an IllegalAccessError when getting the connection from a data source.

I'm running Java 8 on Debian 10, using Maven and IntelliJ, HikariCP V3.2.0, SLF4J API V1.7.25.
I'm calling the constructor of the below class and getting error when using the getConnection method.

Here's the error:
```
[01:47:27 WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[01:47:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin ExoticCore v0.0.1 generated an exception while executing task 101
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessError: tried to access class com.zaxxer.hikari.pool.ProxyLeakTask from class com.zaxxer.hikari.pool.ProxyLeakTaskFactory
        at com.zaxxer.hikari.pool.ProxyLeakTaskFactory.schedule(ProxyLeakTaskFactory.java:40)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at space.debian.exoticcore.utils.sql.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:66)
        at space.debian.exoticcore.modules.ranking.Classement.fetchData(Classement.java:163)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

Here's my code:
```java
package space.debian.exoticcore.utils.sql;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import space.debian.exoticcore.Main;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ConnectionPoolManager {
    private final Main plugin;

    private HikariDataSource dataSource;

    private String hostname;
    private String port;
    private String database;
    private String username;
    private String password;

    private int minimumConnections;
    private int maximumConnections;
    private long connectionTimeout;

    public ConnectionPoolManager(Main plugin) {
        this.plugin = plugin;
        init();
        setupPool();
    }

    private void init() {
        hostname = "localhost";
        port = "3306";
        database = "XX";
        username = "XX";
        password = "XX";
        minimumConnections = 5;
        maximumConnections = 50;
        connectionTimeout = 28000;
    }

    private void setupPool() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(
                "jdbc:mysql://" +
                        hostname +
                        ":" +
                        port +
                        "/" +
                        database
        );
        config.setDriverClassName("com.mysql.jdbc.Driver");
        config.setUsername(username);
        config.setPassword(password);
        config.setMinimumIdle(minimumConnections);
        config.setMaximumPoolSize(maximumConnections);
        config.setConnectionTimeout(connectionTimeout);
        dataSource = new HikariDataSource(config);
    }

    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }

    public void close(Connection conn, PreparedStatement ps, ResultSet res) {
        if (conn != null) try { conn.close(); } catch (SQLException ignored) {}
        if (ps != null) try { ps.close(); } catch (SQLException ignored) {}
        if (res != null) try { res.close(); } catch (SQLException ignored) {}
    }

    public void closePool() {
        if (dataSource != null && !dataSource.isClosed()) {
            dataSource.close();
        }
    }

}
```

**Comment by PeterWippermann** [comment]
Are you trying to run your app from IntelliJ IDEA?
If so, build your app with `mvn package` and try to execute the jar file.

**Comment by DotDebian** [comment]
> Are you trying to run your app from IntelliJ IDEA?
> If so, build your app with `mvn package` and try to execute the jar file.

I'm creating a Minecraft Plugin.
I tried `mvn clean package`, `mvn clean install`, the result isn't the same, I'm now getting:
```
java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.hikari.HikariConfig
        at space.debian.exoticcore.utils.sql.ConnectionPoolManager.setupPool(ConnectionPoolManager.java:46) ~[?:?]
        at space.debian.exoticcore.utils.sql.ConnectionPoolManager.<init>(ConnectionPoolManager.java:31) ~[?:?]
        at space.debian.exoticcore.Main.onEnable(Main.java:90) ~[?:?]
```

I can't manage to make it works at all now. (the error is at plugin boot)

**Comment by PeterWippermann** [comment]
Please share your `pom.xml` file with us 🙂
