### ISSUE TITLE
Exception during asynchronous handling of setNetworkTimeout

### ISSUE THREAD

**Issue by mq2195** [brettwooldridge/HikariCP#1603]
Hi, I am experiencing following error. Application works OK, but the pool manager seems to attempt setting timeout on already timmed-out connections. There are muliple entries of this errors, starting around 30 min after last use.

Is it my settings or JDBC driver?

```
2020-06-19 14:49:56,244 DEBUG [HikariPool-1 connection closer] com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:129) - HikariPool-1 - Closing connection org.firebirdsql.jdbc.FBConnection@ed5dc39: (connection has passed idleTimeout) - MDC[]
2020-06-19 14:49:56,294 ERROR [HikariPool-1 network timeout executor] org.firebirdsql.jdbc.FBConnection.error(JulLogger.java:109) - Exception during asynchronous handling of setNetworkTimeout - MDC[]
java.sql.SQLException: No connection established to the database server [SQLState:08003, ISC error code:337248273]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:539)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.checkConnected(AbstractFbWireDatabase.java:122)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.setNetworkTimeout(AbstractFbWireDatabase.java:166)
	at org.firebirdsql.jdbc.FBConnection$SetNetworkTimeoutCommand.run(FBConnection.java:1268)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: No connection established to the database server
```

platform: linux
hibernate-core: 5.4.17.Final
hibernate-hikaricp: 5.4.17.Final (with HikariCP 3.4.5 it is the same error )
jaybird: 4.0.0.java11 (JDBC driver)
DB: firebird 3.0.5 

persistence.xml:
```
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.2"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_2.xsd">
	
	<persistence-unit name="scout-roles" transaction-type="RESOURCE_LOCAL">
		<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
		<class>...</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes>
		
		<properties>
			<property name="hibernate.dialect" value="org.hibernate.dialect.FirebirdDialect" />
			
			<property name="hibernate.show_sql" value="true" />
			<property name="hibernate.format_sql" value="true" />
			<property name="hibernate.generate_statistics" value="true" />
			
			<property name="hibernate.cache.provider_class" value="org.hibernate.cache.NoCacheProvider" />
			
			<property name="hibernate.hikari.dataSourceClassName" value="org.firebirdsql.ds.FBSimpleDataSource" />
			<property name="hibernate.connection.provider_class" value="org.hibernate.hikaricp.internal.HikariCPConnectionProvider" />
			<property name="hibernate.hikari.minimumIdle" value="5" />
			<property name="hibernate.hikari.maximumPoolSize" value="10" />
			<property name="hibernate.hikari.idleTimeout" value="30000" />
			<property name="hibernate.hikari.autoCommit" value="false" />
			
			<property name="hibernate.hikari.dataSource.database" value="//192.168.122.1:3050/test_db.fdb" />
			<property name="hibernate.hikari.dataSource.encoding" value="UTF8" />
			<property name="hibernate.hikari.dataSource.userName" value="..." />
			<property name="hibernate.hikari.dataSource.password" value="..." />
			
		</properties>
		
	</persistence-unit>
	
</persistence>
```

and pool configuration:
```
14:48:53.131 I [qtp440938038-16] org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation(LogHelper.java:31) - HHH000204: Processing PersistenceUnitInfo [name: scout-roles]
14:48:53.462 I [qtp440938038-16] org.hibernate.Version logVersion(Version.java:44) - HHH000412: Hibernate ORM core version 5.4.17.Final
14:48:54.471 I [qtp440938038-16] org.hibernate.annotations.common.Version <clinit>(JavaReflectionManager.java:49) - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
14:48:55.226 I [qtp440938038-16] org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator initiateService(ConnectionProviderInitiator.java:137) - HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
14:48:55.252 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1020) - HikariPool-1 - configuration:
14:48:55.263 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - allowPoolSuspension.............false
14:48:55.264 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - autoCommit......................false
14:48:55.265 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - catalog.........................none
14:48:55.266 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - connectionInitSql...............none
14:48:55.266 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - connectionTestQuery.............none
14:48:55.267 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - connectionTimeout...............30000
14:48:55.269 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - dataSource......................none
14:48:55.271 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - dataSourceClassName............."org.firebirdsql.ds.FBSimpleDataSource"
14:48:55.275 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - dataSourceJNDI..................none
14:48:55.279 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - dataSourceProperties............{database=//192.168.122.1:3050/test_db.fdb, password=<masked>, userName=..., encoding=UTF8}
14:48:55.291 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - driverClassName.................none
14:48:55.302 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - healthCheckProperties...........{}
14:48:55.306 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - healthCheckRegistry.............none
14:48:55.310 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - idleTimeout.....................30000
14:48:55.317 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - initializationFailTimeout.......1
14:48:55.322 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - isolateInternalQueries..........false
14:48:55.328 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - jdbcUrl.........................none
14:48:55.330 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - leakDetectionThreshold..........0
14:48:55.333 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - maxLifetime.....................1800000
14:48:55.336 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - maximumPoolSize.................10
14:48:55.337 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - metricRegistry..................none
14:48:55.339 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - metricsTrackerFactory...........none
14:48:55.341 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - minimumIdle.....................5
14:48:55.345 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - password........................<masked>
14:48:55.348 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - poolName........................"HikariPool-1"
14:48:55.352 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - readOnly........................false
14:48:55.354 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - registerMbeans..................false
14:48:55.356 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - scheduledExecutor...............none
14:48:55.357 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - schema..........................none
14:48:55.358 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - threadFactory...................internal
14:48:55.358 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - transactionIsolation............default
14:48:55.359 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - username........................none
14:48:55.360 D [qtp440938038-16] com.zaxxer.hikari.HikariConfig logConfiguration(HikariConfig.java:1052) - validationTimeout...............5000
14:48:55.363 I [qtp440938038-16] com.zaxxer.hikari.HikariDataSource <init>(HikariDataSource.java:80) - HikariPool-1 - Starting...
14:48:56.116 I [qtp440938038-16] com.zaxxer.hikari.HikariDataSource <init>(HikariDataSource.java:82) - HikariPool-1 - Start completed.
14:48:56.299 I [qtp440938038-16] org.hibernate.dialect.Dialect <init>(Dialect.java:172) - HHH000400: Using dialect: org.hibernate.dialect.FirebirdDialect
14:48:56.810 D [qtp440938038-16] com.zaxxer.hikari.pool.ProxyConnection close(ProxyConnection.java:234) - HikariPool-1 - Executed rollback on connection org.firebirdsql.jdbc.FBConnection@5d2af45d due to dirty commit state on close().
14:48:59.032 I [qtp440938038-16] org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService(JtaPlatformInitiator.java:52) - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
```
code to create EntityManager:
```
factory = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
em = factory.createEntityManager();
```

**Comment by mq2195** [comment]
So, 
hibernate-hikaricp: 5.4.17.Final = HikariCP 3.2.0

Updating to newer version does not solve the issue.
```
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-hikaricp</artifactId>
			<version>${version.hibernate}</version>
			<exclusions>
				<exclusion>
					<groupId>com.zaxxer</groupId>
					<artifactId>HikariCP</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/com.zaxxer/HikariCP -->
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>3.4.5</version>
		</dependency>

```

**Comment by mq2195** [comment]
Debug logs:
```
21:46:41.589 D [HikariPool-1 connection closer] com.zaxxer.hikari.pool.PoolBase quietlyCloseConnection(PoolBase.java:134) - HikariPool-1 - Closing connection org.firebirdsql.jdbc.FBConnection@36d4c6f6: (connection has passed maxLifetime) - MDC[]
21:46:41.592 D [HikariPool-1 connection closer] org.firebirdsql.jdbc.FBConnection trace(JulLogger.java:64) - Connection closed requested at - MDC[]
java.lang.RuntimeException: Connection close logging
	at org.firebirdsql.jdbc.FBConnection.close(FBConnection.java:441)
	at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143)
	at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
21:46:41.594 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.auth.ClientAuthBlock debug(JulLogger.java:44) - Trying authentication plugin SrpAuthenticationPlugin : Srp256 - MDC[]
21:46:41.595 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.auth.srp.SrpAuthenticationPlugin debug(JulLogger.java:44) - SRP phase 1, user: michal - MDC[]
21:46:41.595 D [HikariPool-1 connection closer] org.firebirdsql.gds.ng.wire.AbstractWireOperations debug(JulLogger.java:44) - readStatusVector arg:isc_arg_gds int: 0 - MDC[]
21:46:41.601 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.version13.V13WireOperations debug(JulLogger.java:44) - authReceiveResponse: cond_accept data=0 pluginName=3 'Srp' - MDC[]
21:46:41.602 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.version13.V13WireOperations debug(JulLogger.java:44) - receiveResponse: authenticate(Srp) - MDC[]
21:46:41.602 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.auth.srp.SrpAuthenticationPlugin debug(JulLogger.java:44) - SRP phase 1, user: michal - MDC[]
21:46:41.627 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.version13.V13WireOperations debug(JulLogger.java:44) - authReceiveResponse: cont_auth data=324 pluginName=3 'Srp' - MDC[]
21:46:41.628 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.version13.V13WireOperations debug(JulLogger.java:44) - receiveResponse: authenticate(Srp) - MDC[]
21:46:41.628 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.auth.srp.SrpAuthenticationPlugin debug(JulLogger.java:44) - SRP phase 2 - MDC[]
21:46:41.654 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.AbstractWireOperations debug(JulLogger.java:44) - readStatusVector arg:isc_arg_gds int: 0 - MDC[]
21:46:41.654 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.WireConnection debug(JulLogger.java:44) - Ignored unexpected tag type: 1 - MDC[]
21:46:41.632 E [HikariPool-1 network timeout executor] org.firebirdsql.jdbc.FBConnection error(JulLogger.java:109) - Exception during asynchronous handling of setNetworkTimeout - MDC[]
java.sql.SQLException: no transaction for request [SQLState:25000, ISC error code:335544363]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:539)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
	at org.firebirdsql.jdbc.FBConnection.getGDSHelper(FBConnection.java:1083)
	at org.firebirdsql.jdbc.FBConnection.getFbDatabase(FBConnection.java:214)
	at org.firebirdsql.jdbc.FBConnection$SetNetworkTimeoutCommand.run(FBConnection.java:1268)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: no transaction for request
21:46:41.655 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.AbstractWireOperations debug(JulLogger.java:44) - readStatusVector arg:isc_arg_gds int: 0 - MDC[]
21:46:41.655 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.version13.V13WireOperations debug(JulLogger.java:44) - Wire encryption established with Symmetric/Arc4 - MDC[]
21:46:41.660 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.AbstractWireOperations debug(JulLogger.java:44) - readStatusVector arg:isc_arg_gds int: 0 - MDC[]
21:46:41.661 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.wire.AbstractWireOperations debug(JulLogger.java:44) - readStatusVector arg:isc_arg_gds int: 0 - MDC[]
21:46:41.662 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.AbstractFbDatabase debug(JulLogger.java:44) - DatabaseInformationProcessor.process: first 2 bytes are 013E or: 3E, 01 - MDC[]
21:46:41.662 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.AbstractFbDatabase debug(JulLogger.java:44) - isc_info_db_sql_dialect:3 - MDC[]
21:46:41.662 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.AbstractFbDatabase debug(JulLogger.java:44) - isc_info_firebird_version: [LI-V3.0.5.33220 Firebird 3.0, LI-V3.0.5.33220 Firebird 3.0/tcp (firebird)/P15:C] - MDC[]
21:46:41.662 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.AbstractFbDatabase debug(JulLogger.java:44) - isc_info_ods_version:12 - MDC[]
21:46:41.662 D [HikariPool-1 connection adder] org.firebirdsql.gds.ng.AbstractFbDatabase debug(JulLogger.java:44) - isc_info_ods_minor_version:0 - MDC[]
21:46:41.668 D [HikariPool-1 connection adder] com.zaxxer.hikari.pool.HikariPool call(HikariPool.java:728) - HikariPool-1 - Added connection org.firebirdsql.jdbc.FBConnection@54469b78 - MDC[]
```
As far as I can tell, HicariCP is doing something that my JDBC driver does not like...

**Comment by mq2195** [comment]
Problem does not appear any more.

platform: linux
hibernate-core: 5.4.23.Final
HikariCP: 3.4.5 
jaybird: 4.0.1.java11 (JDBC driver)
DB: firebird 3.0.5
