### ISSUE TITLE
Oracle Transaction Isolation Issue

### ISSUE THREAD

**Issue by timothyneyman** [brettwooldridge/HikariCP#1611]
Hi there. I have a Kotlin app that is connecting to multiple jdbc datasources. We have two datasources configured and working properly: MySQL and regular SQL, but we can't get the Oracle connection working. I've googled the heck out of this error, but we're stumped.

The pool is actually successfully created and starts up, but a test transaction (INSERT) is resulting in an error. 

Successful startup from log
15:28:47.521 [main] INFO  com.zaxxer.hikari.HikariDataSource - ORACLE_POOL - Starting...
15:28:48.490 [main] INFO  com.zaxxer.hikari.HikariDataSource - ORACLE_POOL - Start completed.

Error StackTrace
Caused by: java.sql.SQLException: READ_COMMITTED and SERIALIZABLE are the only valid transaction levels
	at oracle.jdbc.driver.PhysicalConnection.setTransactionIsolation(PhysicalConnection.java:3301)
	at com.zaxxer.hikari.pool.ProxyConnection.setTransactionIsolation(ProxyConnection.java:396)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setTransactionIsolation(HikariProxyConnection.java)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:42)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:32)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:46)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.Database.metadata$exposed(Database.kt:30)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:33)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getUrl(Database.kt)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:36)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getDialect(Database.kt)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:416)
	at org.jetbrains.exposed.sql.BooleanColumnType.nonNullValueToString(ColumnType.kt:391)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToString(ColumnType.kt:43)
	at org.jetbrains.exposed.sql.ColumnType.valueToString(ColumnType.kt:60)
	at org.jetbrains.exposed.sql.QueryBuilder$registerArguments$1.invoke(Expression.kt:50)
	at org.jetbrains.exposed.sql.QueryBuilder.registerArguments(Expression.kt:52)
	at org.jetbrains.exposed.sql.QueryBuilder.registerArgument(Expression.kt:45)
	at org.jetbrains.exposed.sql.QueryBuilder.registerArgument(Expression.kt:42)
	at org.jetbrains.exposed.sql.statements.InsertStatement$prepareSQL$sql$1$1.invoke(InsertStatement.kt:102)
	at org.jetbrains.exposed.sql.statements.InsertStatement$prepareSQL$sql$1$1.invoke(InsertStatement.kt:14)
	at org.jetbrains.exposed.sql.QueryBuilder.appendTo(Expression.kt:14)
	at org.jetbrains.exposed.sql.QueryBuilder.appendTo$default(Expression.kt:10)
	at org.jetbrains.exposed.sql.statements.InsertStatement.prepareSQL(InsertStatement.kt:101)
	at org.jetbrains.exposed.sql.statements.StatementContext.sql(Statement.kt:72)
	at org.jetbrains.exposed.sql.statements.StatementKt.expandArgs(Statement.kt:76)
	at org.jetbrains.exposed.sql.StdOutSqlLogger.log(SQLLog.kt:25)
	at org.jetbrains.exposed.sql.CompositeSqlLogger.log(SQLLog.kt:50)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:166)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at modules.azure.service.AzureDataService$Companion.insertAzureItemOracle(AzureDataService.kt:14)

We're using ojdbc7, but we've also tried the latest ojdbc10 version and we get the same error (<dependency><groupId>com.oracle.database.jdbc</groupId><artifactId>ojdbc10</artifactId><version>19.6.0.0</version></dependency>)
        <dependency>
            <groupId>com.oracle.jdbc</groupId>
            <artifactId>ojdbc7</artifactId>
            <version>12.1.0.2</version>
        </dependency>

Here is version info from the DB:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
"CORE	12.1.0.2.0	Production"
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production

The error occurs when we try an insert transaction: 
val azureItemId = transaction(CasperUiDatabaseFactory.oracleDb) {
                addLogger(StdOutSqlLogger)
                AzureItemTable.insert {
                    it[storageType] = item.storageType
                    it[storageName] = item.storageName
                    it[containerName] = item.containerName
                    it[kind] = item.kind
                    it[fileFullPath] = item.fileFullPath
                    it[fileName] = item.fileName
                    it[fileExtension] = item.fileExtension
                    it[fileSize] = item.fileSize
                    it[firstFoundDate] = item.firstFoundDate
                    it[fileHash] = item.fileHash
                    it[hitsFound] = item.hitsFound
                    it[permissionJson] = item.permissionJson
                    it[historyJson] = item.historyJson
                    it[ownerJson] = item.ownerJson
                    it[scanJson] = item.scanJson
                } [AzureItemTable.azureItemId]

Instantiation Code for the connection
val oracleDb = Database.connect(
            hikariDbConfigOracle(CasperUiConfig.config.oracleDb),
            {
                it.transactionIsolation = Connection.TRANSACTION_SERIALIZABLE
            }
    )

Configuration Code for the Hikari Data Source
  private fun hikariDbConfigOracle(dbConfig: OracleDatabaseConfig): HikariDataSource {
        val config = HikariConfig()
        config.poolName = dbConfig.connectionPoolName
        config.driverClassName = dbConfig.driverClassName (oracle.jdbc.OracleDriver)
        config.jdbcUrl = dbConfig.host jdbc:oracle:thin:@(DESCRIPTION=(.....
        config.username = dbConfig.user.value
        config.password = dbConfig.pass.value
        config.isAutoCommit = true
        config.maximumPoolSize = dbConfig.maximumPoolSize (10)
        config.minimumIdle = 5
        config.idleTimeout = 30000
        config.maxLifetime = 2000000
        config.connectionTimeout = 30000
        return HikariDataSource(config)
    }

Thanks in advance...

**Comment by quaff** [comment]
try
```
config.transactionIsolation = "TRANSACTION_READ_COMMITTED"
```

**Comment by timothyneyman** [comment]
I have tried all of the possible Transaction Isolation levels, all to no avail. Same error with each and every one.
TRANSACTION_READ_COMMITTED
TRANSACTION_SERIALIZABLE
TRANSACTION_REPEATABLE_READ
TRANSACTION_READ_UNCOMMITTED
TRANSACTION_NONE

**Comment by brettwooldridge** [comment]
@timothyneyman It looks, from the code above, that you are setting the transaction level programatically. Try setting it to ``TRANSACTION_SERIALIZABLE`` in the HikariConfig before constructing the HikariDataSource.  Also, make sure that if you are using transaction annotations with JetBrain's Exposed that the annotation specified the correct isolation level.  Otherwise, I would take this up with the Exposed project.
