### ISSUE TITLE
 Connection is not available, request timed out after 10003ms

### ISSUE THREAD

**Issue by ImSFa7** [brettwooldridge/HikariCP#1619]
```
12:20:46 [SEVERE] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 10003ms.
12:20:46 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
12:20:46 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
12:20:46 [SEVERE]     at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
12:20:46 [SEVERE]     at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
12:20:46 [SEVERE]     at net.seagull.core.bungee.database.ConnectionPool.getConnection(ConnectionPool.java:51)
12:20:46 [SEVERE]     at net.seagull.core.bungee.database.MySQL.lambda$query$0(MySQL.java:47)
12:20:46 [SEVERE]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12:20:46 [SEVERE]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:20:46 [SEVERE]     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
12:20:46 [SEVERE]     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
12:20:46 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:20:46 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:20:46 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
```
```
    public void query(String string, Consumer<ResultSet> consumer) {
        execute(() -> {
            try {
                PreparedStatement ps = connectionPool.getConnection().prepareStatement(string); -> line 47
                ResultSet rs = ps.executeQuery();
                consumer.accept(rs);
                rs.close();
                ps.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });
    }
```

HikariConfig
```
        Class.forName("com.mysql.jdbc.Driver");
        HikariConfig hikariConfig = new HikariConfig();
        hikariConfig.setMaximumPoolSize(10);
        hikariConfig.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
        hikariConfig.setUsername(username);
        hikariConfig.setPassword(password);
        hikariConfig.addDataSourceProperty("serverName", serverName);
        hikariConfig.addDataSourceProperty("databaseName", database);
        hikariConfig.addDataSourceProperty("port", port);
        hikariConfig.setAutoCommit(true);
        hikariConfig.setMinimumIdle(1);
        hikariConfig.setMaximumPoolSize(10);
        hikariConfig.setValidationTimeout(3000);
        hikariConfig.setConnectionTimeout(10000);
        hikariConfig.setIdleTimeout(60000);
        hikariConfig.setMaxLifetime(60000);
        hikariConfig.addDataSourceProperty("cachePrepStmts", "true");
        hikariConfig.addDataSourceProperty("prepStmtCacheSize", "250");
        hikariConfig.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
        hikariConfig.addDataSourceProperty("useServerPrepStmts", "true");
        hikariConfig.addDataSourceProperty("useLocalSessionState", "true");
        hikariConfig.addDataSourceProperty("useLocalTransactionState", "true");
        hikariConfig.addDataSourceProperty("rewriteBatchedStatements", "true");
        hikariConfig.addDataSourceProperty("cacheResultSetMetadata", "true");
        hikariConfig.addDataSourceProperty("cacheServerConfiguration", "true");
        hikariConfig.addDataSourceProperty("elideSetAutoCommits", "true");
        hikariConfig.addDataSourceProperty("maintainTimeStats", "false");
        hikariConfig.addDataSourceProperty("useSSL", "false");
        hikariConfig.setLeakDetectionThreshold(60 * 1000);
        connectionPool = new HikariDataSource(hikariConfig);
```

**Comment by nunnrlc** [comment]
Make sure the connection is returned to pool by auto close:

```
public void query(String string, Consumer<ResultSet> consumer) {
        execute(() -> {
            try (Connection con = connectionPool.getConnection()) {
                PreparedStatement ps = con.prepareStatement(string);
                ResultSet rs = ps.executeQuery();
                consumer.accept(rs);
                rs.close();
                ps.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });
    }
```
