### ISSUE TITLE
Closed connection on java.sql.SQLTimeoutException: The query has timed out

### ISSUE THREAD

**Issue by talk2debendra** [brettwooldridge/HikariCP#1631]
_version=3.4.3
groupId=com.zaxxer
artifactId=HikariCP
Spring Boot 2.2.7.RELEASE_

I have a stored procedure on MSSQL server. While executing the procedure, it is giving me java.sql.SQLTimeoutException: The query has timed out. 

`[c.z.h.p.ProxyConnection] report-pool - Connection ConnectionID:XXX ClientConnectionId: XXX marked as broken because of SQLSTATE(HY008), ErrorCode(0)java.sql.SQLTimeoutException: The query has timed out.
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:226)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.executeQuery(HikariProxyCallableStatement.java)`

After that for next procedure call, it is giving  connection closed error
`Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	at com.sun.proxy.$Proxy83.prepareCall(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareCall(ProxyConnection.java:316)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareCall(HikariProxyConnection.java)`

**Comment by talk2debendra** [comment]
@brettwooldridge  Why HikariCP is closing the connections on SQLTimeOut Exception?

**Comment by quaff** [comment]
HikariCP doesn't know why, you should ask sqlserver.

**Comment by brettwooldridge** [comment]
This is a database level timeout.  Nothing to do with HikariCP timeouts.
