### ISSUE TITLE
HikariCP make connections over maximumPoolSize

### ISSUE THREAD

**Issue by scollector65** [brettwooldridge/HikariCP#1635]
If HikariCP failed Closing connection, HikariCP make connections over maximumPoolSize.
DB session is still alive.

2020-08-07 16:09:31.572 DEBUG 1 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@2e277051: (connection has passed maxLifetime)
2020-08-07 16:09:46.601 DEBUG 1 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@2e277051 failed
java.sql.SQLRecoverableException: IO Error: Socket read timed out
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1002) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2268) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143) ~[HikariCP-3.4.5.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451) ~[HikariCP-3.4.5.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: oracle.net.nt.TimeoutInterruptHandler$IOReadTimeoutException: Socket read timed out
	at oracle.net.nt.TimeoutSocketChannel.handleInterrupt(TimeoutSocketChannel.java:254) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:180) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:764) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:429) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:407) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:64) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:991) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
	... 6 common frames omitted

**Comment by scollector65** [comment]
2020-08-07 16:09:59.896 DEBUG 1 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Pool stats (total=2, active=0, idle=2, waiting=0)

But DB session is over than 2

SELECT      *
FROM        v$session
WHERE       PROGRAM='JDBC Thin Client'
ORDER BY    MACHINE;

**Comment by mharig2303** [comment]
@scollector65 , probably you need to update to latest version of Hikari CP?

**Comment by scollector65** [comment]
I tested it with HikariCP 3.4.5 (Spring Boot v2.3.2.RELEASE)

**Comment by scollector65** [comment]
When this issue is happened?

1. Oracle TEMP Tablespace LOB Segments increasing too much (using TO_CLOB or DECODE)

2. HikariPool Closing connection failed

2020-08-07 16:09:31.572 DEBUG 1 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@2e277051: (connection has passed maxLifetime)
2020-08-07 16:09:46.601 DEBUG 1 --- [nnection closer] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@2e277051 failed
java.sql.SQLRecoverableException: IO Error: Socket read timed out
at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1002) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2268) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143) ~[HikariCP-3.4.5.jar!/:na]
at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451) ~[HikariCP-3.4.5.jar!/:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: oracle.net.nt.TimeoutInterruptHandler$IOReadTimeoutException: Socket read timed out
at oracle.net.nt.TimeoutSocketChannel.handleInterrupt(TimeoutSocketChannel.java:254) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:180) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:764) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:429) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:407) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:64) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:991) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
... 6 common frames omitted

3. but HikariCP PoolEntry was closed already. so HikariCP make connections over maximumPoolSize.

**Comment by brettwooldridge** [comment]
You should never get this error if maxLifetime is configured correctly.  It should be shorter.  Maximum lifetime should never be reached only to find that the connection was already closed by the database. Maximum lifetime should always occur *before* the database has a chance to terminate a connection itself.

**Comment by scollector65** [comment]
@brettwooldridge 
It is not about maxLifetime. In this case, maximum lifetime occur before the database terminate connection. "Socket read timed out" will happen at Oracle TEMP Tablespace LOB Segments increasing too much
Of cource, shorter maxLifetime work fine sometime. Because shorter maxLifetime means lower Oracle TEMP Tablespace LOB Segments increasing > Oracle Closing connection success sometime.

I solved this issue by release Oracle TEMP Tablespace LOB Segments.
clob.freeTemporary()

Sorry about my bad english.

**Comment by davidkarlsen** [comment]
@scollector65 I see this tied to LOBs as well, seems growing the TS or something makes this happen.
