### ISSUE TITLE
HikariPool Open Connection is constantly throwing error message. Can i evict every connection before closing it?

### ISSUE THREAD

**Issue by ashwinbks83** [brettwooldridge/HikariCP#1650]
I am getting the following message on every open connection, it seems like the connection.isAlive check is trying to setNetworkTimeout, which is not implemented. It is just a warning message, but i noticed that it ends up just closing the connection. Is is okay for me to do that, but evicting the connection manually before calling hikariconn.close(), this way it does the same thing, but does not throw this nasty exception everytime ?

WARN 1 --- [   scheduling-1] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-5 - Connection oracle.jdbc.driver.T4CConnection@65eff3f5 marked as broken because of SQLSTATE(08003), ErrorCode(17008)
java.sql.SQLRecoverableException: Closed Connection
	at oracle.jdbc.driver.T4CConnection.doSetNetworkTimeout(T4CConnection.java:6967) ~[ojdbc8-12.2.0.1.jar!/:12.2.0.1.0]
	at oracle.jdbc.driver.PhysicalConnection.setNetworkTimeout(PhysicalConnection.java:9083) ~[ojdbc8-12.2.0.1.jar!/:12.2.0.1.0]
	at com.zaxxer.hikari.pool.ProxyConnection.setNetworkTimeout(ProxyConnection.java:425) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setNetworkTimeout(HikariProxyConnection.java) [HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:550) [HikariCP-3.2.0.jar!/:na]

I am able to resolve this issue, but just evicting the connection and then closing the connection, but does this cause other problems if i do this ?

**Comment by brettwooldridge** [comment]
"HikariCP-3.2.0.jar!"  This is an absurdly old version of the pool.  Upgrade.
