### ISSUE TITLE
java.sql.SQLRecoverableException: IO Error: Socket channel is closed

### ISSUE THREAD

**Issue by norberto-enomoto** [brettwooldridge/HikariCP#1651]
I'm using HikariCP with Spring Data JPA. I have a Microservice that persists some data in some tables. If the Microservices is idle for most 5 minutes, I call the Microservice and I start getting the following errors. After this errors, the Microservice is able to persist the data into database.

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

pom.xml:

		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>3.4.5</version>
		</dependency>
		<dependency>
			<groupId>com.oracle.jdbc</groupId>
			<artifactId>ojdbc8</artifactId>
			<version>12.2.0.1</version>
		</dependency>			

application.properties:
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver
datasource.hikari.minimum-idle=5
datasource.hikari.maximum-pool-size=20
datasource.hikari.connection-timeout=30000
datasource.hikari.idle-timeout=30000
datasource.hikari.max-lifetime=2000000

Database: Oracle XE 11g

Errors:

07-09-20 03:46:36.180 INFO  br.com.clarobr.multitenant.configuration.TenantContext : getCurrentTenant: DDBH13F
07-09-20 03:46:36.180 INFO  br.com.clarobr.multitenant.configuration.MultitenantDataSource : determineCurrentLookupKey: DDBH13F
07-09-20 03:46:41.194 WARN  com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Failed to validate connection oracle.jdbc.driver.T4CConnection@2ff7308a (IO Error: Invalid Operation, NOT Connected). Possibly consider using a shorter maxLifetime value.
07-09-20 03:46:41.198 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@2ff7308a: (connection is dead)
07-09-20 03:46:41.205 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@2ff7308a failed
java.sql.SQLRecoverableException: IO Error: Socket channel is closed
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:919)
        at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2005)
        at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143)
        at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Socket channel is closed
        at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:213)
        at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:211)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:181)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:132)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalSB1(T4CMAREngineNIO.java:188)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalUB1(T4CMAREngineNIO.java:201)
        at oracle.jdbc.driver.T4CTTIMsg.marshalTTCcode(T4CTTIMsg.java:301)
        at oracle.jdbc.driver.T4CTTIfun.marshalFunHeader(T4CTTIfun.java:181)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:246)
        at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:62)
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:908)
        ... 6 common frames omitted
07-09-20 03:46:41.256 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - Added connection oracle.jdbc.driver.T4CConnection@6f7a3c17
07-09-20 03:46:41.327 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - Added connection oracle.jdbc.driver.T4CConnection@210722ea
07-09-20 03:46:41.327 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - After adding stats (total=7, active=2, idle=5, waiting=0)
07-09-20 03:46:46.201 WARN  com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Failed to validate connection oracle.jdbc.driver.T4CConnection@490beb8e (IO Error: Invalid Operation, NOT Connected). Possibly consider using a shorter maxLifetime value.
07-09-20 03:46:46.201 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@490beb8e: (connection is dead)
07-09-20 03:46:46.203 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@490beb8e failed
java.sql.SQLRecoverableException: IO Error: Socket channel is closed
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:919)
        at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2005)
        at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143)
        at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Socket channel is closed
        at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:213)
        at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:211)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:181)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:132)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalSB1(T4CMAREngineNIO.java:188)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalUB1(T4CMAREngineNIO.java:201)
        at oracle.jdbc.driver.T4CTTIMsg.marshalTTCcode(T4CTTIMsg.java:301)
        at oracle.jdbc.driver.T4CTTIfun.marshalFunHeader(T4CTTIfun.java:181)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:246)
        at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:62)
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:908)
        ... 6 common frames omitted
07-09-20 03:46:46.230 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - Added connection oracle.jdbc.driver.T4CConnection@59897228
07-09-20 03:46:46.230 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - After adding stats (total=7, active=2, idle=5, waiting=0)
07-09-20 03:46:51.204 WARN  com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Failed to validate connection oracle.jdbc.driver.T4CConnection@31c57ec5 (IO Error: Invalid Operation, NOT Connected). Possibly consider using a shorter maxLifetime value.
07-09-20 03:46:51.205 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@31c57ec5: (connection is dead)
07-09-20 03:46:51.207 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@31c57ec5 failed
java.sql.SQLRecoverableException: IO Error: Socket channel is closed
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:919)
        at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2005)
        at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143)
        at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Socket channel is closed
        at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:213)
        at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:211)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:181)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:132)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalSB1(T4CMAREngineNIO.java:188)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalUB1(T4CMAREngineNIO.java:201)
        at oracle.jdbc.driver.T4CTTIMsg.marshalTTCcode(T4CTTIMsg.java:301)
        at oracle.jdbc.driver.T4CTTIfun.marshalFunHeader(T4CTTIfun.java:181)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:246)
        at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:62)
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:908)
        ... 6 common frames omitted
07-09-20 03:46:51.247 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - Added connection oracle.jdbc.driver.T4CConnection@5660b236
07-09-20 03:46:51.248 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - After adding stats (total=7, active=2, idle=5, waiting=0)
07-09-20 03:46:56.208 WARN  com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Failed to validate connection oracle.jdbc.driver.T4CConnection@18a41837 (IO Error: Invalid Operation, NOT Connected). Possibly consider using a shorter maxLifetime value.
07-09-20 03:46:56.209 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@18a41837: (connection is dead)
07-09-20 03:46:56.211 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@18a41837 failed
java.sql.SQLRecoverableException: IO Error: Socket channel is closed
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:919)
        at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2005)
        at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143)
        at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Socket channel is closed
        at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:213)
        at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:211)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:181)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:132)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalSB1(T4CMAREngineNIO.java:188)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalUB1(T4CMAREngineNIO.java:201)
        at oracle.jdbc.driver.T4CTTIMsg.marshalTTCcode(T4CTTIMsg.java:301)
        at oracle.jdbc.driver.T4CTTIfun.marshalFunHeader(T4CTTIfun.java:181)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:246)
        at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:62)
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:908)
        ... 6 common frames omitted
07-09-20 03:46:56.244 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - Added connection oracle.jdbc.driver.T4CConnection@7c3321aa
07-09-20 03:46:56.244 DEBUG com.zaxxer.hikari.pool.HikariPool : HikariCP-BH - After adding stats (total=7, active=2, idle=5, waiting=0)
07-09-20 03:47:01.214 WARN  com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Failed to validate connection oracle.jdbc.driver.T4CConnection@2ac1d521 (IO Error: Invalid Operation, NOT Connected). Possibly consider using a shorter maxLifetime value.
07-09-20 03:47:01.216 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@2ac1d521: (connection is dead)
07-09-20 03:47:01.218 DEBUG br.com.clarobr.partyinteractionmanagementservice.services.ProtocoloUnicoService : criarProcoloUnicoAtendimento - Inicio
07-09-20 03:47:01.218 DEBUG com.zaxxer.hikari.pool.PoolBase : HikariCP-BH - Closing connection oracle.jdbc.driver.T4CConnection@2ac1d521 failed
java.sql.SQLRecoverableException: IO Error: Socket channel is closed
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:919)
        at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2005)
        at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:143)
        at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:451)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Socket channel is closed
        at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:213)
        at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:211)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:181)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:132)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalSB1(T4CMAREngineNIO.java:188)
        at oracle.jdbc.driver.T4CMAREngineNIO.marshalUB1(T4CMAREngineNIO.java:201)
        at oracle.jdbc.driver.T4CTTIMsg.marshalTTCcode(T4CTTIMsg.java:301)
        at oracle.jdbc.driver.T4CTTIfun.marshalFunHeader(T4CTTIfun.java:181)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:246)
        at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:62)
        at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:908)
        ... 6 common frames omitted
07-09-20 03:47:01.218 DEBUG br.com.clarobr.partyinteractionmanagementservice.services.ProtocoloUnicoService : gerarProtocoloUnico - Inicio
07-09-20 03:47:01.218 DEBUG br.com.clarobr.partyinteractionmanagementservice.services.ProtocoloUnicoService : gerarProtocoloUnico - assinatura: codOperadora = 013
07-09-20 03:47:01.218 DEBUG br.com.clarobr.partyinteractionmanagementservice.services.ProtocoloUnicoService : getSequence - assinatura: codOperadora = 013
07-09-20 03:47:01.219 DEBUG org.hibernate.SQL :
    SELECT
        test.sq_id_test.nextval
    FROM
        dual
07-09-20 03:47:01.222 DEBUG br.com.clarobr.partyinteractionmanagementservice.services.ProtocoloUnicoService : getSequence - sequence: 000001836
07-09-20 03:47:01.222 DEBUG br.com.clarobr.partyinteractionmanagementservice.services.ProtocoloUnicoService : protocolo --- 01320000001836

Does anyone have any suggestion?

Thanks,

Norberto Enomoto

**Comment by brettwooldridge** [comment]
None of these exceptions are errors that would reach your application, they are simply logged.  Maybe consider taking the advice of the log message, "*Possibly consider using a shorter maxLifetime value.*"  2000000 is a lot, that's 23 days.  Try something like 30 minutes, or even 10 minutes.

**Comment by tantivy04** [comment]
hi @brettwooldridge ,

Your problem have resolve??

I have same problem. I dont know how to resolve
