### ISSUE TITLE
Timeout failure even though showing 29 idle connections out of total 30 

### ISSUE THREAD

**Issue by sumitchopra16** [brettwooldridge/HikariCP#1662]
Timeout failure stats (total=30, active=1, idle=29, waiting=163

Caused by: java.sql.SQLTransientConnectionException: My Connection Pool - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:170)
        at com.ccclogic.dashboard.config.multitenancy.CCCMsLogicRoutingDatasource.getConnection(CCCMsLogicRoutingDatasource.java:27)
        at com.ccclogic.dashboard.config.multitenancy.MetadataConnectionProviderImpl.getAnyConnection(MetadataConnectionProviderImpl.java:23)
        at com.ccclogic.dashboard.config.multitenancy.MetadataConnectionProviderImpl.getConnection(MetadataConnectionProviderImpl.java:34)
        at org.hibernate.internal.ContextualJdbcConnectionAccess.obtainConnection(ContextualJdbcConnectionAccess.java:43)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)

Using default configuration, except max pool size, which is set to 30

**Comment by brettwooldridge** [comment]
That is not a full stacktrace.  And you deleted the entire issue preamble, so I have no idea what version of HikariCP, what database, what driver version?  Turn on debug logging.
