### ISSUE TITLE
Hikari - Oracle connection pool not recovering after DB restart

### ISSUE THREAD

**Issue by Ramji-S** [brettwooldridge/HikariCP#1663]
Hi Bret

We are noticing a behavior where HikariCP connections do NOT recover after a DB restart. I went through some of the issues reported earlier on the similar lines and also read through the Rapid Recovery pages, but the error I noticed (SQL error) after the DB was brought UP seems strange and hence requesting your advise on what needs to be addressed to fix this. 

Config details

 Java 8 - 8u232
 Hikari - 3.4.2
 Oracle - ojdbc7-12.1.0.2.jar
 Spring Boot 2.2.4
 
 DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
 DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
 DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
 DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
 DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
 DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery............."SELECT 1 from dual"
 DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............3000
 DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
 DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
 DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
 DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>, prepStmtCacheSqlLimit=2048, cachePrepStmts=true, prepStmtCacheSize=250}
 DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................."oracle.jdbc.OracleDriver"
 DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
 DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
 DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................10000
 DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
 DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
 DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:oracle:thin:<masked>
 DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
 DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
 DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................100
 DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
 DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
 DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
 DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
 DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-1"
 DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
 DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
 DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
 DEBUG com.zaxxer.hikari.HikariConfig - schema..........................none
 DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
 DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
 DEBUG com.zaxxer.hikari.HikariConfig - username........................"<masked>"
 DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............2000
 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] INFO  AccessServiceGfApplication - Started AccessServiceGfApplication (JVM running)
[TBL-1] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@8f78ed9
[TBL-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.

DEBUG enabled in Hikari and also stackTrace printed below for reference. Even after DB was restarted, we notice the below error in logs several minutes later. Some of the other applications (not on Hikari) recovered and I can confirm that DB was accessible post the restart. The only solution to recover this was restarting my application.

Please advise what am I missing here, should I try out the socketTimeout in Oracle to be added to DatasourceProperties in Hikari ?

The trouble is, the timeout failure stats keeps showing 0 connections 
HikariPool-1 - Timeout failure stats (total=0, active=0, idle=0, waiting=0)

StackTrace:

java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 3000ms. at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689) at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196) at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161) at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) at 
.....
at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLRecoverableException: ORA-01089: immediate shutdown or close in progress - no operations are permitted at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399) at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)

**Comment by Ramji-S** [comment]
And by the way, for the above test though the leak detection was not set, in one of our earlier tests, we did enable it and did not find any connection leaks in the application. In one of the other applications running on Hikari, we intentionally did not restart the application and noticed that the connection is not available error still occurs even after 2 days of DB restart. @brettwooldridge please advise

**Comment by Ramji-S** [comment]
This was the full error trace after even several minutes post Oracle DB restart

```
Caused by: java.sql.SQLRecoverableException: ORA-01089: immediate shutdown or close in progress - no operations are permitted

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:210)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:30)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:762)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1792)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1745)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:334)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:165)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)

```
At the time of restart, observed Connection closure failures

```
WARN com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to validate connection oracle.jdbc.driver.T4CConnection@5e4c610c (No more data to read from socket). Possibly consider using a shorter maxLifetime value. 22:25:16.387 [HikariPool-1 connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - **Closing connection oracle.jdbc.driver.T4CConnection@7617fb44 failed** java.sql.SQLRecoverableException: ORA-01089: immediate shutdown or close in progress - no operations are permitted at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:392) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:385) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4C7Ocommoncall.processError(T4C7Ocommoncall.java:91) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:59) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:844) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2502) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:139) ~[HikariCP-3.4.2.jar!/:?] 
at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:447) ~[HikariCP-3.4.2.jar!/:?] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] 22:25:16.387 [HikariPool-1 connection closer] 

DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - **Closing connection oracle.jdbc.driver.T4CConnection@5e4c610c: (connection is dead) 22:25:16.388 [HikariPool-1 connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@5e4c610c failed** java.sql.SQLRecoverableException: No more data to read from socket at oracle.jdbc.driver.T4CMAREngineStream.unmarshalUB1(T4CMAREngineStream.java:456) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:397) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:59) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:844) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0]
at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2502) ~[ojdbc7-12.1.0.2.jar!/:12.1.0.2.0] 
at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:139) ~[HikariCP-3.4.2.jar!/:?] 
at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$1(HikariPool.java:447) ~[HikariCP-3.4.2.jar!/:?] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] 22:25:16.412 [TrantorDatabaseListener-1] 
WARN com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - **Failed to validate connection** oracle.jdbc.driver.T4CConnection@86eb6e1 (ORA-01089: immediate shutdown or close in progress - no operations are permitted ). Possibly consider using a shorter maxLifetime value.
```

The exact place where we notice these errors are at PoolBase#isConnectionAlive(), makes me believe that Hikari was able to get connection but for some reason the connectionTest query is failing in this method where the driver still thinks the DB shutdown is still in progress and not allowing SUCCESS.

**Comment by Ramji-S** [comment]
Can someone please check and provide an update ?

**Comment by brettwooldridge** [comment]
I don't know what to say.  If the database driver is throwing an exception reporting, "ORA-01089: immediate shutdown or close in progress - no operations are permitted" when we try to run a validation query, that is an Oracle issue.  Try stackoverflow.

**Comment by johnlabarge** [comment]
I've started to experience this as well running tests locally with dockerized oracle.  I don't have an answer yet.
