### ISSUE TITLE
Make use of Statement.setQueryTimeout 

### ISSUE THREAD

**Issue by NHebrard** [brettwooldridge/HikariCP#1670]
Hello!

Is there a reason explaining why we cannot make use of `Statement.setQueryTimeout(seconds)`?
I would like to specify a global timeout applied to all queries.

Happy to contribute if needed.

**Comment by krisewang-cell** [comment]
hello, my jstack log appear many :

"MySQL Statement Cancellation Timer" #128162 daemon prio=5 os_prio=0 tid=0x00007fbfb0008800 nid=0x8e06 in Object.wait() [0x00007fbd150c5000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	- locked <0x0000000605125268> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

My preliminary judgment should be related to this parameter...
