### ISSUE TITLE
PROD ISSUE : Connection marked as broken because of SQLSTATE(08S01) , ErrorCode(0)

### ISSUE THREAD

**Issue by RamaAncha** [brettwooldridge/HikariCP#1719]
@brettwooldridge .. Can you please help us with the issue.

I have set maxLifetime from 30 to 20 mins based on your comments in other tickets, still I am getting the issue.
Use case : Trying to insert around 4 million records.

versions:::
HikariCP - 3.2.0
mysql-connector-java -8.0.15
eclipseLink - 2.6.4

################### Log ################

2021-01-13 06:47:39.860  WARN 29858 --- [catalina-exec-8] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@38ffb771 marked as broken because of SQLSTATE(08S01), ErrorCode(0)

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 183,531 milliseconds ago.  The last packet sent successfully to the server was 62,974 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:408)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:375)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:417)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$802/1217912645.proceedWithInvocation(Unknown Source)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)

**Comment by quaff** [comment]
Have you tried not to insert 4 million records in a large transaction?

**Comment by LuxSun** [comment]
how to fix ?
