### ISSUE TITLE
Most datasource properties cannot be set for MariaDbDataSource

### ISSUE THREAD

**Issue by bugabinga** [brettwooldridge/HikariCP#1728]
It seems that the assumption, that DataSource-Implementations expose their Properties as Beans does not hold in the case of the MariaDB DataSource.

The MariaDB-Driver has beans for the most generic properties (user, password,...), but other properties are only picked up if part of the JDBC-URL or set via `setProperties(String)` (deprecated).

I am not sure if this is a Hikari issue or if the MariaDB DataSource is "supposed to" expose the properties as beans.
If so, I will move the issue to their bug tracker.

Versions used:
-  Java 11
- mariadb-java-client-2.7.1.jar
- HikariCP-4.0.1.jar

[Documentation for `serverTimezone`](https://mariadb.com/kb/en/about-mariadb-connector-j/#infrequently-used-parameters).

```java
final HikariConfig config = new HikariConfig();
config.setDataSourceClassName( "org.mariadb.jdbc.MariaDbDataSource" );
config.setUsername( "xxx" );
config.setPassword( "***" );
config.addDataSourceProperty( "serverTimezone", "UTC" );
new HikariDataSource( config );
...
```
```
java.lang.RuntimeException: Property serverTimezone does not exist on target class org.mariadb.jdbc.MariaDbDataSource
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:135)
	at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:59)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at java.base/java.util.Properties.forEach(Properties.java:1446)
	at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:54)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:328)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
...
```

**Comment by brettwooldridge** [comment]
I do suggest opening an issue against them if they do not expose standard getters/setters.

However, an alternative is to not setup the DataSource in this way, via reflection, and instead do it directly (programatically).  The ``HikariConfig`` object also exposes a ``setDataSource(DataSource dataSource)`` method, so the MariaDB DataSource could be constructed via whatever mechanism, and then set into the ``HikariConfig`` instance.
