### ISSUE TITLE
Hikari does not want to connect with database

### ISSUE THREAD

**Issue by bbroken776** [brettwooldridge/HikariCP#1729]
When i try to start the plugin i receive this error, it was working 5 days ago.

[05:04:00 INFO]: [Starlands-Economy] ~ [Information] ~ Loading file config.yml
[05:04:00 INFO]: [Starlands-Economy] ~ [DataBase] ~ Connecting to Server database.
[05:04:00 WARN]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-10 - Starting...
[05:04:05 WARN]: [Server thread] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-10 - Exception during pool initialization.
[05:04:05 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[05:04:05 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[05:04:05 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[05:04:05 WARN]:        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[05:04:05 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[05:04:05 WARN]:        at me.fcplugins.economy.database.DataConnection.getConnection(DataConnection.java:49)
[05:04:05 WARN]:        at me.fcplugins.economy.database.DataConnection.loadTables(DataConnection.java:35)
[05:04:05 WARN]:        at me.fcplugins.economy.Main.loadManagers(Main.java:72)
[05:04:05 WARN]:        at me.fcplugins.economy.Main.onEnable(Main.java:37)
[05:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[05:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[05:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
[05:04:05 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:535)
[05:04:05 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[05:04:05 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[05:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[05:04:05 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[05:04:05 WARN]:        at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
[05:04:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[05:04:05 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[05:04:05 WARN]:        ... 37 more
[05:04:05 WARN]: Caused by: java.net.ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine
[05:04:05 WARN]:        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
[05:04:05 WARN]:        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
[05:04:05 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
[05:04:05 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
[05:04:05 WARN]:        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.PlainSocketImpl.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.SocksSocketImpl.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.<init>(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.<init>(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[05:04:05 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[05:04:05 WARN]:        ... 39 more
[05:04:05 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[05:04:05 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:04:05 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[05:04:05 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[05:04:05 WARN]:        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
[05:04:05 WARN]:        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[05:04:05 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[05:04:05 WARN]:        at me.fcplugins.economy.database.DataConnection.getConnection(DataConnection.java:49)
[05:04:05 WARN]:        at me.fcplugins.economy.database.DataConnection.loadTables(DataConnection.java:35)
[05:04:05 WARN]:        at me.fcplugins.economy.Main.loadManagers(Main.java:72)
[05:04:05 WARN]:        at me.fcplugins.economy.Main.onEnable(Main.java:37)
[05:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[05:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[05:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
[05:04:05 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:535)
[05:04:05 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[05:04:05 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[05:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[05:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[05:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[05:04:05 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[05:04:05 WARN]:        at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
[05:04:05 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:04:05 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[05:04:05 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[05:04:05 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[05:04:05 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[05:04:05 WARN]:        ... 37 more
[05:04:05 WARN]: Caused by: java.net.ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine
[05:04:05 WARN]:        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
[05:04:05 WARN]:        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
[05:04:05 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
[05:04:05 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
[05:04:05 WARN]:        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.PlainSocketImpl.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.SocksSocketImpl.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.connect(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.<init>(Unknown Source)
[05:04:05 WARN]:        at java.net.Socket.<init>(Unknown Source)
[05:04:05 WARN]:        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[05:04:05 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[05:04:05 WARN]:        ... 39 more

**Comment by THyyy** [comment]
From your information, you should check whether your database connection address is correct.

**Comment by albertcheng** [comment]
I see the same thing. I can use the original jdbc to connect to local database with no problem. Not really sure what happened. It used to work fine.
