### ISSUE TITLE
HikariCP Appears Stuck

### ISSUE THREAD

**Issue by victropolis** [brettwooldridge/HikariCP#1815]
We just had a problem where our network firewall started blocking our postgres traffic and HikariCP reported problems, but then seemingly got stuck trying to connect, ignoring the configured timeout settings.  Similarly, when we restarted our app, HikariCP again seemly got stuck trying to connect, ignoring the configured timeout settings.  What I would have expected is for HikariCP to immediately go into some kind of recovery mode where it would log problems, continue trying to connect, continue logging problems, until such time as the connectivity had been restored.  Here's all the relevant information for your review.  Thanks in advance for your insight into this issue.  It appears we may have found a way to break HikariCP or maybe this has already been addressed in a newer version of HikariCP.

```
[hikari.HikariConfig] - 1-MemberConnectionPool - configuration:                                                                                                                  
[hikari.HikariConfig] - allowPoolSuspension.............false                                                                                                                    
[hikari.HikariConfig] - autoCommit......................true                                                                                                                     
[hikari.HikariConfig] - catalog.........................null                                                                                                                     
[hikari.HikariConfig] - connectionInitSql...............null                                                                                                                     
[hikari.HikariConfig] - connectionTestQuery.............null                                                                                                                     
[hikari.HikariConfig] - connectionTimeout...............30000                                                                                                                    
[hikari.HikariConfig] - dataSource......................null                                                                                                                     
[hikari.HikariConfig] - dataSourceClassName.............null                                                                                                                     
[hikari.HikariConfig] - dataSourceJNDI..................null                                                                                                                     
[hikari.HikariConfig] - dataSourceProperties............{password=<masked>}                                                                                                      
[hikari.HikariConfig] - driverClassName................."org.postgresql.Driver"                                                                                                  
[hikari.HikariConfig] - healthCheckProperties...........{}                                                                                                                       
[hikari.HikariConfig] - healthCheckRegistry.............null                                                                                                                     
[hikari.HikariConfig] - idleTimeout.....................60000                                                                                                                    
[hikari.HikariConfig] - initializationFailFast..........true                                                                                                                     
[hikari.HikariConfig] - isolateInternalQueries..........false                                                                                                                    
[hikari.HikariConfig] - jdbc4ConnectionTest.............false                                                                                                                    
[hikari.HikariConfig] - jdbcUrl........................."jdbc:postgresql://SCRUBBEDHOST:5433/dgcs?socketTimeout=3600&ApplicationName=memberServices@SCRUBBEDHOST:8082"
[hikari.HikariConfig] - leakDetectionThreshold..........0                                                                                                                        
[hikari.HikariConfig] - maxLifetime.....................1800000                                                                                                                  
[hikari.HikariConfig] - maximumPoolSize.................10                                                                                                                       
[hikari.HikariConfig] - metricRegistry..................null                                                                                                                     
[hikari.HikariConfig] - metricsTrackerFactory...........null                                                                                                                     
[hikari.HikariConfig] - minimumIdle.....................1                                                                                                                        
[hikari.HikariConfig] - password........................<masked>                                                                                                                 
[hikari.HikariConfig] - poolName........................"1-MemberConnectionPool"                                                                                                 
[hikari.HikariConfig] - readOnly........................false                                                                                                                    
[hikari.HikariConfig] - registerMbeans..................true                                                                                                                     
[hikari.HikariConfig] - scheduledExecutorService........null                                                                                                                     
[hikari.HikariConfig] - threadFactory...................null                                                                                                                     
[hikari.HikariConfig] - transactionIsolation............null                                                                                                                     
[hikari.HikariConfig] - username........................"SCRUBBEDUSER"                                                                                                              
[hikari.HikariConfig] - validationTimeout...............5000                                                                                                                     
[hikari.HikariDataSource] - 1-MemberConnectionPool - Started.
```

Below is a thread dump that indicates Hikari is waiting on a socketRead.

```
“localhost-startStop-1” #16 daemon prio=5 os_prio=0 tid=0x00007ff284002000 nid=0xdf1 runnable [0x00007ff2e99e0000]
  java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
    at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
    at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
    at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
    at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:405)
    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
    at org.postgresql.Driver.makeConnection(Driver.java:454)
    at org.postgresql.Driver.connect(Driver.java:256)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:509)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
```

Our HikariCP version is as follows:

```
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.4.4</version>
        </dependency>
```

**Comment by victropolis** [comment]
@brettwooldridge CORRECTION!  When it was healthy and then became unhealthy, it did go into recovery mode to try to reestablish the connections.  So the timeouts were working at that point.  It was only on STARTUP that the timeouts did not seem to be taking effect and it seemed to get stuck.

**Comment by brettwooldridge** [comment]
@victropolis Are you saying that the pool was *started* (later) while the firewall was in force, and at that time it seemed that timeouts are not working?

**Comment by victropolis** [comment]
@brettwooldridge initially, after the firewall started blocking the traffic and BEFORE we knew it was a firewall issue, HikariCP was reporting problems with the connections and it was trying to reestablish the connections (using the connection confired timeout).  During the outage, we tried restarting the application, and that's when we noticed that HikariCP seemed to not be using the connection timeout setting since it seemed to just get stuck indefinitely on startup.  Once the firewall was updated to allow the traffic again, HikariCP wasn't able to recover from this state (after having started the app again) and we had to restart the app again for HikariCP to be healthy again.

**Comment by brettwooldridge** [comment]
@victropolis What version of the postgres driver are you using? They have only in the past few months resolved issues related to supporting network timeout correctly.

Also, that is a *really* old version of HikariCP you are running. I normally don't even look at issues reported on anything but the latest release.

Finally, read this and implemented measures as necessary:
https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery

**Comment by victropolis** [comment]
@brettwooldridge 

```
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.2.5</version>
            </dependency>
```
