### ISSUE TITLE
jstack appear many ”MySQL Statement Cancellation Timer“

### ISSUE THREAD

**Issue by krisewang-cell** [brettwooldridge/HikariCP#1828]
Yesterday, I found a large number of thread alarms in my java program.
firstly I grep my log, catch the timeout exception, Ask the DBA to confirm that there is a short-term network jitter

today I catch the jstack log (one instance), 105 threads waiting like:

"MySQL Statement Cancellation Timer" #128162 daemon prio=5 os_prio=0 tid=0x00007fbfb0008800 nid=0x8e06 in Object.wait() [0x00007fbd150c5000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	- locked <0x0000000605125268> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

Should I modify any configuration to solve this problem?

**Comment by krisewang-cell** [comment]
this is config:
autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&connectTimeout=2000&jdbcCompliantTruncation=false&cacheServerConfiguration=true&characterSetResults=utf8&useSSL=false&useLocalSessionState=true
