### ISSUE TITLE
Error with Updates

### ISSUE THREAD

**Issue by Zemux1613** [brettwooldridge/HikariCP#1881]
Why I get this error?

Connection
```
private HikariDataSource getDataSource(String database) {
        HikariConfig hikariConfig = new HikariConfig();
        hikariConfig.setPoolName("MyPool");
        hikariConfig.setMaximumPoolSize(7);
        hikariConfig.setMinimumIdle(2);

        String jdbc = "jdbc:mysql://" +
                config.getString("sql.host") +
                ":" +
                config.getString("sql.port") +
                "/" +
                database;

        hikariConfig.setJdbcUrl(jdbc);
        hikariConfig.setUsername(config.getString("sql.username"));
        hikariConfig.setPassword(config.getString("sql.password"));
        hikariConfig.setDriverClassName("com.mysql.cj.jdbc.Driver");

        hikariConfig.addDataSourceProperty("cachePrepStmts", true);
        hikariConfig.addDataSourceProperty("prepStmtCacheSize", 256);
        hikariConfig.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);
        hikariConfig.addDataSourceProperty("useServerPrepStmts", true);

        return new HikariDataSource(hikariConfig);
    }
```

Code
```
database.executeUpdate(database.getConnection(Database.DatabaseType.DEFAULT).prepareStatement("INSERT INTO users (userId, experience) VALUES ('" + user.getId() + "', '0')"));

            String permissionQry = "";
            String permissionValues = "";

            for (Permission permission1 : Permission.values()) {
                permissionQry += permission1.name() + ", ";
                permissionValues += 0 + ", ";
            }

            permissionQry = permissionQry.substring(0, permissionQry.length() - 2) + ", userId";
            permissionValues = permissionValues.substring(0, permissionValues.length() - 2);
            String sql = "INSERT INTO permissions (" + permissionQry + ", userId) VALUES (" + permissionValues + ", '" + getUserId(user.getId()) + "')";
            database.executeUpdate(database.getConnection(Database.DatabaseType.DEFAULT).prepareStatement(sql));`
```

Error:
```
java.sql.SQLTransientConnectionException: BraveFM - Connection is not available, request timed out after 30015ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at de.bravefm.discord.controlbot.util.Database.getConnection(Database.java:73)
        at de.bravefm.discord.controlbot.handler.UserHandler.load(UserHandler.java:62)
        at de.bravefm.discord.controlbot.handler.UserHandler.getUser(UserHandler.java:89)
        at de.bravefm.discord.controlbot.handler.CommandHandler.executeCommand(CommandHandler.java:46)
        at de.bravefm.discord.controlbot.event.MessageEvent.onMessageReceived(MessageEvent.java:50)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:466)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:123)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

Important to know the database server ist arrivable!

**Comment by lfbayer** [comment]
Based on the code snippets you've provided, I'm willing to bet you aren't closing the connections.

Every call to the HikariDataSource to get a connection will borrow a connection, and if it isn't closed it will never be returned to the pool. If you then borrow more connections than the maximum pool size, then you will see the error you are seeing if no connections are returned to the pool within the connection timeout.

A typical usage which will automatically return the connection to the pool for you uses the try-with-resources syntax:
```java
try (Connection connection = getConnection())
{
    // use connection
}
```
