### ISSUE TITLE
Required config changes for MySQL8+ ?

### ISSUE THREAD

**Issue by jimmerk** [brettwooldridge/HikariCP#1898]
using 4.0.3 on Java 1.8.0_212

Hi. I've been using the following configuration successfully with MySQL 5.7 for a couple of years. We recently updated to 8.0.28, which started throwing the connection errors below. Anything obvious?

 `
//       hikari.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource"); Used this with 5.7
        hikari.setDriverClassName("com.mysql.cj.jdbc.Driver");  //then tried this with 8.0.28
        hikari.addDataSourceProperty("url", "jdbc:mysql://db:3306/dbname?characterEncoding=utf8&autoReconnect=true");
        hikari.addDataSourceProperty("user", "sadffasdaa");
        hikari.addDataSourceProperty("password", "asdf!asd");
        hikari.addDataSourceProperty("cachePrepStmts","true");
        hikari.addDataSourceProperty("prepStmtCacheSize","250");
        hikari.addDataSourceProperty("prepStmtCacheSqlLimit","2048");
        hikari.addDataSourceProperty("useServerPrepStmts","true");
        hikari.addDataSourceProperty("useLocalSessionState","true");
        hikari.addDataSourceProperty("rewriteBatchedStatements","true");
        hikari.addDataSourceProperty("cacheResultSetMetadata","true");
        hikari.addDataSourceProperty("cacheServerConfiguration","true");
        hikari.addDataSourceProperty("elideSetAutoCommits","true");
        hikari.addDataSourceProperty("maintainTimeStats","false");
        hikari.addDataSourceProperty("characterEncoding","utf8");
        hikari.addDataSourceProperty("useUnicode","true");
        hikari.setMaximumPoolSize(4);
        hikari.setMaxLifetime(28000*1000);
        hikari.setConnectionTimeout(10000);

----

[22:59:15 WARN]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[22:59:15 WARN]: Mon Jan 31 22:59:15 GMT 2022 WARN: Invalid value 'null' for server variable named 'auto_increment_increment', falling back to sane default of '1'.
[22:59:15 WARN]: Mon Jan 31 22:59:15 GMT 2022 WARN: Invalid value 'null' for server variable named 'auto_increment_increment', falling back to sane default of '1'.
[22:59:17 WARN]: Mon Jan 31 22:59:17 GMT 2022 WARN: Invalid value 'null' for server variable named 'auto_increment_increment', falling back to sane default of '1'.
[22:59:20 WARN]: [Server thread] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
[22:59:20 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[22:59:20 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:59:20 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:59:20 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:59:20 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:59:20 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[22:59:20 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[22:59:20 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[22:59:20 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:59:20 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:59:20 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:59:20 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:59:20 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[22:59:20 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[22:59:20 WARN]:        at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:440)
[22:59:20 WARN]:        at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:138)
[22:59:20 WARN]:        at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:108)
[22:59:20 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
[22:59:20 WARN]:        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[22:59:20 WARN]:        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
[22:59:20 WARN]:        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
[22:59:20 WARN]:        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[22:59:20 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[22:59:20 WARN]:        at ctf.Database.Queries.GetLeaders.getLeadersByPoints(GetLeaders.java:19)
[22:59:20 WARN]:        at ctf.CTF.updateTop10(CTF.java:275)
[22:59:20 WARN]:        at ctf.CTF.onEnable(CTF.java:259)
[22:59:20 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[22:59:20 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[22:59:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[22:59:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[22:59:20 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[22:59:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[22:59:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[22:59:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[22:59:20 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[22:59:20 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[22:59:20 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:59:20 WARN]: Caused by: java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[22:59:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.configureClientCharacterSet(ConnectionImpl.java:1794)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3523)
[22:59:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2202)
[22:59:20 WARN]:        ... 33 more`

**Comment by jimmerk** [comment]
Fixed with docker-compose setting:

```
security-opt:
  - seccomp:unconfined
```
