### ISSUE TITLE
The pool didn't recover after AWS RDS failover

### ISSUE THREAD

**Issue by vraikov** [brettwooldridge/HikariCP#1924]
We have an application that runs on AWS/EKS and is using Amazon's RDS for Postgres.
The application has been running fine for quite some time till this Monday when after a DB failover the pool didn't recover.
All "get connection" attempts from Hikari resulted in timeout which went on for 2 days until we restarted the service.
`
                java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
		at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695) ~[HikariCP-3.4.5.jar:na]
		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[HikariCP-3.4.5.jar:na]
		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[HikariCP-3.4.5.jar:na]
		at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-3.4.5.jar:na]
		at com.zaxxer.hikari.HikariDataSource$$FastClassBySpringCGLIB$$eeb1ae86.invoke(<generated>) ~[HikariCP-3.4.5.jar:na]
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.12.jar:5.3.12]
		at io.opentracing.contrib.spring.cloud.jdbc.JdbcAspect.getConnection(JdbcAspect.java:56) ~[opentracing-spring-cloud-jdbc-starter-0.5.9.jar:na]
		at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source) ~[na:na]
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.12.jar:5.3.12]
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.12.jar:5.3.12]
		at com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$cfdedbe.getConnection(<generated>) ~[HikariCP-3.4.5.jar:na]
		at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
		at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
		at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
`

as can be seen from the stack we're using Hikari with Spring(boot) and Hibernate. We use Hikari's default configuration - no settings have been modified.

AWS's report on the DB connections show that all connections shifted to the new writer immediately after the failover but their number decreased(probably some connections were closed but this was somehow not registered by Hikari)

<img width="1753" alt="Screenshot 2022-04-12 at 23 10 38" src="https://user-images.githubusercontent.com/1762809/163047254-c5a9f2e0-b160-44ce-a618-90f384adf31f.png">

Any ideas where to look for resolution?

**Comment by Dnguye92** [comment]
Curious on what happened here because we experienced something similar. NewRelic shows that at 3:21am 3/2/22 that db operations completely stopped and didn't recover until a dyno restart on Heroku.

A multitude of errors were thrown but the one that stands out was this:
```
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
--
```

![image](https://user-images.githubusercontent.com/17717354/166572862-8a7cd088-4d3a-402e-a2c3-6eacbf0e5408.png)

**Comment by WellingR** [comment]
We experienced similar issues. For us we found out that active connections remained active. it appears that the tcp connection is never terminated.

Configuring tcpKeepAlive (both in the postgres connection string and at the os level) solved the issue for us.

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.BestPractices.html shows some info on how to configure this.

**Comment by vraikov** [comment]
thanks @WellingR - we concluded we had a similar issue(TCP connections pointing to the old master never timing out) and decided to set the 2 properties on the Hikari pool. This configuration hasn't proven to work yet(but we haven't experienced such failovers either)
tcpKeepAlive=true
socketTimeout=30min

**Comment by WellingR** [comment]
Keep in mind that you need to configure the keepalive time, interval and probes on the OS level as wel. Depending on the os, keepAlive might kick in after two hours, which is not what I call a fast recovery.
See https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
