### ISSUE TITLE
PostgreSQL dead connection handling

### ISSUE THREAD

**Issue by mmimica** [brettwooldridge/HikariCP#1931]
Here is an excerpt from the stacktrace I've been getting from HikariCP 5.0.1 (+pgjdbc 42.3.4), after there have been some network issues between my JDBC client and the database. The network has recovered, but the connection pool has not.

Seems that `isConnectionDead` doesn't detect a closed connection as a dead one.

```
Caused by: java.sql.SQLTransientConnectionException: remote - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:883)
	at org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1620)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:561)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionDead(PoolBase.java:168)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:170)
	... 23 common frames omitted
```

**Comment by mmimica** [comment]
misreported exception at best

**Comment by OrdinaryMiracles** [comment]
I encountered the same exception. Have you found the cause?

**Comment by OrdinaryMiracles** [comment]
I encountered the same exception. Have you found the cause?
