### ISSUE TITLE
Connection is not available despite idle connections being available

### ISSUE THREAD

**Issue by valentin-panalyt** [brettwooldridge/HikariCP#1937]
I have the classical "Connection is not available" problem, even though Hikari shows that idle connections are available.

The problem only happens under load when queries take a long time and are getting forcefully cancelled automatically using a query timeout of ~2min (see https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Statement.html#setQueryTimeout(int)).

Once that has happened, the pool looks good again, i.e.
```
api     HikariPool-1 - Before cleanup stats (total=10, active=0, idle=10, waiting=0)
api     HikariPool-1 - After cleanup  stats (total=10, active=0, idle=10, waiting=0)
api     HikariPool-1 - Fill pool skipped, pool is at sufficient level.
```

But all subsequent queries fail with `Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30235ms.` and I don't understand what the cause of this could be. I tried different configurations and fails with all of them, so I'll post logs with mostly default settings.

```
api 2022.05.26 15:01:35:325 zio-default-async-1 INFO api.Main.run:22
api     Loading xxx-backend-api dependencies, running database migrations and and starting application
api 2022.05.26 15:01:35:473 zio-default-async-1 DEBUG com.zaxxer.hikari.HikariConfig
api     HikariPool-1 - configuration:
api     allowPoolSuspension.............false
api     autoCommit......................true
api     catalog.........................none
api     connectionInitSql...............none
api     connectionTestQuery.............none
api     connectionTimeout...............30000
api     dataSource......................none
api     dataSourceClassName.............none
api     dataSourceJNDI..................none
api     dataSourceProperties............{sslmode=require, password=<masked>, ssl=on}
api     driverClassName.................none
api     exceptionOverrideClassName......none
api     healthCheckProperties...........{}
api     healthCheckRegistry.............none
api     idleTimeout.....................600000
api     initializationFailTimeout.......1
api     isolateInternalQueries..........false
api     jdbcUrl.........................jdbc:postgresql://xxx:5432/xxx-qa
api     leakDetectionThreshold..........0
api     maxLifetime.....................1800000
api     maximumPoolSize.................10
api     metricRegistry..................none
api     metricsTrackerFactory...........none
api     minimumIdle.....................3
api     password........................<masked>
api     poolName........................"HikariPool-1"
api     readOnly........................false
api     registerMbeans..................false
api     scheduledExecutor...............none
api     schema..........................none
api     threadFactory...................internal
api     transactionIsolation............default
api     username........................"xxx-qa"
api     validationTimeout...............5000
api 2022.05.26 15:01:35:489 zio-default-async-1 INFO com.zaxxer.hikari.HikariDataSource
api     HikariPool-1 - Starting...
api 2022.05.26 15:01:35:547 zio-default-async-1 DEBUG com.zaxxer.hikari.util.DriverDataSource
api     Loaded driver with class name org.postgresql.Driver for jdbcUrl=jdbc:postgresql://34.135.60.35:5432/xxx-qa
api 2022.05.26 15:01:37:267 zio-default-async-1 DEBUG com.zaxxer.hikari.pool.HikariPool
api     HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@2bb1e6a4
api 2022.05.26 15:01:37:268 zio-default-async-1 INFO com.zaxxer.hikari.HikariDataSource
api     HikariPool-1 - Start completed.
api 2022.05.26 15:01:37:306 zio-default-async-1 INFO api.Main.run:27
api     Running flyway database migrations
api 2022.05.26 15:01:37:371 HikariPool-1 housekeeper DEBUG com.zaxxer.hikari.pool.HikariPool
api     HikariPool-1 - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
api     HikariPool-1 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
```

Then I make about a 100 queries and everything works fine. Until I start the long-running queries.

```
api 2022.05.26 15:07:37:411 HikariPool-1 housekeeper DEBUG com.zaxxer.hikari.pool.HikariPool
api     HikariPool-1 - Before cleanup stats (total=10, active=10, idle=0, waiting=0)
api     HikariPool-1 - After cleanup  stats (total=10, active=10, idle=0, waiting=0)
api     HikariPool-1 - Fill pool skipped, pool is at sufficient level.
api 2022.05.26 15:07:55:663 zio-default-async-85 WARN api.repositories.user.ziocached.ZioCachedUserRepository.combinedUpdateStream:73
api     Error when refreshing users-cache
api     api.utils.xxxException: Database error when looking up all users
api             at api.repositories.user.postgres.PostgresUserRepository.$anonfun$all$2(PostgresUserRepository.scala:30)
api             at zio.ZIO.$anonfun$orDieWith$2(ZIO.scala:1143)
api             at zio.ZIO$.$anonfun$die$1(ZIO.scala:2691)
api             at zio.internal.FiberContext.evaluateNow(FiberContext.scala:413)
api             at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:787)
api             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
api             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
api             at java.lang.Thread.run(Thread.java:833)
api     Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30235ms.
```

So far that is all fine. Some requests fail because certains queries take too long until they get cancelled.

```
(...)
api     Caused by: org.postgresql.util.PSQLException: ERROR: canceling statement due to user request`
``` 

Now all queries got cancelled - no active queries in postgres anymore. However, new requests fail:

```
api 2022.05.26 15:09:37:424 HikariPool-1 housekeeper DEBUG com.zaxxer.hikari.pool.HikariPool
api     HikariPool-1 - Before cleanup stats (total=10, active=0, idle=10, waiting=0)
api     HikariPool-1 - After cleanup  stats (total=10, active=0, idle=10, waiting=0)
api     HikariPool-1 - Fill pool skipped, pool is at sufficient level.
api 2022.05.26 15:09:55:675 zio-default-async-103 WARN 
api     api.repositories.auth.postgres.PostgresAuthRepository$DatabaseError: Database error when listing all permissions
api             at api.repositories.auth.postgres.PostgresAuthRepository.$anonfun$allPermissions$2(PostgresAuthRepository.scala:121)
api             at zio.ZIO.$anonfun$orDieWith$2(ZIO.scala:1143)
api             at zio.ZIO$.$anonfun$die$1(ZIO.scala:2691)
api             at zio.internal.FiberContext.evaluateNow(FiberContext.scala:413)
api             at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:787)
api             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
api             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
api             at java.lang.Thread.run(Thread.java:833)
api     Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30235ms.
api             at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
api             at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
api             at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
api             at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
api             at io.getquill.context.ZioJdbc$DataSourceLayer$.$anonfun$layer$4(ZioJdbc.scala:42)
api             at zio.internal.FiberContext.evaluateNow(FiberContext.scala:496)
api             at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:787)
api             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
api             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
api             at java.lang.Thread.run(Thread.java:833)
```

There are no Hikari logs removed here - the housekeeper shows 10 idle connections and the next thing that happens is a background refresh that sends a query - but fails with the error. It never recovers from that state until a restart.

There are also no other logs from Hikari such as clock leaps or anything.

**Comment by valentin-panalyt** [comment]
Shamefully I have to admit the error being on my side. In the end it turned out that the error was caused due to a cache (which cached the error exactly as is, including stacktrace). No failure in Hikari :)
