### ISSUE TITLE
Tomcat 8 failing to start with global jndi data source

### ISSUE THREAD

**Issue by tim-oe** [brettwooldridge/HikariCP#194]
running tomcat 8.0.12 (64b windows with arp libs), HikariCP 2.2.5

i have a jndi configuration in $CATALINA_HOME/conf/context.xml

```
<Resource
        auth="Container"
        type="javax.sql.DataSource"
        name="jdbc/oeDatabase"
        factory="com.zaxxer.hikari.HikariJNDIFactory"
        dataSourceClassName="com.mysql.jdbc.jdbc2.optional.MysqlDataSource" 
        driverClass="com.mysql.jdbc.Driver"
        driverClassName="com.mysql.jdbc.Driver"
        idleMaxAgeInMinutes="15"
        idleConnectionTestPeriodInMinutes="10"
        partitionCount="3"
        acquireIncrement="5"
        maxConnectionsPerPartition="10"
        minConnectionsPerPartition="5"
        statementsCacheSize="50"
        dataSource.url="jdbc:mysql://localhost:3306/outboundengine"
        dataSource.user="root"
        dataSource.password="root"
        />
```

I have no custom webapps installed, just ROOT from the install.

I have added the following jars to $CATALINA_HOME/lib
HikariCP-2.2.5.jar
javassist-3.18.1-GA.jar
jul-to-slf4j-1.7.7.jar
mysql-connector-java-5.1.33.jar
slf4j-api-1.7.7.jar
slf4j-jdk14-1.7.7.jar

I get the following errors trying to start tomcat

Nov 17, 2014 4:33:02 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\java\tomcat\webapps\ROOT
Nov 17, 2014 4:33:03 AM com.zaxxer.hikari.metrics.CodaHaleShim loadOrShimCodahale
SEVERE: Cannot generate CodaHale metrics shim
javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  org/apache/catalina/loader/WebappClassLoader): attempted  duplicate class definition for name: "com/codahale/metrics/MetricRegistry"
    at javassist.ClassPool.toClass(ClassPool.java:1099)
    at javassist.CtClass.toClass(CtClass.java:1265)
    at com.zaxxer.hikari.metrics.CodaHaleShim.loadOrShimCodahale(CodaHaleShim.java:81)
    at com.zaxxer.hikari.metrics.CodaHaleShim.initialize(CodaHaleShim.java:52)
    at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:90)
    at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:82)
    at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:73)
    at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
    at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:841)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:152)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:829)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
    at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1084)
    at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:663)
    at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:256)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5074)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1071)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1722)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.LinkageError: loader (instance of  org/apache/catalina/loader/WebappClassLoader): attempted  duplicate class definition for name: "com/codahale/metrics/MetricRegistry"
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at javassist.ClassPool.toClass2(ClassPool.java:1112)
    at javassist.ClassPool.toClass(ClassPool.java:1093)
    ... 29 more

Nov 17, 2014 4:33:03 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1071)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1722)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
    at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:82)
    at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:73)
    at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
    at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:841)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:152)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:829)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
    at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1084)
    at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:663)
    at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:256)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5074)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 10 more
Caused by: java.lang.RuntimeException: javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  org/apache/catalina/loader/WebappClassLoader): attempted  duplicate class definition for name: "com/codahale/metrics/MetricRegistry"
    at com.zaxxer.hikari.metrics.CodaHaleShim.loadOrShimCodahale(CodaHaleShim.java:85)
    at com.zaxxer.hikari.metrics.CodaHaleShim.initialize(CodaHaleShim.java:52)
    at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:90)
    ... 25 more
Caused by: javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  org/apache/catalina/loader/WebappClassLoader): attempted  duplicate class definition for name: "com/codahale/metrics/MetricRegistry"
    at javassist.ClassPool.toClass(ClassPool.java:1099)
    at javassist.CtClass.toClass(CtClass.java:1265)
    at com.zaxxer.hikari.metrics.CodaHaleShim.loadOrShimCodahale(CodaHaleShim.java:81)
    ... 27 more
Caused by: java.lang.LinkageError: loader (instance of  org/apache/catalina/loader/WebappClassLoader): attempted  duplicate class definition for name: "com/codahale/metrics/MetricRegistry"
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at javassist.ClassPool.toClass2(ClassPool.java:1112)
    at javassist.ClassPool.toClass(ClassPool.java:1093)
    ... 29 more

Nov 17, 2014 4:33:03 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory C:\java\tomcat\webapps\ROOT
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:727)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1071)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1722)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by pjBooms** [comment]
It seems that com/codahale/metrics/MetricRegistry has the same problem as described in my comment in #268
