### ISSUE TITLE
Connection is closed

### ISSUE THREAD

**Issue by jie-xiang** [brettwooldridge/HikariCP#1988]
Envirenment
jdk: 1.8
OS: centOS7.6
hikariCP: 4.0.3

###  org.apache.ibatis.exceptions.PersistenceException: 
Error querying database.  Cause: java.sql.SQLException: Connection is closed
The error may exist in org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
The error may involve org.camunda.bpm.engine.impl.persistence.entity.HistoricVariableInstanceEntity.selectHistoricVariableInstanceByQueryCriteria
The error occurred while executing a query
SQL: select distinct RES.*                 from ACT_HI_VARINST RES                     WHERE ( RES.NAME_ IN  (    ?     ,      ?     ,      ?     ,      ?     ,      ?      )  )                                    and RES.PROC_INST_ID_ = ?                                                          and (RES.STATE_ != 'DELETED' or RES.STATE_ is null)                                                                                                                                                                                   and (RES.TENANT_ID_ is null                  or RES.TENANT_ID_ in           (             ?           )              )          order by RES.ID_ asc     LIMIT ? OFFSET ?
### Cause: java.sql.SQLException: Connection is closed
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.lambda$executeSelectList$1(DbSqlSession.java:111)
	at org.camunda.bpm.engine.impl.util.ExceptionUtil.doWithExceptionWrapper(ExceptionUtil.java:254)
	... 61 common frames omitted
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	at com.sun.proxy.$Proxy133.prepareStatement(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at sun.reflect.GeneratedMethodAccessor239.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:238)
	at com.sun.proxy.$Proxy132.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.BatchExecutor.doQuery(BatchExecutor.java:90)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 64 common frames omitted

**Comment by jie-xiang** [comment]
My hikariCP config as below. I don't know what happened. Please give me some advice to resolve the  @problem.

HikariConfig hikariConfig = new HikariConfig();
hikariConfig.setPoolName("process-engine-datasource");
hikariConfig.setConnectionTimeout(30000);
hikariConfig.setMinimumIdle(10);
hikariConfig.setMaximumPoolSize(200);
hikariConfig.setIdleTimeout(30000);
hikariConfig.setMaxLifetime(1800000);
hikariConfig.setJdbcUrl(this.url);
hikariConfig.setUsername(this.username);
hikariConfig.setPassword(this.password);
hikariConfig.setAutoCommit(false);
hikariConfig.setDriverClassName("com.mysql.cj.jdbc.Driver");
hikariConfig.addDataSourceProperty("cachePrepStmts", true);
hikariConfig.addDataSourceProperty("prepStmtCacheSize", 260);
hikariConfig.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);
hikariConfig.addDataSourceProperty("useServerPrepStmts", true);
hikariConfig.addDataSourceProperty("useLocalSessionState", true);
hikariConfig.addDataSourceProperty("rewriteBatchedStatements", true);
hikariConfig.addDataSourceProperty("cacheResultSetMetadata", true);
hikariConfig.addDataSourceProperty("cacheServerConfiguration", true);
hikariConfig.addDataSourceProperty("elideSetAutoCommits", true);
hikariConfig.addDataSourceProperty("maintainTimeStats", false);
hikariConfig.addDataSourceProperty("connectionCollation", "utf8mb4_general_ci");
hikariConfig.addDataSourceProperty("characterEncoding", StandardCharsets.UTF_8.name());
hikariConfig.addDataSourceProperty("serverTimezone", "Asia/Shanghai");
hikariConfig.addDataSourceProperty("allowPublicKeyRetrieval", true);
hikariConfig.addDataSourceProperty("testOnBorrow", false);
hikariConfig.addDataSourceProperty("testOnReturn", false);
hikariConfig.addDataSourceProperty("testWhileIdle", true);
return new HikariDataSource(hikariConfig);

**Comment by crazylulululu** [comment]
testOnBorrow, testOnReturn,testWhileIdle this  configuration is  Druid  Pool ， hikariCP  doest not need this  configuration.  , the connection closed  , you  can check your datasource wait_timeout   ,whether the  value is  smaller than the  maxlifetime

**Comment by jie-xiang** [comment]
The wait_timeout value is 7200s for production mysql database.
