### ISSUE TITLE
Cannot acquire connection from data source

### ISSUE THREAD

**Issue by nimo10050** [brettwooldridge/HikariCP#2001]
This problem happens frequently

**Version**

* hikari version : 3.2.0
* mysql version: 5.6
* mysql connector: 8.x

**log:** 

```
2022-11-09 14:00:04.416 [DEBUG] [,] [l-2 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Pool stats (total=8, active=0, idle=8, waiting=0) 
2022-11-09 14:00:04.454 [DEBUG] [,] [l-1 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:04.670 [DEBUG] [,] [l-8 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-8 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:04.670 [DEBUG] [,] [l-5 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-5 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:04.671 [DEBUG] [,] [l-3 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:04.671 [DEBUG] [,] [l-7 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-7 - Pool stats (total=15, active=0, idle=15, waiting=0) 
2022-11-09 14:00:04.672 [DEBUG] [,] [l-6 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-6 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:04.683 [DEBUG] [,] [l-4 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-4 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:06.985 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@58f33115 
2022-11-09 14:00:06.989 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@19ce3b2e 
2022-11-09 14:00:06.989 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - After adding stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:21.909 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-3 - Closing connection oracle.jdbc.driver.T4CConnection@2e1adfa2: (connection has passed maxLifetime) 
2022-11-09 14:00:21.928 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@3ae0e72 
2022-11-09 14:00:34.416 [DEBUG] [,] [l-2 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:34.454 [DEBUG] [,] [l-1 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:34.671 [DEBUG] [,] [l-8 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-8 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:34.671 [DEBUG] [,] [l-5 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-5 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:34.671 [DEBUG] [,] [l-3 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:34.671 [DEBUG] [,] [l-7 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-7 - Pool stats (total=15, active=0, idle=15, waiting=0) 
2022-11-09 14:00:34.672 [DEBUG] [,] [l-6 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-6 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:34.683 [DEBUG] [,] [l-4 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-4 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:00:54.243 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@5d627fe6: (connection has passed maxLifetime) 
2022-11-09 14:01:04.417 [DEBUG] [,] [l-2 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Pool stats (total=9, active=0, idle=9, waiting=0) 
2022-11-09 14:01:04.454 [DEBUG] [,] [l-1 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:04.671 [DEBUG] [,] [l-5 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-5 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:04.671 [DEBUG] [,] [l-8 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-8 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:04.671 [DEBUG] [,] [l-3 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:04.671 [DEBUG] [,] [l-7 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-7 - Pool stats (total=15, active=0, idle=15, waiting=0) 
2022-11-09 14:01:04.672 [DEBUG] [,] [l-6 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-6 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:04.683 [DEBUG] [,] [l-4 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-4 - Pool stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:19.820 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@6cf5a7e1: (connection has passed maxLifetime) 
2022-11-09 14:01:21.625 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@1c5f75dd: (connection has passed maxLifetime) 
2022-11-09 14:01:24.156 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-3 - Closing connection oracle.jdbc.driver.T4CConnection@3ce3be19: (connection has passed maxLifetime) 
2022-11-09 14:01:24.179 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@27e78501 
2022-11-09 14:01:24.275 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-2 - Failed to create/setup connection: Communications link failure 
 
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. 
2022-11-09 14:01:24.275 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Cannot acquire connection from data source 
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure 
 
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. 
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) 
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) 
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) 
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) 
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) 
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197) 
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) 
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354) 
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) 
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) 
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) 
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:719) 
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:705) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at java.lang.Thread.run(Thread.java:748) 
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure 
 
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. 
	at sun.reflect.GeneratedConstructorAccessor121.newInstance(Unknown Source) 
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) 
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) 
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) 
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) 
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) 
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) 
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) 
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) 
	... 14 common frames omitted 
Caused by: java.net.SocketTimeoutException: connect timed out 
	at java.net.PlainSocketImpl.socketConnect(Native Method) 
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) 
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) 
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) 
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) 
	at java.net.Socket.connect(Socket.java:589) 
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) 
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) 
	... 17 common frames omitted 
2022-11-09 14:01:24.531 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@477e4ef0 
2022-11-09 14:01:24.535 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@64344cb 
2022-11-09 14:01:24.535 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - After adding stats (total=9, active=0, idle=9, waiting=0) 
2022-11-09 14:01:24.539 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@378fe6dd 
2022-11-09 14:01:24.539 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - After adding stats (total=10, active=0, idle=10, waiting=0) 
2022-11-09 14:01:24.808 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-2 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@3d4d80a9: (connection has passed maxLifetime) 
2022-11-09 14:01:24.813 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@666cbb84 
```

**Comment by nimo10050** [comment]
**additional log**


```
2022-11-09 20:29:35.968 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-7 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@7b1a7308: (connection has passed maxLifetime)
2022-11-09 20:29:45.283 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-7 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@f18d3d9: (connection has passed maxLifetime)
2022-11-09 20:29:46.058 [DEBUG] [,] [nnection closer] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-7 - Closing connection com.mysql.cj.jdbc.ConnectionImpl@1cbeabb3: (connection has passed maxLifetime)
2022-11-09 20:30:02.231 [DEBUG] [,] [l-1 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
2022-11-09 20:30:02.367 [DEBUG] [,] [l-2 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-2 - Pool stats (total=10, active=0, idle=10, waiting=0)
2022-11-09 20:30:02.560 [DEBUG] [,] [l-4 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-4 - Pool stats (total=15, active=0, idle=15, waiting=0)
2022-11-09 20:30:02.560 [DEBUG] [,] [l-3 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Pool stats (total=10, active=0, idle=10, waiting=0)
2022-11-09 20:30:02.596 [DEBUG] [,] [l-6 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-6 - Pool stats (total=10, active=0, idle=10, waiting=0)
2022-11-09 20:30:02.596 [DEBUG] [,] [l-5 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-5 - Pool stats (total=10, active=0, idle=10, waiting=0)
2022-11-09 20:30:02.636 [DEBUG] [,] [l-7 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-7 - Pool stats (total=1, active=0, idle=1, waiting=0)
2022-11-09 20:30:02.684 [DEBUG] [,] [l-8 housekeeper] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-8 - Pool stats (total=10, active=0, idle=10, waiting=0)
2022-11-09 20:30:05.996 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.PoolBase]: HikariPool-7 - Failed to create/setup connection: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2022-11-09 20:30:05.997 [DEBUG] [,] [onnection adder] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-7 - Cannot acquire connection from data source
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:719)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:705)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor103.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 14 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 17 common frames omitted
```

**Comment by nimo10050** [comment]
@brettwooldridge

**Comment by lfbayer** [comment]
Is there anything in that log that makes you think that HikariCP is the root cause? My first impression is that there is a connection issue with the database, rather than a HikariCP issue.
