### ISSUE TITLE
Property useShutdownHook does not exist on target class com.mysql.cj.jdbc.MysqlDataSource

### ISSUE THREAD

**Issue by paliwalsam** [brettwooldridge/HikariCP#2002]
**Version**

1. java version: openjdk 1.11
2. mysql-connector-java version: 8.0.30
3. HikariCP version: 5.0.1

**Log**
[2022-11-10 17:08:36,238]-[main] INFO  com.zaxxer.hikari.HikariDataSource - mysql.jooby - Starting...
[2022-11-10 17:08:36,286]-[main] ERROR com.zaxxer.hikari.util.PropertyElf - Property useShutdownHook does not exist on target class com.mysql.cj.jdbc.MysqlDataSource
[2022-11-10 17:08:36,288]-[main] ERROR io.jooby.Jooby - Application initialization resulted in exception
java.lang.RuntimeException: Property useShutdownHook does not exist on target class com.mysql.cj.jdbc.MysqlDataSource
        at myapp//com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:127)
        at myapp//com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:51)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
        at java.base/java.util.Properties.forEach(Properties.java:1446)
        at myapp//com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:46)
        at myapp//com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:323)
        at myapp//com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:112)
        at myapp//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:93)
        at myapp//com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at myapp//io.jooby.hikari.HikariModule.install(HikariModule.java:209)
        at myapp//io.jooby.Jooby.install(Jooby.java:522)
        at myapp//app.App.<init>(App.java:9)
        at myapp//io.jooby.Jooby.createApp(Jooby.java:1148)
        at myapp//io.jooby.Jooby.runApp(Jooby.java:1118)
        at myapp//io.jooby.Jooby.runApp(Jooby.java:1082)
        at myapp//app.App.main(App.java:14)
        at org.jboss.modules.Module.run(Module.java:353)
        at io.jooby.run.JoobyRun$AppModule.start(JoobyRun.java:115)
        at io.jooby.run.JoobyRun.start(JoobyRun.java:357)
        at io.jooby.maven.RunMojo.doExecute(RunMojo.java:121)
        at io.jooby.maven.BaseMojo.execute(BaseMojo.java:78)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] execution of app.App resulted in exception

**Comment by lfbayer** [comment]
As the error message states, "useShutdownHook" is not a valid DataSource property for the mysql driver. You probably want to remove that from your hikaricp properties.
