### ISSUE TITLE
Connection is closed

### ISSUE THREAD

**Issue by CraigX09** [brettwooldridge/HikariCP#2047]
I have added everything rightly but still its say "Your Connection is closed " here is this error`java.sql.SQLException: Connection is closed
        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
        at com.sun.proxy.$Proxy5.prepareStatement(Unknown Source)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at kx.Functions.Functions.loadaccount(Functions.java:5756)
        at kx.main.main.lambda$onPlayerConnect$1(main.java:542)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
RECEIVED CLIENT STREAM, SIZE:4
java.sql.SQLException: Connection is closed
        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
        at com.sun.proxy.$Proxy5.prepareStatement(Unknown Source)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at kx.Functions.Functions.checkban(Functions.java:4293)
        at kx.main.main$9.run(main.java:532)
        at com.maxorator.vcmp.java.tools.timers.TimerRegistry.process(TimerRegistry.java:56)
        at kx.main.main.onServerFrame(main.java:626)
        at com.maxorator.vcmp.java.plugin.integration.RootEventHandler.onServerFrameInternal(RootEventHandler.java:30)
java.sql.SQLException: Connection is closed
        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)`
        
        Here is Configuration:
        
        

> `import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;`

    `private static final HikariConfig config = new HikariConfig();
    private static DataSource datasource = null;
    public static DataSource getDataSource() {
        if (datasource == null) {
        config.setJdbcUrl( "jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12601478" );
        config.setUsername( "sql12601478" );
        config.setPassword( "5JMGIH4Exb" );
        config.addDataSourceProperty( "cachePrepStmts" , "true" );
        config.addDataSourceProperty( "prepStmtCacheSize" , "250" );
        config.addDataSourceProperty( "prepStmtCacheSqlLimit" , "2048" );
        config.addDataSourceProperty("useServerPrepStmts" , "true" );
       config.addDataSourceProperty("useLocalSessionState" , "true" );
       config.addDataSourceProperty("rewriteBatchedStatements" , "true" );
       config.addDataSourceProperty("cacheResultSetMetadata" , "true" );
       config.addDataSourceProperty("cacheServerConfiguration" , "true" );
       config.addDataSourceProperty("elideSetAutoCommits=" , "true" );
       config.addDataSourceProperty("maintainTimeStats=" , "false" );
        datasource = new HikariDataSource( config );
        }
        return datasource;
    }
    private DB() {}
    public static Connection getConnection() throws SQLException {
        DataSource mkk = getDataSource();
            try(Connection connection = datasource.getConnection()){
                return connection;
    }                        
    }
}`

**Comment by PeyaPeyaPeyang** [comment]
It seems that the `getConnection()` method opens a connection and returns it, but the return statement is within a try-with-resources block for Connection. As a result, the Connection is automatically closed before the return statement is executed, and a closed connection is always returned.

To address this issue, you may want to consider using a regular try block instead of a try-with-resources block.
