### ISSUE TITLE
Persistence connection pool connection adder - hangs

### ISSUE THREAD

**Issue by fesse** [brettwooldridge/HikariCP#2062]
With high availability and failover of MsSQL, we have sometimes experienced hanging in the PoolEntryCreator. This causes the whole pool to stop working. It mostly happens during high load, and according to the stack trace, setting the socket timeout should probably help. After about 15 minutes (probably our socket timeout time), everything recovers, and the pool works again.

I know there is a systemwide socket timeout setting, but can we have a shorter Socket Timeout (somehow) for the newConnection() call without affecting all the other sockets?

Stacktrace - (notice the elapsed time of 662 seconds).
`
"Persistence connection pool connection adder" #10071 daemon prio=5 os_prio=0 cpu=14.11ms elapsed=662.19s tid=0x0000560e5fb91800 nid=0x3cea24 runnable  [0x00007f6f80be8000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.18/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.18/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.18/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.18/SocketInputStream.java:140)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1193)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1179)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2151)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6840)
	at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.ensureSSLPayload(IOBuffer.java:881)
	at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.readInternal(IOBuffer.java:938)
	at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.read(IOBuffer.java:931)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1193)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1179)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.18/SSLSocketInputRecord.java:484)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(java.base@11.0.18/SSLSocketInputRecord.java:478)
	at sun.security.ssl.SSLSocketInputRecord.decode(java.base@11.0.18/SSLSocketInputRecord.java:160)
	at sun.security.ssl.SSLTransport.decode(java.base@11.0.18/SSLTransport.java:111)
	at sun.security.ssl.SSLSocketImpl.decode(java.base@11.0.18/SSLSocketImpl.java:1507)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(java.base@11.0.18/SSLSocketImpl.java:1417)
	at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@11.0.18/SSLSocketImpl.java:456)
	at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@11.0.18/SSLSocketImpl.java:427)
	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1839)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3456)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.util.concurrent.FutureTask.run(java.base@11.0.18/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)
`

**Comment by ryanrupp** [comment]
We've hit this as well a few times over the past couple of years - not sure the exact trigger in our case but it's connections over a VPN and think it has to do something with that (network partition as described in [Connection.setNetworkTimeout](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#setNetworkTimeout-java.util.concurrent.Executor-int-)) - has happened for both SQL Server and Oracle for us fwiw. I think the complexity here is that while Hikari guards its own operations on connections with `setNetworkTimeout` - in this case though it's _before_ the `Connection` is actually available and there's not a standardized part of the JDBC API to enable socket timeouts on the `Driver.connect` call.

That said, possibly Hikari could guard the pool creator thread and interrupt it if it hangs on an operation like this.

In our case as a workaround we probably will set a global (conservatively high) socket read timeout but in theory Hikari could be more aggressive then about this because it knows the specific operation being taken i.e. deadline the connect to 15-30s before failing (maybe some nuance to this to avoid orphaning a connection that does establish just not in time or making sure the original error is propagated i.e. on firewall issues).

**Comment by ryanrupp** [comment]
Actually, I forgot `DriverManager.setLoginTimeout` exists and I believe Hikari is by default setting this to 30s (at least in the version I'm using which is older, have to look at newer versions). I do remember now I logged an issue for the SQL Server driver about respecting this and pushing login timeout down into the connect/login operations, see https://github.com/microsoft/mssql-jdbc/issues/1529 - so I guess in theory if the JDBC drivers all did this then Hikari wouldn't need to guard. FWIW though, the issue appears to happen with either Oracle or SQL Server JDBC drivers, not sure beyond that but basically thinking it would help for Hikari to just guard this on its own anyway (gray area of course).

Here's an Oracle stack for reference

```
"<pool_name> connection adder" #11385568 daemon prio=5 os_prio=0 tid=0x0000561d78880000 nid=0x2e122b runnable [0x00007f19878c0000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        - locked <0x00000000928a53b8> (a java.lang.Object)
        at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:187)
        at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:676)
        at oracle.net.ns.NIOPacket.readPayload(NIOPacket.java:308)
        at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:212)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:137)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:110)
        at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91)
        at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:791)
        at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:449)
        at oracle.jdbc.driver.T4C8TTIdty.receive(T4C8TTIdty.java:759)
        at oracle.jdbc.driver.T4C8TTIdty.doRPC(T4C8TTIdty.java:670)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1808)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:626)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:813)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:80)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:816)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:620)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by fesse** [comment]
To answer my own question/request, this is how I "solved" the problem. It might be useful for someone else out there.
The solution will only work with the JDBC driver for MsSQL (I used version com.microsoft.sqlserver:mssql-jdbc:12.2.0.jre11)

It takes advantage of that there is a possibility to specify your own SocketFactory in the JDBC-string.

`jdbc:sqlserver://1.2.3.4;database=my_database;multiSubnetFailover=true;socketFactoryClass=your.package.ConnectionPoolSocketFactory`

The custom socket factory looks at the thread name of the thread requesting a socket and overrides the socket timeout value in two cases.
1. If it is the HikariCp connection adder thread.
2. If it is a thread with a name that starts with "Thread-" and has a default timeout value of 0. (This is true for the IdleConnectionResiliency$ReconnectThread inside the MsSQL JDBC driver)

This workaround has worked fine for us.
I would have wanted a more direct approach than relying on thread names, but this is what I came up with at the time.

Change the two values in the code to your needs (our application, in this case, has a really long default socket time out)
private static final int DEFAULT_SOCKET_TIMEOUT = **1200000**;
private static final int OVERRIDE_SOCKET_TIMEOUT = **5000**;

The socket factory code:

public class ConnectionPoolSocketFactory extends SocketFactory {

	private static Logger logger = LogManager.getLogger();

	// Taken from com.zaxxer.hikari.pool.HikariPool:addConnectionExecutor
	private static final String HIKARICP_CONNECTION_ADDER_THREAD_NAME_POSTFIX = " connection adder";

	// Taken from com.microsoft.sqlserver.jdbc.IdleConnectionResiliency$ReconnectThread
	private static final String MSSQL_RECONNECT_THREAD_PREFIX = "Thread-";

	// Timeout in ms
	private static final int DEFAULT_SOCKET_TIMEOUT = 1200000;
	private static final int OVERRIDE_SOCKET_TIMEOUT = 5000;

	@Override
	public Socket createSocket() throws IOException {
		return new ShortTimeoutSocket();
	}

	@Override
	public Socket createSocket(String host, int port) throws IOException {
		return new ShortTimeoutSocket(host, port);
	}

	@Override
	public Socket createSocket(String host, int port, InetAddress localHost, int localPort) throws IOException {
		return new ShortTimeoutSocket(host, port, localHost, localPort);
	}

	@Override
	public Socket createSocket(InetAddress host, int port) throws IOException {
		return new ShortTimeoutSocket(host, port);
	}

	@Override
	public Socket createSocket(InetAddress address, int port, InetAddress localAddress, int localPort) throws IOException {
		return new ShortTimeoutSocket(address, port, localAddress, localPort);
	}

	private static class ShortTimeoutSocket extends Socket {

		/**
		 * A crude way of determine if the timeout should be overridden
		 */
		private static int getSocketTimeoutValue(int timeout) {
			String threadName = Thread.currentThread().getName();
			if (threadName.endsWith(HIKARICP_CONNECTION_ADDER_THREAD_NAME_POSTFIX)) {
				return OVERRIDE_SOCKET_TIMEOUT;
			}
			if (timeout == 0) {
				if (threadName.startsWith(MSSQL_RECONNECT_THREAD_PREFIX)) {
					return OVERRIDE_SOCKET_TIMEOUT;
				} else {
					return DEFAULT_SOCKET_TIMEOUT;
				}
			}
			return timeout;
		}

		public ShortTimeoutSocket() {
			super();
		}

		public ShortTimeoutSocket(String host, int port) throws IOException {
			super(host, port);
		}

		public ShortTimeoutSocket(InetAddress address, int port) throws IOException {
			super(address, port);
		}

		public ShortTimeoutSocket(String host, int port, InetAddress clientAddress, int clientPort) throws IOException, UnknownHostException {
			super(host, port, clientAddress, clientPort);
		}

		public ShortTimeoutSocket(InetAddress address, int port, InetAddress clientAddress, int clientPort) throws IOException {
			super(address, port, clientAddress, clientPort);
		}

		@Override
		public synchronized void setSoTimeout(int timeout) throws SocketException {
			int updatedTimeout = getSocketTimeoutValue(timeout);
			logger.debug("Socket timeout: [{}]:[{}{}]", () -> Thread.currentThread().getName(), () -> timeout, () -> timeout != updatedTimeout ? " -> " + updatedTimeout : "");
			super.setSoTimeout(updatedTimeout);
		}
	}
}
