### ISSUE TITLE
Fail Fast on bad credentials

### ISSUE THREAD

**Issue by kycrow32** [brettwooldridge/HikariCP#2106]
HikariPool takes 30 seconds to report that a database password is bad.  This seems wrong.
I've searched online for how to "fail fast" when I pass bad credentials to hikari.  The closest I've found is:
https://github.com/brettwooldridge/HikariCP/issues/32

which introduced initializationFailFast  (later replaced by initializationFailTimeout).

That seems to control how quickly hikari will fail when first starting up.  My situation is different--I am looking at a case where my service (and hikari) are already running, and the password on the database gets changed.  I can recover dynamically by looking to our secret management solution (vault) to get an updated password.  But it takes 30 seconds for hikari to let my code know that it failed.

The stack trace I examined:

>     at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
>         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
>         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
>         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> 		
> 	caused by org.postgresql.util.PSQLException: FATAL: password authentication failed for user "exd_system"
> 
>         at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:659)
>         at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
>         at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
>         at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
>         at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
>         at org.postgresql.Driver.makeConnection(Driver.java:434)
>         at org.postgresql.Driver.connect(Driver.java:291)
>         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
>         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
>         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
>         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
>         at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
>         at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
> 

and the HikariPool is pretty obviously waiting 30 seconds (configurable) for a connection, no matter what connection error occurs.

>    public Connection getConnection(final long hardTimeout) throws SQLException
>    {
>       suspendResumeLock.acquire();
>       final var startTime = currentTime();
>       try {
>          var timeout = hardTimeout;
>          do {
>             var poolEntry = connectionBag.borrow(timeout, MILLISECONDS);
>             if (poolEntry == null) {
>                break; // We timed out... break and throw exception
>             }
>             final var now = currentTime();
>             if (poolEntry.isMarkedEvicted() || (elapsedMillis(poolEntry.lastAccessed, now) > aliveBypassWindowMs && isConnectionDead(poolEntry.connection))) {
>                closeConnection(poolEntry, poolEntry.isMarkedEvicted() ? EVICTED_CONNECTION_MESSAGE : DEAD_CONNECTION_MESSAGE);
>                timeout = hardTimeout - elapsedMillis(startTime);
>             }
>             else {
>                metricsTracker.recordBorrowStats(poolEntry, startTime);
>                return poolEntry.createProxyConnection(leakTaskFactory.schedule(poolEntry));
>             }
>          } while (timeout > 0L);
>          metricsTracker.recordBorrowTimeoutStats(startTime);
>          throw createTimeoutException(startTime);
>       }
>       catch (InterruptedException e) {
>          Thread.currentThread().interrupt();
>          throw new SQLException(poolName + " - Interrupted during connection acquisition", e);
>       }
>       finally {
>          suspendResumeLock.release();
>       }
>    }

Waiting for a connection to get through a flaky network requires a timeout, so that code makes sense from a fault tolerance perspective.
I cannot imagine a reason to retry a bad password more than once.  Once Hikari knows it has a bad password, it should fail trying to get a connection immediately.

**Comment by lfbayer** [comment]
@kycrow32 if you open a pull request with a fix and unit test coverage I'll take a look and merge it.

But also, I would recommend instead of changing the configured password in reaction to a password failure, it would be better to subclass or wrap your DataSource implementation and override the getConnection method so that you can control which password is used when getConnection is called rather than waiting for a failure to happen. This way you can likely ensure that all connections work without failure.

**Comment by c0stra** [comment]
Was there any update? I think the trend is exactly this use case. Regular password rotation and management by vault. I wonder, how does the DataSource wrapper helps. The sata source is exactly the Hikari one, where the getConnection() method is reaching this timeout no matter what's the undrlying exception. I'm now exploring handling it at the Driver level (Driver wrapper) but that also doesn't seem to solve it nicely. Native support in HikariCP may be the best option.

**Comment by lfbayer** [comment]
Likely the easiest way to do it would be one of two approaches:

Approach 1
Subclass your target driver's DataSource class and override the `getConnection()` method to call `getConnection(username, password)` using whatever mechanism you need to to get the username and password. Be sure to not set a "username" on the hikari datasource properties.

Approach 2
Create a delegate class that implements the jdbc DataSource interface delegating all method calls to your target DataSource instance, except for the `getConnection()` method. For `getConnection()` essentially implement it as described in Approach 1.

This is essentially the way that HikariCP would have to do it internally anyway if it were implemented in the connection pool itself. Whether HikariCP is the one that does this getConnection redirection or it is you, the actual hard work of getting the new username and password is still on you as the user. Such a FetchCurrentUsernamePasswordDataSource seems like something that makes sense as its own library rather than being a concern of the database connection pool. There is a reason that there are very few releases of HikariCP. It does one thing and it does it well. Adding separate concerns may not be in line with the philosophy of the library.

**Comment by c0stra** [comment]
I agree, that Hikari should stay simple and focused on it's responsibility, which is the pooling. And I also agree, that handling of this situation should be ideally decorator/wrapper onf the underlying implementation of the specific DB connection. From Hikari I'd only expect some flexibility allowing me to hook at that layer.
With mu current evaluation I found roghly these layers:

- HikariDatSource
- PoolEntry
- DriverDataSource (still class from Hikari jar, created internally in layers above)
- Driver - created inernally using default constructor based on spring property `spring.datasource.driver-class`.

So, I can wrap HikariDataSource.getConnection() (either with wrapper or by extending it) but that suffers from this timeout issue. And obviously it's not the right place, because it serves for taking potentially existing connection from the pool.

I cannot wrap or replace the DriverDataSource, which would be ideal from my perspecrive.

I can provide custom Driver wrapper, but I'll have to deal with detection of the final driver, falling back to use DriverManager low level. And what's not nice here: I'm out of spring injection.

Si the ask here is rather make the HikariCP more configurable to allow hooks with spring config at some of those two later places, ideally around the DriverDatSource.

**Comment by c0stra** [comment]
Btw. I managed to wrap the Driver layer and makexthis work. But I don't like those 2 things - disconnect from Spring, so I have to pass the spring beans responsible for vault access via static fields and second - I have to use DriverManager to let it resolve the final driver (e.g. mssql, pgsql etc) because the spring property driver-class points to my wrapper.

**Comment by c0stra** [comment]
From my perspective, the sufficient solution would be, if instantiation of the java.sql.Driver instance for given driver-class name would first cosider spring context for getting it.
