### ISSUE TITLE
In the Android project environment, the connection fails and the message Socket closed is displayed

### ISSUE THREAD

**Issue by DreamToffee** [brettwooldridge/HikariCP#2209]
> com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: 驱动程序无法通过使用安全套接字层(SSL)加密与 SQL Server 建立安全连接。错误:“Socket closed”。 ClientConnectionId:0de127cb-7513-4bad-8784-499fe2d75ca6
2024-06-24 16:10:42.693  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
2024-06-24 16:10:42.693  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
2024-06-24 16:10:42.694  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
2024-06-24 16:10:42.694  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
2024-06-24 16:10:42.694  9711-9737  System.err              com.ymc.pda                          W  	at com.ymc.pda.utils.DatabaseManager.lambda$static$0(DatabaseManager.java:28)
2024-06-24 16:10:42.695  9711-9737  System.err              com.ymc.pda                          W  	at com.ymc.pda.utils.DatabaseManager$$ExternalSyntheticLambda0.run(Unknown Source:0)
2024-06-24 16:10:42.695  9711-9737  System.err              com.ymc.pda                          W  	at java.lang.Thread.run(Thread.java:764)
2024-06-24 16:10:42.696  9711-9737  System.err              com.ymc.pda                          W  Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 驱动程序无法通过使用安全套接字层(SSL)加密与 SQL Server 建立安全连接。错误:“Socket closed”。 ClientConnectionId:0de127cb-7513-4bad-8784-499fe2d75ca6
2024-06-24 16:10:42.697  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3206)
2024-06-24 16:10:42.697  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1916)
2024-06-24 16:10:42.697  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2760)
2024-06-24 16:10:42.698  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
2024-06-24 16:10:42.698  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
2024-06-24 16:10:42.698  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
2024-06-24 16:10:42.699  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
2024-06-24 16:10:42.699  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
2024-06-24 16:10:42.699  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
2024-06-24 16:10:42.700  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
2024-06-24 16:10:42.700  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
2024-06-24 16:10:42.700  9711-9737  System.err              com.ymc.pda                          W  	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
2024-06-24 16:10:42.701  9711-9737  System.err              com.ymc.pda                          W  	... 5 more
2024-06-24 16:10:42.702  9711-9737  System.err              com.ymc.pda                          W  Caused by: java.net.SocketException: Socket closed
2024-06-24 16:10:42.702  9711-9737  System.err              com.ymc.pda                          W  	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2024-06-24 16:10:42.703  9711-9737  System.err              com.ymc.pda                          W  	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
2024-06-24 16:10:42.703  9711-9737  System.err              com.ymc.pda                          W  	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
2024-06-24 16:10:42.703  9711-9737  System.err              com.ymc.pda                          W  	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1824)
2024-06-24 16:10:42.704  9711-9737  System.err              com.ymc.pda                          W  	... 15 more

I'm sorry that my English is not up to par, please forgive me for using Google Translate. I can successfully connect to the SQL Server database in a normal Java project, but when I try to use it in an Android project environment, I find that I can't connect

**Comment by DreamToffee** [comment]
> Failed to initialize pool: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Socket closed". ClientConnectionId: 0de127cb-7513-4bad-8784-499fe2d75ca6

Fault prompt information
