### ISSUE TITLE
Failed to initialize pool: java.lang.NullPointerException

### ISSUE THREAD

**Issue by KweezyCode** [brettwooldridge/HikariCP#2232]
```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: java.lang.NullPointerException
    at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
    at com.kweezy.monitoringmetrics.SQL.setupDataSource(SQL.java:47)
    at com.kweezy.monitoringmetrics.SQL.<init>(SQL.java:24)
    at com.kweezy.monitoringmetrics.Main.<init>(Main.java:16)
    at com.kweezy.monitoringmetrics.runners.BungeeCord.onEnable(BungeeCord.java:14)
    at net.md_5.bungee.api.plugin.PluginManager.loadAndEnablePlugins(PluginManager.java:153)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:156)
    at net.md_5.bungee.BungeeCord.main(BungeeCord.java:139)
Caused by: java.sql.SQLException: java.lang.NullPointerException
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
    at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1074)
    at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3590)
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2531)
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2301)
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
    at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:317)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
    ... 9 more
Caused by: java.lang.NullPointerException
    at java.base/java.util.Objects.requireNonNull(Unknown Source)
    at java.base/java.util.TreeMap.put(Unknown Source)
    at java.base/java.util.TreeMap.put(Unknown Source)
    at com.mysql.jdbc.Util.resultSetToMap(Util.java:508)
    at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1004)
    ... 25 more
```

SQL.java:
```

package com.kweezy.monitoringmetrics;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.io.File;
import java.sql.*;

public class SQL {
    private final String dbName;
    private final String tableName;
    private HikariDataSource dataSource;

    public SQL(File dataFolder, String dbName, String tableName) throws SQLException {
        this.dbName = dbName;
        this.tableName = tableName;

        try {
            this.createDB();
            this.setupDataSource();
            this.setup();
        } catch (Exception ex) {
            throw ex;
        }
    }

    private void setupDataSource() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://" + Settings.IMP.MYSQL_HOST + "/" + Settings.IMP.MYSQL_DB);
        config.setUsername(Settings.IMP.MYSQL_USER);
        config.setPassword(Settings.IMP.MYSQL_PASSWORD);
        config.addDataSourceProperty("cachePrepStmts", "true");
        config.addDataSourceProperty("prepStmtCacheSize", "250");
        config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
        config.addDataSourceProperty("useServerPrepStmts", "true");
        config.addDataSourceProperty("useLocalSessionState", "true");
        config.addDataSourceProperty("rewriteBatchedStatements", "true");
        config.addDataSourceProperty("cacheResultSetMetadata", "true");
        config.addDataSourceProperty("cacheServerConfiguration", "true");
        config.addDataSourceProperty("elideSetAutoCommits", "true");
        config.addDataSourceProperty("maintainTimeStats", "false");

        this.dataSource = new HikariDataSource(config);
    }

    protected void setup() throws SQLException {
        try (Connection con = dataSource.getConnection(); Statement st = con.createStatement()) {
            st.executeUpdate("CREATE TABLE IF NOT EXISTS " + tableName +
                    " (id INTEGER PRIMARY KEY AUTO_INCREMENT, " +
                    "timestamp BIGINT NOT NULL, " +
                    "username TEXT NOT NULL UNIQUE, " +
                    "port INTEGER NOT NULL);"
            );

            DatabaseMetaData md = con.getMetaData();

            // if (isColumnMissing(md, "birthday")) {
            //     st.executeUpdate("ALTER TABLE " + tableName
            //             + " ADD COLUMN birthday INTEGER;");
            // }

        }
    }

    protected void createDB() {
        try {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException e) {
                throw new IllegalStateException("Failed to load MySQL JDBC class", e);
            }

            try (Connection localcon = DriverManager.getConnection("jdbc:mysql://" + Settings.IMP.MYSQL_HOST + "/?user=" + Settings.IMP.MYSQL_USER + "&password=" + Settings.IMP.MYSQL_PASSWORD + "&validationQuery=\"SELECT 1\"&testOnBorrow=true&autoReconnect=true&character_set_server=utf8mb4");
                 Statement statement = localcon.createStatement()) {
                String sql = "CREATE DATABASE " + this.dbName;
                //To delete database: sql = "DROP DATABASE DBNAME";
                statement.executeUpdate(sql);
                System.out.println("Database created!");
            }
        } catch (SQLException sqlException) {
            if (sqlException.getErrorCode() == 1007) {
                // Database already exists error
                System.out.println(sqlException.getMessage());
            } else {
                // Some other problems, e.g. Server down, no permission, etc
                sqlException.printStackTrace();
            }
        }
    }

    public void createAccount(String username, int port) throws SQLException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement("INSERT IGNORE INTO " + tableName + " (timestamp, username, port) VALUES (UNIX_TIMESTAMP(), ?,?)")) {
            ps.setString(1, username);
            ps.setInt(2, port);
            ps.executeUpdate();
        }
    }

    public boolean isAccountExists(long userid) throws SQLException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement("SELECT * FROM " + tableName + " WHERE userid = ?")) {
            ps.setLong(1, userid);
            ResultSet result = ps.executeQuery();
            return result.next();
        }
    }

    public int getId(long userid) throws SQLException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement("SELECT * FROM " + tableName + " WHERE userid = ?")) {
            ps.setLong(1, userid);
            ResultSet result = ps.executeQuery();
            if (result.next()) {
                return result.getInt("id");
            }
            return -1;
        }
    }
}
```

```
Aborted connection 680032 to db: 'unconnected' user: 'rasphost_metrics' host: '10.0.0.245' (Got an error reading communication packets)
```

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KweezyCode** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

please do not post viruses

**Comment by quaff** [comment]
As you can see, the exception is caused by:
```
Caused by: java.lang.NullPointerException
    at java.base/java.util.Objects.requireNonNull(Unknown Source)
    at java.base/java.util.TreeMap.put(Unknown Source)
    at java.base/java.util.TreeMap.put(Unknown Source)
    at com.mysql.jdbc.Util.resultSetToMap(Util.java:508)
    at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1004)
    ... 25 more
```
I don't think it's related to HikariCP.

**Comment by KweezyCode** [comment]
> As you can see, the exception is caused by:
> 
> ```
> Caused by: java.lang.NullPointerException
>     at java.base/java.util.Objects.requireNonNull(Unknown Source)
>     at java.base/java.util.TreeMap.put(Unknown Source)
>     at java.base/java.util.TreeMap.put(Unknown Source)
>     at com.mysql.jdbc.Util.resultSetToMap(Util.java:508)
>     at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1004)
>     ... 25 more
> ```
> 
> I don't think it's related to HikariCP.

native mysql driver works fine for me, so issue is in hikaricp
