### ISSUE TITLE
Password not provided to db after upgrade to 6.0.0

### ISSUE THREAD

**Issue by OrangeDog** [brettwooldridge/HikariCP#2242]
There was nothing in CHANGES that suggested this would happen.

My code currently does stuff like this:

```yaml
spring.datasource:
  url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/postgres?currentSchema=test
  username: ${PGUSER}
  password: ${PGPASSWORD}
  hikari:
    idle-timeout: 10000
    maximum-pool-size: 2
    minimum-idle: 0
```

```java
@Bean
@ConfigurationProperties("spring.datasource")
public DataSourceProperties defaultDataSourceProperties() {
    return new DataSourceProperties();
}

@Bean
@Scope(AbstractBeanFactory.SCOPE_PROTOTYPE)
@ConfigurationProperties("spring.datasource.hikari")
public HikariConfig defaultHikariConfig() {
    return new HikariConfig();
}

@Bean
public DataSource defaultDataSource() {
    DataSourceProperties properties = defaultDataSourceProperties();
    HikariConfig config = defaultHikariConfig();
    config.setPoolName(properties.determineDatabaseName());

    DataSource dataSource = properties.initializeDataSourceBuilder().type(HikariDataSource.class).build();
    copyNonNullProperties(config, dataSource, "class");
    return dataSource;
}

private static void copyNonNullProperties(Object source, Object target, String... ignoreProperties) {
    Collection<String> ignoredSet = Set.of(ignoreProperties);
    BeanWrapper sourceWrapper = PropertyAccessorFactory.forBeanPropertyAccess(source);
    BeanWrapper targetWrapper = PropertyAccessorFactory.forBeanPropertyAccess(target);

    Arrays.stream(sourceWrapper.getPropertyDescriptors())
            .map(pd -> new PropertyValue(pd.getName(), sourceWrapper.getPropertyValue(pd.getName())))
            .filter(pv -> pv.getValue() != null)
            .filter(pv -> !ignoredSet.contains(pv.getName()))
            .forEach(targetWrapper::setPropertyValue);
}
```

With HikariCP 5.1.0 this works fine, with 6.0.0 this exception is thrown:
```stacktrace
org.postgresql.util.PSQLException: The server requested SCRAM-based authentication, but no password was provided.
        at org.postgresql.core.v3.ConnectionFactoryImpl.lambda$doAuthentication$5(ConnectionFactoryImpl.java:854)
        at org.postgresql.core.v3.AuthenticationPluginManager.withPassword(AuthenticationPluginManager.java:82)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:851)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:122)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:362)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:203)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:479)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:568)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:99)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111)
```

Hopefully I'll get some time soon to debug this properly and find the problem.

**Comment by OrangeDog** [comment]
I've worked it out. This release added the `credentials` property, which returns an empty object instead of `null` if not set.
No bugs here.
