### ISSUE TITLE
oracle  getConnection -> logon   no response

### ISSUE THREAD

**Issue by qiaochunxiang2** [brettwooldridge/HikariCP#2255]
Our program often experiences the adder thread getting stuck on the login and unresponsive for a long time, which can only be resolved by restarting the application. May I ask what the reason is and how to solve it?

Is there any way to make the adder thread exceed a certain time, such as throwing an exception after 30 seconds without response? Set socketimeout param? Please help to clarify any confusion.Thank you!

The following is the status of the adder thread：

"hikari-cp connection adder" #90976 daemon prio=5 os_prio=0 tid=0x00007f490d92a000 nid=0x3112db runnable [0x00007f47fd2ec000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	- locked <0x00007f4cbf8a1d40> (a java.lang.Object)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:174)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555)
	at oracle.net.ns.NIOPacket.readNIOPacket(NIOPacket.java:403)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:127)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by qiaochunxiang2** [comment]
version: 3.4.5

**Comment by brettwooldridge** [comment]
First, upgrade HikariCP. Second, investigate Oracle property ``oracle.jdbc.ReadTimeout``.
