### ISSUE TITLE
Upgrade 6.0 database password error

### ISSUE THREAD

**Issue by wugegezuishuai** [brettwooldridge/HikariCP#2256]
Upgrade 6.0 database password error, not using configured user but obtaining machine username

**Comment by wugegezuishuai** [comment]
mysql

**Comment by brettwooldridge** [comment]
I don't know what this means. Can you provide more detail? If you're not confident in English use deepl.com to translate.

**Comment by ChetWang** [comment]
I have same issue. I'm using postgresql, it's ok when using HikariCP 5.x.x.  
If  postgresql server is in localhost, then HikariCP 6.x.x is also ok. 
But, if the db is from a remote server, error below will occur:

Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "user"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:704)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:484)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:572)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:101)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111)
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)

**Comment by brettwooldridge** [comment]
@ChetWang Can you post the DataSource authentication parts of your configuration (password redacted)? I will also test locally.

UPDATE: I am unable to reproduce this issue on v6.3.0.

**Comment by WSJHawkins** [comment]
@brettwooldridge I am also having this issue. 5.1.0 is fine. 6.0.0 is the release that breaks it and it is still broken for me in 6.3.0. I interestingly only see this when connecting to an AWS RDS database, local mysql works fine. My AWS auth tokens expire after 15 minutes so I am wondering if some behaviour around the calls to getPassword and password life cycles has changed. We had put some code in which worked to handle this but It might not be the intended use of the library and thus had an issue in this upgrade. Please point me at a better way to change the password than what we have implemented if that is the case.

 Stack trace and code snippets below. 

```
[2025-05-11T11:57:53.888Z] Caused by: java.sql.SQLTransientConnectionException: App_NAME - Connection is not available, request timed out after 30000ms (total=0, active=0, idle=0, waiting=7)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:709)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:188)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
[2025-05-11T11:57:53.888Z] 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
[2025-05-11T11:57:53.888Z] 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
[2025-05-11T11:57:53.888Z] 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
[2025-05-11T11:57:53.888Z] 	... 34 more
[2025-05-11T11:57:53.888Z] Caused by: java.sql.SQLException: Access denied for user 'acceptance'@'IP_ADDRESS' (using password: YES)
[2025-05-11T11:57:53.888Z] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[2025-05-11T11:57:53.888Z] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[2025-05-11T11:57:53.888Z] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[2025-05-11T11:57:53.888Z] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[2025-05-11T11:57:53.888Z] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[2025-05-11T11:57:53.888Z] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:368)
[2025-05-11T11:57:53.888Z] 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
[2025-05-11T11:57:53.889Z] 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:483)
[2025-05-11T11:57:53.889Z] 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:747)
[2025-05-11T11:57:53.889Z] 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
[2025-05-11T11:57:53.889Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2025-05-11T11:57:53.889Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2025-05-11T11:57:53.889Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2025-05-11T11:57:53.889Z] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[2025-05-11T11:57:53.889Z] 
```

The data source code I have is 
````
@Override
    public DataSource getDataSource(final String poolName, final boolean readOnly, final boolean autoCommit)
    {
        final HikariConfig hikariConfig = new HikariConfig();

        hikariConfig.setJdbcUrl("jdbc:mysql://" + databaseConfig.host() + ":" + databaseConfig.port() + databaseConfig.additionalJDBCProperties());

        hikariConfig.setUsername(databaseConfig.user());

        hikariConfig.setPassword(generateAuthToken(databaseConfig.host(), databaseConfig.user(), databaseConfig.port()));

        hikariConfig.setAutoCommit(autoCommit);

        hikariConfig.setKeepaliveTime(60_000);

        hikariConfig.setMinimumIdle(1);

        hikariConfig.setMaximumPoolSize(5);

        hikariConfig.setConnectionTimeout(3000);

        hikariConfig.setPoolName(poolName);

        hikariConfig.setReadOnly(readOnly);

        hikariConfig.setMaxLifetime(840000);
        return createAndStoreDatasource(hikariConfig, databaseConfig.host(), databaseConfig.user(), databaseConfig.port());
    }

    private RdsDataSource createAndStoreDatasource(final HikariConfig hikariConfig, final String url, final String user, final int port)
    {
        final RdsDataSource rdsDataSource = new RdsDataSource(hikariConfig, url, user, port);
        dataSourcesProvided.add(rdsDataSource);
        return rdsDataSource;
    }

    public class RdsDataSource extends HikariDataSource
    {
        private final String url;
        private final String user;
        private final int port;
    
        public RdsDataSource(final HikariConfig config, final String url, final String user, final int port)
        {
            super(config);
            this.url = url;
            this.user = user;
            this.port = port;
        }
    
        @Override
        public String getPassword()
        {
            if (url == null || user == null)
            {
                return super.getPassword();
            }
            return generateAuthToken(url, user, port);
        }
    
    }
```
Let me know if I can provide any other details.

**Comment by brettwooldridge** [comment]
@WSJHawkins Try this:
```java
        @Override
        public String getPassword()
        {
            if (url != null && user != null)
            {
                super.setPassword(generateAuthToken(url, user, port));
            }
            return super.getPassword();
        }
```
In general, it would be better not to extend ``HikariDataSource`` and instead use a scheduled task to periodically change the password through the ``HikariConfigMXBean`` (obtained through lookup or via ``ds.getHikariConfigMXBean()``) using the ``MikariConfigMXBean.setPassword()`` method.

**Comment by WSJHawkins** [comment]
Appreciate the quick response. Unfortunately that did not work so I will try using the HikariConfigMXBean. Thanks again

**Comment by internetstaff** [comment]
We were using a similar extension of `HikariDataSource`, but this problem is motivating us to move to https://github.com/aws/aws-advanced-jdbc-wrapper/

It seems to have a lot of benefits in addition to making iam rds auth transparent.

**Comment by brettwooldridge** [comment]
@WSJHawkins Sorry, my mistake. I shouldn't answer questions in the middle of the night. Overriding ``getPassword()`` is not going to work anymore. In order to fix a race condition for another issue, the credentials are now managed atomically via an object called ``Credentials``.

[This code](https://github.com/brettwooldridge/HikariCP/blob/491c9fb75ba88f47085c4ac29fc60fa6ba30a638/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L362) _used_ to call ``getUsername()`` and ``getPassword()`` on the ``HikariConfig``, which is extended by ``HikariDataSource`` and was ultimately overridden by you. However, _now_ this code calls ``getCredentials()`` followed by ``credentials.getUsername()`` and ``credentials.getPassword()``, so your overridden method is never called.

What should work is this, instead of overriding ``getPassword()``:
```java
@Override
public Credentials getCredentials() {
   if (url == null || user == null) {
      return super.getCredentials();
   }
   return Credentials.of(user, generateAuthToken(url, user, port));
}
```

**Comment by brettwooldridge** [comment]
HikariCP v6.3.2 now supports a system property ``com.zaxxer.hikari.legacy.supportUserPassDataSourceOverride`` that honors legacy behavior. See https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#see_no_evil-secret-properties
