### ISSUE TITLE
Race condition on Shutdown?

### ISSUE THREAD

**Issue by Adhara3** [brettwooldridge/HikariCP#229]
Hi,

if I shutdown Hikari before the Pool has been fully initialized (I guess before all the connections have been opened) sometimes I get an IllegalSateException

`2015.01.19 13:47:44,793 CET [main] DEBUG HikariPool - Before shutdown pool stats HikariPool-0 (total=8, inUse=0, avail=8, waiting=0)
2015.01.19 13:47:44,933 CET [HikariCP connection filler (pool HikariPool-0)] DEBUG HikariPool - Connection attempt to database HikariPool-0 failed: ConcurrentBag has been closed
java.lang.IllegalStateException: ConcurrentBag has been closed
	at com.zaxxer.hikari.util.ConcurrentBag.add(ConcurrentBag.java:184)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$400(HikariPool.java:73)
	at com.zaxxer.hikari.pool.HikariPool$1AddConnection.run(HikariPool.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
2015.01.19 13:47:45,41 CET [main] DEBUG HikariPool - After shutdown pool stats HikariPool-0 (total=0, inUse=0, avail=0, waiting=0)`

Note the before shutting down total being 8 while my setting is `config.setMaximumPoolSize(10);`
Maybe the `shutdown()` command does not stop the `addConnection()`?

Another question (probably unrelated): I have a project organized this way:
* war
   * jar1 accessing Oracle DB
   * jar2 accessing MSSQL DB

On startup but jar1 & 2 try to create their own Pool (they create a new config and create a new pool). In the classpath they share the same Hikari Jar. Is that supposed to work? Because I get strange errors!

Thanks
Andrea

**Comment by Adhara3** [comment]
Skip the last question, it was my fault.
Let me know about the race condition, instead!

Thanks
Andrea

**Comment by brettwooldridge** [comment]
Is this with version 2.2.5, or 2.3.0-rc4?  If 2.2.5, can you re-test with 2.3.0-rc4 and let me know if you still observe the issue?

**Comment by brettwooldridge** [comment]
This exception should be suppressed in 2.3.0.

**Comment by Adhara3** [comment]
Thanks!

Andrea

**Comment by Adhara3** [comment]
Thank you very much, I'll try that version then.

Andrea

**Comment by Adhara3** [comment]
The exception is raised, does not throw but still in the logs. If that is the intended behaviour, it's ok!

Thanks
Andrea

**Comment by rawbertp** [comment]
Hi,

I believe this is still an issue with 2.3.7. It should be easy to reproduce -> Initialize the pool with e.g. 5 connections and immediately call .close() (or shutdown()) afterwards.

Occasionally, the mentioned exception will be thrown.

These are the settings I'm using (should they be of any interest):

```
allowPoolSuspension.............false
autoCommit......................false
catalog.........................
connectionCustomizer............com.zaxxer.hikari.AbstractHikariConfig$1@7dcf94f8
connectionCustomizerClassName...
connectionInitSql...............
connectionTestQuery.............
connectionTimeout...............300000
dataSource......................
dataSourceClassName.............oracle.jdbc.pool.OracleDataSource
dataSourceJNDI..................
dataSourceProperties............{password=<masked>, url=jdbc:oracle:thin:@//xxx:1521/xxx}
driverClassName.................
healthCheckProperties...........{}
healthCheckRegistry.............
idleTimeout.....................600000
initializationFailFast..........true
isolateInternalQueries..........false
jdbc4ConnectionTest.............false
jdbcUrl.........................jdbc:oracle:thin:@//xxx:1521/xxx
leakDetectionThreshold..........0
maxLifetime.....................1800000
maximumPoolSize.................5
metricRegistry..................
minimumIdle.....................5
password........................<masked>
poolName........................HikariPool-0
readOnly........................true
registerMbeans..................false
threadFactory...................
transactionIsolation............
username........................xxx
validationTimeout...............5000
```

As @Adhara3 mentioned, it appears that the CP tries to shut down before all connections got created.

Logs:

```
2015-04-28 11:23:56,108 INFO [main] [BaseHikariPool.java:259] HikariCP pool HikariPool-0 is shutting down.
2015-04-28 11:23:56,108 DEBUG [main] [BaseHikariPool.java:580] Before shutdown pool stats HikariPool-0 (total=4, inUse=0, avail=4, waiting=0)
2015-04-28 11:23:56,120 DEBUG [HikariCP connection closer (pool HikariPool-0)] [PoolUtilities.java:52] Closing connection oracle.jdbc.driver.T4CConnection@4bb33f74
2015-04-28 11:23:56,129 DEBUG [HikariCP connection closer (pool HikariPool-0)] [PoolUtilities.java:52] Closing connection oracle.jdbc.driver.T4CConnection@6d488995
2015-04-28 11:23:56,135 DEBUG [HikariCP connection closer (pool HikariPool-0)] [PoolUtilities.java:52] Closing connection oracle.jdbc.driver.T4CConnection@2c7583ae
2015-04-28 11:23:56,141 DEBUG [HikariCP connection closer (pool HikariPool-0)] [PoolUtilities.java:52] Closing connection oracle.jdbc.driver.T4CConnection@1d932d5c
2015-04-28 11:23:56,156 INFO [HikariCP connection filler (pool HikariPool-0)] [ConcurrentBag.java:177] ConcurrentBag has been closed, ignoring add()
2015-04-28 11:23:56,157 DEBUG [HikariCP connection filler (pool HikariPool-0)] [PoolUtilities.java:52] Closing connection oracle.jdbc.driver.T4CConnection@4c5a7ce1
2015-04-28 11:23:56,172 DEBUG [HikariCP connection filler (pool HikariPool-0)] [BaseHikariPool.java:460] Connection attempt to database HikariPool-0 failed: ConcurrentBag has been closed, ignoring add()
java.lang.IllegalStateException: ConcurrentBag has been closed, ignoring add()
	at com.zaxxer.hikari.util.ConcurrentBag.add(ConcurrentBag.java:178) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:453) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool$1.run(BaseHikariPool.java:413) [HikariCP-2.3.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
2015-04-28 11:23:56,376 DEBUG [HikariCP connection filler (pool HikariPool-0)] [BaseHikariPool.java:580] After fill pool stats HikariPool-0 (total=0, inUse=0, avail=0, waiting=0)
2015-04-28 11:23:56,378 DEBUG [main] [BaseHikariPool.java:580] After shutdown pool stats HikariPool-0 (total=0, inUse=0, avail=0, waiting=0)
```

Note the 'Before' message and the fact that there should be 5 connections in the pool.

**Comment by Adhara3** [comment]
As @rawbertp says, I still see those logs too.
That happens especially during unit tests, when you init the pool, run the tests and release. Usually the release happens before all the connections have been opened.

Andrea
