### ISSUE TITLE
PoolUtilities.quitelyCloseConnection setNetworkTimeout

### ISSUE THREAD

**Issue by willemvd** [brettwooldridge/HikariCP#247]
We are using HikariCP 2.3.1 together with the jt400 driver to connect to an AS400 machine.
When a connection is closed the PoolUtilities.quitelyCloseConnection is calling the setNetworkTimeout, but this fails because the connection is already closed.
Why is this method called when closing a connection and should this not be removed and instead just only close the connection?

Lots of log is generated because for each connection it is generating:
11:24:53,895 | WARN  | AS400Datasource) | PoolUtilities                    | 311 - com.zaxxer.HikariCP-java6 - 2.3.1 | Unable to reset network timeout for connection <machine name is removed> in pool AS400Datasource
java.sql.SQLNonTransientConnectionException: The connection does not exist.
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:826)[273:JT400:7.8.0]
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:404)[273:JT400:7.8.0]
	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:460)[273:JT400:7.8.0]
	at com.ibm.as400.access.AS400JDBCConnection.setNetworkTimeout(AS400JDBCConnection.java:5581)[273:JT400:7.8.0]
	at com.zaxxer.hikari.pool.PoolUtilities.setNetworkTimeout(PoolUtilities.java:218)[311:com.zaxxer.HikariCP-java6:2.3.1]
	at com.zaxxer.hikari.pool.PoolUtilities.quietlyCloseConnection(PoolUtilities.java:53)[311:com.zaxxer.HikariCP-java6:2.3.1]
	at com.zaxxer.hikari.pool.HikariPool$1.run(HikariPool.java:128)[311:com.zaxxer.HikariCP-java6:2.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_67]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_67]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_67]

**Comment by brettwooldridge** [comment]
@willemvd We will augment this method with an additional ``connection.isClosed()`` check.  As to why HikariCP is setting the network timeout, version 2.3.0+ has been increasing the number of guards against network partitioning events.

Basically, if a network partition occurs, eg. a network switch between the application and the database fails, or a firewall rule is changed that temporarily blocks access, or a network engineer mistakenly unplugs a cable, even an innocent call like connection.close() can hang indefinitely due to unacknowledged TCP packets.  Setting the network timeout before closing ensures that the ``close()`` actually returns within a reasonable time.  However, clearly this needs to be guarded as it is an incorrect assumption that a connection being closed is necessarily still open.

We should be releasing 2.3.2 in the next day or two, and this fix will be included.  For now, you can back down to 2.2.5 to work around this issue.

**Comment by brettwooldridge** [comment]
HikariCP 2.3.2 has been released with a fix for this issue.
