### ISSUE TITLE
SQLTimeoutException at  BaseHikariPool.getConnection(BaseHikariPool.java:228)

### ISSUE THREAD

**Issue by nucleartip** [brettwooldridge/HikariCP#257]
Hi,

am little new to web programming, am developing a mobile app for which I needed a small scale rest enabled web app with mysql db support.

after reading lots of review, I went configuring HikariCP for managing connection pool database, however even after spending couple of days with it, am not yet able to make it work.

This is where am doing all my initialization.

// Init servlet
  
public class CPInit extends HttpServlet implements ServletContextListener{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private final static String TAG = CPInit.class.getSimpleName();
	private static HikariConfig mConfig;
	private static HikariDataSource mDataSource;

	public static String POOL_NAME = "MyPool";
	public static int POOL_SIZE = 50;
	public static int TIME_OUT = 2*30*1000;
	public static int MIN_IDLE_SIZE = 5;
	public static boolean isDebuggable;

	private static String PASSWORD = "PASSWORD";

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		super.doGet(req, resp);
		resp.getWriter()
		.write("Not supported");

	}

	public CPInit(){
		initPool();
	}

	public static void initPool(){

		
		TLog.info(TAG, "Password = " + string);
		mConfig = new HikariConfig();
		mConfig.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
		mConfig.addDataSourceProperty("url", "jdbc:mysql://127.0.0.1:3306/mydb");
		mConfig.addDataSourceProperty("cachePrepStmts", "true");
		mConfig.addDataSourceProperty("prepStmtCacheSize", "250");
		mConfig.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
		mConfig.addDataSourceProperty("useServerPrepStmts", "true");
		mConfig.addDataSourceProperty("user", "root");
		mConfig.addDataSourceProperty("password", PASSWORD);
		mConfig.setMaximumPoolSize(POOL_SIZE);
		mConfig.setMinimumIdle(MIN_IDLE_SIZE);
		
		mConfig.setPoolName(POOL_NAME);
		mConfig.setConnectionTimeout(TIME_OUT);
		mConfig.setAutoCommit(true);
		mConfig.setInitializationFailFast(true);
		mConfig.setConnectionTestQuery("show tables");
		mDataSource = new HikariDataSource(mConfig);
	
	}

	@Override
	public void contextDestroyed(ServletContextEvent arg0) {
		TLog.info(TAG, "CP has being destroyed");
		mDataSource.close();
		mDataSource.shutdown();

	}

	public static Connection getConnection() throws SQLException{
		TLog.info(TAG, "get data connection");

		Connection mConnection =  mDataSource.getConnection();

		if(mConnection == null || mConnection.isClosed()){
			initPool();
			mConnection =  mDataSource.getConnection();
		}

		return mConnection;

	}

	@Override
	public void contextInitialized(ServletContextEvent arg0) {
		TLog.info(TAG, "CP has been initilizing");
		String parm = arg0.getServletContext().getInitParameter("debugging");
		isDebuggable = Boolean.valueOf(parm);
	}

}

// This is how am taking connection, and closing it in a data manager class

class DataManager{

	private Connection getConnection(){
		try{
			return CPInit.getConnection();
		}catch(SQLException e){
			TLog.error(TAG, "Connection is null");
			e.printStackTrace();
			TLog.error(TAG, e.getMessage());
			TLog.error(TAG, e.getMessage());
			return null;
		}
	}
	public int getServiceId(String number) throws SQLException{

		Connection mConn = getConnection();
		if(mConn == null){
			throw new SQLException("Connection cannot be Initialized");
		}
        TLog.info(TAG, "Looking up service id for = " + number);
		PreparedStatement selectStmt = mConn.prepareStatement(SELECT_DEVICE_BY_NUMBER_ONLY);
		selectStmt.setString(1, number);
		ResultSet set  = selectStmt.executeQuery();
		if(set != null){
			if(set.next()){
				int serviceId = set.getInt(Devices._ID);
				set.close();
				selectStmt.close();
				if(mConn != null){
					mConn.close();
				}
				TLog.info(TAG, "service id found for = " + number + ", service id = " + serviceId);
				return serviceId;
			}
			set.close();
		}
		selectStmt.close();
		if(mConn != null){
			mConn.close();
		}
		
		TLog.info(TAG, "service id not found for = " + number);
		return -1;
	}
}

Now when am running query in bulk, after first few queries this is all am getting from connection call.

[INFO ] 2015-02-09 22:24:17.243 [http-nio-8080-exec-5] TLog - CPInit--get data connection
[ERROR] 2015-02-09 22:25:17.245 [http-nio-8080-exec-5] TLog - [DatabaseManager] --Connection is null
java.sql.SQLTimeoutException: Timeout after 60001ms of waiting for a connection.
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:228)
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:183)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:91)
	at com.mkgcorp.travelweb.controller.CPInit.getConnection(CPInit.java:90)
	at com.mkgcorp.travelweb.data.Database.getConnection(Database.java:18)
	at com.mkgcorp.travelweb.data.DataManager.getConnection(DataManager.java:100)
	at com.mkgcorp.travelweb.data.DataManager.getServiceId(DataManager.java:200)
	at com.mkgcorp.travelweb.webservices.SyncResource.syncContacts(SyncResource.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by brettwooldridge** [comment]
I suggest enabling leak detection (see the documentation) -- your "early return" that does ``return serviceId;`` is leaking a ``Connection``.

Code that obtains a resource (like a ``Connection``) should *always* close it in a *finally* block:
```java
public int getServiceId(String number) throws SQLException {
   Connection mConn = getConnection();
   if (mConn == null) {
      throw new SQLException("Connection cannot be Initialized");
   }

   try {
      ... // all your current logic here
   }
   finally {
      mConn.close();  // null check is unnecessary here, you already checked it above
   }

   return -1;
}
```
