### ISSUE TITLE
Codahale metrics and JNDI config

### ISSUE THREAD

**Issue by kuroneko25** [brettwooldridge/HikariCP#260]
I have two questions regarding metrics in Hikari:
- We are using Tomcat's JNDI to configure a Hikari data source on production. Is there a way to specify a metrics registry there? If not how would I obtain a handle to HikariDataSource/HikariConfig so I could set the metrics registry programmatically? 

- The metrics registry instance we use in our application is actually a subclass of the Yammer Metrics/Codahale Metrics registry class. And in the setMetricRegistry in AbstractHikariConfig there is a check:
if (metricRegistry != null && !metricRegistry.getClass().getName().contains("MetricRegistry")) {
         throw new IllegalArgumentException("Class must be an instance of com.codahale.metrics.MetricRegistry");
}
I'm a bit puzzled as to why we have a check like this that doesn't seem very robust.

**Comment by brettwooldridge** [comment]
こんにちは。

We consider the inability to set a Metrics instance when using JNDI to be a bug.   We will investigate how this can be done.  Unfortunately, for performance reasons, the internal ``CodahaleMetricsTracker`` instance is *final* and initialized in the pool constructor.  Therefore, it is not currently possible to set it later (after construction).

The reason we have the "strange" check in ``setMetricRegistery()`` is that we need to avoid a runtime dependency on Dropwizard/Codahale (because it is optional), so currently the method signature takes an ``Object`` instead of a ``MetricRegistry``.  However, we wanted a check to ensure that the object passed into the set method was really a ``MetricRegistry`` instance.

However, looking at the code again, we think we can actually refer to the ``MetricRegistry`` class *inside* the ``setMetricRegistry()`` method without incuring a runtime dependency.  It is *only the method signature*, which is inspected via reflection by Spring and other frameworks, that needs to avoid a direct reference.

So, we should be able to change the method to:
```java
public void setMetricRegistry(Object metricRegistry) {
   if (!(metricRegistry instanceof MetricRegistry)) {
      throw new IllegalArgumentException("Class must be an instance of com.codahale.metrics.MetricRegistry");
   }
   this.metricRegistry = metricRegistry;
}
```

**Comment by kuroneko25** [comment]
When can we expect a fix for the JNDI config issue?

**Comment by brettwooldridge** [comment]
@kuroneko25 The change to the ``setMetricRegistry()`` method is trivial, but does not really solve the problem because it must be called before the pool is constructed.

Ideally, there would be a way to pass an object reference (MetricRegistry) through the JNDI &lt;resource> definition, but we are not sure if this is possible.  If we have to estimate a timeline for the fix, it would be within the next week.

Can you also tell us what version of Tomcat you are running?

**Comment by kuroneko25** [comment]
We are running Tomcat 8.0.9

**Comment by brettwooldridge** [comment]
Any chance you are also running Spring? :smile:

**Comment by kuroneko25** [comment]
Nope. We use Guice for DI purposes but that's probably not relevant.

**Comment by brettwooldridge** [comment]
@kuroneko25 I don't know if you are using maven or not, but we have published a 2.3.3-SNAPSHOT build that is available from the sonatype snapshot repository.  If not, jars can be downloaded here:

https://oss.sonatype.org/content/repositories/snapshots/com/zaxxer/

Here is what we have done ... we have allowed the ``metricRegistry`` property setter to accept a String that can be used to find a ``MetricRegistry`` instance in JNDI.

Here is a usage where the MetricRegistry is created in the Global Naming Context and shared by all WARs:

*conf/server.xml*
```xml
<Server ...>
   <GlobalNamingResources>
      <Resource name="sharedMetricRegistry"
                global="sharedMetricRegistry"
                description="The name attribute above can be anything"
                type="com.codahale.metrics.MetricRegistry"
                factory="org.apache.naming.factory.BeanFactory"/>
   </GlobalNamingResources>
   ...
</Server>
```
*WEB-INF/web.xml*
```xml
<Context ...>
   <Resource name="jdbc/EmployeeDB" auth="Container"
              type="javax.sql.DataSource"
              factory="com.zaxxer.hikari.HikariJNDIFactory"
              metricRegistry="java:comp/env/sharedMetricRegistry"
              ... />
</Context>
```
If possible, can you test this code to see if it works?

**Comment by kuroneko25** [comment]
We are using maven. I'll give that a shot today.

**Comment by kuroneko25** [comment]
I'm getting a stack trace when starting the web application

```
[2015-02-13 15:58:53,129]ERROR     1[localhost-startStop-1] - com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:158) - Exception setting property metricRegistry on target class com.zaxxer.hikari.HikariConfig
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:154)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setTargetFromProperties(PropertyBeanSetter.java:63)
	at com.zaxxer.hikari.AbstractHikariConfig.<init>(AbstractHikariConfig.java:129)
	at com.zaxxer.hikari.HikariConfig.<init>(HikariConfig.java:49)
	at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:76)
	at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:67)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:841)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:152)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:829)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
	at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1084)
	at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:663)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:256)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5083)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: javax.naming.NameNotFoundException: Name [comp/env] is not bound in this Context. Unable to find [comp].
	at com.zaxxer.hikari.AbstractHikariConfig.setMetricRegistry(AbstractHikariConfig.java:512)
	... 29 more
Caused by: javax.naming.NameNotFoundException: Name [comp/env] is not bound in this Context. Unable to find [comp].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:818)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:157)
	at javax.naming.InitialContext.lookup(InitialContext.java:411)
	at com.zaxxer.hikari.AbstractHikariConfig.setMetricRegistry(AbstractHikariConfig.java:508)
	... 29 more
Feb 13, 2015 3:58:53 PM org.apache.naming.NamingContext lookup
WARNING: Unexpected exception resolving reference
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:159)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setTargetFromProperties(PropertyBeanSetter.java:63)
	at com.zaxxer.hikari.AbstractHikariConfig.<init>(AbstractHikariConfig.java:129)
	at com.zaxxer.hikari.HikariConfig.<init>(HikariConfig.java:49)
	at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:76)
	at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:67)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:841)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:152)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:829)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
	at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1084)
	at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:663)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:256)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5083)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:154)
	... 24 more
Caused by: java.lang.IllegalArgumentException: javax.naming.NameNotFoundException: Name [comp/env] is not bound in this Context. Unable to find [comp].
	at com.zaxxer.hikari.AbstractHikariConfig.setMetricRegistry(AbstractHikariConfig.java:512)
	... 29 more
Caused by: javax.naming.NameNotFoundException: Name [comp/env] is not bound in this Context. Unable to find [comp].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:818)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:157)
	at javax.naming.InitialContext.lookup(InitialContext.java:411)
	at com.zaxxer.hikari.AbstractHikariConfig.setMetricRegistry(AbstractHikariConfig.java:508)
	... 29 more
```

**Comment by brettwooldridge** [comment]
@kuroneko25 Thanks for giving it a shot.  The naming context must be different scope.  I'll investigate.

**Comment by brettwooldridge** [comment]
After some Googling, I may have the answer.  Can you try this change to *WEB-INF/web.xml*?

*WEB-INF/web.xml*
```xml
<Context ...>
   <ResourceLink name="sharedMetricRegistry" 
                 type="com.codahale.metrics.MetricRegistry"
                 global="sharedMetricRegistry"/>

   <Resource name="jdbc/EmployeeDB" auth="Container"
             type="javax.sql.DataSource"
             factory="com.zaxxer.hikari.HikariJNDIFactory"
             metricRegistry="java:comp/env/sharedMetricRegistry"
              ... />
</Context>
```

**Comment by kuroneko25** [comment]
After trying a bunch of different approaches I've managed to get it to work. I've submitted a pull request to make AbstractHikariConfig a bit more flexible in terms of what JNDI resource name it can accept.

**Comment by brettwooldridge** [comment]
Fixed by pull request #264 thanks @kuroneko25

**Comment by eepstein** [comment]
ah-so, was just looking at this.  +1 to including the dependency as "provided" scope and checking instanceof inside the method.

**Comment by kuroneko25** [comment]
Can we get a snapshot maven build while we wait for this in the next official release?

**Comment by brettwooldridge** [comment]
@kuroneko25 I just published an official release of 2.3.3 to the Sonatype repository.  It should be available in most mirrors after replication in several hours.

**Comment by azk** [comment]
This is the only description I've found of a scenario similar to what I'm trying, specifying a metrics registry using Tomcat's (Tomcat 7 here) JNDI. 
I've been able to find the way to make it work although this issue and PR have made it possible.

This is a snippet of the app context.xml:

```xml
	<Resource name="immunoMetrics"
   			  auth="Container"
	 		  type="com.codahale.metrics.MetricRegistry" 
	 		  factory="org.apache.naming.factory.BeanFactory" />

	<Resource name="jdbc/imDB" 
			  auth="Container" 
			  type="javax.sql.DataSource"
			  factory="com.zaxxer.hikari.HikariJNDIFactory"
			  metricRegistry="java:comp/env/immunoMetrics"
                          ....
```

And this is the exception:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:159)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setTargetFromProperties(PropertyBeanSetter.java:63)
	at com.zaxxer.hikari.AbstractHikariConfig.<init>(AbstractHikariConfig.java:128)
	at com.zaxxer.hikari.HikariConfig.<init>(HikariConfig.java:49)
	at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:76)
	at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:67)
	at org.apache.naming.factory.ResourceFactory.getObjectInstance(ResourceFactory.java:141)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:842)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:830)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:167)
	at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1103)
	at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:682)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:271)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5416)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:154)
	... 24 more
Caused by: java.lang.IllegalArgumentException: javax.naming.NameNotFoundException: Name [comp/env/immunoMetrics] is not bound in this Context. Unable to find [comp].
	at com.zaxxer.hikari.AbstractHikariConfig.setMetricRegistry(AbstractHikariConfig.java:512)
	... 29 more
Caused by: javax.naming.NameNotFoundException: Name [comp/env/immunoMetrics] is not bound in this Context. Unable to find [comp].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:819)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:167)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:156)
	at javax.naming.InitialContext.lookup(InitialContext.java:411)
	at com.zaxxer.hikari.AbstractHikariConfig.setMetricRegistry(AbstractHikariConfig.java:509)
	... 29 more
```
I'm using the 2.3.8 release.

Any help is appreciated.
Thank you.

**Comment by eepstein** [comment]
Looks like your setting up via JNDI using the JNDI name "comp/env/immunoMetrics" but the exception indicates that you've not bound anything at that name. Check your configuration of the container.

**Comment by eepstein** [comment]
Here's the relevant exception:

javax.naming.NameNotFoundException: Name [comp/env/immunoMetrics] is not bound in this Context. Unable to find [comp]. at org.apache.naming.NamingContext.lookup(NamingContext.java:819)
