### ISSUE TITLE
HikariCP + Cloud SQL+ Hibernate Search

### ISSUE THREAD

**Issue by RichardBrown384** [brettwooldridge/HikariCP#265]
Further to this post http://stackoverflow.com/questions/28561649/google-cloud-sql-hikari-cp-communications-link-failure

I start up an instance of a Spring Boot server. 

10 minutes later I start up a Hibernate Search mass index. The mass index takes 15 minutes to complete (so the server has been up about 25-6 minutes).

Just prior to the index completing successfully I get the following stack trace below.

The interesting numbers are 1,607,452, approximately the uptime of the server, and 927,774 being the length of time the search took to index. I don't think the index is being wrapped up in a transaction but some of the elements in the stack trace look suspicious.

EntityManager entityManager = entityManagerFactory.createEntityManager();
FullTextEntityManager fullTextEntityManager = Search.getFullTextEntityManager(entityManager);
        fullTextEntityManager.createIndexer(DomainObject.class).startAndWait();

As I write this I'm not entirely sure HikariCP has anything to do with this. It just seems that the indexing operation takes far too long to complete. But I'll post it here for consideration.

Connection com.mysql.jdbc.JDBC4Connection@4c080dc9 (HikariPool-0) marked as broken because of SQLSTATE(08S01), ErrorCode(0).

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1,607,452 milliseconds ago.  The last packet sent successfully to the server was 927,774 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
        at com.mysql.jdbc.SQLError.convertShowWarningsToSQLWarnings(SQLError.java:714)
        at com.mysql.jdbc.SQLError.convertShowWarningsToSQLWarnings(SQLError.java:666)
        at com.mysql.jdbc.StatementImpl.getWarnings(StatementImpl.java:2299)
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.getWarnings(PreparedStatementJavassistProxy.java)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:320)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logAndClearWarnings(SqlExceptionHelper.java:273)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.close(JdbcCoordinatorImpl.java:529)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.release(JdbcCoordinatorImpl.java:421)
        at org.hibernate.internal.AbstractScrollableResults.close(AbstractScrollableResults.java:121)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.loadAllIdentifiers(IdentifierProducer.java:164)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.inTransactionWrapper(IdentifierProducer.java:111)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.run(IdentifierProducer.java:95)
        at org.hibernate.search.batchindexing.impl.OptionallyWrapInJTATransaction.runWithErrorHandler(OptionallyWrapInJTATransaction.java:114)
        at org.hibernate.search.batchindexing.impl.ErrorHandledRunnable.run(ErrorHandledRunnable.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
        at sun.security.ssl.InputRecord.read(InputRecord.java:480)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:884)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2911)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3337)
        ... 24 common frames omitted
2015-02-18 17:28:18.165  WARN 1 --- [ntifierloader-1] com.zaxxer.hikari.proxy.ConnectionProxy  : Connection com.mysql.jdbc.JDBC4Connection@4c080dc9 (HikariPool-0) marked as broken because of SQLSTATE(08003), ErrorCode(0).
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
        at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:445)
        at com.mysql.jdbc.ServerPreparedStatement.checkClosed(ServerPreparedStatement.java:504)
        at com.mysql.jdbc.StatementImpl.clearWarnings(StatementImpl.java:520)
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.clearWarnings(PreparedStatementJavassistProxy.java)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:329)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logAndClearWarnings(SqlExceptionHelper.java:273)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.close(JdbcCoordinatorImpl.java:529)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.release(JdbcCoordinatorImpl.java:421)
        at org.hibernate.internal.AbstractScrollableResults.close(AbstractScrollableResults.java:121)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.loadAllIdentifiers(IdentifierProducer.java:164)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.inTransactionWrapper(IdentifierProducer.java:111)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.run(IdentifierProducer.java:95)
        at org.hibernate.search.batchindexing.impl.OptionallyWrapInJTATransaction.runWithErrorHandler(OptionallyWrapInJTATransaction.java:114)
        at org.hibernate.search.batchindexing.impl.ErrorHandledRunnable.run(ErrorHandledRunnable.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by RichardBrown384** [comment]
Additional stack trace.

2015-02-18 17:28:18.167  WARN 1 --- [ntifierloader-1] com.zaxxer.hikari.proxy.ConnectionProxy  : Connection com.mysql.jdbc.JDBC4Connection@4c080dc9 (HikariPool-0) marked as broken because of SQLSTATE(08003), ErrorCode(0).
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1232)
        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1225)
        at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1576)
        at com.zaxxer.hikari.proxy.ConnectionProxy.commit(ConnectionProxy.java:305)
        at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.commit(ConnectionJavassistProxy.java)
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doCommit(JdbcTransaction.java:112)
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:180)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.inTransactionWrapper(IdentifierProducer.java:112)
        at org.hibernate.search.batchindexing.impl.IdentifierProducer.run(IdentifierProducer.java:95)
        at org.hibernate.search.batchindexing.impl.OptionallyWrapInJTATransaction.runWithErrorHandler(OptionallyWrapInJTATransaction.java:114)
        at org.hibernate.search.batchindexing.impl.ErrorHandledRunnable.run(ErrorHandledRunnable.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by brettwooldridge** [comment]
One quick suggestion, if ``autocommit=true``, can you try adding a datasource property, ``autoReconnect=true``?

**Comment by brettwooldridge** [comment]
Also, can you post your Hibernate/HikariCP config?

**Comment by RichardBrown384** [comment]
datasource.datasourceclassname = com.mysql.jdbc.jdbc2.optional.MysqlDataSource

    final HikariDataSource dataSource = new HikariDataSource();
    dataSource.setRegisterMbeans(true);
    dataSource.setMaximumPoolSize(28);
    dataSource.setMaxLifetime(1200000);
    dataSource.setDataSourceClassName(environment.getProperty("datasource.datasourceclassname"));
    dataSource.addDataSourceProperty("url", environment.getProperty("datasource.url"));
    dataSource.addDataSourceProperty("user", environment.getProperty("datasource.username"));
    dataSource.addDataSourceProperty("password", environment.getProperty("datasource.password"));
    dataSource.addDataSourceProperty("cachePrepStmts", true);
    dataSource.addDataSourceProperty("prepStmtCacheSize", 250);
    dataSource.addDataSourceProperty("prepStmtCacheSqlLimit", 2048);
    dataSource.addDataSourceProperty("useServerPrepStmts", true);

**Comment by RichardBrown384** [comment]
I added autoReconnect=true to the datasource properties and a very slow index completed without error.

**Comment by brettwooldridge** [comment]
I'm glad to hear it.  I consider that a sub-optimal solution, but at least it works.  I feel like maybe there is some Hibernate Search tuning parameter that could also avoid the issue -- batch size or something -- but I'm not really familiar with Hibernate Search...

**Comment by RichardBrown384** [comment]
Thanks very much for your time. I'm currently trying to tune the indexing
to see if I can improve throughput. There's something not right since my
development environment can index a couple of thousand records per second
and the test live environment manages twenty.
