### ISSUE TITLE
StackOverflowError in ConnectionProxy

### ISSUE THREAD

**Issue by gfaerie** [brettwooldridge/HikariCP#269]
Hello

I have discovered what might be a cornercase bug. During a loadtest, as one of the databases ran out of disc space we encountered the following exception:

ava.lang.StackOverflowError
        at com.zaxxer.hikari.proxy.ConnectionProxy.checkException(ConnectionProxy.java:104)
        at com.zaxxer.hikari.proxy.ConnectionProxy.checkException(ConnectionProxy.java:113)
        at com.zaxxer.hikari.proxy.ConnectionProxy.checkException(ConnectionProxy.java:113)
        at com.zaxxer.hikari.proxy.ConnectionProxy.checkException(ConnectionProxy.java:113)
        at com.zaxxer.hikari.proxy.ConnectionProxy.checkException(ConnectionProxy.java:113)
....

Looking at the code it seems you got a bad exception (with itself as the next exception or with a closed loop of exceptions ?). It would be good if the code handled this in a better way though. checkException might for example only allow a recursive call so many times.  

We were using:
Postgres 9.3.5
9.3-1101-jdbc41 postgres driver
Hikari CP 2.3.2
Java 1.8.0.31
Ubuntu 14.04

Would gladly contribute with a PR if you want.

**Comment by gfaerie** [comment]
We were able to reproduce the error with a batch size insert of 100k entries (without any disc overflow).

**Comment by fommil** [comment]
is there any chance of getting this backported and released on the java 6 version?

**Comment by rorygraves** [comment]
Depends on who is throwing the bad exception (self cause). It may be their FB driver (different to ours) which might explain why we can't reproduce their test case.
