### ISSUE TITLE
HikariCP fails every time after the first on every reboot with a cryptic exception

### ISSUE THREAD

**Issue by utaal** [brettwooldridge/HikariCP#281]
sbt.ForkMain$ForkError: Fail-fast during pool initialization
      at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:500)
      at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:172)
      at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:61)
      at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:49)
      at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:78)
      at labonline.OracleDatabaseModule$class.$init$(OracleDatabaseModule.scala:46)
      at labonline.ProductionTests.<init>(AllSuites.scala:33)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
      at java.lang.Class.newInstance(Class.java:437)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:621)
      at sbt.ForkMain$Run$2.call(ForkMain.java:294)
      at sbt.ForkMain$Run$2.call(ForkMain.java:284)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
    Caused by: sbt.ForkMain$ForkError: ConcurrentBag has been closed, ignoring add()
      at com.zaxxer.hikari.util.ConcurrentBag.add(ConcurrentBag.java:172)
      at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:411)
      at com.zaxxer.hikari.pool.HikariPool.lambda$addBagItem$2(HikariPool.java:75)
      at com.zaxxer.hikari.pool.HikariPool$$Lambda$11/1058948650.run(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)

Can you help out?

Thanks.

**Comment by brettwooldridge** [comment]
This is really a Scala sbt issue, so you might want to ask on Stackoverflow.com or Scala group.  It looks like the first run is shutting down the pool and somehow the second run is trying to reuse it...

I don't really get what is going on with sbt.forkMain() or how it is even possible for the ConcurrentBag of a new instance to be closed, but I suspect there is some impedance mismatch between HikariCP's threading and sbt.

**Comment by utaal** [comment]
Thanks a lot.
