### ISSUE TITLE
poolName which contains ":" causes MalformedObjectNameException

### ISSUE THREAD

**Issue by hrchu** [brettwooldridge/HikariCP#299]
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at com.zaxxer.hikari.pool.HikariMBeanElf.unregisterMBeans(HikariMBeanElf.java:90)
	at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:256)
	at com.zaxxer.hikari.HikariDataSource.shutdownHelper(HikariDataSource.java:261)
	at com.zaxxer.hikari.HikariDataSource.shutdown(HikariDataSource.java:243)
	at com.zaxxer.hikari.HikariDataSource.close(HikariDataSource.java:228)
	at com.trendmicro.staas.core.shards.ShardManager.dispose(ShardManager.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by brettwooldridge** [comment]
Would you consider it acceptable for HikariCP to replace : (colon) with _ (underscore) when registering in JMX?  Or would you prefer that HikariCP fail-fast during configuration if there is a colon in the *poolName*?

I actually prefer failing fast, rather than modifying the user-specified *poolName* under the covers, but either is probably acceptable.

**Comment by hrchu** [comment]
fail fast +1

**Comment by slyoldfox** [comment]
Fail fast++
