### ISSUE TITLE
I configurate the `poolName`, but throw Exception

### ISSUE THREAD

**Issue by diguage** [brettwooldridge/HikariCP#327]
I first use HikariCP. And my configuration file is as follows:

```
dataSourceClassName=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
dataSource.url=${dataSource.url}
dataSource.user=${dataSource.user}
dataSource.password=${dataSource.password}
dataSource.poolName=${dataSource.poolName}
dataSource.cachePrepStmts=${dataSource.cachePrepStmts}
dataSource.prepStmtCacheSize=${dataSource.prepStmtCacheSize}
dataSource.prepStmtCacheSqlLimit=${dataSource.prepStmtCacheSqlLimit}
```

But the code throws exception as follows:

```
Exception in thread "main" java.lang.RuntimeException: java.beans.IntrospectionException: Method not found: setPoolName
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:134)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setTargetFromProperties(PropertyBeanSetter.java:63)
	at com.zaxxer.hikari.pool.PoolUtilities.initializeDataSource(PoolUtilities.java:103)
	at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:156)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
	at com.abc.main(DataAddressServer.java:40)
Caused by: java.beans.IntrospectionException: Method not found: setPoolName
	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:110)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:125)
	... 7 more

```

Then I configurate it in the code as follows:

```java
HikariConfig hikariConfig = new HikariConfig("/database.properties");
hikariConfig.setMetricRegistry(MetricUtils.METRICS);
HikariDataSource dataSource = new HikariDataSource(hikariConfig);
dataSource.setPoolName("MyPool");

``` 
Bad luck. It do not work.

The option `maxLifetime` is as the `poolName`.

How do I configurate it ?

**Comment by brettwooldridge** [comment]
``poolName`` and ``maxLifetime`` are not DataSource properties, they are HikariCP properties.  So this:

```ini
dataSourceClassName=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
poolName=${dataSource.poolName}
maxLifetime=900000
dataSource.url=${dataSource.url}
dataSource.user=${dataSource.user}
dataSource.password=${dataSource.password}
...
```

**Comment by diguage** [comment]
Thanks.
