### ISSUE TITLE
no MBean interface

### ISSUE THREAD

**Issue by shanezr** [brettwooldridge/HikariCP#334]
Just finished implementing HikariCP in an app to replace BoneCP.  The pool configures and runs successfully, but as soon as I try and turn on the JMX monitoring, I see the following.

[2015-06-27 12:00:56.756] [WARN] HikariMBeanElf - Unable to register management beans.
javax.management.NotCompliantMBeanException: com.zaxxer.hikari:type=PoolConfig (ZC_DBA) mbean has no MBean interface for class com.zaxxer.hikari.HikariDataSource
        at com.caucho.jmx.AbstractMBeanServer.createMBean(AbstractMBeanServer.java:441)
        at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:415)
        at com.zaxxer.hikari.pool.HikariMBeanElf.registerMBeans(HikariMBeanElf.java:67)
        at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:170)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
        at com.zaneray.foundation.dbconnection.HikariCPPool.connect(HikariCPPool.java:79)

[12:00:53.700] {main} Windows 8.1 6.3 amd64
[12:00:53.700] {main} Java(TM) SE Runtime Environment 1.8.0_45-b15, UTF-8, en

And this is using the most recent 2.3.8 release.

(edit)

I suppose this could simply be an issue with an outdated version of Resin also, not the pool or the JVM

**Comment by shanezr** [comment]
As a follow up, I just downloaded the snapshot HikariCP-2.4.0-rc3-20150615.073114-1.jar and do not have this issue.  the JMX Beans are registered correctly.  I'll use that version to continue testing.

**Comment by brettwooldridge** [comment]
Thank you for the report, I will investigate.

**Comment by dharrigan** [comment]
Hi,

Using rc4. From this morning, started to get this:

```
[2015-07-01 09:54:23.330][               ][DEVELOPMENT][WARN ][com.zaxxer.hikari.pool.PoolElf          ][292 ] - Unable to register management beans.
javax.management.NotCompliantMBeanException: MBean class com.zaxxer.hikari.pool.HikariPool does not implement DynamicMBean, and neither follows the Standard MBean conventions (javax.management.NotCompliantMBeanException: Class com.zaxxer.hikari.pool.HikariPool is not a JMX compliant Standard MBean) nor the MXBean conventions (javax.management.NotCompliantMBeanException: com.zaxxer.hikari.pool.HikariPool: Class com.zaxxer.hikari.pool.HikariPool is not a JMX compliant MXBean)
	at com.sun.jmx.mbeanserver.Introspector.checkCompliance(Introspector.java:176) ~[na:1.8.0_40]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317) ~[na:1.8.0_40]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[na:1.8.0_40]
	at com.zaxxer.hikari.pool.PoolElf.registerMBeans(PoolElf.java:285) ~[HikariCP-2.4.0-rc4-SNAPSHOT.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:137) [HikariCP-2.4.0-rc4-SNAPSHOT.jar:na]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) [HikariCP-2.4.0-rc4-SNAPSHOT.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [na:1.8.0_40]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) [spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) [spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267) [spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1139) [spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1042) [spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
...
...
```

**Comment by brettwooldridge** [comment]
This is fixed.  For now, you can continue to use rc3.

**Comment by dharrigan** [comment]
Thank you Brett! :-)

-=david=-

On 1 July 2015 at 15:18, Brett Wooldridge <notifications@github.com> wrote:

> This is fixed. For now, you can continue to use rc3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettwooldridge/HikariCP/issues/334#issuecomment-117691431>
> .
>



-- 
I prefer encrypted and signed messages. KeyID: B20A22F9
Fingerprint: 110A F423 3647 54E2 880F ADAD 1C52 85BF B20A 22F9

"It is not usually until you've built and used a version of the program
that you understand the issues well enough to get the design right." - Rob
Pike, Brian Kernighan.

No trees were harmed in the sending of this message, however, a number of
electrons were inconvenienced.

**Comment by brettwooldridge** [comment]
v2.3.9 is now available with this fix.

**Comment by dharrigan** [comment]
Hi Brett!

Thank you for the update :-) I'll wait until 2.4.0 comes out (or the next
RC of 2.4.0). I'm not scheduling a release for a few weeks at least... :-)

-=david=-

On 11 July 2015 at 01:33, Brett Wooldridge <notifications@github.com> wrote:

> v2.3.9 is now available with this fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettwooldridge/HikariCP/issues/334#issuecomment-120556191>
> .
>



-- 
I prefer encrypted and signed messages. KeyID: B20A22F9
Fingerprint: 110A F423 3647 54E2 880F ADAD 1C52 85BF B20A 22F9

"It is not usually until you've built and used a version of the program
that you understand the issues well enough to get the design right." - Rob
Pike, Brian Kernighan.

No trees were harmed in the sending of this message, however, a number of
electrons were inconvenienced.
