### ISSUE TITLE
Registering MBeans twice?

### ISSUE THREAD

**Issue by piefel** [brettwooldridge/HikariCP#342]
The change-log for HikariCP 2.3.9 says ‘Fixed regression in JMX MBean registration.’ However, my experience is different.

With 2.3.8 it works as I expect it, MBeans for my datasources are registered. With 2.3.9 it seems that HikariCP tries to register them twice, which won’t work, of course. I provided a stack trace below. Now the code has the database creation somewhere deep down in ancient libraries, so I cannot guarantee that the datasources are not somehow re-initialized somehow (if that’s possible at all).

I can confirm there’s only one `new HikariDataSource(hikariConfig)` per datasource. There are, however, 5 datasources.

    javax.management.InstanceAlreadyExistsException: MXBean already registered with name com.zaxxer.hikari:type=PoolConfig (DATABASE_NAME)
        at com.sun.jmx.mbeanserver.MXBeanLookup.addReference(MXBeanLookup.java:151) ~[na:1.8.0_45]
        at com.sun.jmx.mbeanserver.MXBeanSupport.register(MXBeanSupport.java:160) ~[na:1.8.0_45]
        at com.sun.jmx.mbeanserver.MBeanSupport.preRegister2(MBeanSupport.java:173) ~[na:1.8.0_45]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:930) [na:1.8.0_45]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) [na:1.8.0_45]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) [na:1.8.0_45]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) [na:1.8.0_45]
        at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:195) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:670) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:615) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:550) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:432) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    Wrapped by: org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [HikariDataSource (DATABASE_NAME)] with key 'coachingDataSource'; nested exception is javax.management.InstanceAlreadyExistsException: MXBean already registered with name com.zaxxer.hikari:type=PoolConfig (DATABASE_NAME)
        at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:550) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:432) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016) [catalina.jar:7.0.62]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528) [catalina.jar:7.0.62]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.62]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.62]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.62]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.62]

**Comment by brettwooldridge** [comment]
@piefel This is not HikariCP trying to register an MBean twice, it is Spring.  HikariCP is nowhere in that stacktrace.  HikariCP has [protection against double-registration](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/pool/HikariMBeanElf.java#L66) and logs a different message.

HikariCP only registers MBeans when ``registerMeans`` is set to ``true``.

**Comment by piefel** [comment]
I know HikariCP is not in the stack trace.

However, the behaviour changed when I switched from HikariCP 2.3.8 to 2.3.9 and not when I changed any Spring dependency. Therefore, a change in HikariCP is responsible for the changed behaviour.

**Comment by brettwooldridge** [comment]
HikariCP JMX beans changed from MBeans to MXBeans (from static MBeans to dynamic MXBeans).  This change may have *affected* Spring's behavior, but that is 100% controlled by the Spring-side of the equation.

I strongly suspect that somewhere in your Spring configuration, Spring's own [MBeanExporter](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jmx.html#jmx-introduction) and/or [automatic registration](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jmx.html#jmx-exporting-auto) is causing this error.  It is likely that after the switch to MXBeans, Spring started to detect and attempt to automatically register HikariCP's beans.

You can:
 * Turn off Spring's exporter completely, or
 * Configure Spring's (registration behaviors](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jmx.html#jmx-exporting-registration-behavior), or
 * Turn off automatic registration of MBeans

**Comment by piefel** [comment]
Thank you for the pointer. Before the change, Spring’s MBean detection looked at a bean of type `HikariDataSource` and, looking for an MBean called `HikariDataSourceMBean`, did not find any. Now, Spring’s MXBean detection looks at a bean of type `HikariDataSource` and goes up the whole inheritance hierarchy, finally finding `HikariConfigMXBean`.

The best strategy here seems to tell Spring to ignore doubled MBeans. However, this may not be acceptable for some people. (It is for me.)

Telling HikariCP not to export its beans is _not_ a good solution: HikariCP exports two MBeans, and only one of them (the configuration) will be picked up by Spring in a normal setup. The other, more interesting, one will be lost. Also, the Spring exporter uses a slightly different naming scheme.

**Comment by DevWantJustHaveFun** [comment]
this spring boot config can help for this issue:

`@Configuration
public class JmxConfig
{
    // this beans should not be monitored by jmx
    private static final String[] jmxExcludedBeans = { "dataSource" };

    @Bean
    public MBeanExporter exporter()
    {
        final MBeanExporter exporter = new MBeanExporter();
        exporter.setAutodetect(true);
        exporter.setExcludedBeans(jmxExcludedBeans);
        return exporter;
    }
}
`

**Comment by brettwooldridge** [comment]
@DevWantJustHaveFun Thanks for the update, it surely will help other users.

**Comment by tonyfalabella** [comment]
Thank you @DevWantJustHaveFun.

The code from @DevWantJustHaveFun needed a slight tweak for me using Spring Boot 1.4.2 .
It appears Spring Boot wants to create AnnotationMBeanExporter (a subclass of MBeanExporter) .
[http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/jmx/JmxAutoConfiguration.html](url)

```
  @Bean
  public MBeanExporter exporter() {
    final MBeanExporter exporter = new AnnotationMBeanExporter();
    exporter.setAutodetect(true);
    exporter.setExcludedBeans("dataSource");
    return exporter;
  }
```

Without the modification below I get this error:
```
`org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [driverClassName = xxx
url = yyy
username = zzz
maximumPoolSize = 10
] with key 'dataSource'; nested exception is javax.management.MalformedObjectNameException: Key properties cannot be empty`
```

**Comment by tonyfalabella** [comment]
Perhaps I'm doing something incorrectly, but when I use the above `MBeanExporter` method and I register 3 `HikariDataSource` beans each with a `poolName` specified and `registerMbeans=true` I only get the primary `DataSource` to show in JMX - the other 2 beans do not.  Just to note that there is no error that duplicates are being registered.

Versions used:
Spring Boot 1.4.2.RELEASE with HikariCP 2.4.7 .  I've also tried with HikariCP 2.6.1.

**Comment by brettwooldridge** [comment]
@tonyfalabella I'm totally not an expert on Spring Boot, especially regarding JMX.  This question is probably best asked on stackoverflow.  One related question/answer I could find was this https://stackoverflow.com/questions/36869669/overriding-default-registrationpolicy-on-annotationmbeanexporter-in-spring-boot but I don't know if that really helps in this case or not.

**Comment by DevWantJustHaveFun** [comment]
Hello @tonyfalabella 

I'm using Spring Boot 1.5.3.RELEASE with HikariCP 2.6.1, this is my configuration of my two datasource and my jmx configuration  

`@Bean
    @Qualifier("datasource1")
    @ConfigurationProperties(prefix = "datasource1")
    public HikariDataSource dcsDataSource()
    {
        final HikariDataSource dataSource = (HikariDataSource) DataSourceBuilder.create().type(HikariDataSource.class).build();
        dataSource.setMaximumPoolSize(MAXIMUN_POOL_SIZE);
        dataSource.setPoolName("datasource1PoolName");
        dataSource.setRegisterMbeans(true);
        return dataSource;
    }`

`@Bean
    @Qualifier("datasource2")
    @ConfigurationProperties(prefix = "datasource2")
    public HikariDataSource dcsDataSource()
    {
        final HikariDataSource dataSource = (HikariDataSource) DataSourceBuilder.create().type(HikariDataSource.class).build();
        dataSource.setMaximumPoolSize(MAXIMUN_POOL_SIZE);
        dataSource.setPoolName("datasource2PoolName");
        dataSource.setRegisterMbeans(true);
        return dataSource;
    }`

    @Bean
    public MBeanExporter exporter()
    {
        final MBeanExporter exporter = new MBeanExporter();
        // we exclude the "datasource" beans because it's already managed by hikari itself
        exporter.setExcludedBeans({ "datasource1", "datasource2"});
        return exporter;
    }

And my application properties : 

datasource1.username=username
datasource1.password=password
datasource1.jdbcUrl=jdbc:postgresql://some_url:5432/db1
datasource1.driverClassName=org.postgresql.Driver

datasource2.username=username
datasource2.password=password
datasource2.jdbcUrl=jdbc:postgresql://some_url:5432/db2
datasource2.driverClassName=org.postgresql.Driver

**Comment by LizzyMiao** [comment]
Use the existing exporter instead of creating a new exporter would be better, like this:
@Autowired
    MBeanExporter mBeanExporter;

otherwise, the existing jmx beans in the project will be ignored

**Comment by binakot** [comment]
Just like that:

```java
@Configuration
public class MBeanConfig {

    @Autowired
    public MBeanConfig (final MBeanExporter mBeanExporter) {
        mBeanExporter.setExcludedBeans("dataSource");
    }
}
```

And 

```yaml
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db
    username: username
    password: password
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: HIKARI_CP
      minimumIdle: 1
      maximumPoolSize: 4
      registerMbeans: true
```

Works like a charm ☕️

**Comment by russellhoff** [comment]
> Just like that
> 
> ```java
> @Configuration
> public class MBeanConfig {
> 
>     @Bean
>     public MBeanExporter exporter(final @Qualifier("endpointMBeanExporter") MBeanExporter mBeanExporter) {
>         mBeanExporter.setExcludedBeans("dataSource");
>         return mBeanExporter;
>     }
> }
> ```
> 
> And
> 
> ```yaml
> spring:
>   datasource:
>     url: jdbc:postgresql://127.0.0.1:5432/db
>     username: username
>     password: password
>     driverClassName: org.postgresql.Driver
>     type: com.zaxxer.hikari.HikariDataSource
>     hikari:
>       poolName: HIKARI_CP
>       minimumIdle: 1
>       maximumPoolSize: 4
>       registerMbeans: true
> ```
> 
> Works like a charm ☕️

My case was related to Maven's Cargo plugin, which wasn't working well: didn't deploy my application, but locally it was working right.

I didn't need to create a `MBeanExporter` bean, I just added `spring.datasource.type` and `spring.datasource.hikari.*`, plus renamed from `spring.datasource.driver-class-name` to `spring.datasource.driverClassName` and it worked.

**Comment by macgregor** [comment]
Using spring boot 2.0.3.RELEASE I had to specify AnnotationMBeanExporter:
```java
@Bean
public MBeanExporter exporter(final AnnotationMBeanExporter mBeanExporter) {
  mBeanExporter.setExcludedBeans("activemqPersistenceDataSource", "activemqLockerDataSource");
  return mBeanExporter;
}
```

Also, if you are instantiating beans in your own autoconfig class you will need to add `@AutoConfigureAfter(JmxAutoConfiguration.class)`

Now if only I could get these runtime pool size changes to actually take effect...

**Comment by 52Jolynn** [comment]
override the default registrationpolicy is work for me. Using springboot 2.1.3.RELEASE

```java
@Configuration
@EnableMBeanExport(registration = RegistrationPolicy.IGNORE_EXISTING)
public class MXBeansConfig {
}
```

**Comment by BinaryYS** [comment]
> override the default registrationpolicy is work for me. Using springboot 2.1.3.RELEASE
> 
> ```java
> @Configuration
> @EnableMBeanExport(registration = RegistrationPolicy.IGNORE_EXISTING)
> public class MXBeansConfig {
> }
> ```

Thank you, It works for me with another setting below
 
    @Bean
    public MBeanExporter exporter(final AnnotationMBeanExporter mBeanExporter) {
        mBeanExporter.setExcludedBeans("userDataSource");
        return mBeanExporter;
    }

**Comment by BinaryYS** [comment]
> Using spring boot 2.0.3.RELEASE I had to specify AnnotationMBeanExporter:
> 
> ```java
> @Bean
> public MBeanExporter exporter(final AnnotationMBeanExporter mBeanExporter) {
>   mBeanExporter.setExcludedBeans("activemqPersistenceDataSource", "activemqLockerDataSource");
>   return mBeanExporter;
> }
> ```
> 
> Also, if you are instantiating beans in your own autoconfig class you will need to add `@AutoConfigureAfter(JmxAutoConfiguration.class)`
> 
> Now if only I could get these runtime pool size changes to actually take effect...

It works with setting below
@EnableMBeanExport(registration = RegistrationPolicy.IGNORE_EXISTING)
