### ISSUE TITLE
java.sql.SQLTimeoutException: Timeout after 30002ms of waiting for a connection.

### ISSUE THREAD

**Issue by maoxianfly** [brettwooldridge/HikariCP#366]
2015-08-04 13:59:10.735 [pool-6-thread-16] DEBUG com.zaxxer.hikari.pool.HikariPool - Timeout failure pool HikariPool-0 stats (total=10, active=10, idle=0, waiting=1)
2015-08-04 13:59:10.736 [pool-6-thread-16] ERROR  - 
java.sql.SQLTimeoutException: Timeout after 30002ms of waiting for a connection.
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:211) ~[HikariCP-2.4.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161) ~[HikariCP-2.4.0.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85) ~[HikariCP-2.4.0.jar:?]
	at com.flhx.core.db.memory.Memory.getConnection(Memory.java:453) ~[core-0.1.1.jar:0.1.1]
	at com.flhx.core.db.memory.Memory.query(Memory.java:44) ~[core-0.1.1.jar:0.1.1]
	at com.flhx.gs.role.dao.RoleBaseDao.readRoleIdByUid(RoleBaseDao.java:57) ~[gs-0.1.1.jar:0.1.1]
	at com.flhx.gs.role.service.RoleBaseService.readRoleIdByUidFormDb(RoleBaseService.java:794) ~[gs-0.1.1.jar:0.1.1]
	at com.flhx.gs.role.service.RoleBaseService.loginGame(RoleBaseService.java:189) ~[gs-0.1.1.jar:0.1.1]
	at com.flhx.gs.role.handler.LoginGameHandler.execute(LoginGameHandler.java:34) ~[gs-0.1.1.jar:0.1.1]
	at com.flhx.core.net.handler.GameHandler.action(GameHandler.java:19) ~[core-0.1.1.jar:0.1.1]
	at com.flhx.core.net.dispatcher.HandlerDispatcher$MessageWorker.handMessageQueue(HandlerDispatcher.java:225) [core-0.1.1.jar:0.1.1]
	at com.flhx.core.net.dispatcher.HandlerDispatcher$MessageWorker.run(HandlerDispatcher.java:194) [core-0.1.1.jar:0.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

only a client connection test

**Comment by maoxianfly** [comment]
Hi Brett,

The active connection pool is not recycled ?

=======================

2015-08-04 15:56:23.591 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0)
2015-08-04 15:56:53.594 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0)
2015-08-04 15:56:53.594 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0

2015-08-04 16:34:23.591 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0)
2015-08-04 16:34:23.591 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0)
2015-08-04 16:34:53.591 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - Before cleanup pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0)
2015-08-04 16:34:53.594 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@e36894: (connection passed idleTimeout)
2015-08-04 16:34:53.601 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@157d523: (connection passed idleTimeout)
2015-08-04 16:34:53.602 [Hikari housekeeper (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After cleanup pool HikariPool-0 stats (total=3, active=2, idle=1, waiting=0)
2015-08-04 16:34:53.603 [Hikari connection closer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@f5408a: (connection passed idleTimeout)
2015-08-04 16:34:53.604 [Hikari connection closer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@1a8ac6e: (connection passed idleTimeout)
2015-08-04 16:34:53.605 [Hikari connection closer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@1e529e8: (connection passed idleTimeout)
2015-08-04 16:34:53.605 [Hikari connection closer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@a756e5: (connection passed idleTimeout)
2015-08-04 16:34:53.606 [Hikari connection closer (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.PoolElf - HikariPool-0 - Closing connection com.mysql.jdbc.JDBC4Connection@fe2a44: (connection passed idleTimeout)
2015-08-04 16:34:53.616 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@45eee9 added to pool
2015-08-04 16:34:53.623 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@666f73 added to pool
2015-08-04 16:34:53.630 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@19adea3 added to pool
2015-08-04 16:34:53.637 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@13773a added to pool
2015-08-04 16:34:53.643 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@e3244a added to pool
2015-08-04 16:34:53.648 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@c25630 added to pool
2015-08-04 16:34:53.652 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - Connection com.mysql.jdbc.JDBC4Connection@153d1c added to pool
2015-08-04 16:34:53.652 [Hikari connection filler (pool HikariPool-0)] DEBUG com.zaxxer.hikari.pool.HikariPool - After fill pool HikariPool-0 stats (total=10, active=2, idle=8, waiting=0)

**Comment by brettwooldridge** [comment]
This looks like a connection leak.  Some thread allocated 2 connections and did not release them.  Set leakDetectionThreshold to some reasonable value, like 20000.  You'll find the leak.
