### ISSUE TITLE
upgrade from 2.3.9 to 2.4.0 - java.nio.file.InvalidPathException

### ISSUE THREAD

**Issue by g8373653** [brettwooldridge/HikariCP#375]
I tried to upgrade from 2.3.9 to 2.4.0. There seems to be a problem with accessing the properties file. 

Code:

`new HikariConfig(getClass().getClassLoader().getResource("hikari.properties").getFile()))`

Exception:

`java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/Projects/Module-App1/target/classes/hikari.properties
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.zaxxer.hikari.HikariConfig.loadProperties(HikariConfig.java:848)
	at com.zaxxer.hikari.HikariConfig.<init>(HikariConfig.java:142)`

**Comment by mwegrz** [comment]
@g8373653 a valid Windows file path passed to the `HikariConfig` constructor should not contain a leading `/` or `\`. In your example it should be just `D:/Projects/Module-App1/target/classes/hikari.properties`. 

You might try the following:
```java
String path = getClass().getClassLoader().getResource("hikari.properties").getFile();
String validPath = path.substring(1);
new HikariConfig(validPath);
```

**Comment by nitincchauhan** [comment]
@g8373653 @mwegrz a commit to dev branch currently has a fix for this. Please test and let us know.

**Comment by brettwooldridge** [comment]
Fixed in dev.
