### ISSUE TITLE
SQLite JDBC

### ISSUE THREAD

**Issue by Xephi** [brettwooldridge/HikariCP#393]
Hi ! Is there any way to make HikariCP work with an sqlite datasource ?

I've test that kind of things with no success : 

```java
        Properties props = new Properties();
        props.setProperty("dataSourceClassName", "org.sqlite.SQLiteDataSource");
        HikariConfig config = new HikariConfig(props);
        HikariDataSource ds = new HikariDataSource(config);
```

it returns an error as Connection.isValid() isn't a defined method ^^"

**Comment by minecrafter** [comment]
Try setting `connectionTestQuery`.

**Comment by Xephi** [comment]
Huuum i have set it to "SELECT 1;", it works well, by the way, i've tested to set the database url, but idk why, the database stay volatile and nothing is write on disk : 

```JAVA
        Properties props = new Properties();
        props.setProperty("dataSourceClassName", "org.sqlite.SQLiteDataSource");
        props.setProperty("dataSource.url", "plugins/AuthMe/" + this.database + ".db");
        props.setProperty("dataSource.databaseName", this.database);
        HikariConfig config = new HikariConfig(props);
        config.setPoolName("AuthMeSQLiteLPool");
        config.setConnectionTestQuery("SELECT 1;");
        ds = new HikariDataSource(config);
```

I think i'm doing it wrongly :p

**Comment by brettwooldridge** [comment]
Are you sure you have write permissions in the filesystem, or that a command-line client is not also accessing at the same time?

Read the [SQLite FAQ](https://www.sqlite.org/faq.html#q5) questions 5 and 6 to make sure you aren't having issues related to filesystem locks or multithreading.

Finally, make sure you are using the latest SQLite driver.

**Comment by Xephi** [comment]
It hasn't create the file if not found, i try with created the file without success :/ I got no problem without HikariCP : 

```JAVA
        Class.forName("org.sqlite.JDBC");
        Connection con = DriverManager.getConnection("jdbc:sqlite:plugins/AuthMe/" + database + ".db");
```
And i use sqlite-jdbc version 3.8.11.1 (latest one actually)

Thanks for your help anyway

**Comment by brettwooldridge** [comment]
@Xephi In that case, create the configuration like so:
```java
HikariConfig config = new HikariConfig();
config.setPoolName("AuthMeSQLitePool");
config.setDriverClassName("org.sqlite.JDBC");
config.setJdbcUrl("jdbc:sqlite:plugins/AuthMe/" + database + ".db");
config.setConnectionTestQuery("SELECT 1");
config.setMaxLifetime(60000); // 60 Sec
config.setIdleTimeout(45000); // 45 Sec
config.setMaximumPoolSize(50); // 50 Connections (including idle connections)
ds = new HikariDataSource(config);
```

**Comment by brettwooldridge** [comment]
@Xephi any update on this issue?

**Comment by Xephi** [comment]
Hi ! Thanks for your help, we done it like  that you said in your previous comment, it works like a charm :) 

Sorry for late reply and again thanks for your work :)

Xephi

**Comment by mburger81** [comment]
@Xephi do you know how we can set "PRAGMA main.cache_size = 5000" and other parameters like that with HikariCP, doing the work with addDataSourceProperty seems to not work.

@brettwooldridge

**Comment by user20161119** [comment]
> @Xephi In that case, create the configuration like so:
> 
> ```java
> HikariConfig config = new HikariConfig();
> config.setPoolName("AuthMeSQLitePool");
> config.setDriverClassName("org.sqlite.JDBC");
> config.setJdbcUrl("jdbc:sqlite:plugins/AuthMe/" + database + ".db");
> config.setConnectionTestQuery("SELECT 1");
> config.setMaxLifetime(60000); // 60 Sec
> config.setIdleTimeout(45000); // 45 Sec
> config.setMaximumPoolSize(50); // 50 Connections (including idle connections)
> ds = new HikariDataSource(config);
> ```

I set the ConnectionTestQuery in properies file with SQLite,my question is
i set the setJdbcUrl with not exist file,but i init HikariDataSource success and get connection success,
```java
  String dbFile = "F:/tmp/etl/360428/GW15001420140921.d2b"; // not exist db file

    @Test
    public void testGetHikariDS() throws SQLException {
        HikariDataSource dataSource = SQLiteDSConfig.getHikariDS(dbFile);
        Connection connection = dataSource.getConnection();
       // System.out.println(connection.getClientInfo().keySet());
       // PreparedStatement ps = connection.prepareStatement("select * from rundata limit 0,1");
      //  System.out.println(ps.getMaxRows());
    }
```
set the right jdbc url,
but run ` PreparedStatement ps = connection.prepareStatement("select * from rundata limit 0,1");`
get errror
```java
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: rundata)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at com.jfhn.config.ds.SQLiteDSConfigTest.testGetHikariDS(SQLiteDSConfigTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

```
I used the java native jdbc run sql as follow
```java
 Class.forName("org.sqlite.JDBC");
        Connection connection = DriverManager.getConnection("jdbc:sqlite:" + dbFile);
        PreparedStatement ps = connection.prepareStatement("select * from rundata limit 0,1");
```
every is fine,do not know why HikariCP not work

**Comment by user20161119** [comment]
my SQLite db file work correctly in Navicat and SQLite command tool
