### ISSUE TITLE
cannot connect to mysql after change the default port to other number

### ISSUE THREAD

**Issue by hepin1989** [brettwooldridge/HikariCP#398]
```
Caused by: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:580)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:150)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at qgame.engine.data.db.DefaultDB$.qgame$engine$data$db$DefaultDB$$getDatabaseViaUrl(DB.scala:124)
	at qgame.engine.data.db.DefaultDB$$anonfun$3.apply(DB.scala:83)
	at qgame.engine.data.db.DefaultDB$$anonfun$3.apply(DB.scala:67)
	at scala.Option.map(Option.scala:146)
	at qgame.engine.data.db.DefaultDB$.qgame$engine$data$db$DefaultDB$$createDatabaseFromConfigOrFail(DB.scala:66)
	at qgame.engine.data.db.DefaultDB$$anonfun$database$1.apply(DB.scala:146)
	at qgame.engine.data.db.DefaultDB$$anonfun$database$1.apply(DB.scala:145)
	at scala.Option.getOrElse(Option.scala:121)
	at qgame.engine.data.db.DefaultDB$.database(DB.scala:145)
	at qgame.engine.data.db.DefaultDB$.database(DB.scala:54)
	at qgame.engine.libs.DB$.database(DB.scala:10)
	at cn.qgame.xxjh.gate.module.infer.db.DBHelper$.db$lzycompute(DBHelper.scala:16)
	at cn.qgame.xxjh.gate.module.infer.db.DBHelper$.db(DBHelper.scala:16)
	at cn.qgame.xxjh.gate.module.infer.db.DBHelper$.tableExist(DBHelper.scala:47)
	at cn.qgame.xxjh.gate.module.infer.db.DBHelper$.checkExistOrCreateTable(DBHelper.scala:20)
	at cn.qgame.xxjh.gate.module.infer.InferModuleActor.preStart(InferModuleActor.scala:182)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:472)
	at cn.qgame.xxjh.gate.module.infer.InferModuleActor.aroundPreStart(InferModuleActor.scala:20)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	... 9 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2237)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:134)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:495)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:564)
	... 30 more
Caused by: java.net.ConnectException: connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 46 more

```

the code setup is
```
    val cpConfig = new HikariConfig()
        val jdbcUrl = s"jdbc:mysql://127.0.0.1:3307/gate"
        log.info(jdbcUrl)
        cpConfig.setJdbcUrl(jdbcUrl)
        cpConfig.addDataSourceProperty("databaseName", dbName)
        cpConfig.setUsername(username)
        cpConfig.setPassword(password)
        val dataSource = new HikariDataSource(cpConfig)
```
I hard coding here for test.

I change the ```my.cnf```
the port to ```3307``` and ```service mysql restart``` then it throws.
I used this lib for a low time and really don't know why it throws now.
- mysql 5.6
- jdbc  "mysql" % "mysql-connector-java" % "5.1.35",
- ubuntu 14.04

the problem is that I could connect to mysql via navicat with port 3307,but not via code .

**Comment by ystarikovich** [comment]
Did you check telnet to port 3307 ? Looks like you have firewall filtering.

**Comment by hepin1989** [comment]
it seem like a user error,closing now,will update later

**Comment by hepin1989** [comment]
//        hikariConfig.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource")

after I comment this out,it works.why?
@ystarikovich @brettwooldridge 
shoud not use the ```hikariConfig.setJdbcUrl ```with ``` hikariConfig.setDataSourceClassName``` this one?

**Comment by brettwooldridge** [comment]
You use either jdbcUrl *or* dataSourceClassName, but not both, as documented of the project page.

If you use dataSourceClassName, you need to configure the host, port, database name, etc. through dataSource properties.

**Comment by hepin1989** [comment]
thank you very much.
