### ISSUE TITLE
Specifying both the setDataSourceClassName & jdbc url leading to connection error on localhost.

### ISSUE THREAD

**Issue by happyili** [brettwooldridge/HikariCP#401]
Through this is not recommended to use both setDataSourceClassName and setJdbcUrl but I found the error message is mis-leading (while I have sqlServerJdbcUrl to pointing to some other external ip)

    public void init(int minimum,int Maximum){
        HikariConfig config = new HikariConfig();
        config.setDataSourceClassName("com.microsoft.sqlserver.jdbc.SQLServerDataSource");
        config.setJdbcUrl(sqlServerJdbcUrl.get());
        config.setAutoCommit(true);
        config.setMinimumIdle(minimum);
        config.setMaximumPoolSize(Maximum);
        config.setInitializationFailFast(true);

        ds = new HikariDataSource(config);
    }

Error:
Exception in thread "main" com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)

**Comment by happyili** [comment]
So after removing the line    config.setDataSourceClassName("com.microsoft.sqlserver.jdbc.SQLServerDataSource").  Everything runs ok.

**Comment by javajack** [comment]
This issue still persists or what ?

I feel a meaningful error message should be shown , right at the beginning that both data-source and jdbc url properties are set.

**Comment by dcheckoway** [comment]
This issue definitely does still persist in `2.6.1`.
