### ISSUE TITLE
Connecting Redshift fails.

### ISSUE THREAD

**Issue by saubhagyab** [brettwooldridge/HikariCP#409]
Hi @brettwooldridge 

I am trying the following configuration in my hibernate.cfg.xml 

<property name="connection.driver_class">com.amazon.redshift.jdbc41.Driver</property>
        <property name="connection.url">jdbc:redshift://host:5439/databasename</property>
        <property name="connection.username">username</property>
        <property name="connection.password">password</property>
        <property name="hibernate.connection.provider_class">com.zaxxer.hikari.hibernate.HikariConnectionProvider</property>
        <property name="hibernate.hikari.dataSourceClassName">com.amazon.redshift.jdbc41.DataSource</property>
        <property name="hibernate.hikari.minimumIdle">5</property>
        <property name="hibernate.hikari.maximumPoolSize">10</property>
        <property name="hibernate.hikari.idleTimeout">30000</property> 

But it gives me Null pointer 

java.lang.NullPointerException: null
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:244) ~[stormjar.jar:na]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111) ~[stormjar.jar:na]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234) ~[stormjar.jar:na]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206) ~[stormjar.jar:na]
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887) ~[stormjar.jar:na]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845) ~[stormjar.jar:na]

Can you please help me out of this I think I have done something wrong in the configuration ?

Thanks

**Comment by brettwooldridge** [comment]
I don't see HikariCP in this stacktrace, I suspect a misconfiguration elsewhere.  However, you do not need both the *driverClassName* and *jdbcUrl* **and** *dataSourceClassName*.  Likely, the driver class and JDBC url are all you need, get rid of the dataSourceClassName.
