### ISSUE TITLE
Postgres and Log4J2

### ISSUE THREAD

**Issue by MeMyselfI** [brettwooldridge/HikariCP#411]
Hi. 

I try to combine Log4J2 and Hikari but I do get this exception with the newest JDBC driver:

Caused by: java.sql.SQLFeatureNotSupportedException: Die Methode org.postgresql.jdbc4.Jdbc4PreparedStatement.setNString(int, String) ist noch nicht implementiert.
	at org.postgresql.Driver.notImplemented(Driver.java:670)
	at org.postgresql.jdbc4.AbstractJdbc4Statement.setNString(AbstractJdbc4Statement.java:101)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.setNString(HikariPreparedStatementProxy.java)
	at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.writeInternal(JdbcDatabaseManager.java:110)
	... 12 more

What can I do?

**Comment by MeMyselfI** [comment]
Sorry, it's more a problem of Log4J. Found this solution: http://stackoverflow.com/questions/24242137/log4j2-jdbc-appender-issuefailed-to-insert-record

Can be closed.
