### ISSUE TITLE
Code requires Java 8 instead of the documented Java 7

### ISSUE THREAD

**Issue by daniel-anjos-zeroturnaround** [brettwooldridge/HikariCP#471]
Although it's written on the main page (under requirements): ⇒ Java 7 and above, once I start my Play 2.3.8 application with HikariCP 2.3.7 and HikariCP Plugin for Play 2.3.x v.2.0.5 with Java 7 I get the following error:

    Caused by: java.lang.UnsupportedClassVersionError: com/zaxxer/hikari/HikariConfig : Unsupported major.minor version 52.0

Please clarify if HikariCP supports only Java 8 (and update the documentation) or it should support Java 7 (and fix the release bundles accordingly). I have checked the code and 

Full startup error log below:

````
Play server process ID is 24679
[08:52:20.076] [info] [application] [main] - Creating Pool for datasource 'default'
Oops, cannot start the server.
@6o0aaicfb: Cannot load plugin
	at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:154)
	at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:130)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.WithDefaultPlugins$$anonfun$plugins$1.apply(Application.scala:130)
	at play.api.WithDefaultPlugins$$anonfun$plugins$1.apply(Application.scala:166)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.WithDefaultPlugins$class.plugins(Application.scala:128)
	at play.api.DefaultApplication.plugins$lzycompute(Application.scala:402)
	at play.api.DefaultApplication.plugins(Application.scala:402)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.UnsupportedClassVersionError: com/zaxxer/hikari/HikariConfig : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.edulify.play.hikaricp.HikariCPConfig$.toHikariConfig(HikariCPConfig.scala:25)
	at com.edulify.play.hikaricp.HikariCPDBApi$$anonfun$2$$anonfun$3.apply(HikariCPDBApi.scala:49)
	at com.edulify.play.hikaricp.HikariCPDBApi$$anonfun$2$$anonfun$3.apply(HikariCPDBApi.scala:46)
	at scala.util.Try$.apply(Try.scala:161)
	at com.edulify.play.hikaricp.HikariCPDBApi$$anonfun$2.apply(HikariCPDBApi.scala:46)
	at com.edulify.play.hikaricp.HikariCPDBApi$$anonfun$2.apply(HikariCPDBApi.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:93)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at com.edulify.play.hikaricp.HikariCPDBApi.<init>(HikariCPDBApi.scala:44)
	at com.edulify.play.hikaricp.HikariCPPlugin.<init>(HikariCPPlugin.scala:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:132)
	... 24 more````

**Comment by brettwooldridge** [comment]
This is fixed in 2.3.12.
