### ISSUE TITLE
com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Communications link failure

### ISSUE THREAD

**Issue by dolphineor** [brettwooldridge/HikariCP#474]
Hi brettwooldridge, I'm using HikariCP as MySQL'dataSource with Spring Boot recently, but found some problems.
This is my hikari config in application.yml:

```
hikari:
    poolName: HikariCP
    minimumIdle: 5
    maximumPoolSize: 25
    connectionTimeout: 30000
    idleTimeout: 30000
    connectionTestQuery: SELECT 1
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    dataSourceProperties:
        url: jdbc:mysql://127.0.0.1:13206/reactive?characterEncoding=UTF-8
        user: test
        password: test1234
        ## Only for mysql
        cachePrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048
```
And the corresponding Java Bean is:
```
/**
 * provide url, user, password by calling addDataSourceProperty method
 */
@Bean
    public DataSource dataSource() {
        HikariConfig configuration = new HikariConfig();
        configuration.setPoolName(poolName);
        configuration.setMinimumIdle(minimumIdle);
        configuration.setMaximumPoolSize(maximumPoolSize);
        configuration.setConnectionTimeout(connectionTimeout);
        configuration.setIdleTimeout(idleTimeout);
        configuration.setConnectionTestQuery(connectionTestQuery);
        configuration.setDataSourceClassName(dataSourceClassName);

        configuration.addDataSourceProperty("url", url);
        configuration.addDataSourceProperty("user", user);
        configuration.addDataSourceProperty("password", password);
        configuration.addDataSourceProperty("cachePrepStmts", cachePrepStmts);
        configuration.addDataSourceProperty("prepStmtCacheSize", prepStmtCacheSize);
        configuration.addDataSourceProperty("prepStmtCacheSqlLimit", prepStmtCacheSqlLimit);

        return new HikariDataSource(configuration);
    }
```
In this case, the connection pool works fine. When I use other configuration, exception occurred, as following:
```
hikari:
    poolName: HikariCP
    jdbcUrl: jdbc:mysql://127.0.0.1:13206/reactive?characterEncoding=UTF-8
    username: test
    password: test1234
    minimumIdle: 5
    maximumPoolSize: 25
    connectionTimeout: 30000
    idleTimeout: 30000
    connectionTestQuery: SELECT 1
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    dataSourceProperties:
        ## Only for mysql
        cachePrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048

/**
 * provide jdbcUrl, username, password instead of calling addDataSourceProperty method
 */
@Bean
    public DataSource dataSource() {
        HikariConfig configuration = new HikariConfig();
        configuration.setPoolName(poolName);
        configuration.setJdbcUrl(jdbcUrl);
        configuration.setUsername(username);
        configuration.setPassword(password);
        configuration.setMinimumIdle(minimumIdle);
        configuration.setMaximumPoolSize(maximumPoolSize);
        configuration.setConnectionTimeout(connectionTimeout);
        configuration.setIdleTimeout(idleTimeout);
        configuration.setConnectionTestQuery(connectionTestQuery);
        configuration.setDataSourceClassName(dataSourceClassName);

        configuration.addDataSourceProperty("cachePrepStmts", cachePrepStmts);
        configuration.addDataSourceProperty("prepStmtCacheSize", prepStmtCacheSize);
        configuration.addDataSourceProperty("prepStmtCacheSqlLimit", prepStmtCacheSqlLimit);

        return new HikariDataSource(configuration);
    }
```
The **exception** information is:
```
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 30 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/github/dolphineor/springboot/configure/JpaConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 32 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 44 more
Caused by: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at com.github.dolphineor.springboot.configure.JpaConfig.dataSource(JpaConfig.java:80)
	at com.github.dolphineor.springboot.configure.JpaConfig$$EnhancerBySpringCGLIB$$20918aa0.CGLIB$dataSource$1(<generated>)
	at com.github.dolphineor.springboot.configure.JpaConfig$$EnhancerBySpringCGLIB$$20918aa0$$FastClassBySpringCGLIB$$cf46bcfb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
	at com.github.dolphineor.springboot.configure.JpaConfig$$EnhancerBySpringCGLIB$$20918aa0.dataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 45 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:422)
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:134)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	... 58 more
Caused by: java.net.ConnectException: connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
	... 74 more
```

The network's solution is setting MySQL's wait_timeout and interactive_timeout, but it doesn't work.

dolphineor.

**Comment by brettwooldridge** [comment]
@dolphineor In the second case, you don't need:
```
dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
```
The ``jdbcUrl`` entry alone is sufficient.  If you get a driver not found error, you can add ``driverClassName``, but it shouldn't be necessary.

**Comment by dolphineor** [comment]
^_^Thanks a lot, it works.
