### ISSUE TITLE
Spring JdbcTemplate batch update causing leak detection trigger

### ISSUE THREAD

**Issue by tim-oe** [brettwooldridge/HikariCP#475]
using mysql and Spring jdbc template the line is triggering the error is in spring code
		Connection con = dataSource.getConnection();

2015-10-28 15:20:00,209 [Hikari Housekeeping Timer (pool oeDatabase)] 
WARN  com.zaxxer.hikari.util.LeakTask- Connection leak detection triggered, stack trace follows
java.lang.Exception
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:615)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658)
        at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:946)
        at com.outboundengine.dba.base.BaseEntity.batchUpdate(BaseEntity.java:184)

**Comment by brettwooldridge** [comment]
You might try asking this on the Spring forum or stackoverflow.  It looks like someone isn't closing the connection -- or the connection is in use for longer than the leak detection threshold.  Either it is a real leak, or you need to extend the leakDetectionThreshold to a longer period.

**Comment by tim-oe** [comment]
ok thanks

On Sat, Oct 31, 2015 at 10:58 PM, Brett Wooldridge <notifications@github.com
