### ISSUE TITLE
Tomcat JNDI Configuration

### ISSUE THREAD

**Issue by wesoos** [brettwooldridge/HikariCP#486]
Hi, I'm trying to set this up using jndi, but getting an error on startup.  Here is my configuration in context.xml

<Resource name="jdbc/name" 
        auth="Container" 
	factory="com.zaxxer.hikari.HikariJNDIFactory" 
        type="javax.sql.DataSource" 
        maximumPoolSize="10"
        connectionTimeout="300000"
        dataSourceClassName="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"
        dataSource.url="jdbc:mysql://host:port/database?useUnicode=true&amp;characterEncoding=UTF-8&amp;useOldAliasMetadataBehavior=true"
        dataSource.user="root" 
        dataSource.password="password" 
	dataSource.implicitCachingEnabled="true"
/>

And here is the stack trace

WARNING: Unexpected exception resolving reference
java.lang.RuntimeException: java.beans.IntrospectionException: Method not found: setImplicitCachingEnabled
        at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:141)
        at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:64)
        at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:154)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
        at com.zaxxer.hikari.HikariJNDIFactory.createDataSource(HikariJNDIFactory.java:76)
        at com.zaxxer.hikari.HikariJNDIFactory.getObjectInstance(HikariJNDIFactory.java:67)
        at org.apache.naming.factory.ResourceFactory.getObjectInstance(ResourceFactory.java:143)
        at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:843)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:154)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:831)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:168)
        at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1061)
        at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:671)
        at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:270)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5161)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1099)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1621)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.beans.IntrospectionException: Method not found: setImplicitCachingEnabled
        at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:110)
        at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:132)
        ... 29 more

**Comment by brettwooldridge** [comment]
@wesoos Try the latest version of HikariCP.  The use of ``java.beans`` was removed several releases ago.
