### ISSUE TITLE
hikaricp too slow with enterprise db  (postgres)

### ISSUE THREAD

**Issue by abhishekparwal** [brettwooldridge/HikariCP#507]
Below is the stack trace, it takes 10 mins to initialize hikari cp with enterprise db (postgres)

It is executing getTypeInfo() method of AbstractJdbc2Statement and is in while loop

while (rs.next())
{
....
tuple[1] = connection.encodeString(Integer.toString(connection.getTypeInfo().getSQLType(typname)));
....
}

 select version();
                                                      version                                                      
-------------------------------------------------------------------------------------------------------------------
 EnterpriseDB 9.2.1.3 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-52), 64-bit

I use 2.4.1 of hikari cp. 2.4.2 seems broken with enterprise db , It gives exceptions.

postgres driver used: 

<dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
  <version>9.4-1205-jdbc42</version>
</dependency>

"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	  at java.net.SocketInputStream.read(SocketInputStream.java:170)
	  at java.net.SocketInputStream.read(SocketInputStream.java:141)
	  at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
	  at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
	  at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:71)
	  at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:282)
	  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1718)
	  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	  - locked <0x1c7e> (a org.postgresql.core.v3.QueryExecutorImpl)
	  at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:616)
	  at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:466)
	  at org.postgresql.jdbc2.TypeInfoCache.getSQLType(TypeInfoCache.java:229)
	  - locked <0x1c80> (a org.postgresql.jdbc2.TypeInfoCache)
	  at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getTypeInfo(AbstractJdbc2DatabaseMetaData.java:3995)
	  at org.hibernate.engine.jdbc.spi.TypeInfo.extractTypeInfo(TypeInfo.java:84)
	  at org.hibernate.engine.jdbc.env.internal.ExtractedDatabaseMetaDataImpl$Builder.apply(ExtractedDatabaseMetaDataImpl.java:194)
	  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.<init>(JdbcEnvironmentImpl.java:209)
	  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:114)
	  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	  at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	  at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
	  at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
	  at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	  at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	  at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	  at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217)
	  at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	  at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
	  at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
	  at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:770)
	  at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:797)
	  at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
	  at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	  at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
	  at com.google.inject.persist.jpa.JpaPersistService.start(JpaPersistService.java:110)

**Comment by nitincchauhan** [comment]
@abhishekparwal 
'I use 2.4.1 of hikari cp. 2.4.2 seems broken with enterprise db , It gives exceptions.'
2.4.1 works OK but 2.4.2 takes 10 mins and throws exception?
Also If you can pls post log from start till exception setting hikari package to debug level

**Comment by brettwooldridge** [comment]
@abhishekparwal ``com.zaxxxer.hikari`` is not in that stacktrace at all.  I would expect to see HikariCP classes between these two in the stacktrace:
```
at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getTypeInfo(AbstractJdbc2DatabaseMetaData.java:3995)
at org.hibernate.engine.jdbc.spi.TypeInfo.extractTypeInfo(TypeInfo.java:84)
```
To me this indicates that Hibernate is not configured to use HikariCP at all.

**Comment by brettwooldridge** [comment]
The stack trace above appears to indicate blocking at the driver-level, not within HikariCP.  Can you please enable DEBUG level logging, and post the output?

**Comment by abhishekparwal** [comment]
it was because of hibernate trying to load the metadata http://stackoverflow.com/questions/10075081/hibernate-slow-to-acquire-postgres-connection.

**Comment by nitincchauhan** [comment]
@abhishekparwal I assume it was taking same time with hikjaricp 2.4.1 and 2.4.2. Hope solution from SO worked for you and Thanks for reporting back.
