### ISSUE TITLE
HikariCP throws exceptions when multiple threads try to get and update at the same time

### ISSUE THREAD

**Issue by kewangie** [brettwooldridge/HikariCP#509]
the code:
Order order = this.hibernateTemplate.get(Order.class, id);
order.setDescription(String.valueOf(System.currentTimeMillis()));
this.hibernateTemplate.update(order);

if you run the above code in multiple threads, you probably will get the following exception:
and this is not happening for org.apache.commons.dbcp2.BasicDataSource

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_05]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_05]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:384) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:463) ~[mysql-connector-java-5.1.30.jar:na]
	at com.mysql.jdbc.StatementImpl.getMaxRows(StatementImpl.java:2155) ~[mysql-connector-java-5.1.30.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.getMaxRows(HikariProxyPreparedStatement.java) [HikariCP-2.4.2.jar:na]
	at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.close(ResourceRegistryStandardImpl.java:154) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.release(ResourceRegistryStandardImpl.java:82) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.releaseStatements(AbstractBatchImpl.java:157) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.release(AbstractBatchImpl.java:195) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.close(JdbcCoordinatorImpl.java:190) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.hibernate.internal.SessionImpl.close(SessionImpl.java:420) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
	at org.springframework.orm.hibernate5.SessionFactoryUtils.closeSession(SessionFactoryUtils.java:122) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCleanupAfterCompletion(HibernateTransactionManager.java:668) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1016) [spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:811) [spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730) [spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485) [spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291) [spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) [spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at com.ke.db.hibernate.repo.OrderDao$$EnhancerBySpringCGLIB$$55c00ebb.readAndUpdate(<generated>) [spring-core-4.2.2.RELEASE.jar:na]
	at com.ke.db.hibernate.KeDbMain$1.run(KeDbMain.java:22) [bin/:na]
Exception in thread "Thread-1" org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:206)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:741)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:589)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.ke.db.hibernate.repo.OrderDao$$EnhancerBySpringCGLIB$$55c00ebb.readAndUpdate(<generated>)
	at com.ke.db.hibernate.KeDbMain$1.run(KeDbMain.java:22)
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3069)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2948)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3328)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:447)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:333)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:335)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1224)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:464)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2894)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2270)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:485)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:146)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:230)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:581)
	... 9 more

**Comment by brettwooldridge** [comment]
This is because dbcp is not tracking Statements and closing them when the connection is closed (in violation of the JDBC specification).  I suspect if you run the same code without any pool, just a bare MySQL DataSource, you will get the same exception.

**Comment by kewangie** [comment]
Cool. I was just wondering how HikariCP handles multi threading in this case?

**Comment by brettwooldridge** [comment]
@kewangie It is generally a bad idea to access a single Connection from multiple threads at the same time.  The JDBC specification used to allow it, but it was removed, and it not reliable on many drivers.  HikariCP *should* work, but also makes no guarantees.
