### ISSUE TITLE
2.4.3 error using hsqldb

### ISSUE THREAD

**Issue by debop** [brettwooldridge/HikariCP#527]
using HikariCP 2.4.3, 2.4.2  (not 2.4.1)

hsqldb connection error like this (other database all success)

2015-12-23 01:30:46,179 DEBUG [ol HikariPool-5)] com.zaxxer.hikari.pool.HikariPool.createPoolEntry: HikariPool-5 - Cannot acquire connection from data source
java.sql.SQLSyntaxErrorException: unexpected token: ;
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.3.jar:2.3.3]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.3.jar:2.3.3]
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[hsqldb-2.3.3.jar:2.3.3]
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source) ~[hsqldb-2.3.3.jar:2.3.3]
	at com.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:467) ~[HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.checkValidationMode(PoolBase.java:377) ~[HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:336) ~[HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:315) ~[HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171) ~[HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:441) [HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.access$300(HikariPool.java:66) [HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:576) [HikariCP-2.4.2.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:569) [HikariCP-2.4.2.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by brettwooldridge** [comment]
@debop HikariCP did not used to test validation queries during startup, now it does.  It looks like your ``connectionTestQuery`` contains an unnecessary trailing semi-colon.  Remove it and the error should go away.
