### ISSUE TITLE
Exception during pool initialization

### ISSUE THREAD

**Issue by devpuck001** [brettwooldridge/HikariCP#535]
I use the example code like this
HikariConfig config = new HikariConfig();
config.setJdbcUrl("jdbc:mysql://localhost:3306/mytest");
config.setUsername("mytest");
config.setPassword("mytest");
config.addDataSourceProperty("cachePrepStmts", "true");
config.addDataSourceProperty("prepStmtCacheSize", "250");
config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");

HikariDataSource ds = new HikariDataSource(config);

but I went the exception:
6 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-0 - is starting.
306 [main] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-0 - is closing down.
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: You need to run the CLI build and you need target/classes in your classpath to run.
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
	at com.test.Mytest.main(Mytest.java:19)
Caused by: java.lang.IllegalStateException: You need to run the CLI build and you need target/classes in your classpath to run.
	at com.zaxxer.hikari.pool.ProxyFactory.getProxyConnection(ProxyFactory.java:54)
	at com.zaxxer.hikari.pool.PoolEntry.createProxyConnection(PoolEntry.java:99)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:177)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510)
	... 3 more

Who can help me?

**Comment by brettwooldridge** [comment]
That is a very strange error only seen during development builds from an IDE.  Where did you get the HikariCP jar file?  It should contain the following class files:
```
com/zaxxer/hikari/pool/HikariProxyCallableStatement.class
com/zaxxer/hikari/pool/HikariProxyConnection.class
com/zaxxer/hikari/pool/HikariProxyPreparedStatement.class
com/zaxxer/hikari/pool/HikariProxyResultSet.class
com/zaxxer/hikari/pool/HikariProxyStatement.class
```
Does it?

**Comment by devpuck001** [comment]
I use the source code from github https://github.com/brettwooldridge/HikariCP, and where to download the HikariCP jar file?

**Comment by slyoldfox** [comment]
@devpuck001 It's best if you use a maven dependency in your project, but if you want to stick to a jar, download it on http://mvnrepository.com/artifact/com.zaxxer/HikariCP/2.4.3 for example

**Comment by brettwooldridge** [comment]
@devpuck001 If you're building from source, you need to use maven and not your IDE to build it.  This is because there is some code-generation involved that is not invoked by the IDE build.

Running:
```
mvn clean package
```
will leave a jar file in the *"target"* directory.  That should be a functional jar.

**Comment by devpuck001** [comment]
Thanks

**Comment by arjenzhou** [comment]
> @devpuck001 If you're building from source, you need to use maven and not your IDE to build it. This is because there is some code-generation involved that is not invoked by the IDE build.
> 
> Running:
> 
> ```
> mvn clean package
> ```
> 
> will leave a jar file in the _"target"_ directory. That should be a functional jar.

Hi, I am running tests under com.zaxxer.hikari.db.BasicPoolTest, and encounter the same situation.

**Comment by arjenzhou** [comment]
It works, sry.
