### ISSUE TITLE
Connection.setNetworkTimeout() is not supported (Redshift)

### ISSUE THREAD

**Issue by vmorales** [brettwooldridge/HikariCP#557]
Hello Brett.

Is there a config to avoid making this call?  Its preventing Hikari from init'ing a data source to a Redshift backend.  We're using HikariCP 2.4.0.

Thanks.

```
2016-01-25 21:19:59.124  INFO 1653 [WrapperJarAppMain] --- com.zaxxer.hikari.HikariDataSource       : Hikari pool HikariPool-7 is starting.
2016-01-25 21:19:59.202 DEBUG 1653 [WrapperJarAppMain] --- com.zaxxer.hikari.pool.PoolElf           : HikariPool-7 - Connection.setNetworkTimeout() is not supported ([Amazon][JDBC](10220) Driver not capable.)
2016-01-25 21:19:59.215 DEBUG 1653 [WrapperJarAppMain] --- com.zaxxer.hikari.pool.HikariPool        : HikariPool-7 - Connection attempt to database failed

java.sql.SQLException: [JDBC Driver]String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at com.amazon.redshift.core.PGJDBCConnection.toNativeSQL(Unknown Source)
        at com.amazon.jdbc.common.SConnection.nativeSQL(Unknown Source)
        at com.amazon.jdbc.common.SStatement.executeNoParams(Unknown Source)
        at com.amazon.jdbc.common.SStatement.execute(Unknown Source)
        at com.zaxxer.hikari.pool.PoolElf.executeSql(PoolElf.java:441)
        at com.zaxxer.hikari.pool.PoolElf.setupConnection(PoolElf.java:183)
        at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
        at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:564)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:150)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:124)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
        at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:845)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
```

**Comment by brettwooldridge** [comment]
Which call?  The redshift driver is failing in *Statement.execute()*.  HikariCP is calling this because your configuration defines *connectionInitSql* .  Whatever that SQL is, it appears to be causing the problem.

**Comment by vmorales** [comment]
Brett....thank you SO much.  That was it.  Things are working awesomely.

**Comment by Danilo-Araujo-Silva** [comment]
I'm having the same problem. Can you share how did you solve it?
