### ISSUE TITLE
Connections blocks randomly after several interations

### ISSUE THREAD

**Issue by danjee** [brettwooldridge/HikariCP#565]
A simple jdbc call blocks connections to mysql after a few iterations with mysql.
Database properties are:

- 'innodb_version', '5.5.46'
- 'protocol_version', '10'
- 'slave_type_conversions', ''
- 'version', '5.5.46-0ubuntu0.14.04.2'
- 'version_comment', '(Ubuntu)'
- 'version_compile_machine', 'x86_64'
- 'version_compile_os', 'debian-linux-gnu'

```java
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

public class HikariCPTest {

	public void test(){
		String sql = "select * from USERS";
		try(Connection con = getConnection(); Statement stm = con.createStatement(); ResultSet rs = stm.executeQuery(sql)){
			if (rs.next()){ //first record
 				String username = rs.getString("USERNAME");
				System.out.println(username);
			}
		}catch(Exception e){
			e.printStackTrace();
		}
	}

	
	public static void main(String[] args) {
		HikariCPTest dw = new HikariCPTest();
		for (int i = 0; i < 100; i++){
			dw.test();
		}
	}
	
	private Connection getConnection() throws SQLException{
	return getDatasource().getConnection();
}
	
	private DataSource getDatasource() {
		HikariConfig config = new HikariConfig();
		config.setJdbcUrl("jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8");
		config.setUsername("myuser");
		config.setPassword("mysecret");
		config.setMaximumPoolSize(20);
		config.setMinimumIdle(5);
		config.setIdleTimeout(2 * 60 * 1000);
		HikariDataSource ds = new HikariDataSource(config);
		return ds;
	}
}
```
After a a few iterations I get this error

```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-30 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
	at ro.sok.scraper.jobescu.DatabaseWriter.getDatasource(DatabaseWriter.java:72)
	at ro.sok.scraper.jobescu.DatabaseWriter.getConnection(DatabaseWriter.java:61)
	at ro.sok.scraper.jobescu.DatabaseWriter.test(DatabaseWriter.java:37)
	at ro.sok.scraper.jobescu.DatabaseWriter.main(DatabaseWriter.java:51)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-30 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510)
	... 6 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1038)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2255)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by danjee** [comment]
Stupid mistake and instantiate the datasource multiple times
