### ISSUE TITLE
Issues after upgrading connection pool to HikariCP

### ISSUE THREAD

**Issue by jddipqd** [brettwooldridge/HikariCP#578]
I was using a very old version of Apache Commons DBCP (1.2.2) together with mariadb-java-client (1.1.1). I tried upgrading them to HikariCP 2.3.4 and mariadb-java-client 1.3.4, however I was plagued with DB instability.
In the application logs there were lots of:
```
[WARN ] com.zaxxer.hikari.proxy.ConnectionProxy - Connection org.mariadb.jdbc.MariaDbConnection@1edbfe9 (HikariPool-0) marked as broken because of SQLSTATE(08), ErrorCode(-1).
java.sql.SQLNonTransientConnectionException: Could not send query: Last stream not finished
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
        at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:261)
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:290)
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:344)
        at org.mariadb.jdbc.MariaDbConnection.rollback(MariaDbConnection.java:532)
        at com.zaxxer.hikari.proxy.ConnectionProxy.rollback(ConnectionProxy.java:313)
        at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.rollback(ConnectionJavassistProxy.java)
```

After rolling back to previous driver and connection pool, everything returned to normal. 
Any ideas on what might have caused the issue and how to resolve it?

Not sure if i's related, but my transaction isolation is read uncommitted (set at connection pool level using transactionIsolation="TRANSACTION_READ_UNCOMMITTED")
However, it is also read uncommitted when using commons dbcp.

**Comment by nitincchauhan** [comment]
this is because dbcp and hikaricp both have different defaults for options and your configuration.
I hope quick read of the options for both pools will reveal lot more than fix.

**Comment by brettwooldridge** [comment]
@jddipqd This is most likely caused by having MariaDB's ``wait_timeout`` set shorter than HikariCP's ``maxLifetime``.  If you don't want to, or can't, change the MariaDB configuration, you can set HikariCP's ``maxLifetime`` to a shorter interval, for example 10 minutes (``maxLifetime=600000``).
