### ISSUE TITLE
Strange pool behavior

### ISSUE THREAD

**Issue by doom369** [brettwooldridge/HikariCP#585]
Hello. I'm using Hikari for a while and found some strange behaviour I can't explain.

Pool creation :

```
Java 1.8_40
<postgresql.version>9.4.1207.jre7</postgresql.version>
<HikariCP.version>2.4.3</HikariCP.version>
```

```
dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
dataSource.serverName=x.x.x.x
dataSource.portNumber=5432
dataSource.databaseName=test
dataSource.user=test
dataSource.password=test
```
   
```
HikariConfig config = new HikariConfig(serverProperties);
config.setAutoCommit(false);
config.setConnectionTimeout(15000);
config.setMaximumPoolSize(2);
config.setLeakDetectionThreshold(30000);
HikariDataSource ds = new HikariDataSource(config);
```

Once a minute I call `saveUsers` method

```
    public void saveUsers(List<User> users) {
        try (Connection connection = getConnection();
             PreparedStatement ps = connection.prepareStatement(upsertUser)) {

            for (User user : users) {
                ps.setString(1, user.name);
                ps.setString(2, user.toString());
                ps.addBatch();
            }

            ps.executeBatch();
            connection.commit();
        } catch (Exception e) {
            log.error("Error upserting users in DB.", e);
        }
    }

    public Connection getConnection() throws Exception {
        return ds.getConnection();
    }
```

Everything works fine for a while.

But at some point I get

```
java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 15002ms.
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
```

My code continue to work. But after a while I'm getting again :

```
java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 939707ms.
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
```

What I do not understand is where `939707ms` comes from? It's like 15 minutes... I don't see anywhere such settings. Could you please advice?

**Comment by nitincchauhan** [comment]
few questions:
saveUsers() is called by multiple threads?
what is batch size of connection and in postgresql?
please set log level for hikaricp to debug to trace issue

**Comment by doom369** [comment]
> saveUsers() is called by multiple threads?

Yes. I have 2 threads. One calls saveUsers, another similar query to another table.

> what is batch size of connection and in postgresql?

I don't know. I don't set it anywhere explicitly. Also I didn't find nothing like that in [postgres JDBC properties](https://jdbc.postgresql.org/documentation/head/connect.html).

**Comment by nitincchauhan** [comment]
please time 'another similar query to another table.' as well.
only debug logs would shed more light :) everything else would be guess work.

**Comment by doom369** [comment]
```
    public void insertReporting(Map<AggregationKey, AggregationValue> map, GraphType graphType) {
        String insertSQL = getSQL(graphType);

        try (Connection connection = getConnection();
             PreparedStatement ps = connection.prepareStatement(insertSQL)) {

            for (Map.Entry<AggregationKey, AggregationValue> entry : map.entrySet()) {
                prepareReportingInsert(ps, entry, graphType);
                ps.addBatch();
            }

            ps.executeBatch();
            connection.commit();
        } catch (Exception e) {
           log.error("Error inserting reporting data in DB.", e);
        }
    }

    private static void prepareReportingInsert(PreparedStatement ps,
                                              Map.Entry<AggregationKey, AggregationValue> entry,
                                              GraphType type) throws SQLException {
        final AggregationKey key = entry.getKey();
        final AggregationValue value = entry.getValue();
        prepareReportingInsert(ps, key.username, key.dashId, key.pin, key.pinType, key.ts * type.period, value.calcAverage());
    }

    public static void prepareReportingInsert(PreparedStatement ps,
                                              String username,
                                              int dashId,
                                              byte pin,
                                              PinType pinType,
                                              long ts,
                                              double value) throws SQLException {
        ps.setString(1, username);
        ps.setInt(2, dashId);
        ps.setByte(3, pin);
        ps.setString(4, pinType.pinTypeString);
        ps.setLong(5, ts);
        ps.setDouble(6, value);
    }
```

I already started test with debug info. will update you with more info when issue will be reproduced.

**Comment by doom369** [comment]
I found https://github.com/brettwooldridge/HikariCP/issues/326 - it is totaslly corresponds to situation I have. I'll close this one will post more details in those thread when I'll have more info.
