### ISSUE TITLE
java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String error when using HikariCP with certain third party libraries

### ISSUE THREAD

**Issue by TomiTakussaari** [brettwooldridge/HikariCP#594]
Hi

2.4.4 introduced feature that generates unique poolIds by storing AtomicInteger in System.getProperties.

While nice feature, this broke some of our applications that used libraries that expected all system properties to be Strings, such as Typesafe Config and Ivy.

Not sure how it could be fixed while keeping this functionality, I would create PR if i had any ideas..

```
java.lang.ClassCastException: java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String
	at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:589)
	at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:583)
	at org.apache.ivy.core.settings.IvySettings.addSystemProperties(IvySettings.java:303)
	at org.apache.ivy.core.settings.IvySettings.<init>(IvySettings.java:298)
	at org.apache.ivy.core.settings.IvySettings.<init>(IvySettings.java:218)
	at sbt.IvySbt.sbt$IvySbt$$settings$lzycompute(Ivy.scala:71)
	at sbt.IvySbt.sbt$IvySbt$$settings(Ivy.scala:69)
	at sbt.IvySbt.ivyLockFile$lzycompute(Ivy.scala:119)
	at sbt.IvySbt.ivyLockFile(Ivy.scala:119)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.makePom(IvyActions.scala:94)
	at sbt.Classpaths$$anonfun$36.apply(Defaults.scala:1059)
	at sbt.Classpaths$$anonfun$36.apply(Defaults.scala:1059)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
Caused by: java.lang.ExceptionInInitializerError: null
	at com.typesafe.config.impl.ConfigImpl.systemPropertiesAsConfigObject(ConfigImpl.java:315) ~[na:na]
	at com.typesafe.config.impl.ConfigImpl.systemPropertiesAsConfig(ConfigImpl.java:323) ~[na:na]
	at com.typesafe.config.ConfigFactory.systemProperties(ConfigFactory.java:497) ~[na:na]
	at com.typesafe.config.ConfigFactory.defaultOverrides(ConfigFactory.java:422) ~[na:na]
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:184) ~[na:na]
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:113) ~[na:na]
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:74) ~[na:na]
        at <some of our code>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_71]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_71]
	at <some of our code> 	
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_71]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_71]
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2454) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:1939) ~[jetty-webapp-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1894) ~[jetty-webapp-9.3.7.v20160115.jar:9.3.7.v20160115]
	... 31 common frames omitted
Caused by: java.lang.ClassCastException: java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String
	at com.typesafe.config.impl.PropertiesParser.fromPathMap(PropertiesParser.java:145) ~[na:na]
	at com.typesafe.config.impl.PropertiesParser.fromProperties(PropertiesParser.java:67) ~[na:na]
	at com.typesafe.config.impl.Parseable$ParseableProperties.rawParseValue(Parseable.java:717) ~[na:na]
	at com.typesafe.config.impl.Parseable$ParseableProperties.rawParseValue(Parseable.java:699) ~[na:na]
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176) ~[na:na]
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170) ~[na:na]
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:227) ~[na:na]
	at com.typesafe.config.impl.ConfigImpl.loadSystemProperties(ConfigImpl.java:304) ~[na:na]
	at com.typesafe.config.impl.ConfigImpl.access$000(ConfigImpl.java:27) ~[na:na]
	at com.typesafe.config.impl.ConfigImpl$SystemPropertiesHolder.<clinit>(ConfigImpl.java:310) ~[na:na]
```

**Comment by TomiTakussaari** [comment]
Typesafe config >= 1.2.1 seems to support non-String values in System properties, but that still leaves atleast sbt/ivy and possibly other libraries that are not that easily upgraded even if new versions would support this..

**Comment by brettwooldridge** [comment]
@TomiTakussaari Thanks for this feedback.  We'll look into how we can address it.  Likely we can store the value as a String, and convert as needed.

**Comment by thesamet** [comment]
We have started to get this problem in SBT after upgrading to 2.4.4 today. After every run, we need to restart SBT due to this exception.

**Comment by brettwooldridge** [comment]
@thesamet @TomiTakussaari You will need to downgrade to 2.3.3 until 2.4.5 is released, or run from a local build of HikariCP.

I *would* like to ask a favor.  Please subscribe to the Google group, we announced two release candidates over the period of a month and could have easily caught this if developers like you had picked it up.

**Comment by brettwooldridge** [comment]
HikariCP 2.4.5 was been released with a fix for this issue.

**Comment by TomiTakussaari** [comment]
Thanks @brettwooldridge It seems to work fine

Will subscribe to Google group, but no exact promises about picking up problems early  :smile:
