### ISSUE TITLE
java.lang.UnsupportedOperationException: setLoginTimeout in Spring boot 1.3.3, Hibernate 4 and H2

### ISSUE THREAD

**Issue by abhiesa-tolexo** [brettwooldridge/HikariCP#613]
Spring class is not playing well with HikariCP

```java
  @Bean
  public DataSource primaryDataSource() {
    HikariDataSource hikariDataSource = new HikariDataSource();
    hikariDataSource.setDataSource(dataSource());
    hikariDataSource.setMaximumPoolSize(maximumPoolSize);
    hikariDataSource.setMaxLifetime(maxLifetime);
    hikariDataSource.setIdleTimeout(idleTimeout);
    hikariDataSource.setPoolName(poolName);
    hikariDataSource.setConnectionTimeout(connectionTimeout);
    return hikariDataSource;
  }

  private DataSource dataSource() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName(dbDriver);
    dataSource.setUrl(dbURL);
    dataSource.setUsername(dbUserName);
    dataSource.setPassword(dbPassword);

    Properties dsProps = new Properties();
    dsProps.put("prepStmtCacheSize", 250);
    dsProps.put("prepStmtCacheSqlLimit", 2048);
    dsProps.put("cachePrepStmts", Boolean.TRUE);
    dsProps.put("useServerPrepStmts", Boolean.TRUE);

    dataSource.setConnectionProperties(dsProps);
    return dataSource;
  }
```

```
java.lang.UnsupportedOperationException: setLoginTimeout
	at org.springframework.jdbc.datasource.AbstractDataSource.setLoginTimeout(AbstractDataSource.java:58) ~[spring-jdbc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.zaxxer.hikari.pool.PoolBase.setLoginTimeout(PoolBase.java:523) [HikariCP-2.4.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:300) [HikariCP-2.4.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:84) [HikariCP-2.4.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:102) [HikariCP-2.4.3.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) [HikariCP-2.4.3.jar:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:124) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857) [hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) [hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425) [hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849) [hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) [spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) [spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319) [spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:98) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	
```

**Comment by abhiesa-tolexo** [comment]
```
#Database Configuration
spring.datasource.driver-class-name = org.h2.Driver
spring.jpa.databasePlatform = org.hibernate.dialect.H2Dialect

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect

spring.jpa.show-sql = true
#create-drop
spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#jdbc:h2:mem:datajpa
spring.datasource.url = jdbc:h2:./target/test
spring.datasource.username = sa
spring.datasource.password = 
spring.datasource.poolName = SpringBootHikariCP
spring.datasource.maximumPoolSize = 5
spring.datasource.minimumIdle = 3
spring.datasource.maxLifetime = 2000000
#spring.datasource.connectionTimeout = 30000
#spring.datasource.idleTimeout = 30000
spring.datasource.pool-prepared-statements = true
spring.datasource.max-open-prepared-statements = 250

entitymanager.packagesToScan = model

spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1
spring.datasource.pool-prepared-statements=true
spring.datasource.max-open-prepared-statements=250
```

**Comment by brettwooldridge** [comment]
@abhiesa-tolexo An improved message is logged now (v2.4.6+)

**Comment by myxibrium** [comment]
I am using Hikari 2.4.6 and still getting this error.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception; nested exception is java.lang.UnsupportedOperationException: setLoginTimeout
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 84 more
Caused by: java.lang.UnsupportedOperationException: setLoginTimeout
	at org.springframework.jdbc.datasource.AbstractDataSource.setLoginTimeout(AbstractDataSource.java:58)
	at com.zaxxer.hikari.pool.PoolUtilities.setLoginTimeout(PoolUtilities.java:247)
	at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:170)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 86 more

**Comment by brettwooldridge** [comment]
Is there a specific reason that you require AbstractDataSource instead of using the driver DataSource directly?

**Comment by brettwooldridge** [comment]
The AbstractDataSource is not JDBC compliant.  The change made in 2.4.6 was to merely log a better message than before.

**Comment by myxibrium** [comment]
For some reason HikariCP-java6 was on my classpath and was causing this issue. The code was catching SQLException instead of Throwable, so this exception was not being caught. By excluding HikariCP-java6 it was using the correct classes and the issue no longer exists. Thanks.
