### ISSUE TITLE
Connection is not available

### ISSUE THREAD

**Issue by mohsinniveus** [brettwooldridge/HikariCP#628]
Hi,

We are facing this issue, where there is a load in the server.

Please let us know if you have any information to solve this issue.

The configuration is

jdbc.hikari.maximumPoolSize=100
jdbc.hikari.minimumIdle=20
jdbc.hikari.idleTimeout=30000
jdbc.hikari.maxLifetime=2000000
jdbc.hikari.connectionTimeout=30000
jdbc.hikari.prepStmtCacheSize=250
jdbc.hikari.prepStmtCacheSqlLimit=2048

We are using hibernate and spring in our application in every transaction we are 

                        session.flush();
		        session.clear();
			session.close();

Will this release the connection and connection is available afterwards.

2016-05-18 10:06:35 ERROR SqlExceptionHelper:129 - HikariCP - Connection is not available, request timed out after 30000ms.
2016-05-18 10:06:35 ERROR RestController:4820 - Exception while getting the configuration system 
org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:90)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:112)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1928)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1897)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1875)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2611)
	at org.hibernate.loader.Loader.doList(Loader.java:2594)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2423)
	at org.hibernate.loader.Loader.list(Loader.java:2418)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1268)

**Comment by brettwooldridge** [comment]
@mohsinniveus Can you enable debug logging for the package ``com.zaxxer.hikari`` (for whatever logging framework you use, log4j etc.), and also set the ``leakDetectionThreshold`` to something reasonable like 30 seconds or one minute.  Post the logs for the 2-3 minutes prior to this kind of failure here.

**Comment by mohsinniveus** [comment]
in my log4j properties i have enabled it debug for com.zaxxer.hikari package but logs are not coming, it is showing only info logs not the debug logs.

**Comment by mohsinniveus** [comment]
I think connection are not returning to the pool, Some times back i shifted to C3p0 connection pool, there i got too many connection exception.  There i was able to get the connection pool stats.

Then i put this property for hibernate

<prop key="hibernate.connection.release_mode">after_transaction</prop>

It worked, Is this will work for hikaricp as well,

**Comment by brettwooldridge** [comment]
@mohsinniveus There are many factors that affect which Hibernate connection release mode is best for an application, but if you experienced the same issue with c3p0 and "after_transaction" release mode seemed to fix it in that case, then I would say "yes" try it and see if it works.
