### ISSUE TITLE
sporadic broken connections

### ISSUE THREAD

**Issue by schmeic** [brettwooldridge/HikariCP#631]
Hi-

  I've been getting getting sporadic broken connections to MariaDb, but most of the time the same query works. It appears to be happening under fairly heavy load.  Here's the error I see:

2016-05-25 13:02:24 WARN  [c.zaxxer.hikari.pool.ProxyConnection]: HikariPool-0 - Connection org.mariadb.jdbc.MariaDbConnection@215ac0f5 marked as broken because of
 SQLSTATE(08), ErrorCode(-1)
java.sql.BatchUpdateException: Could not read resultset: unexpected end of stream, read 0 bytes from 4

And here is the relevant portion of the stack trace:

        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:378) ~[mariadb-java-client-1.4.4.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:342) ~[mariadb-java-client-1.4.4.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQuery(MariaDbServerPreparedStatement.java:323) ~[mariadb-java-client-1.4.4.jar:na]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-2.4.3.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) [HikariCP-2.4.3.jar:na]

And then a bit after this occurs, I see a line like this for every connection in the pool:

2016-05-25 13:03:22 DEBUG [com.zaxxer.hikari.pool.PoolBase]: HikariPool-0 - Closing connection org.mariadb.jdbc.MariaDbConnection@2bb274e: (connection evicted or dead)

Any ideas what could be causing this?

Thanks,
Kevin

**Comment by schmeic** [comment]
Actually, this appears to be an issue with MariaDb. Sorry about the premature report. I was able to reproduce this error using the Apache dbcp2 connection pool.
