### ISSUE TITLE
Not recovering from Amazon Redshift disconnects

### ISSUE THREAD

**Issue by xstevens** [brettwooldridge/HikariCP#650]
We are seeing an issue where Hikari was not recovering from a Redshift disconnect. It produces a stack trace like this:

```
! Causing: java.sql.SQLException: [Amazon](500150) Error setting/closing connection: Not Connected.
! at com.amazon.redshift.client.PGClient.isConnected(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.redshift.client.PGClient.prepareStatement(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.redshift.dataengine.PGQueryExecutor.<init>(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.redshift.dataengine.PGDataEngine.prepare(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.redshift.core.jdbc41.PGJDBC41PreparedStatement.<init>(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.redshift.core.jdbc41.PGJDBC41ObjectFactory.createPreparedStatement(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source) ~[aws-redshift-jdbc41-1.1.10.1010.jar:RedshiftJDBC_1.1.10.1010]
! at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:310) ~[HikariCP-2.4.7-SNAPSHOT.jar:na]
! at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-2.4.7-SNAPSHOT.jar:na]
```

Looking in my debugger I noticed that the Redshift driver returns a SQL state of "HY000" while the connection is down.

I was going to propose a patch to add this:

`SQL_ERRORS.add("HY000"); // Redshift disconnect error`

to the ProxyConnection class. This seems to get the connection logic to properly acknowledge that its in a closed state and remove the connection from the pool.

**Comment by johnou** [comment]
When this happens are you able to resolve the redshift host name from the server running your application?

**Comment by brettwooldridge** [comment]
@xstevens @johnou It looks like the ``HY000`` code is a "general error".  It looks like we need the ability to inspect the vendor specific "error code" not just the "SQL State".  I'm working on this now...
