### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by dirkhillbrecht** [brettwooldridge/HikariCP#684]
Hi,

we're using HikariCP which is built into Play 2.4.7. For parts of our application's core framework, we're obtaining Connections directly from the Play-built-in HikariCP. We ensure to release them properly by combining try-with-resource with a functional design:

```java
public default <T> T onConnectionApply(FunctionWithSQLException<Connection,T> function) {
  try (Connection conn=DB.getConnection("default")) {  // Play's DB object...
    return function.apply(conn);
  } catch (SQLException sqe) { throw new UncheckedSQLException(sqe);  }
    // wrap SQLExceptions into a specialized RuntimeException due to Java's Streams framework
}

public default <T> T onStatementApply(FunctionWithSQLException<Statement,T> function) {
  return onConnectionApply(conn->{
    try (Statement stmt=createStatement(conn)) {
      // createStatement() delivers Statement without escape processing
      return function.apply(stmt);
    } catch (SQLException sqe) { throw new UncheckedSQLException(sqe); }
  });
}
```

We're opening a new Connection for each Statement and a new Statement for each query this way to ensure that Connections are released _fast_ by our framework.

In our unit test environment, we use the default HikariCP settings from play with the only exception of `db.default.hikaricp.maximumPoolSize` being `50` as we know that there are issues with legacy code opening parallel database connections.

In our unit test environment, we're using a MySQL 5.5 server storing everything in a Linux tmpfs-RAM-disk. We have a unit test which adds _vast_ amounts of data in parallel on about 10 threads and with a very high rate. In the past, this test has discovered subtle parallelism bugs in our own framework. Today, I observed this:

```
de.cantamen.quarterback.db.UncheckedSQLException: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at de.cantamen.quarterback.db.ConnectionProvider.lambda$onStatementApply$3(ConnectionProvider.java:136)
        at de.cantamen.quarterback.db.ConnectionProvider.onConnectionApply(ConnectionProvider.java:110)
        at de.cantamen.quarterback.db.ConnectionProvider.onStatementApply(ConnectionProvider.java:131)
        at de.cantamen.quarterback.db.ConnectionProvider.insertWithAutoIncrement(ConnectionProvider.java:226)
        at biz.chitec.quarterback.util.DBAbstractor.insertWithAutoIncrement(DBAbstractor.java:648)
        at de.chitec.ebus.server.importer.GenericImporter.performAction(GenericImporter.java:848)
        at de.chitec.ebus.server.importer.GenericImporter.handleImport(GenericImporter.java:427)
        at de.chitec.ebus.server.adminexecs.BookeeTypeAdminExecutor.importBookeeType(BookeeTypeAdminExecutor.java:58)
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at [... our own server framework ...]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1065)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2713)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1794)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1882)
        at com.zaxxer.hikari.proxy.StatementProxy.executeUpdate(StatementProxy.java:124)
        at com.zaxxer.hikari.proxy.StatementJavassistProxy.executeUpdate(StatementJavassistProxy.java)
        at de.cantamen.quarterback.db.ConnectionProvider.lambda$insertWithAutoIncrement$8(ConnectionProvider.java:227)
        at de.cantamen.quarterback.db.ConnectionProvider.lambda$onStatementApply$3(ConnectionProvider.java:133)
```

I have never seen this before. Could this be a problem in HikariCP? Note that we are only using auto-committing transactions. The operation in question was an insert into a table with an `ìnt auto_increment primary key` row. For these, we use the following helper method to obtain that newly inserted primary key:

```java
public default int insertWithAutoIncrement(String insertstatement) {
  return onStatementApply(dbstmt-> {
    dbstmt.executeUpdate(insertstatement, Statement.RETURN_GENERATED_KEYS);
    ResultSet rs = dbstmt.getGeneratedKeys();
    return (rs.next()?rs.getInt(1):-1);
  });
}
```

Could it be that there are any issues with connection pooling and obtaining the newly generated key this way? Or is it more probable that - after all - MySQL has a problem with auto_incrementing and the problem was raised there. Have you ever seen such a behaviour? Where should I dig to find out what is going on? I would really appreciate if you could comment on this issue. I will give any additional information needed.

Best regards,
Dirk

**Comment by brettwooldridge** [comment]
@dirkhillbrecht I do not think this is an issue with HikariCP.  Possibly HikariCP is allowing you to punish your DB more than before. 😄 

This seems a fairly common issue:

http://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans

http://stackoverflow.com/questions/2596005/working-around-mysql-error-deadlock-found-when-trying-to-get-lock-try-restarti

One solution is to see if you can force a locking order (link 1) or use indexes to avoid table-scans that can cause locking (also link 1).  A more drastic solution is to tweak MySQL settings -- though the suggestions come with caveats and warnings (link 2).

Though as suggested also in link 2, yet another solution is to expect that the exception is possible, and do as the error message suggests ... retry the query.
