### ISSUE TITLE
Can't catch Exception on call "new HikariDataSource()"

### ISSUE THREAD

**Issue by Wolf2323** [brettwooldridge/HikariCP#708]
Hi,

I have a problem with catching an exception. 

First i show you my code:
```
try
{
	....
	final HikariConfig databaseconfig = new HikariConfig();
	....
	hikari = new HikariDataSource(databaseconfig);    <<--- ther is the problem
	....
}
catch(Exception e)
{
	e.printStackTrace();
}
```

now, if i use the wrong Login dates(for testing dumbest assumable user), i get this exception:
```
30.08 17:26:10 [Server] INFO [MySQL] Enabling MySQL v1.0.1-SNAPSHOT
30.08 17:26:11 [Server] WARN com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
30.08 17:26:11 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
30.08 17:26:11 [Server] WARN at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
30.08 17:26:11 [Server] WARN at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
30.08 17:26:11 [Server] WARN at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
30.08 17:26:11 [Server] WARN at de.derspielpirat.mysql.MySQL.configureConnPool(MySQL.java:151)
30.08 17:26:11 [Server] WARN at de.derspielpirat.mysql.MySQL.onEnableSetup(MySQL.java:64)
30.08 17:26:11 [Server] WARN at de.derspielpirat.origin.DSPJavaPlugin.onEnable(DSPJavaPlugin.java:34)
30.08 17:26:11 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
30.08 17:26:11 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
30.08 17:26:11 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
30.08 17:26:11 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
30.08 17:26:11 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
30.08 17:26:11 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
30.08 17:26:11 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
30.08 17:26:11 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
30.08 17:26:11 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
30.08 17:26:11 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
30.08 17:26:11 [Server] WARN at java.lang.Thread.run(Thread.java:745)
30.08 17:26:11 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
30.08 17:26:11 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
30.08 17:26:11 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
30.08 17:26:11 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
30.08 17:26:11 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
30.08 17:26:11 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
30.08 17:26:11 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
30.08 17:26:11 [Server] WARN at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
30.08 17:26:11 [Server] WARN at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
```

so i looked for the exception and i find this peace of code in HikariCP:
```
/**
    * Fill the pool up to the minimum size.
    */
   private void checkFailFast()
   {
      if (config.isInitializationFailFast()) {
         try {
            newConnection().close();
         }
         catch (Throwable e) {
            try {
               shutdown();
            }
            catch (Throwable ex) {
               e.addSuppressed(ex);
            }

            throw new PoolInitializationException(e);        <<--- right there
         }
      }
   }
```

there is thrown an exception but the method does not have an "throws PoolInitializationException" or handle the exception on an other way. So i cant realy do something against this exception or catch them.

**Comment by brettwooldridge** [comment]
@Wolf2323 ``PoolInitializationException`` is a ``RuntimeException``, and your example try-catch code will surely catch it.  It is likely that ``e.printStackTrace()`` is not going to show anything visible if a logging framework is present.  But if you run the code under a debugger, and set a breakpoint in that ``catch`` you'll see that the exception is indeed caught.

**Comment by kailashpandey0101** [comment]
@brettwooldridge  in above case , it did caught the exception like you said. But when i change the db password while the application is running, it will eventually throw java.sql.SQLException: but the try block won't catch it afterwards. I am trying to figure out how to catch whenever password get changed and this exception get's thrown.

**Comment by brettwooldridge** [comment]
The above discussion and exception are only related to pool initialization at startup.  If you change the password at runtime, the pool is already started.

If the password is incorrect, you will eventually get timeout exceptions when calling getConnection().  Calling getNextException() on *that* SQLException should give you the native driver’s SQLException.

**Comment by anujocpdba431** [comment]
Hey brettwooldridge,

we are getting same issue our platform. please help from the logs.

[app.services][ERROR][2019-01-03T13:17:34.750+04:00]:[]:[]:[]:[Timer-5]:[com.kony.rdbms.connection.AnnotatedJDBCConnectionManager:intialize:70]:Failed to create connection pool: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:568) ~[HikariCP-2.7.4.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554) ~[HikariCP-2.7.4.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114) ~[HikariCP-2.7.4.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[HikariCP-2.7.4.jar:?]
	at com.kony.rdbms.connection.HikariCpConnectionPool.<init>(HikariCpConnectionPool.java:57) ~[RDBMSDataAdapter-8.2.0.10.jar:?]
	at com.kony.rdbms.connection.RDBMSConnectionPoolFactory.getRdbmsConnectionPool(RDBMSConnectionPoolFactory.java:11) ~[RDBMSDataAdapter-8.2.0.10.jar:?]
	at com.kony.rdbms.connection.AnnotatedJDBCConnectionManager.intialize(AnnotatedJDBCConnectionManager.java:68) [RDBMSDataAdapter-8.2.0.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.commons.beanutils.MethodUtils.invokeExactMethod(MethodUtils.java:402) [commons-beanutils-1.9.2.jar:1.9.2]
	at org.apache.commons.beanutils.MethodUtils.invokeExactMethod(MethodUtils.java:352) [commons-beanutils-1.9.2.jar:1.9.2]
	at com.kony.dataadapter.annotations.utilities.ReflectionUtil.invokeMethod(ReflectionUtil.java:60) [DataAdapterEngine-8.2.0.10.jar:?]
	at com.kony.dataadapter.annotations.utilities.ReflectionUtil.invokeMethod(ReflectionUtil.java:76) [DataAdapterEngine-8.2.0.10.jar:?]
	at com.kony.dataadapter.annotations.utilities.MethodUtil.executeOperation(MethodUtil.java:38) [DataAdapterEngine-8.2.0.10.jar:?]
	at com.kony.dataadapter.connection.InitializeCommand.execute(InitializeCommand.java:91) [DataAdapterEngine-8.2.0.10.jar:?]
	at com.kony.dataadapter.connection.InitializeCommand.performInitialize(InitializeCommand.java:34) [DataAdapterEngine-8.2.0.10.jar:?]
	at com.kony.dataadapter.annotations.adapter.AnnotationAdapter.initialize(AnnotationAdapter.java:144) [DataAdapterEngine-8.2.0.10.jar:?]
	at com.konylabs.middleware.connectors.dataadapter.DataAdapterTask.newOperationInitializeWithNewConnProps(DataAdapterTask.java:357) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.connectors.dataadapter.DataAdapterTask.newOperationInitialize(DataAdapterTask.java:326) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.connectors.dataadapter.DataAdapterTask.initializeService(DataAdapterTask.java:171) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.connectors.dataadapter.DataAdapterTask.initializeDataAdapter(DataAdapterTask.java:141) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.connectors.dataadapter.DataAdapterTask.servicesIntializationTask(DataAdapterTask.java:83) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.connectors.dataadapter.DataAdapterUtil.performAdapterIntialization(DataAdapterUtil.java:199) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.timer.AbstractKonyTimer.initializeAdapterAndClearDataAdapterCache(AbstractKonyTimer.java:341) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.timer.KonyIntegrationServiceTimerImpl.performTimerUpdateTask(KonyIntegrationServiceTimerImpl.java:116) [middleware-8.2.1.1.jar:?]
	at com.konylabs.middleware.timer.AbstractKonyTimer.run(AbstractKonyTimer.java:91) [middleware-8.2.1.1.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_181]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_181]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.44.jar:5.1.44]
