### ISSUE TITLE
2.5.0 version consumes 100% CPU

### ISSUE THREAD

**Issue by doom369** [brettwooldridge/HikariCP#716]
Hello. I have a production system that was working fine with HikariCP and DB logic (non-changed) for 6 months. And recently I updated from 2.4.7 to 2.5.0 and got 100% CPU consumption.

Env. : 
```
Ubuntu 14.04
java version "1.8.0_91"
```

I used `jstack` + `shift+H` to find top consuming thread. Here is it : 

```
"pool-4-thread-4" #30 prio=5 os_prio=0 tid=0x00007fc9a002a800 nid=0x2b3e runnable [0x00007fc98c4f2000]
   java.lang.Thread.State: RUNNABLE
        at com.zaxxer.hikari.pool.ProxyConnection.checkException(ProxyConnection.java:168)
        at com.zaxxer.hikari.pool.ProxyStatement.checkException(ProxyStatement.java:46)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at cc.blynk.server.db.dao.ReportingDBDao.insert(ReportingDBDao.java:95)
        at cc.blynk.server.db.DBManager.lambda$insertReporting$1(DBManager.java:116)
        at cc.blynk.server.db.DBManager$$Lambda$37/2131139621.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

My code is open sourced and I can show it if that helps.

**Comment by brettwooldridge** [comment]
What is the database?  The only way I can see this occurring is if there is a cycle of nested exception objects.

The method basically looks like this:
```java
final SQLException checkException(SQLException sqle) {
   SQLException nse = sqle;
   while (nse != null && delegate != ClosedConnection.CLOSED_CONNECTION) {
      if (...) {
         ...
         delegate = ClosedConnection.CLOSED_CONNECTION;
      }
      else {
         nse = sqle.getNextException();
         if (nse == sqle) {
            break;
         }
      }
   }
}
```
If the code gets inside the ``if`` then the loop will terminate.  If the code gets into the ``else`` and if ``getNextException()`` returns the same exception was was passed in (some drivers do that), the loop will terminate.  Otherwise, our assumption is that ``sqlq.getNextException()`` will eventually return a ``null`` at the end of the "chain".

That appears to be an incorrect assumption.  But it would be nice to know for which this condition is arising.

**Comment by doom369** [comment]
@brettwooldridge 

Database is Postgres 9.4.
```
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4.1208</version>
        </dependency>
```

Please let me know if you need more info.

**Comment by johnou** [comment]
@doom369 can you get a CPU profiler snapshot of where the JVM is burning cycles?

**Comment by doom369** [comment]
@johnou no. I have many envs and this issue was reproduced only on 1 of them. This is production instance with high load so I can't risk there :).

**Comment by johnou** [comment]
Guess the depth of 10 will do, commons lang takes a different approach, probably not as fast though..

```java
*
     * <p>Returns the list of <code>Throwable</code> objects in the
     * exception chain.</p>
     *
     * <p>A throwable without cause will return a list containing
     * one element - the input throwable.
     * A throwable with one cause will return a list containing
     * two elements. - the input throwable and the cause throwable.
     * A <code>null</code> throwable will return a list of size zero.</p>
     *
     * <p>This method handles recursive cause structures that might
     * otherwise cause infinite loops. The cause chain is processed until
     * the end is reached, or until the next item in the chain is already
     * in the result set.</p>
     *
     * @param throwable  the throwable to inspect, may be null
     * @return the list of throwables, never null
     * @since Commons Lang 2.2
     */
    public static List<Throwable> getThrowableList(Throwable throwable) {
        final List<Throwable> list = new ArrayList<Throwable>();
        while (throwable != null && list.contains(throwable) == false) {
            list.add(throwable);
            throwable = ExceptionUtils.getCause(throwable);
        }
        return list;
    }
```

**Comment by brettwooldridge** [comment]
@johnou Yeah, one option was a Set<Throwable> of already seen exceptions.  I thought about it and was then like whatever.  If the SQLException is more then 10 call stacks beneath HikariCP something else is wrong.

**Comment by johnou** [comment]
sgtm.

**Comment by prettynatty** [comment]
We have published a build with this fix while we are waiting for the new release.
https://bintray.com/dialog/maven/hikaricp

**Comment by sbirkl** [comment]
Hi,

I'm not sure whether the fix really fixes everything. Of course, an infinite loop will not happen anymore.

But when looking at the code at SQLException:

```
    /**
     * Retrieves the exception chained to this
     * <code>SQLException</code> object by setNextException(SQLException ex).
     *
     * @return the next <code>SQLException</code> object in the chain;
     *         <code>null</code> if there are none
     * @see #setNextException
     */
    public SQLException getNextException() {
        return (next);
    }
```

It always returns the same exception instance. And the code in ProxyConnection.checkException() also always invokes the same getter on the same instance. So from functional point of view, iterating 10 times does not do much difference than just not iterating?

**Comment by johnou** [comment]
should probably be nse = nse.getNextException();

**Comment by johnou** [comment]
I would have probably written it like this but @brettwooldridge is the JIT pro.

```java
   final SQLException checkException(SQLException sqle)
   {
      SQLException nse = sqle;
      byte depth = 0;
      while (nse != null && delegate != ClosedConnection.CLOSED_CONNECTION && depth < 10) {
         final String sqlState = nse.getSQLState();
         if (sqlState != null && sqlState.startsWith("08") || ERROR_STATES.contains(sqlState) || ERROR_CODES.contains(sqle.getErrorCode())) {
            // broken connection
            LOGGER.warn("{} - Connection {} marked as broken because of SQLSTATE({}), ErrorCode({})",
                        poolEntry.getPoolName(), delegate, sqlState, sqle.getErrorCode(), sqle);
            leakTask.cancel();
            poolEntry.evict("(connection is broken)");
            delegate = ClosedConnection.CLOSED_CONNECTION;
            break;
         }
         nse = nse.getNextException();
         depth++;
      }

      return sqle;
   }
```

**Comment by johnou** [comment]
@brettwooldridge https://github.com/brettwooldridge/HikariCP/pull/723
