### ISSUE TITLE
Exception when closing datasource when in @predestroy method

### ISSUE THREAD

**Issue by tonywestonuk** [brettwooldridge/HikariCP#726]
Hi,
I create, and destroy HikariCP as part of a JavaEE app's lifecycle (rather than the containers lifecycle).

However, I get the following error while closing it in the @PreDestroy method. 

`java.lang.NoClassDefFoundError: java/util/concurrent/ScheduledFuture
	at com.zaxxer.hikari.pool.PoolEntry.close(PoolEntry.java:173)
	at com.zaxxer.hikari.pool.HikariPool.closeConnection(HikariPool.java:411)
	at com.zaxxer.hikari.pool.HikariPool.softEvictConnection(HikariPool.java:525)
	at com.zaxxer.hikari.pool.HikariPool.softEvictConnections(HikariPool.java:339)
	at com.zaxxer.hikari.pool.HikariPool.shutdown(HikariPool.java:205)
	at com.zaxxer.hikari.HikariDataSource.close(HikariDataSource.java:304)

...

Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.util.concurrent.ScheduledFuture]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1292)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1155)
	at org.apache.tomee.catalina.TomEEWebappClassLoader.loadClass(TomEEWebappClassLoader.java:201)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1116)`

**Comment by tonywestonuk** [comment]
I've added a message to TomEE user group, as Im not sure if this is actually an issue with TomEE incorrectly denying loading of classes in the @PostDestroy method....
http://tomee-openejb.979440.n4.nabble.com/HikariCP-problems-with-Tomee-td4680148.html

**Comment by brettwooldridge** [comment]
This is not a HikariCP issue.  Someone (TomEE?) is pulling the classloader rug out from under HikariCP while it is still shutting down.  I don't know if @PreDestroy is meant to be asynchronous or not, but HikariCP can take several seconds or more to shutdown (largely dependent on how fast the DB can close connections).
