### ISSUE TITLE
HikariCP as JNDI resource in Tomcat

### ISSUE THREAD

**Issue by stockstatus** [brettwooldridge/HikariCP#728]
Hi, please could you help me with this problem, i tried many approaches to fix my problem but with no success so far. When i run my app i have set DEBUG mode fir HikariCP and see this exception

`2016-09-22 06:19:34,808 DEBUG HikariPool.?               HikariPool-2 - Pool stats (total=1, active=0, idle=1, waiting=0)
2016-09-22 06:19:44,818 DEBUG HikariPool.?               HikariPool-2 - Cannot acquire connection from data source
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 40000ms.
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196) [HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147) [HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83) ~[HikariCP-2.4.6.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at net.bull.javamelody.JdbcWrapper$3.invoke(JdbcWrapper.java:805) ~[javamelody-core-1.60.0.jar:1.60.0]
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:286) ~[javamelody-core-1.60.0.jar:1.60.0]
	at com.sun.proxy.$Proxy7.getConnection(Unknown Source) ~[na:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:173) ~[HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443) [HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:66) [HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:568) [HikariCP-2.4.6.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:561) [HikariCP-2.4.6.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
`

and in case od restart my app im tomcat manager HikariCP is not releasing conncetions from Psql DB.
This is my Hikari config:

`<Resource name="jdbc/PsqlHikari" auth="Container"
        factory="com.zaxxer.hikari.HikariJNDIFactory"
        type="javax.sql.DataSource"
        maximumPoolSize="1"
        cachePrepStmts="true"
        prepStmtCacheSize="250"
        prepStmtCacheSqlLimit="2048"
        useServerPrepStmts="true"
	connectionTestQuery="select 1"
	connectionTimeout="40000"
        ssl="true"
        sslfactory="org.postgresql.ssl.NonValidatingFactory"
        dataSourceClassName="org.postgresql.ds.PGPoolingDataSource"
        dataSource.url="jdbc:postgresql://localhost:5433/mytest"
        dataSource.user="myuser"
        dataSource.password="pass" />
`

and i am using postgresql-9.3-1103.jdbc3.jar and HikariCP-2.4.6.jar. I also tried various version of psql driver and HikariCP.

**Comment by brettwooldridge** [comment]
@stockstatus This is a tomcat question, of which we know very little about, please ask this question on stackoverflow.
