### ISSUE TITLE
java.sql.SQLException: Method not supported on using HikariCP with Hive JDBC

### ISSUE THREAD

**Issue by devender-yadav** [brettwooldridge/HikariCP#747]
I am using `MySQL` as meta store for hive.

In my JDBC code, I replaced 

     DriverManager.getConnection(connectionUri, username, password);
 
to

     HikariDataSource ds = new HikariDataSource();
     ds.setJdbcUrl(connectionUri);
     ds.setUsername(username);
     ds.setPassword(password); 
     return ds.getConnection();

I got following exception:

    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Method not supported
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.impetus.idw.data.connector.utils.JDBCUtil.getJdbcConnection(JDBCUtil.java:173)
	at com.impetus.idw.data.connector.utils.JDBCUtil.checkTableExistence(JDBCUtil.java:66)
	at com.impetus.idw.data.connector.datasource.HiveTable.exists(HiveTable.java:146)
	at com.impetus.idw.data.connector.tools.hive.HiveToHiveCopyBaseTest.testMetadata(HiveToHiveCopyBaseTest.java:25)
	at com.impetus.idw.data.connector.tools.hive.LocalToLocalTest.testHive(LocalToLocalTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
    Caused by: java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveConnection.setReadOnly(HiveConnection.java:1271)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:372)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:508)
	... 31 more

**Does `HikariCP` supports Hive JDBC?**

**Comment by nitincchauhan** [comment]
use latest hive driver. see [issue](https://issues.apache.org/jira/browse/HIVE-11501) resolved in hive.

**Comment by devender-yadav** [comment]
@nitincchauhan 

Thanks Nitin.

**Comment by ebuildy** [comment]
Fixed from Hive 2.2.0, but most of Hadoop distributions (see HDP 2.6.0 https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.1/bk_release-notes/content/comp_versions.html) are still under 2.1.0 ;-(

**Comment by wsczm** [comment]
I don't understand how to solve this problem? Can you give me some guidance
