### ISSUE TITLE
 Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: password authentication failed for user

### ISSUE THREAD

**Issue by Atul21** [brettwooldridge/HikariCP#748]
2016-10-14 08:59:28.968  INFO 3348 --- [  restartedMain] org.jhipster.demoo.DemoApp               : Starting DemoApp on nuca053 with PID 3348 (D:\jhipster\demo\target\classes started by netadmin in D:
\jhipster\demo)
2016-10-14 08:59:28.968 DEBUG 3348 --- [  restartedMain] org.jhipster.demoo.DemoApp               : Running with Spring Boot v1.4.1.RELEASE, Spring v4.3.3.RELEASE
2016-10-14 08:59:28.968  INFO 3348 --- [  restartedMain] org.jhipster.demoo.DemoApp               : The following profiles are active: swagger,dev
2016-10-14 08:59:29.186 DEBUG 3348 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2016-10-14 08:59:33.093 DEBUG 3348 --- [  restartedMain] o.j.demoo.config.AsyncConfiguration      : Creating Async Task Executor
2016-10-14 08:59:33.781 DEBUG 3348 --- [  restartedMain] o.j.demoo.config.MetricsConfiguration    : Registering JVM gauges
2016-10-14 08:59:33.874 DEBUG 3348 --- [  restartedMain] o.j.demoo.config.MetricsConfiguration    : Monitoring the datasource
2016-10-14 08:59:33.874 DEBUG 3348 --- [  restartedMain] o.j.demoo.config.MetricsConfiguration    : Initializing Metrics JMX reporting
2016-10-14 08:59:34.359  WARN 3348 --- [  restartedMain] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2016-10-14 08:59:34.359  WARN 3348 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2016-10-14 08:59:34.796  INFO 3348 --- [  restartedMain] org.jhipster.demoo.config.WebConfigurer  : Web application configuration, using profiles: [swagger, dev]
2016-10-14 08:59:34.796 DEBUG 3348 --- [  restartedMain] org.jhipster.demoo.config.WebConfigurer  : Initializing Metrics registries
2016-10-14 08:59:34.796 DEBUG 3348 --- [  restartedMain] org.jhipster.demoo.config.WebConfigurer  : Registering Metrics Filter
2016-10-14 08:59:34.796 DEBUG 3348 --- [  restartedMain] org.jhipster.demoo.config.WebConfigurer  : Registering Metrics Servlet
2016-10-14 08:59:34.812  INFO 3348 --- [  restartedMain] org.jhipster.demoo.config.WebConfigurer  : Web application fully configured
2016-10-14 08:59:35.140 DEBUG 3348 --- [  restartedMain] o.j.demoo.config.DatabaseConfiguration   : Configuring Liquibase
2016-10-14 08:59:35.171  WARN 3348 --- [demo-Executor-1] o.j.d.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2016-10-14 08:59:35.312 ERROR 3348 --- [demo-Executor-1] j.d.a.ExceptionHandlingAsyncTaskExecutor : Caught async exception

com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: password authentication failed for user "demo"
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:528)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
        at org.jhipster.demoo.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)
        at org.jhipster.demoo.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$34(AsyncSpringLiquibase.java:50)
        at org.jhipster.demoo.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$29(ExceptionHandlingAsyncTaskExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "demo"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:427)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:203)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:146)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
        at org.postgresql.jdbc42.AbstractJdbc42Connection.<init>(AbstractJdbc42Connection.java:21)
        at org.postgresql.jdbc42.Jdbc42Connection.<init>(Jdbc42Connection.java:28)
        at org.postgresql.Driver.makeConnection(Driver.java:415)
        at org.postgresql.Driver.connect(Driver.java:282)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
        ... 9 common frames omitted

2016-10-14 08:59:35.828  WARN 3348 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframewor
k.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration
.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: password authentication failed for user
"demo"
2016-10-14 08:59:35.843  WARN 3348 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in clas
s path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.spring
framework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.sp
ringframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
2016-10-14 08:59:35.843 ERROR 3348 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJp
aAutoConfiguration.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: password authenticatio
n failed for user "demo"
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.jhipster.demoo.DemoApp.main(DemoApp.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: password authentication failed for user "demo"
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:528)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:124)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
        at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
        ... 19 common frames omitted
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "demo"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:427)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:203)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:146)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
        at org.postgresql.jdbc42.AbstractJdbc42Connection.<init>(AbstractJdbc42Connection.java:21)
        at org.postgresql.jdbc42.Jdbc42Connection.<init>(Jdbc42Connection.java:28)
        at org.postgresql.Driver.makeConnection(Driver.java:415)
        at org.postgresql.Driver.connect(Driver.java:282)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:518)
        ... 39 common frames omitted

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.025 s
[INFO] Finished at: 2016-10-14T08:59:36+05:30
[INFO] Final Memory: 51M/350M
[INFO] ------------------------------------------------------------------------

**Comment by nitincchauhan** [comment]
Solution is in the title. I am glad you READ the log yourself now and changed title :)

**Comment by Atul21** [comment]
This technology is new for me. I am not getting what you are trying to say

**Comment by Atul21** [comment]
Will you please tell me the solution for this?

**Comment by nitincchauhan** [comment]
Putting my reply in other words :)
In your stack of configuration, username and password should be 'available' and 'initialized' before. at the time of creating data source in HikariPool.

**Comment by Atul21** [comment]
Thank You @nitincchauhan
