### ISSUE TITLE
Exception during pool initialization (Can't find a fix)

### ISSUE THREAD

**Issue by Accessory27** [brettwooldridge/HikariCP#753]
Hello.

I currently have one open pool that connects to my main database and it works perfectly. But now, I want to open a new pool for another database. I set up the new pool EXACTLY how I setup the first one, obviously I edited the database name, etc. No errors appear when I load my setupHikari() method but once an actual statement is about to run I get a lot of errors.
`Caused by: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:580) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:150) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[?:?]
	at com.thecodexmc.GameLibrary.xenforo.XenUtils.getUserGroupID(XenUtils.java:51) ~[?:?]
	at com.thecodexmc.GameLibrary.game.GameListeners.onLogin(GameListeners.java:334) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Too many connections
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_79]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_79]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_79]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_79]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:440) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:138) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:108) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:495) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:564) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:150) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[?:?]
	at com.thecodexmc.GameLibrary.xenforo.XenUtils.getUserGroupID(XenUtils.java:51) ~[?:?]
	at com.thecodexmc.GameLibrary.game.GameListeners.onLogin(GameListeners.java:334) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
	... 13 more`

What am I doing wrong here? Here is my XenSQL class, which is what's causing the problem.
`public class XenSQL {

	private static XenSQL instance;
	private HikariDataSource hikari;

	public XenSQL() {
		instance = this;
	}

	public void setupHikari() {
		hikari = new HikariDataSource();
		hikari.setMaximumPoolSize(10);
		hikari.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
		hikari.addDataSourceProperty("serverName", host);
		hikari.addDataSourceProperty("port", port);
		hikari.addDataSourceProperty("databaseName", database);
		hikari.addDataSourceProperty("user", user);
		hikari.addDataSourceProperty("password", password);
		System.out.println("[XenSQL] HikariCP connected to the database successfully.");
	}

	public void queryUpdate(String query) {
		Connection connection = null;

		try {
			connection = hikari.getConnection();
			PreparedStatement pre = connection.prepareStatement(query);
			pre.executeUpdate();
			pre.close();
		} catch (SQLException e) {
			System.out.println("[XenSQL] Error whilst executing the query \"" + query + "\": " + e.getMessage());
		} finally {
			closeConnection(connection);
		}
	}

	public void closeConnection(Connection connection) {
		if(connection != null) {
			try {
				connection.close();
			} catch(SQLException e) {
				e.printStackTrace();
			}
		}
	}

	public HikariDataSource getHikari() {
		return hikari;
	}

	public static XenSQL getInstance() {
		return instance;
	}

}`
I removed the SQL information for obvious reasons, but I don't know what's the issue here. Please help me asap. Thanks!

- Accessory

**Comment by brettwooldridge** [comment]
This seems like an obvious cause "MySQLNonTransientConnectionException: Too many connections".  With both pools running you are exceeding the MySQL configured connection limit.

You can increase the limit in MySQL, a bad idea in my opinion.  Or decrease the *maximumPoolSize*; you must have cranked up the connections pretty high to encounter this error with only two pools.  What makes you think you need more than a handful (~10) of connections in each pool?

**Comment by Accessory27** [comment]
Both of my pools are set to 10 for maximumPoolSize. And I run prepared statements like this:
`	public void savePlayer(final CodexPlayer user) {
		Bukkit.getScheduler().runTaskAsynchronously(Library.getInstance(), new BukkitRunnable() {
			@Override
			public void run() {
				Connection connection = null;
				try {
					connection = MySQL.getInstance().getHikari().getConnection();
					PreparedStatement pre = connection.prepareStatement("UPDATE " + MsgUtil.TABLE_NAME + " SET name=? WHERE uuid=? LIMIT 1;");
					pre.setString(1, user.getName());
					pre.setString(2, user.getUuid().toString());
					pre.execute();
					pre.close();
				} catch(SQLException e) {
					e.printStackTrace();
				} finally {
					MySQL.getInstance().closeConnection(connection);
				}
			}
		});
	}`

(The MySQL.getInstance().closeConnection(connection) code could be found in my first post.)
I honestly don't see what I'm doing wrong here. I'm closing the connection so I'm not sure why there are "too many connections".

**Comment by brettwooldridge** [comment]
Try setting the leakDetectionThreshold at 15000ms and the validationTimeout at 10000ms.
