### ISSUE TITLE
HHH000369: Error stopping service class org.hibernate.hikaricp.internal.HikariCPConnectionProvider

### ISSUE THREAD

**Issue by brunoliveiralcantara** [brettwooldridge/HikariCP#760]
Hello friends.

I'm running a **Spring Web + Hibernate + Hikari** application. On my local machine it works perfectly, but I get the following error on my Amazon AWS Elastic production machine running on Tomcat.

[Gtfs API] 10/11/2016 05:56:52 [DEBUG]: Logging Provider: org.jboss.logging.Log4jLoggerProvider
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH000412: Hibernate Core {5.2.4.Final}
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH000206: hibernate.properties not found
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH000021: Bytecode provider name : javassist
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH80000001: hibernate-spatial integration enabled : true
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH000400: Using dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH000422: Disabling contextual LOB creation as connection was null
[Gtfs API] 10/11/2016 05:56:52 [INFO]: HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@7d271c59
[Gtfs API] 10/11/2016 05:56:53 [INFO]: HHH000250: Starting update timestamps cache at region: org.hibernate.cache.spi.UpdateTimestampsCache
[Gtfs API] 10/11/2016 05:56:53 [INFO]: HHH000248: Starting query cache at region: org.hibernate.cache.internal.StandardQueryCache
[Gtfs API] 10/11/2016 05:56:54 [INFO]: HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
[localhost-startStop-1] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
[Gtfs API] 10/11/2016 05:57:04 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in ServletContext resource [/WEB-INF/spring-context.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
[Gtfs API] 10/11/2016 05:57:04 [INFO]: HHH000369: Error stopping service [class org.hibernate.hikaricp.internal.HikariCPConnectionProvider] : java.lang.NullPointerException
[Gtfs API] 10/11/2016 05:57:04 [ERROR]: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in ServletContext resource [/WEB-INF/spring-context.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1151)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1038)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5027)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5337)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.HibernateException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
	at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:63)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:240)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.getService(SessionFactoryServiceRegistryImpl.java:77)
	at org.springframework.orm.hibernate5.SessionFactoryUtils.getDataSource(SessionFactoryUtils.java:196)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.afterPropertiesSet(HibernateTransactionManager.java:353)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	... 32 more
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
	at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59)
	... 40 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:358)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:72)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
	... 43 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:64)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:150)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:407)
	at org.postgresql.Driver.access$100(Driver.java:55)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:317)
	... 1 more

**My spring-context.xml configurations**

`

    <bean id="sessionFactory" class="org.springframework.orm.hibernate5.LocalSessionFactoryBean">
		<property name="annotatedClasses">
		    <list>
		        <value>com.Class1</value>
		        <value>com.Class2</value>
                        <value>com.ClassN</value>
		    </list>
		</property>

        <property name="hibernateProperties">
            <props>
            	<prop key="hibernate.bytecode.use_reflection_optimizer">false</prop>
		        <prop key="hibernate.dialect">org.hibernate.spatial.dialect.postgis.PostgisDialect</prop>
		        <prop key="hibernate.jdbc.batch_size">80</prop>  
				<prop key="hibernate.order_inserts">true</prop>  
				<prop key="hibernate.order_updates">true</prop>
				<prop key="hibernate.jdbc.batch_versioned_data">true</prop>
				<prop key="hibernate.generate_statistics">false</prop>
				<prop key="hibernate.temp.use_jdbc_metadata_defaults">false</prop>
				<prop key="hibernate.cache.region_prefix"></prop>
				<prop key="show_sql">false</prop>
				
				
		    	<prop key="hibernate.cache.use_second_level_cache">true</prop>
			    <prop key="hibernate.cache.use_query_cache">true</prop>
			    <prop key="hibernate.cache.region.factory_class">org.hibernate.cache.ehcache.EhCacheRegionFactory</prop>
			    <prop key="net.sf.ehcache.configurationResourceName">classpath:hibernate-cache-config.xml</prop>
	    
				
				<prop key="hibernate.connection.provider_class">org.hibernate.hikaricp.internal.HikariCPConnectionProvider</prop>
				<prop key="hibernate.hikari.minimumIdle">5</prop>
				<prop key="hibernate.hikari.maximumPoolSize">80</prop>
				<prop key="hibernate.hikari.idleTimeout">30000</prop>
				<prop key="hibernate.hikari.dataSourceClassName">org.postgresql.ds.PGSimpleDataSource</prop>
				
				
 				<prop key="hibernate.hikari.dataSource.url">jdbc:postgresql://MY_RDS_POSTGRESQL:5432/DATABASE</prop>
				<prop key="hibernate.hikari.dataSource.user">USER</prop>
 				<prop key="hibernate.hikari.dataSource.password">PASSWORD</prop>
            </props>
        </property>
    </bean>

    <bean id="transactionManager" class="org.springframework.orm.hibernate5.HibernateTransactionManager"
    	p:sessionFactory-ref="sessionFactory" />
`

**Comment by billoneil** [comment]
That is a very difficult to read stack trace with no hints what problem you are trying to solve. I see a null pointer exception, a pool started log followed with a failed to connect to db.

My best guesses would be something is configured wrong with DI or the failed to connect exception makes me think your EC2 instance doesn't have access to RDS and you need to change the security groups.

**Comment by brunoliveiralcantara** [comment]
@billoneil thank you so much.

The error was in the security groups configurations on EC2.
