### ISSUE TITLE
HikariCP 2.4.3 and 2.4.7 have some Exception

### ISSUE THREAD

**Issue by dengly** [brettwooldridge/HikariCP#761]
In com.zaxxer.hikari.HikariConfig class I set connectionTimeout to 30000, set idleTimeout to 30000, set leakDetectionThreshold to 600000, set maxLifetime to 10000, set maximumPoolSize to 2, set minimumIdle to 1. Both 2.4.3 and 2.4.7 have the same exception.

Here is the exception : 

```
14:15:27.688 [daoBoxServer11-MsgDao-Ice.ThreadPool.Server-333] WARN  org.hibernate.util.JDBCExceptionReporter -SQL Error: 0, SQLState: null
14:15:27.688 [daoBoxServer11-MsgDao-Ice.ThreadPool.Server-333] ERROR org.hibernate.util.JDBCExceptionReporter -HikariPool-1 - Connection is not available, request timed out after 30000ms.
14:15:28.579 [daoBoxServer11-CommDoorCardDao-Ice.ThreadPool.Server-203] WARN  org.hibernate.util.JDBCExceptionReporter -SQL Error: 0, SQLState: null
14:15:28.579 [daoBoxServer11-CommDoorCardDao-Ice.ThreadPool.Server-203] ERROR org.hibernate.util.JDBCExceptionReporter -HikariPool-1 - Connection is not available, request timed out after 30000ms.


14:15:53.480 [daoBoxServer11-AdminDao-Ice.ThreadPool.Server-296] WARN  daoBoxServer11-AdminDao -dispatch exception:
identity: AdminDao
facet:
operation: getAdminByUuid
remote host: 10.175.206.101 remote port: 36391
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Cannot open connection
        at org.springframework.orm.hibernate3.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:598)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:372)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:417)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:255)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
        at com.zzwtec.community.dao.BaseDaoI$$EnhancerBySpringCGLIB$$1dce7fce.getHibernateTemplate(<generated>)
        at com.zzwtec.community.dao.AdminDaoI.getAdminByUuid(AdminDaoI.java:156)
        at com.zzwtec.community.dao._AdminDaoDisp.___getAdminByUuid(_AdminDaoDisp.java:424)
        at com.zzwtec.community.dao._AdminDaoDisp.__dispatch(_AdminDaoDisp.java:529)
        at Ice.ObjectImpl.ice_dispatch(ObjectImpl.java:294)
        at Ice.ObjectImpl.ice_dispatch(ObjectImpl.java:319)
        at Ice.ObjectImpl$$FastClassBySpringCGLIB$$257bfd82.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
        at com.zzwtec.community.dao.AdminDaoI$$EnhancerBySpringCGLIB$$a7c5ba1e.ice_dispatch(<generated>)
        at com.zzwtec.community.ice.interceptor.PerfDispatchInterceptor.dispatch(PerfDispatchInterceptor.java:62)
        at Ice.DispatchInterceptor.__dispatch(DispatchInterceptor.java:44)
        at IceInternal.Incoming.invoke(Incoming.java:221)
        at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
        at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
        at Ice.ConnectionI.message(ConnectionI.java:1056)
        at IceInternal.ThreadPool.run(ThreadPool.java:395)
        at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
        at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.GenericJDBCException: Cannot open connection
        at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:140)
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:128)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:52)
        at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:449)
        at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:167)
        at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:160)
        at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:81)
        at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1473)
        at org.springframework.orm.hibernate3.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:556)
        ... 32 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:555)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:188)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
        at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:83)
        at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:446)
        ... 37 more
```

How can I fix those exception ?

**Comment by leogps** [comment]
I am seeing this however the database is running locally and I am not sure if it has to do with network interruptions. However, it is deployed in a virtual infrastructure and network interruptions are quite frequent:

```
DEBUG 2016-11-23 20:13:26,023 T[http-apr-8080-exec-71:gui:superadmin] com.hytrust.jobrunner.job.JobManager Job scheduled to run at Nov 23, 2016 8:13:26 PM on target localhost job name ProcessService type ConfigType is started at Nov 23, 2016 8:13:26 PM.
DEBUG 2016-11-23 20:13:56,023 T[pool-4-thread-5:job:gui:superadmin] HikariPool-2 - Timeout failure stats (total=1, active=1, idle=0, waiting=0)
DEBUG 2016-11-23 20:13:56,023 T[HikariPool-2 connection adder] HikariPool-2 - Cannot acquire connection from data source
DEBUG 2016-11-23 20:13:56,053 T[HikariPool-2 connection closer] HikariPool-2 - Closing connection org.postgresql.jdbc4.Jdbc4Connection@6eb31a76: (connection is evicted or dead)
DEBUG 2016-11-23 20:14:26,030 T[pool-4-thread-5:job:gui:superadmin] HikariPool-2 - Timeout failure stats (total=0, active=0, idle=0, waiting=0)
ERROR 2016-11-23 20:14:26,031 T[pool-4-thread-5:job:gui:superadmin] com.company.xxx.Job Execute command finishing job 2397974 exception Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection.
ERROR 2016-11-23 20:14:26,031 T[pool-4-thread-5:job:gui:superadmin] com.hytrust.jobrunner.job.Job Database save exception Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection.
DEBUG 2016-11-23 20:14:26,274 T[HikariPool-2 connection adder] HikariPool-2 - Cannot acquire connection from data source
```

```
DEBUG 2016-11-23 20:15:27,213 T[HikariPool-2 connection adder] HikariPool-2 - Cannot acquire connection from data source
DEBUG 2016-11-23 20:15:41,425 T[http-apr-8080-exec-68:gui:superadmin] HikariPool-2 - Timeout failure stats (total=0, active=0, idle=0, waiting=2)
DEBUG 2016-11-23 20:15:41,426 T[http-apr-8080-exec-68:gui:superadmin] com.company.rest.framework.filter.response.AscResponseGenerator Response Entity Object: AscApiResponse{status=false, error=ErrorDto [code=GEN0005, message=Please check if the URL, HTTP request and content type are valid.], eventJob=null, jobResult=null, data=null, resource=null, hostSystem=null, managementSystem=null, virtualMachine=null, alertDefinition=null, ascAlertDefinition=null, resourceAlertDefinition=null, label=null, complianceTemplate=null, complianceResultDtos=null, complianceEventDtos=null, accountInfo=null, adminUserDetail=null, operation=null, events=null, retentionConfigurations=null, frameworkGenerated=true}
DEBUG 2016-11-23 20:15:45,226 T[pool-4-thread-16:job] HikariPool-2 - Timeout failure stats (total=0, active=0, idle=0, waiting=2)
ERROR 2016-11-23 20:15:45,227 T[pool-4-thread-16:job] com.company.jobrunner.job.Job Execute command finishing job 2397973 exception Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection.
DEBUG 2016-11-23 20:15:45,227 T[pool-4-thread-16:job] com.company.jobrunner.job.Job Job type ArcType Service type UpdateFirewall run on esxi-17.test.company.com using event type UpdateFirewallNoRules.
DEBUG 2016-11-23 20:15:45,292 T[pool-33-thread-35] HikariPool-2 - Timeout failure stats (total=0, active=0, idle=0, waiting=1)
DEBUG 2016-11-23 20:15:58,057 T[HikariPool-2 connection adder] HikariPool-2 - Cannot acquire connection from data source
DEBUG 2016-11-23 20:16:11,884 T[http-apr-8080-exec-87:gui:superadmin] HikariPool-2 - Timeout failure stats (total=0, active=0, idle=0, waiting=1)
DEBUG 2016-11-23 20:16:11,887 T[http-apr-8080-exec-87:gui:superadmin] com.company.gui.webapp.HtRequestCycle Exception caught by GUI
org.hibernate.exception.JDBCConnectionException: Could not open connection
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:65)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
        at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:235)
        at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
        at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:450)
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:201)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle.doGetConnection(HibernateJpaDialect.java:414)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:177)
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:430)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at com.company.authentication.configuration.TwoFactorAuthenConfiguratorImpl$$EnhancerBySpringCGLIB$$3c817123.get(<generated>)
        at sun.reflect.GeneratedMethodAccessor542.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:414)
        at org.apache.wicket.proxy.$Proxy381.get(Unknown Source)
        at com.company.gui.pages.login.LoginPage.doInit(LoginPage.java:207)
        at com.company.gui.pages.login.LoginPage.<init>(LoginPage.java:150)
        at sun.reflect.GeneratedConstructorAccessor9248.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

```

The application is never able to acquire a database connection after this.

**Comment by codeongit** [comment]
I think the problem is related to the " maximumPoolSize 2".Read the source you will find when lib can not  get connect from the pool it will throw this kind of execption.      just increase this config. May it help.
