### ISSUE TITLE
In HikariCP jobs get failed due to stale threads

### ISSUE THREAD

**Issue by Sunshine-23** [brettwooldridge/HikariCP#764]
Hi,
I have recently switched my project to HikariCP. When I run multiple jobs paralelly on the server, random jobs gets failed with below error. I tried to change the HikariCP configurations by changing idleTimeout to 2 mins to remove the stale threads but it didn't helped me. 

java.lang.IllegalStateException: Cannot cancel cache update - current state (1) is not UPDATE_IN_PROGRESS
	at com.opensymphony.oscache.base.EntryUpdateState.cancelUpdate(EntryUpdateState.java:91) ~[oscache-2.3.jar:2.3]
	at com.opensymphony.oscache.base.Cache.cancelUpdate(Cache.java:386) ~[oscache-2.3.jar:2.3]
	at com.opensymphony.oscache.general.GeneralCacheAdministrator.cancelUpdate(GeneralCacheAdministrator.java:184) ~[oscache-2.3.jar:2.3]
	at com.tcs.bfsarch.caching.OSCacheManagerImpl.getCacheObject(OSCacheManagerImpl.java:227) ~[core.jar:?]
	at com.tcs.bfsarch.caching.AbstractCacheManager.getCacheObject(AbstractCacheManager.java:118) ~[core.jar:?]
	at com.tcs.bfsarch.springbatch.utils.SpringBatchServiceInfoManager.getServiceInfo(SpringBatchServiceInfoManager.java:155) ~[springbatch.jar:?]
	at com.tcs.bfsarch.springbatch.writers.WriterAdapter.setWorkFlowData(WriterAdapter.java:772) [springbatch.jar:?]
	at com.tcs.bfsarch.springbatch.writers.WriterAdapter.initWorkFlow(WriterAdapter.java:749) [springbatch.jar:?]
	at com.tcs.bfsarch.springbatch.writers.WriterAdapter.initialize(WriterAdapter.java:670) [springbatch.jar:?]
	at com.tcs.bfsarch.springbatch.writers.WriterAdapter$2.doInTransactionWithoutResult(WriterAdapter.java:355) [springbatch.jar:?]
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34) [spring-tx-4.0.2.RELEASE.jar:4.0.2.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.0.2.RELEASE.jar:4.0.2.RELEASE]
	at com.tcs.bfsarch.springbatch.writers.WriterAdapter.beforeStep(WriterAdapter.java:346) [springbatch.jar:?]
	at org.springframework.batch.core.listener.CompositeStepExecutionListener.beforeStep(CompositeStepExecutionListener.java:77) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:191) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:137) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:152) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:131) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:93) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:90) [spring-batch-core-2.2.5.RELEASE.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

In logger HikariCP configuration is set as below 

2016-11-17|12:02:11,404|INFO |main|com.zaxxer.hikari.pool.PoolBase:469||SchedulerDataSourceConnectionPool - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)|
2016-11-17|12:02:11,608|WARN |main|com.zaxxer.hikari.HikariConfig:804||SchedulerDataSourceConnectionPool - idleTimeout is close to or more than maxLifetime, disabling it.|
2016-11-17|12:02:11,609|DEBUG|main|com.zaxxer.hikari.HikariConfig:841||SchedulerDataSourceConnectionPool - configuration:|
2016-11-17|12:02:11,612|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||allowPoolSuspension.............false|
2016-11-17|12:02:11,613|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||autoCommit......................true|
2016-11-17|12:02:11,613|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||catalog.........................null|
2016-11-17|12:02:11,613|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||connectionInitSql...............null|
2016-11-17|12:02:11,614|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||connectionTestQuery............."SELECT 1 FROM DUAL"|
2016-11-17|12:02:11,614|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||connectionTimeout...............30000|
2016-11-17|12:02:11,614|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSource......................null|
2016-11-17|12:02:11,614|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSourceClassName............."oracle.jdbc.pool.OracleDataSource"|
2016-11-17|12:02:11,615|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSourceJNDI..................null|
2016-11-17|12:02:11,616|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSourceProperties............{user=tcsdev, maxStatements=200, url=jdbc:oracle:thin:@10.33.131.34:1522:bancsdev, password=<masked>, implicitCachingEnabled=true}|
2016-11-17|12:02:11,616|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||driverClassName.................null|
2016-11-17|12:02:11,616|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||healthCheckProperties...........{}|
2016-11-17|12:02:11,617|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||healthCheckRegistry.............null|
2016-11-17|12:02:11,617|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||idleTimeout.....................0|
2016-11-17|12:02:11,617|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||initializationFailFast..........true|
2016-11-17|12:02:11,617|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||isolateInternalQueries..........false|
2016-11-17|12:02:11,618|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||jdbc4ConnectionTest.............false|
2016-11-17|12:02:11,618|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||jdbcUrl.........................null|
2016-11-17|12:02:11,618|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||leakDetectionThreshold..........0|
2016-11-17|12:02:11,618|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||maxLifetime.....................600000|
2016-11-17|12:02:11,619|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||maximumPoolSize.................18|
2016-11-17|12:02:11,619|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||metricRegistry..................null|
2016-11-17|12:02:11,619|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||metricsTrackerFactory...........null|
2016-11-17|12:02:11,619|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||minimumIdle.....................18|
2016-11-17|12:02:11,619|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||password........................<masked>|
2016-11-17|12:02:11,620|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||poolName........................"SchedulerDataSourceConnectionPool"|
2016-11-17|12:02:11,620|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||readOnly........................false|
2016-11-17|12:02:11,620|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||registerMbeans..................false|
2016-11-17|12:02:11,620|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||scheduledExecutorService........null|
2016-11-17|12:02:11,621|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||threadFactory...................null|
2016-11-17|12:02:11,621|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||transactionIsolation............null|
2016-11-17|12:02:11,621|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||username........................null|
2016-11-17|12:02:11,621|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||validationTimeout...............5000|
2016-11-17|12:02:11,622|INFO |main|com.zaxxer.hikari.HikariDataSource:70||SchedulerDataSourceConnectionPool - Started.|
2016-11-17|12:02:11,651|WARN |main|com.zaxxer.hikari.HikariConfig:804||SchedulerDataSourceConnectionPool - idleTimeout is close to or more than maxLifetime, disabling it.|
2016-11-17|12:02:11,652|DEBUG|main|com.zaxxer.hikari.HikariConfig:841||SchedulerDataSourceConnectionPool - configuration:|
2016-11-17|12:02:11,654|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||allowPoolSuspension.............false|
2016-11-17|12:02:11,659|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||autoCommit......................true|
2016-11-17|12:02:11,660|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||catalog.........................null|
2016-11-17|12:02:11,660|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||connectionInitSql...............null|
2016-11-17|12:02:11,660|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||connectionTestQuery............."SELECT 1 FROM DUAL"|
2016-11-17|12:02:11,661|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||connectionTimeout...............30000|
2016-11-17|12:02:11,661|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSource......................null|
2016-11-17|12:02:11,661|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSourceClassName............."oracle.jdbc.pool.OracleDataSource"|
2016-11-17|12:02:11,661|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSourceJNDI..................null|
2016-11-17|12:02:11,672|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||dataSourceProperties............{user=tcsdev, maxStatements=200, url=jdbc:oracle:thin:@10.33.131.34:1522:bancsdev, password=<masked>, implicitCachingEnabled=true}|
2016-11-17|12:02:11,674|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||driverClassName.................null|
2016-11-17|12:02:11,674|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||healthCheckProperties...........{}|
2016-11-17|12:02:11,674|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||healthCheckRegistry.............null|
2016-11-17|12:02:11,674|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||idleTimeout.....................0|
2016-11-17|12:02:11,675|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||initializationFailFast..........true|
2016-11-17|12:02:11,675|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||isolateInternalQueries..........false|
2016-11-17|12:02:11,675|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||jdbc4ConnectionTest.............false|
2016-11-17|12:02:11,675|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||jdbcUrl.........................null|
2016-11-17|12:02:11,676|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||leakDetectionThreshold..........0|
2016-11-17|12:02:11,676|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||maxLifetime.....................600000|
2016-11-17|12:02:11,676|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||maximumPoolSize.................18|
2016-11-17|12:02:11,676|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||metricRegistry..................null|
2016-11-17|12:02:11,677|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||metricsTrackerFactory...........null|
2016-11-17|12:02:11,677|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||minimumIdle.....................18|
2016-11-17|12:02:11,677|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||password........................<masked>|
2016-11-17|12:02:11,677|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||poolName........................"SchedulerDataSourceConnectionPool"|
2016-11-17|12:02:11,677|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||readOnly........................false|
2016-11-17|12:02:11,678|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||registerMbeans..................false|
2016-11-17|12:02:11,678|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||scheduledExecutorService........null|
2016-11-17|12:02:11,678|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||threadFactory...................null|
2016-11-17|12:02:11,678|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||transactionIsolation............null|
2016-11-17|12:02:11,679|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||username........................null|
2016-11-17|12:02:11,679|DEBUG|main|com.zaxxer.hikari.HikariConfig:857||validationTimeout...............5000|
2016-11-17|12:02:11,680|INFO |main|com.zaxxer.hikari.HikariDataSource:70||SchedulerDataSourceConnectionPool - Started.|
2016-11-17|12:02:11,791|DEBUG|SchedulerDataSourceConnectionPool housekeeper|com.zaxxer.hikari.pool.HikariPool:378||SchedulerDataSourceConnectionPool - Pool stats (total=0, active=0, idle=0, waiting=0)|

**Comment by billoneil** [comment]
Why do you think there are stale threads? I don't even see hikaricp in the stack trace. It also looks like you have configured two pools is that intended?
