### ISSUE TITLE
Major Hikari Connection Issues

### ISSUE THREAD

**Issue by AthenaDev** [brettwooldridge/HikariCP#794]
Hi there, i've recently been using HikariCP to have a safe connection pool with my database which stores player data for a Minecraft server. The connection is made inside of the "plugin."

Here's the error I get, which typically ends in a server crash;
`[18:48:48] [Server thread/WARN]: java.sql.SQLTransientConnectionException: GalaxyWarsDatabasePool - Connection is not available, request timed out after 30000ms.
[18:48:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
[18:48:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[18:48:48] [Server thread/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[18:48:48] [Server thread/WARN]: 	at me.athenadev.galaxywars.utils.DataUtils.getAlliance(DataUtils.java:32)
[18:48:48] [Server thread/WARN]: 	at me.athenadev.galaxywars.utils.Utils.isRebel(Utils.java:68)
[18:48:48] [Server thread/WARN]: 	at me.athenadev.galaxywars.listeners.PlayerJoin.onPlayerJoin(PlayerJoin.java:38)
[18:48:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:48:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:48:48] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:48:48] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:48:48] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`
This keeps on happening, and i'm sure i've connected correctly.
Is there anything specific you need to see? Is there anything specific that causes this?

Thanks, AthenaDev

**Comment by brettwooldridge** [comment]
@AthenaDev you most likely have a connection leak. Enable the *leakDetectionThreshold*.
