### ISSUE TITLE
Does not work with Java 8 yet

### ISSUE THREAD

**Issue by maxammann** [brettwooldridge/HikariCP#83]
Heyho tried some days ago and it seems to be pretty solid so far.
There is only one problem atm, which is java 8 support.
I'm not sure whether it's a problem with javaassist or ASM.

```
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: invalid constant type: 15 at 133
    at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:63)
    ... 35 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: invalid constant type: 15 at 133
    at com.zaxxer.hikari.proxy.JavassistProxyFactory.<init>(JavassistProxyFactory.java:103)
    at com.zaxxer.hikari.proxy.JavassistProxyFactory.<clinit>(JavassistProxyFactory.java:57)
    ... 35 more
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 15 at 133
    at javassist.CtClassType.getClassFile2(CtClassType.java:204)
    at javassist.CtClassType.subtypeOf(CtClassType.java:304)
    at javassist.CtClassType.subtypeOf(CtClassType.java:319)
    at javassist.CtClassType.subtypeOf(CtClassType.java:319)
    at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:235)
    at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:107)
    at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:84)
    at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:711)
    at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:688)
    at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
    at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
    at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
    at javassist.compiler.CodeGen.compileExpr(CodeGen.java:229)
    at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:598)
    at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:425)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:204)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:367)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
    at javassist.compiler.Javac.compileBody(Javac.java:223)
    at javassist.CtBehavior.setBody(CtBehavior.java:409)
    at javassist.CtBehavior.setBody(CtBehavior.java:383)
    at com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(JavassistProxyFactory.java:203)
    at com.zaxxer.hikari.proxy.JavassistProxyFactory.<init>(JavassistProxyFactory.java:99)
    ... 36 more
Caused by: java.io.IOException: invalid constant type: 15 at 133
    at javassist.bytecode.ConstPool.readOne(ConstPool.java:1044)
    at javassist.bytecode.ConstPool.read(ConstPool.java:984)
    at javassist.bytecode.ConstPool.<init>(ConstPool.java:125)
    at javassist.bytecode.ClassFile.read(ClassFile.java:770)
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:114)
    at javassist.CtClassType.getClassFile2(CtClassType.java:191)
    ... 65 more
```

**Comment by sunil-ireslab** [comment]
add below node in your pom.xml

<dependency>
	<groupId>org.javassist</groupId>
	<artifactId>javassist</artifactId>
	<version>3.18.0-GA</version>
</dependency>

it will resolve your issue

**Comment by nuliqianxing** [comment]
org.javassist javassist version is 3.18.2-GA,but does not work,how to solve it?

**Comment by brettwooldridge** [comment]
HikariCP no longer depends on Javassist at runtime.

**Comment by nuliqianxing** [comment]
sorry,HikariCP the same as PowerMockito ? I use PowerMockito to run junit test,jdk is 1.8,javassist version is 3.19.0-GA,but it does not work
