### ISSUE TITLE
Integration tests issue H2

### ISSUE THREAD

**Issue by wirdman** [brettwooldridge/HikariCP#832]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111-b14
Database        : H2
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
Hi,
I've been using hikaricp for a while now and decided to update all mvn dependencies (including hikari). Previously I've been using HikariCP-java6.version - 2.2.5 - which worked great so far.

After the upgrade I'm having an issue with the integration tests suite (the application works great after the update - so building with skipping the tests - which uses postgres as a db).

Do you think there is something I've misconfigured or have you by any chance encountered this somewhere? any help is greatly appreciated. Thanks in advance.

this is the config for the tests: 

@Bean(name = "dataSource")
    public DataSource dataSource() {
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setJdbcUrl(jdbcURL);
        dataSource.setUsername(user);
        dataSource.setPassword(password);
        return dataSource;
    }

    @Bean(name = "entityManagerFactory")
    public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
        HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
        vendorAdapter.setDatabase(Database.H2);
        vendorAdapter.setGenerateDdl(true);
        vendorAdapter.setShowSql(true);

        LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
        factory.setJpaVendorAdapter(vendorAdapter);
        factory.setPackagesToScan("com.ctak.scout.core.model");
        factory.setDataSource(dataSource());
        factory.afterPropertiesSet();

        return factory;
    }

which runs just fine with the previous version (java6hikaricp)

part of the stack trace:  

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.hikari.util.ClockSource
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:381) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2.dataSource(<generated>) ~[test-classes/:?]
	at com.ctak.scout.core.JPAConfigIT.entityManagerFactory(JPAConfigIT.java:101) ~[test-classes/:?]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2.CGLIB$entityManagerFactory$1(<generated>) ~[test-classes/:?]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2$$FastClassBySpringCGLIB$$fa6b6ee2.invoke(<generated>) ~[test-classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2.entityManagerFactory(<generated>) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128) ~[spring-test-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60) ~[spring-test-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108) ~[spring-test-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:251) ~[spring-test-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98) ~[spring-test-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116) ~[spring-test-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 25 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.hikari.util.ClockSource
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:502) ~[HikariCP-2.6.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113) ~[HikariCP-2.6.0.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[HikariCP-2.6.0.jar:?]
	at com.ctak.scout.core.JPAConfigIT.dataSource(JPAConfigIT.java:70) ~[test-classes/:?]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2.CGLIB$dataSource$0(<generated>) ~[test-classes/:?]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2$$FastClassBySpringCGLIB$$fa6b6ee2.invoke(<generated>) ~[test-classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2.dataSource(<generated>) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:381) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at com.ctak.scout.core.JPAConfigIT$$EnhancerBySpringCGLIB$$261029d2.dataSource(<generated>) ~[test-classes/:?]
	at com.ctak.scout.core.JPAConfigIT.entityManagerFactory(JPAConfigIT.java:101) ~[test-classes/:?]

**Comment by brettwooldridge** [comment]
@wirdman NoClassDefFoundError is usually caused by one of two things.  One, there could be two versions of HikariCP in the classpath.  Keep in mind that the classpath that maven constructs for tests is different than the compile or run goals.  The other cause is that there is a failure in the static initializer of the class -- in this case ``ClockSource`` -- but looking at the code it is hard to see how that would be the case.

A classpath issue seems most likely.  Make sure you have a completely clean build (maybe delete the contents of the ``target`` directory manually).  Also, make sure that there are not two dependencies accidentally declared in a pom.xml -- the ``HikariCP`` dependency and ``HikariCP-java6`` would not conflict and would result in one, the other, or both being in the classpath.

**Comment by wirdman** [comment]
First thank you for the quick reply. :)

I've ran a mvn dependency:tree and found no duplicates/module of hikari.  

This behaviour is strange - what I mean by that is: tests running from intellij work (run successfully - selecting them and right click run), however when building the mvn project they fail both triggered from intellij or from command line.

The errror from the first test is this one (last time I copied the error from the last one assuming all of them have the same error - and they do, except for the first one) : 

Caused by: java.lang.ArrayIndexOutOfBoundsException: 17
	at com.zaxxer.hikari.util.ClockSource.<clinit>(ClockSource.java:183)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:502)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)

Which makes sense since at that line there is    String[] TIMEUNIT_DISPLAY_VALUES = {"ns", "µs", "ms", "s", "m", "h", "d"};  which obviously doesn't have 17 entries. But for the life of me I don't get why it's looking for that entry. 

Maybe it's helpful that I mention I'm on a unix based os (mac).

I believe it's got something to do with h2 and some misconfiguration (since it works with postgres) so I don't think there's a bug in spring as well (so far at least).

**Comment by wirdman** [comment]
new info :  running this command -> mvn -Dmaven.failsafe.debug -DforkMode=never verify => the tests work no problem (so basically running the tests in parallel seems to cause some issue - forkMode never means same thread ) 
configuring the failsafe plugin (for maven)
<forkCount>0</forkCount> or <forkMode>never</forkMode>
fixes the tests. - Maybe something to look into.

**Comment by brettwooldridge** [comment]
@wirdman We run our unit tests with [reuseForks=false](https://github.com/brettwooldridge/HikariCP/blob/dev/pom.xml#L368).
