### ISSUE TITLE
Connection not release? 

### ISSUE THREAD

**Issue by devpuck** [brettwooldridge/HikariCP#840]
#### Environment
```
HikariCP version: 2.4.11
JDK version     : 1.7.0_111
Database        : MySQL
Driver version  :5.1.41
```
-----------------------------------------------------------------------------------------
My hikariCP config here
		HikariConfig config = new HikariConfig();

		config.setMaximumPoolSize(50);
		config.setMinimumIdle(3);
		config.setDataSourceClassName("com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
		config.addDataSourceProperty("serverName", "192.168.60.106");
		config.addDataSourceProperty("port", "3306");
		config.addDataSourceProperty("databaseName", "magic");

when I query from db，I found when query data is not empty ，I get a exception here
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:583)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at com.db.manager.DBManager.getConection(DBManager.java:98)
	at com.db.manager.UserLoginDBManager.checkUserNameExist(UserLoginDBManager.java:400)
	at com.service.login.LoginService.checkUserNameExist(LoginService.java:212)
	at com.test.dfx.TestDFX.testRegister(TestDFX.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

but when my query data is empty，everything looks ok.
for example
 select id from login where username = ?
when username is right ,AAA there will be a exception after 50 times,but when usename is empty in db like BBB,there will be no exception.

**Comment by brettwooldridge** [comment]
Enable the ``leakDetectionThreshold``.

**Comment by devpuck** [comment]
Yes,I have try,
config.setLeakDetectionThreshold(15000);
but I will get exception like this


java.lang.Exception: Apparent connection leak detected
	at com.db.manager.DBManager.getConection(DBManager.java:98)
	at com.db.manager.UserLoginDBManager.checkUserNameExist(UserLoginDBManager.java:400)
	at com.service.login.LoginService.checkUserNameExist(LoginService.java:212)
	at com.test.dfx.TestDFX.testRegister(TestDFX.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by billoneil** [comment]
Follow the stack trace somewhere in there you are not closing the
connection.

**Comment by brettwooldridge** [comment]
Then most likely ``com.db.manager.UserLoginDBManager.checkUserNameExist()`` is exiting without closing the connection.  Maybe when the username is incorrect it returns early, without closing, and when it is correct it closes than exits.

Database code should *always* use a try-finally block or try-with-resources.
On Java 7+:
```java
try (Connection connection = DBManager.getConection()) {
    // code here
```
on Java 6:
```java
Connection connection = DBManager.getConection();
try {
   // code here
} finally {
   connection.close();
}
```

**Comment by devpuck** [comment]
I am sure I have close. my code like this
		dbManager = DBManager.getInstance();
		Connection connection = dbManager.getConection();
		String sql = "select id from login where username = ?";
		try
		{
			connection.setAutoCommit(true);
			PreparedStatement statement = connection.prepareStatement(sql);
			statement.setString(1, userName);

			ResultSet resultSet = statement.executeQuery();
			if (resultSet.next())
			{
				return MAGICCODE.USER_EMAIL_EXIST;
			}
			connection.close();
		} catch (SQLException e)
		{
			try
			{
				connection.close();
			} catch (SQLException e1)
			{
				e1.printStackTrace();
			}
			e.printStackTrace();
			return MAGICCODE.DB_ERROR;
		}

		return MAGICCODE.USER_NOT_EXIST;

**Comment by billoneil** [comment]
if (resultSet.next())
{
return MAGICCODE.USER_EMAIL_EXIST;
}
connection.close();

This is not closing the connection since it's after the return. It needs to
be in the finally block as Brett showed.

**Comment by billoneil** [comment]
Preferable using try with resources instead.

**Comment by devpuck** [comment]
e....I am a fool....
Thanks
