### ISSUE TITLE
Caused by: org.postgresql.util.PSQLException: The server does not support SSL

### ISSUE THREAD

**Issue by psybox** [brettwooldridge/HikariCP#844]
#### Environment
Windows
HikariCP version: 2.6.0
JDK version     : 1.8.0_65
Database        : PostgreSQL 9.2
Driver version  : 42.0.0 org.postgresql
```
-----------------------------------------------------------------------------------------

It works for some time, like 2 hours, then the exception raises.
My configuration:

        ds = new HikariDataSource();
        ds.setMaximumPoolSize(poolSize);
        ds.setLeakDetectionThreshold(15000);
        ds.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
        ds.addDataSourceProperty("serverName", serverAddress);
        ds.addDataSourceProperty("databaseName", database);
        ds.addDataSourceProperty("user", user);
        ds.addDataSourceProperty("portNumber", port);
        ds.addDataSourceProperty("password", password);

**Comment by psybox** [comment]
![2017-03-20 15_34_56-](https://cloud.githubusercontent.com/assets/300424/24115721/0bc3f99a-0d83-11e7-89db-874bffb6daf1.png)

**Comment by brettwooldridge** [comment]
That's really weird.  You're not running on Heroku are you?  If that is truly the entirety of your configuration, there is no reason HikariCP would be connecting via SSL.  HikariCP doesn't even know what SSL *is*, it simply passes through the driver properties as specified.  

This might be a good question for the PostgreSQL JDBC mailing list.

**Comment by psybox** [comment]
Indeed, very weird, I gonna ask them about this problem.
I'm not running this project on Heroku.

Thank you.

**Comment by psybox** [comment]
There is some logs.
[20170320.zip](https://github.com/brettwooldridge/HikariCP/files/865703/20170320.zip)
[postgresql-2017-03-20_134121.zip](https://github.com/brettwooldridge/HikariCP/files/865704/postgresql-2017-03-20_134121.zip)

**Comment by psybox** [comment]
I created a issue on pgjdbc project on Github and they are trying to help me but nothing yet.

https://github.com/pgjdbc/pgjdbc/issues/788#issuecomment-288809073

**Comment by psybox** [comment]
@brettwooldridge more info:

SEVERE: null
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at sintel.onetouch.db.api.ConnectionPool.getConnection(ConnectionPool.java:57)
	at sintel.onetouch.db.ControleAcessoDB.buscaEquipamento(ControleAcessoDB.java:1550)
	at sintel.onetouch.online.controle.ControlePrincipal.getEquipamento(ControlePrincipal.java:927)
	at sintel.onetouch.online.controle.ControlePrincipal.tratarRequisicaoEquipamento(ControlePrincipal.java:824)
	at sintel.onetouch.online.udp.ServidorUdp.run(ServidorUdp.java:70)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: The server does not support SSL.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:355)
	at org.postgresql.Driver.connect(Driver.java:279)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:86)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:71)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:442)
	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:73)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:620)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:606)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
[pgjdbc_debug.zip](https://github.com/brettwooldridge/HikariCP/files/896018/pgjdbc_debug.zip)

**Comment by brettwooldridge** [comment]
@psybox Yep, that's weird.  Shortly after this timer fires, and closes an existing connection, when HikariCP tries to reconnect the driver reports that SSL is enabled (``enableSSL``):
```java
Apr 03, 2017 3:59:17 PM org.postgresql.util.SharedTimer releaseTimer
FINEST: No outstanding references to shared Timer, will cancel and close it
Apr 03, 2017 3:59:17 PM org.postgresql.core.QueryExecutorBase close
FINEST:  FE=> Terminate
Apr 03, 2017 3:59:21 PM org.postgresql.Driver connect
FINE: Connecting with URL: jdbc:postgresql://127.0.0.1:5432/dev?loggerLevel=TRACE&loggerFile=pgjdbc_debug.log&loginTimeout=30
Apr 03, 2017 3:59:21 PM org.postgresql.jdbc.PgConnection <init>
FINE: PostgreSQL JDBC Driver 42.0.0
Apr 03, 2017 3:59:21 PM org.postgresql.jdbc.PgConnection setDefaultFetchSize
FINE:   setDefaultFetchSize = 0
Apr 03, 2017 3:59:21 PM org.postgresql.jdbc.PgConnection setPrepareThreshold
FINE:   setPrepareThreshold = 5
Apr 03, 2017 3:59:21 PM org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
FINE: Trying to establish a protocol version 3 connection to 127.0.0.1:5432
Apr 03, 2017 3:59:21 PM org.postgresql.core.v3.ConnectionFactoryImpl enableSSL
FINEST:  FE=> SSLRequest
Apr 03, 2017 3:59:21 PM org.postgresql.core.v3.ConnectionFactoryImpl enableSSL
FINEST:  <=BE SSLRefused
Apr 03, 2017 3:59:21 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: The server does not support SSL.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:382)
	at org.postgresql.Driver.connect(Driver.java:254)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:79)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:64)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:442)
	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:73)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:620)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:606)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
If you are adventurous, you can look in their code (maybe ``ConnectionFactoryImpl``) to try to find under what conditions SSL is enabled.  It certainly looks like a pgsql bug.

**Comment by brettwooldridge** [comment]
@psybox [This code](https://github.com/pgjdbc/pgjdbc/blob/07d225ec1028d945533d5023702b3865aee54ad6/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L93) looks like it defaults to SSL under some conditions.  It looks like if you ***explicitly disable*** SSL, it won't do that.

Either add ``ssl.mode=disable`` to your URL, or (my preference) add it to the datasource properties:
```
ds.addDataSourceProperty("ssl.mode", "disable");
```

**Comment by psybox** [comment]
Thank you I will report to them and try this propertie.

**Comment by davecramer** [comment]
there is no such property at least not with that argument

**Comment by brettwooldridge** [comment]
@psybox I just picked it up [from here](http://stackoverflow.com/questions/30539636/ssl-connection-using-pgjdbc-ng-as-java-driver-for-postgres).  Certainly seemed to match the code.  If you have a better reference, can you link it?

**Comment by psybox** [comment]
@brettwooldridge this another driver, pgjdbc-ng and not pgjdbc.

**Comment by brettwooldridge** [comment]
@psybox  Still, the [referenced source code](https://github.com/pgjdbc/pgjdbc/blob/07d225ec1028d945533d5023702b3865aee54ad6/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L93) is for the org.postgresql driver.  Looks like the property you want is simply called ``ssl`` and is a boolean value.  [Here are the driver properties](https://jdbc.postgresql.org/documentation/head/connect.html).

**Comment by davecramer** [comment]
@brettwooldridge it's actually sslMode, and the documentation needs to be fixed (I'm working on it).
