### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by RustJason** [brettwooldridge/HikariCP#845]
#### Environment
```
HikariCP version: 2.5.1
JDK version     : 1.8.0_65
Database        :MySQL
Driver version  : 5.1.41
```
-----------------------------------------------------------------------------------------

```
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 4,317,240 milliseconds ago.  The last packet sent successfully to the server was 4,317,240 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	......
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728)
	... 17 more
```

Everything seems ok,  but this error just periodically to occurs

**Comment by brettwooldridge** [comment]
@RustJason Set your ``maxLifetime`` to at least one minute shorter than the MySQL *wait_timeout* as [per this article](https://support.rackspace.com/how-to/how-to-change-the-mysql-timeout-on-a-server/).

**Comment by RustJason** [comment]
thanks @brettwooldridge

**Comment by brettwooldridge** [comment]
If there is additional network infrastructure, such as load-balancers, between your application and the database, they may be imposing a separate (shorter) timeout.  The pool ``maxLifetime`` should be one minute shorter than the shortest timeout in the infrastructure path.

**Comment by RustJason** [comment]
Yeah, I understand that, I Think it's the LVS at the first layer and behind that, it's haproxy

**Comment by RustJason** [comment]
But I wonder why it is *one minute* shorter, can we just set 5 or 10 sec shorter than that?

**Comment by brettwooldridge** [comment]
Under heavy load Java timers can fire many seconds off the mark.  We typically recommend one minute as a completely safe margin that accounts for load, NTP clock adjustment, and network delay.  Why would you want to try to cut the margin so short?

**Comment by RustJason** [comment]
because longer lifetime will reduce the connection time, Do you think this is a bug?

```

[DEBUG][2017-03-22T09:50:58.267+0800][pool-1-thread-1 - com.zaxxer.hikari.HikariConfig:857 - 19623-huzhou-yinqing]_pubtrans_undef||_msg=maxLifetime.....................120000||
[DEBUG][2017-03-22T09:40:54.660+0800][HikariPool-56 connection adder - com.zaxxer.hikari.pool.HikariPool:445 - ]_pubtrans_undef||_msg=HikariPool-56 - Added connection com.mysql.jdbc.JDBC4Connection@60db6cc8||
[WARN ][2017-03-22T09:50:21.484+0800][main - com.zaxxer.hikari.pool.ProxyConnection:156 - ]_pubtrans_undef||_msg=HikariPool-56 - Connection com.mysql.jdbc.JDBC4Connection@60db6cc8 marked as broken because of SQLSTATE(08S01), ErrorCode(0)||
[DEBUG][2017-03-22T09:50:21.485+0800][HikariPool-56 connection closer - com.zaxxer.hikari.pool.PoolBase:128 - ]_pubtrans_undef||_msg=HikariPool-56 - Closing connection com.mysql.jdbc.JDBC4Connection@60db6cc8: (connection is broken)||
[DEBUG][2017-03-22T09:50:21.485+0800][HikariPool-56 connection closer - com.zaxxer.hikari.pool.PoolBase:137 - ]_pubtrans_undef||_msg=HikariPool-56 - Closing connection com.mysql.jdbc.JDBC4Connection@60db6cc8 failed||
```

This connection `60db6cc8` did not closed after passed the maxLifetime
I was expecting something like this:
```
[DEBUG][2017-03-22T09:36:12.369+0800][HikariPool-13 connection closer - com.zaxxer.hikari.pool.PoolBase:128 - ]_pubtrans_undef||_msg=HikariPool-13 - Closing connection com.mysql.jdbc.JDBC4Connection@75501ddf: (connection has passed maxLifetime)||
```

But didn't see it until error

**Comment by brettwooldridge** [comment]
If the connection is in use at the maxLifetime event, it cannot be evicted.  In that case, it will be marked for eviction and evicted when it is returned.

Can you enable the leakDetectionThreshold, also set for two minutes?

**Comment by RustJason** [comment]
Cool, got this 
```
Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@111486ee, stack trace follows
```

So this means I need to close my connection once the connection is being used.  But I think I need to check the `lifetime` before close. Any way to do so?

**Comment by brettwooldridge** [comment]
@RustJason It means you need to close the connection when you are finished with it.  You do not need to check the lifetime, just ensure that you don't hold connections open longer than the lifetime.

It is always recommended to close connection using Java's try-with-resources blocks:
```java
try (Connection connection = dataSource.getConnection()) {
   ... SQL here
}
```
Getting a connection from the pool is extremely cheap, on the order of nanoseconds, so there is almost no reason to hold connections out of the pool for long periods of time.
