### ISSUE TITLE
java.lang.VerifyError on new connection pool

### ISSUE THREAD

**Issue by Short-Circuit** [brettwooldridge/HikariCP#846]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_102
Database        : MySQL
Driver version  : Unknown
```
-----------------------------------------------------------------------------------------

Initializing a new MySQL connection pool consistently produces the following error:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/zaxxer/hikari/pool/HikariPool.setMetricsTrackerFactory(Lcom/zaxxer/hikari/metrics/MetricsTrackerFactory;)V @43: putfield
  Reason:
    Type 'com/zaxxer/hikari/pool/PoolBase$NopMetricsTrackerDelegate' (current frame, stack[1]) is not assignable to 'com/zaxxer/hikari/pool/PoolBase$MetricsTrackerDelegate'
  Current Frame:
    bci: @43
    flags: { }
    locals: { 'com/zaxxer/hikari/pool/HikariPool', 'com/zaxxer/hikari/metrics/MetricsTrackerFactory' }
    stack: { 'com/zaxxer/hikari/pool/HikariPool', 'com/zaxxer/hikari/pool/PoolBase$NopMetricsTrackerDelegate' }
  Bytecode:
    0x0000000: 2bc6 0022 2abb 001c 592b 2ab4 018e b601
    0x0000010: d22a b701 d6b9 01dc 0300 b701 dfb5 014c
    0x0000020: a700 0e2a bb00 3159 b701 e0b5 014c b1  
  Stackmap Table:
    same_frame(@35)
    same_frame(@46)

	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[?:?]
	at com.shortcircuit.helptickets.HelpTickets.initializeMySQLDatabase(HelpTickets.java:207) ~[?:?]
	at com.shortcircuit.helptickets.HelpTickets.onEnable(HelpTickets.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by brettwooldridge** [comment]
You may have two versions of HikariCP in your classpath.  One of them may be in a shaded jar.
