### ISSUE TITLE
PrometheusMetricsTrackerFactory issue with multiple pools

### ISSUE THREAD

**Issue by ankurbhakta** [brettwooldridge/HikariCP#848]
#### Environment
HikariCP version: 2.5.1
JDK version     : 1.8.0_111
Database        : OracleDB
Driver version  : 12.0.2
-----------------------------------------------------------------------------------------
If i create two HikariCP pools in one JVM and set the PrometheusMetricsTrackerFactory  it causes the below exception because the collector name gets registered twice.  The collectors should be static and should record the pool label (dimension) only on observation of a metric.

Caused by: java.lang.IllegalArgumentException: Collector already registered that provides name: hikaricp_active_connections

**Comment by brettwooldridge** [comment]
@ankurbhakta The Prometheus support was contributed by @tokuhirom .  I seem to recall that there was some reason he did not want to qualify the metric with the pool name, as we do with DropWizard metrics.  May he can comment?

**Comment by ankurbhakta** [comment]
@tokuhirom is correct. We should not qualify the metric name with the pool name.The pool name is a dimension in time series data perspective that can be queried upon. I created a pull request with minor tweaks to fix this issue. 

https://github.com/brettwooldridge/HikariCP/pull/851

**Comment by PascalSchumacher** [comment]
I believe this was fixed by https://github.com/brettwooldridge/HikariCP/pull/890 (released in 2.6.2) and can be closed.

**Comment by zvuki** [comment]
I don't think this was resolved. I am running 3.3.1 and when trying to create multiple pools, there is an exception:
```scala
 java.lang.IllegalArgumentException: Collector already registered that provides name: hikaricp_connection_timeout_total
 	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
 	at io.prometheus.client.Collector.register(Collector.java:139)
 	at com.zaxxer.hikari.metrics.prometheus.PrometheusMetricsTracker.registerMetrics(PrometheusMetricsTracker.java:71)
 	at com.zaxxer.hikari.metrics.prometheus.PrometheusMetricsTracker.<init>(PrometheusMetricsTracker.java:63)
 	at com.zaxxer.hikari.metrics.prometheus.PrometheusMetricsTrackerFactory.create(PrometheusMetricsTrackerFactory.java:55)
 	at com.zaxxer.hikari.pool.HikariPool.setMetricsTrackerFactory(HikariPool.java:308)
 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
```

This line is problematic: https://github.com/brettwooldridge/HikariCP/blob/86cabf08623a8f9c9ab697a95a277690496b6fae/src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java#L63

**Comment by ankurbhakta** [comment]
This hasn't been working for a while, try switching to micrometer using MicrometerMetricsTracker, which can delegate to prometheus, datadog, netflix atlas etc. We have been using that in production for a while with prometheus and grafana.
