### ISSUE TITLE
How to catch and report "Apparent connection leak detected"

### ISSUE THREAD

**Issue by Paxa** [brettwooldridge/HikariCP#852]
I would like to report that exceptions to our error reporting system.

How can I add a handler for it?
```
Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@73b44161, stack trace follows
 java.lang.Exception: Apparent connection leak detected
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[garuda-payments-1.3-all.jar:?]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35) ~[garuda-payments-1.3-all.jar:?]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:99) ~[garuda-payments-1.3-all.jar:?]
....
```

**Comment by brettwooldridge** [comment]
@Paxa There is no inherent handler capability for this.  Most of the logging frameworks, like log4j, have appenders that can send events to syslog (``SyslogAppender``) or perform HTTP post operations.  You might consider one of those.  Alternatively, there are frameworks like LogStash that can monitor ordinary log files and send various kinds of notifications.

**Comment by Paxa** [comment]
Thank you
