### ISSUE TITLE
deadlock with connection closer thread

### ISSUE THREAD

**Issue by Gabol** [brettwooldridge/HikariCP#854]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_112
Database        : MySQL
Driver version  : 5.1.39
```
-----------------------------------------------------------------------------------------
Hi!

I'm using hikari with slick. After updating hikari from 2.5.0 to 2.6.0 and slick from 3.2.0-M1 to 3.2.0 I started to get deadlocks in mysql driver. As a result, my streaming task stuck indefinitely.
The problem occurred twice, however I couldn't reproduce it synthetically.
Here are the thread dumps.
The first one:
```
connection closer id=46518 state=BLOCKED
    - waiting to lock <0x0b7d22b9> (a com.mysql.jdbc.LoadBalancedConnectionProxy)
     owned by slick-db-3 id=440
    at com.mysql.jdbc.MultiHostConnectionProxy.invoke(MultiHostConnectionProxy.java:409)
    at com.sun.proxy.$Proxy2.setNetworkTimeout(Unknown Source)
    at com.mysql.jdbc.MultiHostMySQLConnection.setNetworkTimeout(MultiHostMySQLConnection.java:2323)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.mysql.jdbc.ReplicationConnectionProxy.invokeMore(ReplicationConnectionProxy.java:309)
    at com.mysql.jdbc.MultiHostConnectionProxy.invoke(MultiHostConnectionProxy.java:452)
    at com.sun.proxy.$Proxy3.setNetworkTimeout(Unknown Source)
    at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:516)
    at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:133)
    at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$5(HikariPool.java:419)
    at com.zaxxer.hikari.pool.HikariPool$$Lambda$8/590896586.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@1ae17c12
```
```
slick-db-3 id=440 state=BLOCKED
    - waiting to lock <0x3b5e50f8> (a com.mysql.jdbc.ReplicationConnectionProxy)
     owned by connection closer id=46518
    at com.mysql.jdbc.ReplicationConnectionProxy.getCurrentConnection(ReplicationConnectionProxy.java:509)
    at com.mysql.jdbc.ReplicationMySQLConnection.getCurrentConnection(ReplicationMySQLConnection.java:46)
    at com.mysql.jdbc.ReplicationMySQLConnection.getActiveMySQLConnection(ReplicationMySQLConnection.java:42)
    at com.mysql.jdbc.MultiHostMySQLConnection.getConnectionMutex(MultiHostMySQLConnection.java:2355)
    at com.mysql.jdbc.PreparedStatement.realClose(PreparedStatement.java:2691)
    at com.mysql.jdbc.StatementImpl.close(StatementImpl.java:532)
    at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.mysql.jdbc.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:103)
      - locked com.mysql.jdbc.LoadBalancedConnectionProxy@b7d22b9
    at com.sun.proxy.$Proxy7.close(Unknown Source)
    at com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java:76)
    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:77)
    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
    at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
    at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
    at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
    at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
    at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
    at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
    at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@cc92bfc
```
And the second one:
```
slick-db-8 id=451 state=BLOCKED
    - waiting to lock <0x68b16260> (a com.mysql.jdbc.ReplicationConnectionProxy)
     owned by connection closer id=16614
    at com.mysql.jdbc.ReplicationConnectionProxy.getCurrentConnection(ReplicationConnectionProxy.java:509)
    at com.mysql.jdbc.ReplicationMySQLConnection.getCurrentConnection(ReplicationMySQLConnection.java:46)
    at com.mysql.jdbc.ReplicationMySQLConnection.getActiveMySQLConnection(ReplicationMySQLConnection.java:42)
    at com.mysql.jdbc.MultiHostMySQLConnection.getConnectionMutex(MultiHostMySQLConnection.java:2355)
    at com.mysql.jdbc.PreparedStatement.realClose(PreparedStatement.java:2691)
    at com.mysql.jdbc.StatementImpl.close(StatementImpl.java:532)
    at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.mysql.jdbc.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:103)
      - locked com.mysql.jdbc.LoadBalancedConnectionProxy@155d2dea
    at com.sun.proxy.$Proxy7.close(Unknown Source)
    at com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java:76)
    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:77)
    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
    at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
    at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
    at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
    at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
    at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
    at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
    at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@bc0f752
```
```
connection closer id=16614 state=BLOCKED
    - waiting to lock <0x6649c156> (a com.mysql.jdbc.JDBC4ReplicationMySQLConnection)
     owned by slick-db-8 id=451
    at com.mysql.jdbc.ReplicationMySQLConnection.getCurrentConnection(ReplicationMySQLConnection.java:46)
    at com.mysql.jdbc.ReplicationMySQLConnection.getActiveMySQLConnection(ReplicationMySQLConnection.java:42)
    at com.mysql.jdbc.MultiHostMySQLConnection.setNetworkTimeout(MultiHostMySQLConnection.java:2323)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.mysql.jdbc.ReplicationConnectionProxy.invokeMore(ReplicationConnectionProxy.java:309)
    at com.mysql.jdbc.MultiHostConnectionProxy.invoke(MultiHostConnectionProxy.java:452)
    at com.sun.proxy.$Proxy3.setNetworkTimeout(Unknown Source)
    at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:516)
    at com.zaxxer.hikari.pool.PoolBase.quietlyCloseConnection(PoolBase.java:133)
    at com.zaxxer.hikari.pool.HikariPool.lambda$closeConnection$5(HikariPool.java:419)
    at com.zaxxer.hikari.pool.HikariPool$$Lambda$8/688491727.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@747d5d1a
```

**Comment by brettwooldridge** [comment]
@Gabol While this may be an issue that was surfaced by a timing change in HikariCP or Slick, the deadlock is squarely in MySQL's court.  It certainly looks like a deadlock between a lock they acquire in ``setNetworkTimeout()`` and ``com.mysql.jdbc.ReplicationConnectionProxy.getCurrentConnection()``.

**Comment by brettwooldridge** [comment]
I take that back.  It is possible that the lock is held by Slick (``waiting to lock...owned by slick-db-8 id=451``).

**Comment by Gabol** [comment]
According to MySQL driver changelog it doesn't seem to be fixed. 
I'll try to reproduce the bug with previous version of slick, play with different connection pools and report back if there's any new information. 
Thanks!

**Comment by Gabol** [comment]
I've downgraded to slick 3.2.0-M1 and the problem seems to disappear.
Still have no idea, what was going wrong.
Anyway, thanks for help!
