### ISSUE TITLE
NoClassDefFoundError PGSQL

### ISSUE THREAD

**Issue by 0lig** [brettwooldridge/HikariCP#855]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : 9.4.1212
```

Caught this exception once during normal operations, was unable to reproduce it again by the same chain of calls
-----------------------------------------------------------------------------------------

```
java.lang.NoClassDefFoundError: org/postgresql/core/EncodingPredictor$DecodeResult
  at org.postgresql.core.PGStream.receiveErrorString(PGStream.java:350)
  at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2448)
  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
  at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
  at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
  at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
  at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
  at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
  at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:233)
  at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:108)
  at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
```

**Comment by brettwooldridge** [comment]
Doesn't make much sense, but could be caused by two versions of the PostgreSQL driver in your path.
