### ISSUE TITLE
Reconnect to database

### ISSUE THREAD

**Issue by jiangxiaoqiang** [brettwooldridge/HikariCP#875]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_111
Database        : DM(Oracle like，made in China)
Driver version  : 17
```
-----------------------------------------------------------------------------------------

When restart DB,it throws `connection error`,could support reconnect when DB restart or network failer?

`2017-04-26 12:46:46.647 [http-nio-28080-exec-10] ERROR c.web.controllers.CreditsystemControllerAdvice - 运行异常
org.springframework.dao.DataAccessResourceFailureException: 
### Cause: java.sql.SQLException: Communication  error
; SQL []; Communication  error; nested exception is java.sql.SQLException: Communication  error
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:105)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy81.selectList(Unknown Source)
`

**Comment by brettwooldridge** [comment]
I don't see HikariCP anywhere in that stacktrace.
