### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by lzy1g1225** [brettwooldridge/HikariCP#886]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_121
Database        : MySQL
Driver version  : 6.0.6
```
-----------------------------------------------------------------------------------------
When I using HikariCP, I caught this error when starting up my project.
`Caused by: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
	at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:415)
	at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:851)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at com.baomidou.mybatisplus.entity.GlobalConfiguration.setMetaData(GlobalConfiguration.java:237)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:531)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
`
I am using spring+mybatis+log4j. Seems like a logger error. Does HikariCP use SLF4J and didn't mention it in documentation?
Note I just moved to hikariCP from C3P0, everything is fine when I using c3p0. All I have modified is the datasource configuration below.
`<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <property name="dataSourceClassName" value="${driver}"/>
        <property name="jdbcUrl" value="${url}"/>
        <property name="username" value="${username}"/>
        <property name="password" value="${password}"/>
        <property name="maximumPoolSize" value="${maxPoolSize}"/>
        <property name="allowPoolSuspension" value="${allowPoolSuspension}"/>
        <property name="initializationFailTimeout" value="${initializationFailTimeout}"/>
        <property name="maxLifetime" value="${maxLifetime}"/>
        <property name="connectionTimeout" value="${connectionTimeout}"/>
    </bean>`

**Comment by lzy1g1225** [comment]
OK, I got that problem. By searching in the maven repository, I found out the HikariCP has compile dependencies: SLFJ and javaassist. I will not closed the issue, for you to know this. It will be more clear to add these two dependencies to the documentation. And won't let those newbies turn back to c3p0.

**Comment by brettwooldridge** [comment]
@lzy1g1225 The requirements are documented at the [bottom of the main page](https://github.com/brettwooldridge/HikariCP#requirements).  Javassist should be a compile only dependency, not a runtime dependency.
