### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: You need to run the CLI build and you need target/classes in your classpath to run.

### ISSUE THREAD

**Issue by reyoreyo** [brettwooldridge/HikariCP#908]
HikariCP version: HikariCP-2.6.2
JDK version     : 1.8.0_102
Database        :MySQL
Driver version  : 5.5
```
-----------------------------------------------------------------------------------------
The code is there
package reyo.sdk.utils.test.Hikari;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

public class TestPool {

	public static void main(String[] args) throws SQLException {
		Statement stmt = null;
		ResultSet rs = null;
		Connection conn = null;

		HikariConfig config = new HikariConfig();
		config.setDriverClassName("com.mysql.jdbc.Driver");
		config.setJdbcUrl(
				"jdbc:mysql://localhost:3306/test?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8");
		config.setUsername("root");
		config.setPassword("123");
		config.addDataSourceProperty("cachePrepStmts", "true");
		config.addDataSourceProperty("prepStmtCacheSize", "250");
		config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
		HikariDataSource ds = new HikariDataSource(config);

		try {

			conn = ds.getConnection();
			stmt = conn.createStatement();
			rs = stmt.executeQuery("SELECT * FROM test");
			while (rs.next()) {
				System.out.println(rs.getString(2));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			if (stmt != null) {
				stmt.close();
			}

			if (rs != null) {
				rs.close();
			}

			if (conn != null) {
				conn.close();
			}
			if (ds != null) {
				ds.close();
			}
		}
	}

}

The Error

Exception in thread "main" java.lang.IllegalStateException: You need to run the CLI build and you need target/classes in your classpath to run.
	at com.zaxxer.hikari.pool.ProxyFactory.getProxyConnection(ProxyFactory.java:55)
	at com.zaxxer.hikari.pool.PoolEntry.createProxyConnection(PoolEntry.java:97)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:176)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at reyo.sdk.utils.test.Hikari.TestPool.main(TestPool.java:44)

**Comment by brettwooldridge** [comment]
@reyoreyo Something else is going on.  It works for me.

Here is what I did to try your code:
```
bash$ mvn archetype:generate -Dfilter=com.github.ngeor:archetype-quickstart-jdk8
...
Choose archetype:
1: remote -> com.github.ngeor:archetype-quickstart-jdk8 (A Maven archetype for a simple Java app, updated for Java 8)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): : 1
Choose com.github.ngeor:archetype-quickstart-jdk8 version:
1: 1.0.14
2: 1.0.22
3: 1.0.27
4: 1.0.29
Choose a number: 4: 4
Define value for property 'groupId': reyo.sdk
Define value for property 'artifactId': sdk
Define value for property 'version' 1.0-SNAPSHOT: :
Define value for property 'package' reyo.sdk: : reyo.sdk.utils.test.Hikari
Confirm properties configuration:
groupId: reyo.sdk
artifactId: sdk
version: 1.0-SNAPSHOT
package: reyo.sdk.utils.test.Hikari
 Y: : y

bash$ cd sdk
bash$ vi pom.xml
```
Added to ``pom.xml``:
```xml
<dependency>
    <groupId>com.zaxxer</groupId>
    <artifactId>HikariCP</artifactId>
    <version>2.6.2</version>
</dependency>
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.42</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.25</version>
</dependency>
```
Then I created the your file:
```
bash$ mkdir -p src/main/java/reyo/sdk/utils/test/Hikari
bash$ vi TestPool.java

# copy/pasted your code, change password for my local MySQL, saved file.
# created "test" table with data...
```
Finally, I ran it:
```
bash$ mvn exec:java -Dexec.mainClass=reyo.sdk.utils.test.Hikari.TestPool -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
```
Output:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sdk 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ sdk ---
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>, prepStmtCacheSqlLimit=2048, cachePrepStmts=true, prepStmtCacheSize=250}
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................."com.mysql.jdbc.Driver"
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........true
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl........................."jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8"
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................10
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-1"
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutorService........internal
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - username........................"brettw"
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
[reyo.sdk.utils.test.Hikari.TestPool.main()] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3c7e5a15
[reyo.sdk.utils.test.Hikari.TestPool.main()] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
brett
brettw
brettwooldridge
[reyo.sdk.utils.test.Hikari.TestPool.main()] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before shutdown stats (total=1, active=0, idle=1, waiting=0)
[HikariPool-1 connection closer] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@3c7e5a15: (connection evicted)
[reyo.sdk.utils.test.Hikari.TestPool.main()] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After shutdown stats (total=0, active=0, idle=0, waiting=0)
[reyo.sdk.utils.test.Hikari.TestPool.main()] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
```

**Comment by brettwooldridge** [comment]
@reyoreyo By the way, do not use ``autoReconnect=true`` with HikariCP or any connection pool, it is not designed for that and can interfere with the pool.

**Comment by katlog** [comment]
I just want to know, how to run these test cases in the test package, especially in IDE, which i use idea. It will throw "You need to run the CLI build and you need target/classes" when i run these test cases in ide. Because of source code do not include 'ProxyClass' should be generate by javassist ?

**Comment by brettwooldridge** [comment]
@katlog What IDE? Does the IDE support Maven projects?

**Comment by katlog** [comment]
> @katlog What IDE? Does the IDE support Maven projects?

intellij idea. 

thx. The problem solved, when i run the class TestJavassistCodegen main method, which generate thoese 'ProxyClass' class files, for example HikariProxyConnection.class etc.
