### ISSUE TITLE
DB connections not getting closed

### ISSUE THREAD

**Issue by marodriguez-llbean** [brettwooldridge/HikariCP#912]
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_111
Database        : DB2
Driver version  : jdbc Type 4
```
-----------------------------------------------------------------------------------------
Hi, we have a Java app running in the cloud on top of Jetty and have hystrix commands wrapping each call to DB. Also we are using the following datasource config settings enabled a fixed-size connection pool:
```xml
       <New class="com.zaxxer.hikari.HikariDataSource">
         <Arg>
            <New class="com.zaxxer.hikari.HikariConfig">
               <Set name="jdbcUrl"><Env name="CONNECTION_URL"/></Set>
               <Set name="maximumPoolSize">10</Set>
               <Set name="driverClassName">com.ibm.db2.jcc.DB2Driver</Set>
               <Set name="username"><Env name="USERNAME"/></Set>
               <Set name="password"><Env name="PASSWORD"/></Set>
               <Call name="addDataSourceProperty">
                  <Arg>cachePrepStmts</Arg>
                  <Arg>true</Arg>
               </Call>
               <Call name="addDataSourceProperty">
                  <Arg>prepStmtCacheSize</Arg>
                  <Arg>250</Arg>
               </Call>
               <Call name="addDataSourceProperty">
                  <Arg>prepStmtCacheSqlLimit</Arg>
                  <Arg>2048</Arg>
               </Call>
            </New>
         </Arg>
      </New>
```
The app starts running fine just after some hours of execution, we are noticing this error "Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003" that suggest the connection pool serving an already closed connection as if it were still active.

Do we need to tweak other connection pool properties to prevent this error to happen ?

thanks

Below the stacktrace
```java
2017-06-10 16:38:23 [QA] [App Name:domain-data-cache] [qtp1639622804-3877] ERROR c.l.p.h.d.c.rest.AppExceptionMapper - Unknown runtime exception. ReferenceId = 3a5c004c-5da8-4c37-a6b1-fc32340a3563 com.google.common.util.concurrent.UncheckedExecutionException: com.netflix.hystrix.exception.HystrixRuntimeException: ReadCountryDesc failed and no fallback available. 
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
 at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
 at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
 at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
 at com.llbean.purchase.history.domain.cache.retrieval.DomainDataManager.getCountryDescCacheValue(DomainDataManager.java:231)
 at com.llbean.purchase.history.domain.cache.rest.InitiationResource.getCacheValue(InitiationResource.java:85)
 at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
 at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
 at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
 at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
 at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
 at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
 at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
 at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
 at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
 at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
 at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
 at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.Server.handle(Server.java:564)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
 at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
 at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
 at java.lang.Thread.run(Thread.java:745) Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: ReadCountryDesc failed and no fallback available.
 at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:808)
 at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:793)
 at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
 at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1454)
 at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1379)
 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
 at rx.observers.Subscribers$5.onError(Subscribers.java:230)
 at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
 at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
 at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1176)
 at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
 at rx.observers.Subscribers$5.onError(Subscribers.java:230)
 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
 at rx.observers.Subscribers$5.onError(Subscribers.java:230)
 at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1413)
 at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1344)
 at rx.observers.Subscribers$5.onError(Subscribers.java:230)
 at rx.observers.Subscribers$5.onError(Subscribers.java:230)
 at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
 at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
 at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 at rx.Observable.unsafeSubscribe(Observable.java:10151)
 at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
 at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
 at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
 at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ... 1 common frames omitted Caused by: javax.persistence.PersistenceException: com.ibm.db2.jcc.am.SqlNonTransientConnectionException: [jcc][t4][10335][10366][4.21.29] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
 at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
 at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
 at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1700)
 at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:48)
 at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
 at com.llbean.purchase.history.domain.cache.retrieval.command.ReadCountryDescCommand.run(ReadCountryDescCommand.java:31)
 at com.llbean.purchase.history.domain.cache.retrieval.command.ReadCountryDescCommand.run(ReadCountryDescCommand.java:12)
 at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301)
 at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297)
 at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ... 26 common frames omitted 
 Caused by: com.ibm.db2.jcc.am.SqlNonTransientConnectionException: [jcc][t4][10335][10366][4.21.29] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
 at com.ibm.db2.jcc.am.kd.a(kd.java:800)
 at com.ibm.db2.jcc.am.kd.a(kd.java:66)
 at com.ibm.db2.jcc.am.kd.a(kd.java:133)
 at com.ibm.db2.jcc.am.Connection.checkForClosedConnection(Connection.java:6099)
 at com.ibm.db2.jcc.am.Connection.setAutoCommit(Connection.java:1165)
 at com.zaxxer.hikari.proxy.ConnectionProxy.setAutoCommit(ConnectionProxy.java:334)
 at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.setAutoCommit(ConnectionJavassistProxy.java)
 at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:67)
 at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:235)
 at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214)
 at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:52)
 at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1525)
 at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:45) ... 32 common frames omitted
```

**Comment by brettwooldridge** [comment]
@marodriguez-llbean A couple of things...

Unrelated to the problem, but worth pointing out is that ``cachePrepStmts``, ``prepStmtCacheSize``, and ``prepStmtCacheSqlLimit`` are specific to the MySQL driver and will have no effect on DB2.

I find a lot of occurances on Google when searching for ``db2 "errorcode" "4470" "sqlstate=08003"``.  This link seems to fit most closely:

http://www-01.ibm.com/support/docview.wss?uid=swg21647500

I.e. the error is thrown when ``getAutoCommit/setAutoCommit()`` is called, as in the stack trace above.

Another thread suggests added an explicit validation query, in your case:
```xml
<Set name="connectionTestQuery">SELECT 1 FROM sysibm.sysdummy1</Set>
```

**Comment by brettwooldridge** [comment]
@marodriguez-llbean No solution here per-se but this shows an application getting an almost identical stacktrace with Tomcat dbcp pool:

https://stackoverflow.com/questions/24819524/grails-datasource-db2-issue-connection-closed

Some other threads point to this error occuring when there are unclosed ResultSets or Statements.

In any case, this is either a DB2 configuration issue, or application level issue.  You might consider asking on stackoverflow, though there seem to be a lot of unanswered threads there, or maybe contact IBM DB2 support for assistance.
