### ISSUE TITLE
ClassNotFoundException While ShuttingDown Apache Felix Using H2

### ISSUE THREAD

**Issue by xipki** [brettwooldridge/HikariCP#933]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_121
Database        : H2
Driver version  : 1.4.195
```
-----------------------------------------------------------------------------------------

I got the same error as #298 
[hikaricp-h2-bug.zip](https://github.com/brettwooldridge/HikariCP/files/1134981/hikaricp-h2-bug.zip)
 , even the DataSource is closed explicty. I use apache karaf 4.0.9, HikariCP 2.6.2 and H2 database 1.4.195. The maven project to reproduce the bug is attached.

Here is the error trace:
```
karaf@root()> install file:jars/h2-1.4.195.jar 
Bundle ID: 53
karaf@root()> install file:jars/HikariCP-2.6.2.jar 
Bundle ID: 54
karaf@root()> install file:jars/hikaricp-h2-bug-0.1.0-SNAPSHOT.jar 
Bundle ID: 55
karaf@root()> start 55
Created H2 DataSoruce
karaf@root()> list
START LEVEL 100 , List Threshold: 50
ID | State    | Lvl | Version        | Name
---------------------------------------------------------
53 | Resolved |  80 | 1.4.195        | H2 Database Engine
54 | Resolved |  80 | 2.6.2          | HikariCP
55 | Active   |  80 | 0.1.0.SNAPSHOT | hikaricp-h2-bug
karaf@root()> uninstall 55
Closing H2 DataSoruce
Closed H2 DataSoruce
karaf@root()> ^Dkaraf@root()> 
Exception in thread "Thread-18" java.lang.NoClassDefFoundError: org/h2/mvstore/MVMap$2
	at org.h2.mvstore.MVMap.entrySet(MVMap.java:870)
	at org.h2.store.LobStorageMap.removeAllForTable(LobStorageMap.java:314)
	at org.h2.engine.Database.removeOrphanedLobs(Database.java:1340)
	at org.h2.engine.Database.close(Database.java:1261)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.h2.mvstore.MVMap$2' because the bundle wiring for org.h2 is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1539)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```
[hikaricp-h2-bug.zip](https://github.com/brettwooldridge/HikariCP/files/1046030/hikaricp-h2-bug.zip)

**Comment by brettwooldridge** [comment]
@xipki Thanks for the zip, but I don't have a Karaf installation, so it doesn't help that much.

**Comment by xipki** [comment]
@brettwooldridge Thanks for excellent project. I updated the issue description.
