### ISSUE TITLE
Can't use settings from TNSNAMES.ORA

### ISSUE THREAD

**Issue by Ptitlaby** [brettwooldridge/HikariCP#939]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_121
Database        : Oracle
Driver version  : 12.1.0.2.0
```
-----------------------------------------------------------------------------------------
I am unable to use settings from the TNSNAMES.ORA stored on the same server

Here is the code I am using :

```

        HikariConfig hc = new HikariConfig();
        hc.setUsername(username);
        hc.setPassword(password);
        hc.setDataSourceClassName("oracle.jdbc.pool.OracleDataSource");
        hc.addDataSourceProperty("serverName", TNS);
        hc.addDataSourceProperty("portNumber", 1521);
        hc.addDataSourceProperty("driverType", "thin");


        HikariDataSource hds = new HikariDataSource(hc);
        hds.setPoolName("Pool::"+username+"@"+dbName);
```
the TNS variable comes from my config, and reference a setting in the TNSNAMES.ora files present on the server.
```

SERVER_1 =
    (DESCRPTION = 
        (ADDRESS_LIST = 
                (ADDRESS = (PROTOCOL = TCP)(HOST = server01.intranet)(PORT = 1521))
        )
        (CONNECTION_DATA = 
                (SERVICE_NAME = SERVER1)
        )
    )
```
The code fails with the following stacktrace :

```
INFO  HikariPool-1 - Starting...
ERROR HikariPool-1 - Exception during pool initialization.
java.sql.SQLRecoverableException: Erreur d'E/S: The Network Adapter could not establish the connection
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
    at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
    at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
    at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
    at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:317)
    at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:241)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
    at com.test.commonlib.config.DbConfigReader.getDataSource(DbConfigReader.java:105)
    at com.test.commonlib.config.DbConfigReader.getDataSource(DbConfigReader.java:31)
    at com.test.module1.Module1.getConnectionModule1(Module1.java:258)
    at com.test.module1.fileinjector.fd.loadConf(fd.java:583)
    at com.test.module1.fileinjector.fd.<init>(fd.java:78)
    at com.test.module1.fileinjector.fd.getInstance(fd.java:84)
    at com.test.module1.Module1.init(Module1.java:78)
    at com.test.module1.scripts.TestPerso.TestPerso.testModule1(TestPerso.java:2009)
    at com.test.module1.scripts.TestPerso.TestPerso.main(TestPerso.java:145)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
    at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
    at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:506)
    at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:595)
    at oracle.net.ns.NSProtocol.connect(NSProtocol.java:230)
    at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
    ... 20 more
Caused by: java.net.UnknownHostException: SERVER_1
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
    at java.net.InetAddress.getAllByName(InetAddress.java:1192)
    at java.net.InetAddress.getAllByName(InetAddress.java:1126)
    at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:120)
    at oracle.net.nt.ConnOption.connect(ConnOption.java:159)
    at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:428)
    ... 25 more
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Erreur d'E/S: The Network Adapter could not establish the connection
    at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:543)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:535)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
    at com.test.commonlib.config.DbConfigReader.getDataSource(DbConfigReader.java:105)
    at com.test.commonlib.config.DbConfigReader.getDataSource(DbConfigReader.java:31)
    at com.test.module1.Module1.getConnectionModule1(Module1.java:258)
    at com.test.module1.fileinjector.fd.loadConf(fd.java:583)
    at com.test.module1.fileinjector.fd.<init>(fd.java:78)
    at com.test.module1.fileinjector.fd.getInstance(fd.java:84)
    at com.test.module1.Module1.init(Module1.java:78)
    at com.test.module1.scripts.TestPerso.TestPerso.testModule1(TestPerso.java:2009)
    at com.test.module1.scripts.TestPerso.TestPerso.main(TestPerso.java:145)
Caused by: java.sql.SQLRecoverableException: Erreur d'E/S: The Network Adapter could not establish the connection
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
    at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
    at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
    at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
    at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:317)
    at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:241)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
    ... 11 more
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
    at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
    at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:506)
    at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:595)
    at oracle.net.ns.NSProtocol.connect(NSProtocol.java:230)
    at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
    ... 20 more
Caused by: java.net.UnknownHostException: SERVER_1
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
    at java.net.InetAddress.getAllByName(InetAddress.java:1192)
    at java.net.InetAddress.getAllByName(InetAddress.java:1126)
    at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:120)
    at oracle.net.nt.ConnOption.connect(ConnOption.java:159)
    at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:428)
    ... 25 more

```

I am obviously missing something there. Is it even possible to use settings from the TNSNAMES.ORA files ? I quickly searched the source for the strings "tnsnames" and "tns" to no avail

**Comment by Ptitlaby** [comment]
Please note that the following code works however :

```
        HikariConfig hc = new HikariConfig();
        hc.setUsername(username);
        hc.setPassword(password);
        hc.setJdbcUrl("jdbc:oracle:thin:@SERVER_1")

        HikariDataSource hds = new HikariDataSource(hc);
        hds.setPoolName("Pool::"+username+"@"+dbName);

```

I wish I could use it in the datasource. Is there a property I am missing ?

**Comment by lfbayer** [comment]
Calling `addDataSourceProperty` on the `HikariConfig` just passes through to the setter on the `OracleDataSource` itself.  Does creating the `OracleDataSource` without using HikariCP and calling `setServerName` directly actually work? This sounds like it is more likely to be a driver bug than a HikariCP issue.
