### ISSUE TITLE
Error: Failed to submit a listener notification task. Event loop shut down?

### ISSUE THREAD

**Issue by bazi** [brettwooldridge/HikariCP#961]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_131
Database        : PostgreSQL
Driver version  : pgjdbc-ng 0.7.1
```
-----------------------------------------------------------------------------------------

We had a service interruption over the past weekend. Looking up in log files revealed error messages given below.
We were looking at error-level messages first that were all the same. Then we reached the beginning of error messages where we faced a warning-level OOM messages which made clear the reason of the issue.

I am thinking if there is a memory leak in our app or there are some issues in underlying libraries? May be in HikariCP or may be in Netty whose package names abundantly appear in log messages?

Additional info: the app had run for two months and there were no issues on DB side. `-Xmx320m` is used to launch the app in an instance with 1GB memory. The app usually uses from 30 to 60 percent of available memory.

```
2017-08-26 04:20:07,124  WARN [PG-JDBC EventLoop (1)] i.n.c.n.NioEventLoop Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: Java heap space
        at io.netty.channel.AdaptiveRecvByteBufAllocator.newHandle(AdaptiveRecvByteBufAllocator.java:181)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.recvBufAllocHandle(AbstractChannel.java:434)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)

[removed lines here]

2017-08-26 04:23:18,106  WARN [GrouviDBPool housekeeper] c.z.h.p.HikariPool GrouviDBPool - Thread starvation or clock leap detected (housekeeper delta=50s794ms378µs342ns).
2017-08-26 04:23:18,734 ERROR [PG-JDBC Housekeeper] i.n.u.c.D.rejectedExecution Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
        at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113)
        at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
        at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1010)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.shutdown(ProtocolImpl.java:238)
        at com.impossibl.postgres.jdbc.PGConnectionImpl$Cleanup.run(PGConnectionImpl.java:169)
        at com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference.cleanup(ThreadedHousekeeper.java:129)
        at com.impossibl.postgres.jdbc.ThreadedHousekeeper$1.run(ThreadedHousekeeper.java:195)

```

**Comment by brettwooldridge** [comment]
It is likely that HikariCP was a victim of OOM rather than the perpetrator.

I did notice that you are using the pgjdbc-ng driver, which I have recommended in the past. But activity seems to have dissipated as of late.  You might also consider trying the official driver.

**Comment by brettwooldridge** [comment]
You might also look into the JVM option that automatically creates a heap dump file on OOM...

**Comment by bazi** [comment]
Indeed, last activity on pgjdbc-ng driver was on Feb 2017. Seems need to switch back to official driver.
Thanks for your comments! Closing this issue as it is basically an OOM problem.
