### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by wesoos** [brettwooldridge/HikariCP#963]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 5.1.42
```
-----------------------------------------------------------------------------------------

Hello, I'm starting to see a lot of the following in my logs.  Should I increase my pool size?  My current size is at 15 each, with two web apps behind a load balancer.

`Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30014ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:115)`

**Comment by brettwooldridge** [comment]
Not enough information to tell.  Enable DEBUG logging for com.zaxxer.hikari and watch the pool stats logged every 30s.  Configuring a metrics collector like DropWizard or Prometheus might be useful as well.
