### ISSUE TITLE
Interrupted during connection acquisition

### ISSUE THREAD

**Issue by I-am-zxdong** [brettwooldridge/HikariCP#976]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_91
Database        : MySQL
Driver version  : 5.1.15
org.apache.ibatis.exceptions.PersistenceException: 
### Error opening session.  Cause: java.sql.SQLException: HikariPool-4 - Interrupted during connection acquisition
### Cause: java.sql.SQLException: HikariPool-4 - Interrupted during connection acquisition
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:8)
        at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:83)
        at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:36)
        at com.elex.cok.utils.MyBatisSessionUtil.getAutoCommitSession(MyBatisSessionUtil.java:105)
Caused by: java.sql.SQLException: HikariPool-4 - Interrupted during connection acquisition
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:188)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
        at com.elex.cok.utils.HikariCPDataSourceBase.getConnection(HikariCPDataSourceBase.java:163)
        at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:73)
        ... 11 common frames omitted

Caused by: java.lang.InterruptedException: null
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:944)
        at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:157)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:165)
        ... 15 common frames omitted

-----------------------------------------------------------------------------------------
what make the exception?i don't think  it caused by the SIGTERM

**Comment by brettwooldridge** [comment]
Something called interrupt() on the Thread that was waiting for a connection.  Definitely not a HikariCP problem.

**Comment by tjsingleton** [comment]
@brettwooldridge Didn't the internal SynchronousQueue throw the InterruptedException? 

* https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java#L157
* https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/SynchronousQueue.html#poll-long-java.util.concurrent.TimeUnit-

**Comment by tjsingleton** [comment]
I misread the docs. Ignore me. :)
