### ISSUE TITLE
Application could not connect to database if  i start application then database start

### ISSUE THREAD

**Issue by ayubsarker** [brettwooldridge/HikariCP#997]
I am using play 2.5 and HikarCP  as connection pool.  I start application in following way

1. Shutdown the Database 
2. Start application
3. send requests to application that have some database transaction
4. I can see the log, Pool could not connect the database which ok as database is down
5. Start Database
6.   I can see the log, Pool could not connect the database which is  wrong. as now databse is up.

here is my HokarCP config

   ```
    autoCommit = true
       connectionTimeout = 5 seconds
       idleTimeout = 5 minutes
       maxLifetime = 10 minutes
       connectionTestQuery =  SELECT 1
       minimumIdle = 5
       maximumPoolSize = 25
       poolName = keymaker-pool

       initializationFailTimeout = 0
       isolateInternalQueries = false
       allowPoolSuspension = false
       readOnly = false
       registerMbeans = false
       catalog = null

       connectionInitSql = SELECT 1
       transactionIsolation = null
       validationTimeout = 5 seconds
       leakDetectionThreshold = 15 seconds
```

#### Environment
```
HikariCP version: 2.7.1
JDK version     : 1.8.0_121
Database        : PostgreSQL
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
@ayubsarker Can you enable DEBUG level logging and attach the log here, covering the transition from DB-down to DB-up.  I assume when you write ``"5 seconds"`` etc. above your actualy configuration has valid values (``300000`` etc.).

Also, check that the JVM is not caching the *DNS lookup failure* when the DB is down.  Java *does* cache DNS *failures* and will not re-resolve for quite an extended amount of time.  [See this thread](https://github.com/brettwooldridge/HikariCP/issues/314) for info on how to set the TTL.

**Comment by ayubsarker** [comment]
here is the application log
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Connection to 10.80.10.111:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:548)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:540)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:58)
        at play.api.db.HikariCPConnectionPool$$anonfun$1.apply(HikariCPModule.scala:54)
        at scala.util.Try$.apply(Try.scala:192)
        at play.api.db.HikariCPConnectionPool.create(HikariCPModule.scala:54)
        at play.api.db.PooledDatabase.createDataSource(Databases.scala:200)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:124)
Caused by: org.postgresql.util.PSQLException: Connection to 10.80.10.111:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
        at org.postgresql.Driver.makeConnection(Driver.java:450)
        at org.postgresql.Driver.connect(Driver.java:252)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:376)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:448)

**Comment by brettwooldridge** [comment]
When the master goes down, and the application requests a connection, and HikariCP tries to validate a connection to return, HikariCP is running into unacknowledged TCP issues.  Unfortunately, there is nothing HikariCP itself can do in this case without the assistance of the driver.

This is a big problem, and one that can only be addressed by the driver.  pgjdbc does not support Connection.setNetworkTimeout(). 

I have an outstanding pull request pgjdbc/pgjdbc#849 that has been waiting quite a while to be merged.  Please vote for it.  It borders on unbelievable that PostgreSQL, a supposedly enterprise class database, still does not support a feature so critical to reliability.

**Comment by danjmarques** [comment]
(@ayubsarker and I are co-workers)

@brettwooldridge  I was hoping you could help provide some more clarity as to how HikariCP operates and what is causing this issue.  

Our scenario:

If our database (postgres) is down when the play application starts, we (as expected) see database connection failures upon trying to execute queries.  We then bring the database up.

Upon the database coming up, we see successful connections to it (i.e. we see on the Postgres side that there are connections, and that the are running the "select 1" test query).

Now we attempt to execute another query vs the database.  This fails with the exception above.

Discussion:

Take a look at this log snippet once the database has come up.  It looks like we added a total of 10 jdbc connections (yet only a total of 5 are being reported).

	2017-10-18 16:41:49,027 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=0, active=0, idle=0, waiting=0)
	2017-10-18 16:41:49,027 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - After cleanup  stats (total=0, active=0, idle=0, waiting=0)
	2017-10-18 16:41:57,702 [INFO] from com.zaxxer.hikari.pool.PoolBase in keymaker-pool connection adder - keymaker-pool - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
	2017-10-18 16:41:57,702 [INFO] from com.zaxxer.hikari.pool.PoolBase in keymaker-pool connection adder - keymaker-pool - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
	2017-10-18 16:41:57,776 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@1f0c40f1
	2017-10-18 16:41:57,776 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@66ee65b4
	2017-10-18 16:41:57,817 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@fd77fed
	2017-10-18 16:41:57,830 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@2dc804f6
	2017-10-18 16:41:57,837 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@7f822ce3
	2017-10-18 16:41:57,845 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@6d4d58c1
	2017-10-18 16:41:59,258 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
	2017-10-18 16:41:59,258 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
	2017-10-18 16:42:02,785 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@99d76a2
	2017-10-18 16:42:02,792 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@62e8081d
	2017-10-18 16:42:02,799 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@47a2261
	2017-10-18 16:42:02,805 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@57b41c08
	2017-10-18 16:42:19,025 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=5, active=0, idle=5, waiting=0)

If the connections to Postgres have been made, what "unacknowledged TCP issues" are we running into?

**Comment by danjmarques** [comment]
@brettwooldridge - The following program works correctly in the scenario we described (starting it with the database down, then bringing it up).  So I'm not certain it is due to a limitation on the driver or unacknowledged TCP stuff.  Would you know how Play creates the data source (is it different from how its done in this example) or how it deals with the exception thrown when it tries to tries to create it when it is down?

Thanks in advance.

`   public static void main(String[] args) throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:postgresql://xxxxx:5432/djm_test");
        config.setUsername("postgres");
        config.setPassword("postgres");
        config.addDataSourceProperty("connectionTestQuery", "SELECT 1");
        config.addDataSourceProperty("connectionInitSql", "SELECT 1");
        config.addDataSourceProperty("connectionTimeout", "5000");
        config.addDataSourceProperty("validationTimeout", "5000");
        config.addDataSourceProperty("idleTimeout", "300000");
        config.addDataSourceProperty("maxLifetime", "600000");
        config.addDataSourceProperty("minimumIdle", "5");
        config.addDataSourceProperty("maximumPoolSize", "25");
        config.addDataSourceProperty("initializationFailTimeout", "0");
        
        HikariDataSource ds = null;

        while(true) {
            try {
                while(ds == null) {
                    ds = new HikariDataSource(config);
                }

                try (Connection c = ds.getConnection()) {
                    Statement statement = c.createStatement();
                    ResultSet rs = statement.executeQuery("Select * from public.test_table");
                    while (rs.next()) {
                        System.out.println("Name " + rs.getString("name"));
                        System.out.println("UUID " + rs.getInt("uid"));
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
            catch (Exception e){
                System.out.println(e);
            }
            Thread.sleep(10000);
        }
    }`

**Comment by brettwooldridge** [comment]
@danjmarques I will investigate further.  I don't really know much about Play and how it sets up or controls connections.  It might be more fruitful to ask that question in the Play user forum.

I do want to make note of some "oddities" in the log you provided.

1) Note that HikariCP connection acquisition is [single threaded](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/UtilityElf.java#L113).
2) Note that during connection acquisition, HikariCP calls a method, [getAndSetNetworkTimeout()](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L515).  Calling this method will result in a member variable, ``isNetworkTimeoutSupported``, being set to *either* ``TRUE`` or ``FALSE``.  There is no escape from that method without ``isNetworkTimeoutSupported`` being assigned one of those two values.

Based on both of the two points above, it should only be possible for the message *"Driver does not support get/set network timeout for connections"* to be emitted *once*.  And yet, in the log, we see it emitted twice...
```
2017-10-18 16:41:57,702 [INFO] from com.zaxxer.hikari.pool.PoolBase in keymaker-pool connection adder - keymaker-pool - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
2017-10-18 16:41:57,702 [INFO] from com.zaxxer.hikari.pool.PoolBase in keymaker-pool connection adder - keymaker-pool - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
```
Strange.

Next.

3) The message *"Added connection..."* is emitted in two places in the code, [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L520) during initialization, and [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L635) at all other times a connection is added.
4) The *"Added connection..."* method is always called *after* a call to [ConcurrentBag.add()](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java#L206).  ``ConcurrentBag.add()`` adds the connection to a ``CopyOnWriteArrayList`` called ``sharedList``.
5) The *HouseKeeper* thread calls [logPoolState()](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L388), which in turn calls [getTotalConnections()](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L336), which in turn calls [ConcurrentBag.size()](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java#L365), which finally calls ``sharedList.size()`` on the ``CopyOnWriteArrayList``.

Therefore, it is *impossible* for a connection to be added but not be reflected in the pool stats, if the pool stats are logged after the *"Added connection..."* log appears.

And yet, five connection adds were logged, but the pool stats indicate only single connection in the pool.
```
2017-10-18 16:41:57,776 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@1f0c40f1
2017-10-18 16:41:57,776 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@66ee65b4
2017-10-18 16:41:57,817 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@fd77fed
2017-10-18 16:41:57,830 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@2dc804f6
2017-10-18 16:41:57,837 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@7f822ce3
2017-10-18 16:41:57,845 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool connection adder - keymaker-pool - Added connection org.postgresql.jdbc.PgConnection@6d4d58c1
2017-10-18 16:41:59,258 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
2017-10-18 16:41:59,258 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
```
Because this is *literally impossible*, there must be another explanation.

I find some clues here...
```
2017-10-18 16:41:49,027 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=0, active=0, idle=0, waiting=0)
2017-10-18 16:41:49,027 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - After cleanup  stats (total=0, active=0, idle=0, waiting=0)
...
2017-10-18 16:41:59,258 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
2017-10-18 16:41:59,258 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
...
2017-10-18 16:42:19,025 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in keymaker-pool housekeeper - keymaker-pool - Before cleanup stats (total=5, active=0, idle=5, waiting=0)
```
The *HouseKeeper* runs [every 30 seconds](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L138).  So, how it is possible to get logs at ``16:41:49,027`` and ``16:41:59,258``?

This indicates to me that there are *two* pools running.  Which explains the two *"Driver does not support get/set network timeout for connections"* messages, which also should not be possible in the case of a single pool instance.

**Comment by brettwooldridge** [comment]
@danjmarques As a side-note, the unacknowledged TCP issue is unrelated, and its mention probably the result of my lack of sleep.  It would only come into play if a database to which HikariCP was already connected went *down*.  Your case is the opposite.  There are no connections, and then the database is brought *up*.  Sorry for the confusion, you can ignore it as it does not apply in this case.
