### ISSUE TITLE
HikariCP throw com.mysql.cj.jdbc.exceptions.CommunicationsException while connecting to AWS MySQL RDS After Some Time

### ISSUE THREAD

**Issue by esumit** [brettwooldridge/HikariCP#998]
#### Environment
```
HikariCP version: 2.7.1
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : 5.6
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*
Yes

My Java WAR Code inside Tomcat-9.01 Running with HikariCP in AWS EC2  Connected to AWS MySQL RDS.

HikariCp Configuration on Java based War File :

HikariConfig config = new HikariConfig();

        ```
config.setJdbcUrl(PropertyManager.getSetting("mySQLEndPoint"));
        config.setUsername(PropertyManager.getSetting("dataSourceCode3Manager.username"));
        config.setPassword(PropertyManager.getSetting("dataSourceCode3Manager.password"));
        
```
     
  Properties File :

    mySQLDriver=com.mysql.cj.jdbc.Driver
    mySQLEndPoint=jdbc:mysql://xxxx.xxxx.us-east-1.rds.amazonaws.com:xxx/xx3?autoReconnect=true&useSSL=false
       
      
In Java Code
   
 

  ```
  config.setDriverClassName(PropertyManager.getSetting("mySQLDriver"));
            config.addDataSourceProperty("cachePrepStmts", "true");
            config.addDataSourceProperty("prepStmtCacheSize", "250");
            config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
            config.addDataSourceProperty("verifyServerCertificate", "false");
    
            ds = new HikariDataSource(config);
```

It thrown : **com.mysql.cj.jdbc.exceptions.CommunicationsException:** (See Detailed Logs Below )

Yes I saw various posts which tells the solution about it e.g. [here][1] and [here][2] (It also tells :Configure your HikariCP idleTimeout and maxLifeTime settings to be one minute less than the wait_timeout of MySQL ?)

**My Question : If you are the one who ever face similar issue ?, May you please suggest your approach which solved this issue ?**

Detailed Logs 

    
    ```
12 Oct 12:57:00 [WARN] ProxyConnection.java 160 HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@2214a6bc marked as broken because of SQLSTATE(08S01), ErrorCode(0)
    com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 66,440,015 milliseconds ago.  The last packet sent successfully to the server was 66,440,020 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
            at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:590)
            at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)
            at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
            at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
            at com.mysql.cj.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1923)
            at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
            at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
            at com.code3.apis.regloginlogout.ormhelper.dbaccess.UsersDBAccess.getExistingUserByName(UsersDBAccess.java:240)
            at com.code3.apis.regloginlogout.action.SignInAction.handle(SignInAction.java:75)
            at com.code3.apis.regloginlogout.Code3LoginLogoutServiceImpl.registeredUserToSignedIn(Code3LoginLogoutServiceImpl.java:227)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
            at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
            at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:211)
            at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
            at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
            at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
            at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
            at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
            at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:243)
            at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
            at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197)
            at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149)
            at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
            at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)
            at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
    
    
    Caused by: com.mysql.cj.core.exceptions.CJCommunicationsException: The last packet successfully received from the server was 66,440,015 milliseconds ago.  The last packet sent successfully to the server was 66,440,020 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
            at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)
            at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)
            at com.mysql.cj.core.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:149)
            at com.mysql.cj.mysqla.io.MysqlaProtocol.send(MysqlaProtocol.java:561)
            at com.mysql.cj.mysqla.io.MysqlaProtocol.sendCommand(MysqlaProtocol.java:644)
            at com.mysql.cj.mysqla.io.MysqlaProtocol.sqlQueryDirect(MysqlaProtocol.java:950)
            at com.mysql.cj.mysqla.MysqlaSession.sqlQueryDirect(MysqlaSession.java:431)
            at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1978)
            ... 50 more
    Caused by: java.net.SocketException: Broken pipe (Write failed)
            at java.net.SocketOutputStream.socketWrite0(Native Method)
            at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
            at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
            at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    
    
    
    12 Oct 12:57:00 [INFO] UsersDBAccess.java 280 SQLException
    The last packet successfully received from the server was 66,440,015 milliseconds ago.  The last packet sent successfully to the server was 66,440,020 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.


  [1]: https://forums.aws.amazon.com/thread.jspa?threadID=86205
  [2]: https://github.com/brettwooldridge/HikariCP/wiki/FAQ

```

**Comment by brettwooldridge** [comment]
Well, it looks like the connection died after ~18 hours.  The default HikariCP ``maxLifeTime`` is 30 *minutes*, so the only way a connection can survive that long is if it is out of the pool -- for literally 18+ hours.

Try enabling the ``leakDetectionThreshold``, set to something like 5 minutes (*300000* milliseconds).  Watch your logs to see who is holding the connection.

One other possibility is that the clock leaped inside the VM.  Is there any message in the logs like "*Thread starvation or clock leap detected...*"?  If so, you need to enable the NTP (Network Time Protocol) service inside the VM.

**Comment by esumit** [comment]
Thanks

Set Wait_Timeout at Mysql - 45 Seconds , and other values here on HikariCP 👍 
13 Oct 04:26:32 [DEBUG] HikariConfig.java 953 HikariPool-1 - configuration:
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 allowPoolSuspension.............false
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 autoCommit......................true
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 catalog.........................none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 connectionInitSql...............none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 connectionTestQuery............."Select 1"
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 connectionTimeout...............5000
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 dataSource......................none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 dataSourceClassName.............none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 dataSourceJNDI..................none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 dataSourceProperties............{password=<xxxxx>, prepStmtCacheSqlLimit=2048, verifyServerCertificate=false, cachePrepStmts=true, prepStmtCacheSize=250}
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 driverClassName................."com.mysql.cj.jdbc.Driver"
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 healthCheckProperties...........{}
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 healthCheckRegistry.............none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 idleTimeout.....................10000
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 initializationFailFast..........true
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 initializationFailTimeout.......1
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 isolateInternalQueries..........false
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 jdbc4ConnectionTest.............false
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 jdbcUrl.........................jdbc:mysql:/xxxxx
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 leakDetectionThreshold..........15000
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 maxLifetime.....................30000
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 maximumPoolSize.................10
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 metricRegistry..................none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 metricsTrackerFactory...........none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 minimumIdle.....................10
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 password........................<masked>
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 poolName........................"HikariPool-1"
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 readOnly........................false
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 registerMbeans..................false
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 scheduledExecutor...............none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 scheduledExecutorService........internal
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 schema..........................none
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 threadFactory...................internal
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 transactionIsolation............default
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 username........................"code3"
13 Oct 04:26:32 [DEBUG] HikariConfig.java 985 validationTimeout...............5000
13 Oct 04:26:32 [INFO] Hi


And yes Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl ?, Any Suggestion ?

13 Oct 04:26:51 [WARN] ProxyLeakTask.java 82 Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@9c565e3, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at com.code3.apis.regloginlogout.ormhelper.db.MySqlConnect.<init>(MySqlConnect.java:57)
	at com.code3.apis.regloginlogout.ormhelper.db.MySqlConnect.getDatabaseConnection(MySqlConnect.java:67)
	at com.code3.apis.regloginlogout.ormhelper.dbaccess.UsersTokenDBAccess.getExistingTokenDetailsByUsername(UsersTokenDBAccess.java:132)
	at com.code3.apis.regloginlogout.action.SignoutAction.handle(SignoutAction.java:72)
	at com.code3.apis.regloginlogout.Code3LoginLogoutServiceImpl.logoutSignedInUser(Code3LoginLogoutServiceImpl.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:211)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:243)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by esumit** [comment]
Finally It was the issue related to not properly closing the created MySQL Connection in my own code, It wasn't related to HikariCP !

**Comment by hermitcai** [comment]
> Finally It was the issue related to not properly closing the created MySQL Connection in my own code, It wasn't related to HikariCP !

wo what the problem.
